### ISSUE TITLE
I used the dialog window in the tutorial but it reported an error

### ISSUE THREAD

**Issue by thka2016** [JetBrains/compose-jb#1009]
I looked at DialogState.desktop.kt which seems to be an endless loop?
![Screenshot_20210806003514](https://user-images.githubusercontent.com/46326722/128388031-9704d141-e8cf-41ca-8e3d-e5c7a15ee8fa.jpg)
![Screenshot_20210806003910](https://user-images.githubusercontent.com/46326722/128388056-9fe46aba-3ced-4318-8d05-a33bffd55656.jpg)
![Screenshot_20210806003920](https://user-images.githubusercontent.com/46326722/128388107-7bb130dd-720a-41a5-a8d0-605ad2c56107.jpg)

**Comment by igordmn** [comment]
Wow, thanks for reporting this, will be fixed in today's build.

As a workaround, you can use `DialogState(width=400.dp, height = 500.dp`)

**Comment by igordmn** [comment]
And in Composable function, we should use `rememberDialogState`, so we don't recreate state on every recomposition - this was fixed in a tutorial a minute ago

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6254">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
