### ISSUE TITLE
web: Column doesn't support horizontal alignment / vertical arrangement parameters

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#1010]
I'd like to write the following in Web Compose:

```
Column(
   modifier = Modifier
      .fillMaxWidth(),
   horizontalAlignment = Alignment.CenterHorizontally
) {
   ... // this should be in a ColumnScope?
}
```

similar to the [Android version](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#Column(androidx.compose.ui.Modifier,androidx.compose.foundation.layout.Arrangement.Vertical,androidx.compose.ui.Alignment.Horizontal,kotlin.Function1)).

I assume the API change is planned but I didn't see a bug for it so I added it.

**Comment by bitspittle** [comment]
Not sure if this is technically the right solution, but I'm locally patching things this way:

```kotlin
@Composable
fun Column(
    modifier: Modifier = Modifier,
    verticalArrangement: Arrangement.Vertical = Arrangement.Top,
    horizontalAlignment: Alignment.Horizontal = Alignment.Start,
    content: @Composable () -> Unit
) {
    Div(attrs = modifier.castOrCreate().apply {
        add {
            display(DisplayStyle.Flex)
            flexDirection(FlexDirection.Column)

            when {
                verticalArrangement === Arrangement.Top -> justifyContent(JustifyContent.FlexStart)
                verticalArrangement === Arrangement.Bottom -> justifyContent(JustifyContent.FlexEnd)
            }

            when {
                horizontalAlignment === Alignment.Start -> alignItems(AlignItems.FlexStart)
                horizontalAlignment === Alignment.CenterHorizontally -> alignItems(AlignItems.Center)
                horizontalAlignment === Alignment.End -> alignItems(AlignItems.FlexEnd)
            }
        }
    }.asAttributeBuilderApplier()) {
        content()
    }
}
```

**Comment by akurasov** [comment]
@bitspittle what html do you want to get as a result?

**Comment by bitspittle** [comment]
I'm happy for the team to go in a different final direction - I don't care too much about the html as long as it feels right, and I'm new to frontend development, so it's possible there are better approaches.. For a `Column` with max width and center alignment, I'd expect something where it's width fills the page 100% and that all children elements are arranged one after the other and centered on screen.

But here's some concrete Kotlin code I wrote (using my version of `Row` in this case) plus the html it generated. Note that this is a slightly different version - it's a row which fills max width and centers all row elements veritcally:

```kotlin
@Composable
fun NavHeader() {
    Box(
        Modifier
            .fillMaxWidth()
            .height(50.dp)
            .background(Color.Black)
    ) {
        Row(
            Modifier.padding(10.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            NavLink("/", "HOME")
            NavLink("/about", "ABOUT")
            Spacer()
            ... right side icons ...
        }
    }
}
```

```html
<div style="width: 100%; height: 50px; background-color: rgb(0, 0, 0);">
   <div style="margin: 10px; display: flex; flex-direction: row; justify-content: flex-start; align-items: center;">
   <span style="margin: 5px 15px; color: rgb(255, 255, 255); text-decoration-line: none; cursor: pointer">HOME</span>
   <span style="margin: 5px 15px; color: rgb(255, 255, 255); text-decoration-line: none; cursor: pointer">ABOUT</span>
   <div style="flex-grow: 1;"></div>
   ... right side icons ...
</div>
```

Note: I needed to separate out the Box and the Row because I wanted the black color of the nav bar to touch the top of the page, and I only wanted the row padding to apply to the inner links.

**Comment by bitspittle** [comment]
BTW, this code may change / someday these links may 404, as I'm still playing around with stuff, but if you check soon you can probably see what I'm doing here:

https://github.com/bitspittle/kobweb/blob/main/lib/compose-ext/src/jsMain/kotlin/kobweb/compose/foundation/layout/Column.kt
https://github.com/bitspittle/kobweb/blob/main/lib/compose-ext/src/jsMain/kotlin/kobweb/compose/foundation/layout/Row.kt
https://github.com/bitspittle/kobweb/blob/main/examples/helloworld/src/jsMain/kotlin/helloworld/components/layouts/PageLayout.kt
https://github.com/bitspittle/kobweb/blob/main/examples/helloworld/src/jsMain/kotlin/helloworld/components/sections/NavHeader.kt

**Comment by bitspittle** [comment]
My current implementations:

https://github.com/bitspittle/kobweb/blob/main/lib/compose-ext/src/jsMain/kotlin/kobweb/compose/foundation/layout/Column.kt
https://github.com/bitspittle/kobweb/blob/main/lib/compose-ext/src/jsMain/kotlin/kobweb/compose/foundation/layout/Row.kt

**Comment by hfhbd** [comment]
I already tried porting foundation to web too, but the api is quite different in Compose Web, because html DOM and the different implementation. I would suggest to not use expect/actual in your project, but rather direct upstream, to access more internal functions/apis.

**Comment by eymar** [comment]
closing this issue. Reason: since 1.0.0 `compose.web.widgets` module was deprecated.
