### ISSUE TITLE
How to set margin to auto？

### ISSUE THREAD

**Issue by UramnOIL** [JetBrains/compose-jb#1012]
Hello,

I'd like to set mergin property to auto:
```kotlin
Button(
    attrs = {
        style {
            margin(auto) // margin needs CSSNumeric
         }
    }
) {
    Text("Click")
}
```
but `margin()` can't receive auto because auto doesn't match `CSSNumeric`.
Is there any other way to apply auto to margin?

**Comment by eymar** [comment]
as a quick workaround you can do:
```
property("margin", "auto")
```
But we'll add `margin(auto)` anyway.

**Comment by UramnOIL** [comment]
I see now, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5331">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
