### ISSUE TITLE
Can't run multiplatform desktop compose-jb app if it has java files

### ISSUE THREAD

**Issue by soniccat** [JetBrains/compose-jb#1022]
Hi. I have a compose-jb app with an included multiplatform shared library. We can take your ToDo sample app as an example. After having a java file in a project I see this error when I try to run it: 

> Could not determine the dependencies of task ':desktop:compileJava'.
 > Could not resolve all task dependencies for configuration ':desktop:compileClasspath'.
   > Could not resolve com.arkivanov.decompose:decompose:0.2.6.
     Required by:
         project :desktop
      > The consumer was configured to find an API of a library compatible with Java 14, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally. However we cannot choose between the following variants of com.arkivanov.decompose:decompose:0.2.6:
          - debugApiElements-published
          - debugRuntimeElements-published
...

the full error is quite long: https://pastebin.com/ghZLKS21

I've got this error after trying to add Dagger support which generates java files. You can reproduce this case in your ToDo sample app using my branch: https://github.com/soniccat/compose-jb/tree/try_with_java. All the changes are here: https://github.com/soniccat/compose-jb/commit/df0dc8a88e8cbb4bb0abd8e88e22f20ac8d676ea

Also I've got the same error after moving from gradle buildSrc to includeBuild feature. You can reproduce this case in your ToDo sample app using my branch: https://github.com/soniccat/compose-jb/tree/try_with_indclude_build. All the changes are here: https://github.com/soniccat/compose-jb/commit/cf2dc97e8a42bc1fbd3aa678799537bd5f447921

**Comment by akurasov** [comment]
I reproduced it on 1.0.0-alpha3+kotlin 1.5.21

However on 1.0.0-alpha4-build344+kotlin1.5.30 everything works fine. Do you still have this issue?

**Comment by soniccat** [comment]
Interesting, I'll check on this weekend and let you know. I haven't tried it with 1.5.30.

**Comment by soniccat** [comment]
Hi, I still see the same problem. I've rebased my fork with v1.0.0-alpha4-build348 tag (I hope that build344 works as well as build348). Then I've updated your todo app to kotlin 1.5.30 and I still see the same issue. Probably I've forgotten something. Could you please look at my changes here https://github.com/soniccat/compose-jb/commit/a5aa91784010ed796d84df98767652719e33df29 ? There's the error I see https://pastebin.com/ykwWAatJ.
(I've commented gradle web target as I have unrelated issues with it)

**Comment by akurasov** [comment]
Seems like an Kotlin MPP issue and could be already fixed in 1.6. However Compose is not compatible with 1.6 yet, so waiting until it is supported.

**Comment by akurasov** [comment]
It was built fine on 1.0.1-rc2 + kotlin 1.6.10. Reopen, if you still experience this issue at some project.

**Comment by soniccat** [comment]
Hi, I've checked the both cases I wrote initially and I confirm that now everything works well. Thanks for your support and proper attention. Now I'm able to go forward with porting my small android app to compose-jb desktop.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5324">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
