### ISSUE TITLE
IDE doesn't recognize extension function RoundToPx

### ISSUE THREAD

**Issue by CeH9** [JetBrains/compose-jb#1023]
IDE doesn't recognize extension function RoundToPx

```
    kotlin("jvm") version "1.5.21"
    id("org.jetbrains.compose") version "1.0.0-alpha3"
```

![image](https://user-images.githubusercontent.com/7687412/128581020-84ea8bff-b220-4f5a-a1d9-b43e3ab5fbbc.png)

![image](https://user-images.githubusercontent.com/7687412/128580951-6bde111b-5d69-4ac0-a2f0-1fd96ea1d8b2.png)

**Comment by kirill-grouchnikov** [comment]
Not all such functions are available from any point. It needs to have `Density` available as a receiver.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5323">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
