### ISSUE TITLE
web: Compose should translate dp units to something besides px

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#1033]
Currently, I've seen at least one place that converts DP units to PX units:

https://github.com/JetBrains/compose-jb/blob/0a90ae219488ffbb89759fa9bc9c008d9ce5f4b6/web/widgets/src/jsMain/kotlin/Modifier.kt#L38

https://github.com/JetBrains/compose-jb/blob/242ec6bbf9b9df085e9d6e56e63e14ff82e4a52d/examples/falling-balls-web/src/jsMain/kotlin/modifiers/position.kt#L18

https://github.com/JetBrains/compose-jb/blob/e65dc8c89f906b640178b40c0aeff0819af922f1/web/widgets/src/jsMain/kotlin/modifiers/offset.kt#L12

But the conversion should be screen density dependent. Perhaps it should be "em" instead?

**Comment by eymar** [comment]
apparently there're different answers/solutions to this question.  And one of them is to simply convert dp into px as 1:1.

https://graphicdesign.stackexchange.com/questions/36482/how-to-convert-between-android-dp-and-css-px
The link is only for our information. 
We'll dig into this.

**Comment by eymar** [comment]
closing this issue. Reason: since 1.0.0 compose.web.widgets module was deprecated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5317">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
