### ISSUE TITLE
@Composable invocations can only happen from the context of a @Composable function

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#1038]
I get this error even though my code compiles fine.
<img width="515" alt="Screen Shot 2021-08-10 at 11 40 28 AM" src="https://user-images.githubusercontent.com/31751141/128901703-250e20f6-ba60-41d2-9229-d5afcf9bebd0.png">

To repro. Use the multiplatform template

1. Add Theme.kt in commonMain
2. To this file add

```
import androidx.compose.material.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Stable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

private val LightColorPalette =
    MuAppColors(iconC1 = Color.Blue)

private val DarkColorPalette = MuAppColors(iconC1 = Color.Red)

@Composable
fun MuAppTheme(darkTheme: Boolean = false, content: @Composable () -> Unit) {
    val colors = if (darkTheme) DarkColorPalette else LightColorPalette

    ProvideMuAppColors(colors) {
        MaterialTheme(
            content = content
        )
    }
}

@Stable
class MuAppColors(
    iconC1: Color,
) {
    var textOrIcon_c1 by mutableStateOf(iconC1)
        private set

    fun update(other: MuAppColors) {
        textOrIcon_c1 = other.textOrIcon_c1
    }
}

@Composable
fun ProvideMuAppColors(colors: MuAppColors, content: @Composable () -> Unit) {
    val colorPalette = remember { colors }
    colorPalette.update(colors)
    CompositionLocalProvider(LocalAmbientMuProviderColors provides colorPalette, content = content)
}

private val LocalAmbientMuProviderColors =
    staticCompositionLocalOf<MuAppColors> { error("No MuColorPalette provided") }
```

I found ^ this code via the google samples https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt

3. Use this in desktop app
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        MuAppTheme {
            Text("")
        }
    }
}
**then invalidate caches and restart**

4. Error is visible! (but code still compiles)

**Comment by akurasov** [comment]
Hi! I guess there is the same issue in Android?

**Comment by akurasov** [comment]
Hi! Do you have the same issue in plain Android Jetpack Compose?

**Comment by ColtonIdle** [comment]
Nope! A plain old Android compose project works fine, and the android project in the multiplatform template works fine. It's only when adding the code above (and then invalidate + restart) that the IDE starts to act weird (but still builds fine)

**Comment by akurasov** [comment]
I don't have this issue in IDEA 212 too. Which IDEA do you use?

**Comment by akurasov** [comment]
There are indeed a number of issues in AS. We are going to tackle them in a reasonable timeframe. Thank you for reporting!

**Comment by ColtonIdle** [comment]
Great. Glad it wasn't just me. I will try opening up in IJ now!

**Comment by ColtonIdle** [comment]
@akurasov 

> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.

😭

**Comment by hfhbd** [comment]
@ColtonIdle The sources of AGP 7.0.0 are not yet published, so JetBrains have not updated their plugin. Alternative use AGP 4.2.2.

**Comment by ColtonIdle** [comment]
Okay. I can't use 4.2.2 (have to use at least 7.0 stable), but I'm looking forward to when the plugin is updated. Thanks

**Comment by igordmn** [comment]
> To repro. Use the multiplatform template

Everything fine in this configuration:
```
Android Studio Arctic Fox | 2020.3.1 + Kotlin plugin 203-1.5.21-release-328-AS7717.8
Android Studio Bumblebee | 2021.1.1 Canary 6 +Kotlin plugin 211-1.5.21-release-328-AS7442.40
```
What version of Kotlin Plugin do you use?

**Comment by akurasov** [comment]
> @akurasov
> 
> > This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.
> 
> 😭
> 
> I'm using
> 
> IntelliJ IDEA 2021.2.1 Preview (Community Edition)
> Build #IC-212.5080.17, built on August 12, 2021
> Runtime version: 11.0.11+9-b1504.16 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 11.4
> GC: G1 Young Generation, G1 Old Generation
> Memory: 750M
> Cores: 24
> 
> Kotlin: 212-1.5.10-release-IJ5080.17

Let me try installing the same version

**Comment by akurasov** [comment]
@ColtonIdle most probably something wrong with your env. I installed clean Community edition. It already contains the same kotlin plugin. There are no error message... 

Or maybe there some other changes in your projects. Could you put it somewhere?

**Comment by ColtonIdle** [comment]
@akurasov sorry. I gave you the wrong information.

I am trying this with AS Bumblebee Canary 8. I made a mistake with grabbing IntelliJ information and pasting it here.

Here is my AS details

```
Android Studio Bumblebee | 2021.1.1 Canary 8
Build #AI-211.7628.21.2111.7619903, built on August 6, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 16192M
Cores: 24
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.draculatheme.idea (1.3.1), com.facebook.ktfmt_idea_plugin (1.1.0.27), String Manipulation (8.15.203.000.3), com.vermouthx.idea (1.12.0), vip.okfood.liam.plugin.i18n (1.0.2), wu.seal.tool.jsontokotlin (3.7.2), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.5.21-release-328-AS7442.40), org.jetbrains.compose.desktop.ide (1.0.0-alpha4-build310), izhangzhihao.rainbow.brackets (6.19), org.intellij.plugins.markdown (211.7142.37)
```

I think the issue here is what @hfhbd said

> @ColtonIdle The sources of AGP 7.0.0 are not yet published, so JetBrains did not update their plugin. Alternative use AGP 4.2.2.

I can try again once it supports 7.0.0 stable.

**Comment by akurasov** [comment]
I tested in on 

Android Studio Bumblebee | 2021.1.1 Canary 10
Build #AI-211.7628.21.2111.7667256, built on August 23, 2021
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
Registry: external.system.auto.import.disabled=true

and it worked fine. Can you upgrade to it to see if the issue is still there?

**Comment by ColtonIdle** [comment]
Hm...

```
Android Studio Bumblebee | 2021.1.1 Canary 10
Build #AI-211.7628.21.2111.7667256, built on August 23, 2021
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 16192M
Cores: 24
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: String Manipulation (8.15.203.000.3), com.vermouthx.idea (1.12.0), vip.okfood.liam.plugin.i18n (1.0.2), wu.seal.tool.jsontokotlin (3.7.2), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.5.21-release-328-AS7442.40), org.jetbrains.compose.desktop.ide (1.0.0-alpha4-build315), izhangzhihao.rainbow.brackets (6.19), org.intellij.plugins.markdown (211.7142.37)
```

is still broken. Let me try to update the kotlin plugin? ALthough when I tried updating earlier it gave me a 404.

**Comment by ColtonIdle** [comment]
Yep. After updating everything to latest 1.5.30 and latest JB compose, and kotlin plugin, I still get red everywhere in my single composable defined in

`rollertoaster/commoncomposables/src/commonMain/kotlin/MyApp.kt`
<img width="542" alt="Screen Shot 2021-09-01 at 9 01 23 PM" src="https://user-images.githubusercontent.com/31751141/131764953-f859c015-a104-4c0b-a1f8-4eef9bde891d.png">

**Comment by ColtonIdle** [comment]
Since I opened this bug with the repro steps above. My issue above seems unrelated. I will try to get some minimal repro steps for that and open that bug. Looks like this was fixed with an AS update.

Thanks for checking @akurasov

**Comment by ColtonIdle** [comment]
New bug filed here: https://github.com/JetBrains/compose-jb/issues/1132

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5313">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
