### ISSUE TITLE
Package build step failed

### ISSUE THREAD

**Issue by MikhailZisman** [JetBrains/compose-jb#104]
Hi
I faced with build problem on Ubuntu (for any sample projects). 

` ./gradlew :desktop:package 

> Configure project :common
Kotlin Multiplatform Projects are an Alpha feature.

> Task :desktop:packageDeb FAILED
WARNING: Using incubator modules: jdk.incubator.jpackage
jlink failed with: Error: Hash of java.xml (6ccc60ebddab7b301b79ed14fcc5ac14e98bb6612f1039f65c0111ea70140a35) differs to expected hash (9964eca975974fd89a21124fc102300265cecbc3340481f5a4b104bc1c2a256c) recorded in java.base

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:packageDeb'.
> Process 'command '/usr/lib/jvm/java-14-openjdk-amd64/bin/jpackage'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 978ms
7 actionable tasks: 1 executed, 6 up-to-date
`

**Comment by olonho** [comment]
Please use openjdk 15, openjdk 14 has a bug leading to this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6507">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
