### ISSUE TITLE
Modifier interface should support the "then" function

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#1045]
For reference: https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#then(androidx.compose.ui.Modifier)

I believe this bug applies to multiplatform, but I'm running into a local issue with my Web Compose app. Basically, I have something like this:

```kotlin
@Composable
fun MyComposable(modifier = Modifier) {
   // I want to apply base styles here that may get overridden by the user, so something like
   fun baseModifier = Modifer. ...

   Box(baseModifier.then(modifier)) { ... }
}
```

**Comment by akurasov** [comment]
You mean you want to have "then" functionality for Modifiers in Compose Web?

**Comment by bitspittle** [comment]
Yep! Although I don't think the right approach is solving this just for Web. It's probably an API consideration for the code in commonMain with actual implementations.

Here is the exact code handling it in Android: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/Modifier.kt;l=99

Here's my temporary local hack:
https://github.com/bitspittle/kobweb/blob/main/lib/compose-ext/src/jsMain/kotlin/kobweb/compose/ui/ModifierExtensions.kt#L148

The reason I think I need this is because I'm developing a widget library for web, you can think of it as similar to www.chakra-ui.com. While normally Compose says if you want to change the style, you just pass in parameters to the composable function, what I'm thinking of doing is creating a way to register global styles per widget which can be easily overridden by the user if they care.

A concrete example can help, here. Take a look at my button class (note that this is a WIP):

https://github.com/bitspittle/kobweb/blob/main/lib/ui/src/jsMain/kotlin/kobweb/silk/components/forms/Button.kt#L55

The idea is I define a default style, but later, if a user really cared, they will be able to do something like:

```kotlin
SilkConfig.componentStyles[ButtonKey] = object : ButtonStyle() {
   override val color: Color
      @Composable
      get() = Color.Red
}
```

and then they're done. Of course, the `Button` composable still takes in its own parameters as well, which, if set, overrides this base style.

```kotlin
Button() { Text("Default global style") }
// Modifying color, here, but you could also do padding or whatever
Button(Modifier.color(Color.Blue)) { Text("Blue override") }
```

Note: This is inspired by [Chakra UI Component Styles](https://chakra-ui.com/docs/theming/component-style) by the way.

To accomplish this, I'm doing the following:

https://github.com/bitspittle/kobweb/blob/main/lib/ui/src/jsMain/kotlin/kobweb/silk/components/forms/Button.kt#L91

I'm creating a separate modifier that represents the base style, and then I'm taking the modifier passed in by the user and applying it AFTER that (so my base style's background-color gets overwritten by the user's one, in my example above).

That's quite a text dump at the end of a long day, so let me know if anything doesn't make sense, or if you are aware of a different approach I should be taking. Thanks!

**Comment by eymar** [comment]
closing this issue. Reason: since 1.0.0 compose.web.widgets module was deprecated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5308">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
