### ISSUE TITLE
Getting Started tutorial doesn't show me how to create an installer

### ISSUE THREAD

**Issue by mike-ward** [JetBrains/compose-jb#1047]
The Getting Started guide does an excellent job of getting me from zero to a running desktop app. I do wish it showed me how to create an installer from the IDE. I couldn't figure it out even after reading the tutorial on creating an installer.

P.S. I'm a C#/Avalonia programmer who knows nothing about Kotlin and Gradle so I really need my hand held until I learn more.

**Comment by akurasov** [comment]
If you want to create an installer, open gradle window (view->tool windows->gradle) and run tasks->composeDesktop->package* (* depends on desired platform)

**Comment by akurasov** [comment]
@mike-ward BTW, have you seen Native_distributions_and_local_execution tutorial?

**Comment by mike-ward** [comment]
@akurasov Yes, but not being familiar with the tooling I could not figure out from the tutorial what commands to run to build a package. To be fair, distribution/packaging in many development environment is also challenging. I'm delighted to see that this has been addressed in the IDE's plugin. Having an, "Easy Button", so to speak, helps with getting over the initial hurdles of learning a new framework.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5307">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
