### ISSUE TITLE
How to do update for an desktop app that has been installed ?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#1049]
I want to update  my desktop app that has been installed, my steps are following:

1.include "update.exe" to package
2.check files' md5 in 'app' directory,then compare with server's md5
3.launch "update.exe" if latest version published
4.download the files with new md5 by "update.exe" to replace the old files

but in the photo following,the jar files'(in 'app' directory) names are not fixed
![image](https://user-images.githubusercontent.com/23566361/129302658-89c1d3af-b014-4e9f-9ba2-b7800bb07ed2.png)

how to remove the characters surrounded by red rectangles?
if it can't be resolved, tell me a way to update my app please.

**Comment by ljkgpxs** [comment]
delete all old version files, and put new version files to program directory

**Comment by FlyingYu-Z** [comment]
> delete all old version files, and put new version files to program directory

but this will make big changes. and i want only donwload the files changed to replace

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5306">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
