### ISSUE TITLE
Add isResizable to window attributes

### ISSUE THREAD

**Issue by devBNiebes** [JetBrains/compose-jb#105]
It seems that the ability to say that a window is not reszisable is missing. 

Looking in the Sourcecode of androidx.compose.desktop.Window the window is set to not be reszisable when locked, so the ability to set a window to be not reszisable is there but it is not exposed to the developer.

A implementation could be like the centered boolean atribute.

If this is already possible and i just missed how to do it please feel free to close the issue.

**Comment by Irker** [comment]
@devBNiebes looks like you can do it something like this: 
`AppManager.windows[0].window.isResizable = false`
But I think it's only a temporary solution

**Comment by olonho** [comment]
@Rsedaikin is it still relevant?

**Comment by Rsedaikin** [comment]
Added in version `0.3.0-build138`. See the updated [Window control API](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API) tutorial.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6493">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
