### ISSUE TITLE
README.md link to Widget Gallery is broken

### ISSUE THREAD

**Issue by jfree** [JetBrains/compose-jb#1055]
In the README file the link to the widget gallery is broken, it is missing a hyphen.

https://github.com/JetBrains/compose-jb/tree/master/examples/widgets-gallery

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5302">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
