### ISSUE TITLE
code of Getting_Started does not compile

### ISSUE THREAD

**Issue by robstoll** [JetBrains/compose-jb#1057]
1.::exitApplication does not exist
2.signature of `rememberWindowState(width = 300.dp, height = 300.dp)` is wrong

**Comment by robstoll** [comment]
works, had a wrong version

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5300">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
