### ISSUE TITLE
Web Project Fails to Run

### ISSUE THREAD

**Issue by abueide** [JetBrains/compose-jb#1058]
I followed the barebones getting started with web tutorial and got this error when running the "jsBrowserDevelopmentRun" gradle task.

```
[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property '_assetEmittingWrittenFiles'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }
```

Reproduced on the following versions, mac & windows:
0.5.0-build270, 1.0.0-alpha3, 1.0.0-alpha4-build310

This bug also affects the peopleinspaceproject (https://github.com/joreilly/PeopleInSpace), as well as the minimal getting started project I made (https://github.com/abueide/test3)

**Comment by eymar** [comment]
Hi @abueide ,
Apparently not only compose-web projects affected by this issue. It has been already reported here https://youtrack.jetbrains.com/issue/KT-48273

**Comment by eymar** [comment]
As mentioned in KT-48273 it's possible to use a workarund for now.

In gradle.properties: 
```
kotlin.js.webpack.major.version=4
```

**Comment by abueide** [comment]
thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5299">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
