### ISSUE TITLE
Horizontal scrolling with mouse wheel

### ISSUE THREAD

**Issue by felixdivo** [JetBrains/compose-jb#1064]
Following [this tutorial](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Desktop_Components#scrollbars), one can easily implement vertical scrolling using a mouse wheel (it just works out of the box). How can this be done for horizontal scrolling? `Modifier.horizontalScroll(...)` does not seem to enable mouse wheel input even if no vertical scroll is enabled. The tutorial could benefit from an explanantion of that (or a link to such).

**Comment by igordmn** [comment]
If you have horizontal scrolling list (`horizontalScroll`), you can scroll it with Shift + vertical scroll of the mouse wheel or with horizontal clicks of the mouse wheel.

If it doesn't work - it is a bug.

Scrolling in horizontal direction with vertical scroll of the mouse wheel isn't supported at the moment.

**Comment by felixdivo** [comment]
Okay, that actually works. Nice, thank you! I'll open a PR that mentions that in the tutorial. You decide on whether that's relevant/welcome.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5296">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
