### ISSUE TITLE
TextField display problem after changing the height

### ISSUE THREAD

**Issue by SGPublic** [JetBrains/compose-jb#1069]
When I change the height of the TextField to be less than its default value, The content of the TextField does not appear to be displayed properly, and modifying the fontSize parameter of its textStyle has no effect.

![image](https://user-images.githubusercontent.com/37202870/129679938-4f0da955-0467-447c-ad0f-ec2919363b27.png)

If I make a mistake, what is the correct way to modify the height? thanks.

**Comment by akurasov** [comment]
@SGPublic at the moment there is no way to reduce the height of the TextField. What can you do, is to use BasicTextField, that is smaller due to absence of decorations.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5293">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
