### ISSUE TITLE
Windows Package doesnt allow backslash in installationPath

### ISSUE THREAD

**Issue by ctadlock** [JetBrains/compose-jb#1074]
I would like to set the installation path to `c:\Program Files\GoToTags\DesktopApp`, but its removing the slash. From what I can tell in the jpackage docs a backslash is allowed.

![image](https://user-images.githubusercontent.com/1539397/129824667-a59b374f-6225-4e18-83a9-ff2da482252c.png)

**Comment by ctadlock** [comment]
Apparently you always need to use a forward slash.

Example: `installationPath = "GoToTags/DesktopApp"`

#### References
- https://stackoverflow.com/questions/42080335/cant-set-a-windows-based-path-in-gradle-properties
- https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5288">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
