### ISSUE TITLE
The exe file shows error and could not run

### ISSUE THREAD

**Issue by GaoXing0608** [JetBrains/compose-jb#1094]
The application which convert to mis  and installed by "packageWsi" could not show the details. What is more, it shows double widow while full expand the application

**Comment by GaoXing0608** [comment]
![捕获](https://user-images.githubusercontent.com/47878271/130576606-df2ff144-ecc5-4c75-b488-1786cf22632a.PNG)

**Comment by GaoXing0608** [comment]
The window shows nothing while the exe file running, and it shows two white rectangle and the others is black while setting the exe file full screen

**Comment by akurasov** [comment]
What is the compose version that you use?

**Comment by GaoXing0608** [comment]
The version is 0.4.0

I have solved it, I have added a crash handler to capture the exception while application running, it shows could not find the resources. So the application could not show my resources images, I have solved

**Comment by akurasov** [comment]
We recommend to use at least Alpha build (1.0.0-alpha3). In earlier versions there could be some issues, that are already fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6308">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
