### ISSUE TITLE
Question about the `Image_And_Icons_Manipulations` tutorial

### ISSUE THREAD

**Issue by AzimMuradov** [JetBrains/compose-jb#1099]
There is some confusing part about loading bitmaps in this ([drawing-raw-image-data-using-native-canvas](https://github.com/JetBrains/compose-jb/blob/82468294f43952758fb00f5e13f3267734979d34/tutorials/Image_And_Icons_Manipulations/README.md#drawing-raw-image-data-using-native-canvas)) section of the tutorial.

First, we load it using `useResource`:
```kotlin
// ImageBitmap
private val sample = useResource("sample.png", ::loadImageBitmap)
```

Second, we do it again using `bitmapFromByteArray` and `ImageBitmap.getBytes`:
```kotlin
fun main() {

    // ...

    // ImageBitmap
    val bitmap = remember { bitmapFromByteArray(sample.getBytes(), sample.width, sample.height) }

    // ...
}

fun bitmapFromByteArray(pixels: ByteArray, width: Int, height: Int): ImageBitmap {
    val bitmap = Bitmap()
    bitmap.allocPixels(ImageInfo.makeS32(width, height, ColorAlphaType.PREMUL))
    bitmap.installPixels(bitmap.imageInfo, pixels, (width * 4).toLong())
    return bitmap.asImageBitmap()
}

// creating byte array from BufferedImage
private fun ImageBitmap.getBytes(): ByteArray {
    val buffer = IntArray(width * height)
    readPixels(buffer)

    val pixels = ByteArray(width * height * 4)

    var index = 0
    for (y in 0 until height) {
        for (x in 0 until width) {
            val pixel = buffer[y * width + x]
            pixels[index++] = ((pixel and 0xFF)).toByte() // Blue component
            pixels[index++] = (((pixel shr 8) and 0xFF)).toByte() // Green component
            pixels[index++] = (((pixel shr 16) and 0xFF)).toByte() // Red component
            pixels[index++] = (((pixel shr 24) and 0xFF)).toByte() // Alpha component
        }
    }

    return pixels
}
```

Can't it all be simplified to:

```kotlin
private val sample = useResource("sample.png", ::loadImageBitmap)

@OptIn(ExperimentalComposeUiApi::class)
fun main() = singleWindowApplication {
    val bitmap = remember { sample }
    Canvas(
        modifier = Modifier.fillMaxSize()
    ) {
        drawIntoCanvas { canvas ->
            canvas.drawImage(bitmap, Offset.Zero, Paint())
        }
    }
}
```

P.S. Thanks for the fantastic library!

**Comment by igordmn** [comment]
Actually this tutorial shows multiple things: how to draw an image on canvas, how to convert an image to a pixel array, and how to convert a pixel array to an image. Originally, the main goal was to show how to draw an image if we only have a pixel array. 

But let's keep things simple, and remove converting part, because it isn't directly related to Compose for Desktop, rather to common Compose or Skija.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6314">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
