### ISSUE TITLE
Could not create task ':run'.

### ISSUE THREAD

**Issue by crazy1235** [JetBrains/compose-jb#110]
> Could not create task ':run'.
   > org.gradle.api.tasks.JavaExec.getMainClass()Lorg/gradle/api/provider/Property;

the IDE tip:

![image](https://user-images.githubusercontent.com/5068795/99387724-7048ce80-290f-11eb-99dd-3914fea69e79.png)

**Comment by olonho** [comment]
Could you please try with build "0.2.0-build124"?

**Comment by olonho** [comment]
Please reopen, if still reproducible.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5620">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
