### ISSUE TITLE
BuildKonfig plugin is not working alongside with Compose plugin

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#1104]
Copying this message from [here](https://youtrack.jetbrains.com/issue/KT-48366):

Enabling the Compose compiler for Kotlin/JS alongside the 'BuildKonfig' plugin causes IR 'AssertionError: Unexpected field without property'
1 
There's some problematic interaction between the current latest Multiplatform Compose Compiler and the popular KMP BuildKonfig plugin.

I have attached a minimal reproduction project that I think reveals the bug as a compiler issue, and not with the BuildKonfig plugin itself.

With Compose compiler 'off', the project builds as expected, including BuildKonfig output.
To see this: Ensure that ReproConfig.isEnableCompose under buildSrc is false, then execute project ./gradlew build.
With Compose compiler 'on', the project build fails while processing BuildKonfig output, during Gradle task compileProductionExecutableKotlinJs.
The error is: java.lang.AssertionError: Unexpected field without property myapp.MyConfig.$stable
To see this: Ensure that ReproConfig.isEnableCompose under buildSrc is true, then execute project ./gradlew build.
This is preventing me from using BuildKonfig in a project intended for production; any fix or workaround greatly appreciated.

**Comment by eymar** [comment]
Should work with 1.0.1-rc2 and kotlin 1.6.10

**Comment by yshrsmz** [comment]
@eymar @Schahen 
Hi, thanks for the update.
Can you share which commit/PR is responsible for the fix?

**Comment by eymar** [comment]
@yshrsmz https://github.com/JetBrains/androidx/commit/84519a5c9855f7bb95471ff8218eb0ffc0766e68#diff-6797c64ea0d0928496343a79b279f9b3c128a854e7d08cadeae3965000151fe8R1073 - this commit is not only about that issue though. But the fix is to add `IrProperty` for `IrField` named `$stable`.

**Comment by yshrsmz** [comment]
thanks!
