### ISSUE TITLE
Can it be published to the mavenCentral repository?

### ISSUE THREAD

**Issue by LeonDevLifeLog** [JetBrains/compose-jb#1106]
Due to well-known reasons, the compose related dependencies cannot be downloaded in China.

**Comment by smallshen** [comment]
It can, but just slow, the Jetbrains Space doesn't have server deployed in China, I have tried it, it just slow

**Comment by LeonDevLifeLog** [comment]
> It can, but just slow, the Jetbrains Space doesn't have server deployed in China, I have tried it, it just slow

If published to maven central, there are mirrors in China

**Comment by akurasov** [comment]
We are going to start publishing there in reasonable timeframe

**Comment by xxfast** [comment]
Any updates on this? my sync times are getting quite _unreasonable_ 😄  
<img width="342" alt="Screen Shot 2021-10-20 at 12 01 31 am" src="https://user-images.githubusercontent.com/13775137/137914699-ed6ee21b-5a3e-4843-9fd3-a125a0785c86.png">

**Comment by xxfast** [comment]
Do we need still need to keep
```kotlin
maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")1
```
for specific builds like `1.0.0-alpha4-build398`?

**Comment by akurasov** [comment]
@xxfast we ensure that major builds are published to mavenCentral. However we don't guarantee that all builds will be published there. So if you're going to use dev builds, it is better to keep it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6204">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
