### ISSUE TITLE
Can't create an empty bitmap

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#111]
`ImageBitmap(100, 100)` crashes in native code. It gets to https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/compose/ui/ui-graphics/src/desktopMain/kotlin/androidx/compose/ui/graphics/DesktopImageAsset.kt#61 which then goes to https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/compose/ui/ui-graphics/src/desktopMain/kotlin/androidx/compose/ui/graphics/DesktopImageAsset.kt#172 and crashes there.

This is on 0.2.0-build123 on a Mac

**Comment by kirill-grouchnikov** [comment]
Stack trace:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jetbrains.skija.ColorSpace._nGetFinalizer()J
        at org.jetbrains.skija.ColorSpace._nGetFinalizer(Native Method)
        at org.jetbrains.skija.ColorSpace.<clinit>(ColorSpace.java:82)
        at androidx.compose.ui.graphics.DesktopImageAssetKt.toSkijaColorSpace(DesktopImageAsset.kt:172)
        at androidx.compose.ui.graphics.DesktopImageAssetKt.ActualImageBitmap(DesktopImageAsset.kt:61)
        at androidx.compose.ui.graphics.ImageBitmapKt.ImageAsset(ImageBitmap.kt:255)
        at androidx.compose.ui.graphics.ImageBitmapKt.ImageAsset$default(ImageBitmap.kt:254)
```

**Comment by olonho** [comment]
Could you please share reproducer? Could you please ensure that this code is called after `Window` entrypoint was called? 
An alternative would be calling `androidx.compose.desktop.initCompose()` at the very top of `main()`.

**Comment by jimgoog** [comment]
It looks like it matters when the constructor is invoked.  If invoked within the desktop window composition, it works.  If invoked at the beginning of the main function, it throws.  Presumably the issue is that the skija bindings haven't been setup at the time the constructor was called.

**Comment by kirill-grouchnikov** [comment]
I need to have a bitmap as part of my `Window` initialization. `initCompose()` works as a temporary (?) workaround

**Comment by jimgoog** [comment]
Yeah, calling `initCompose()` does appear to solve the issue.  Presumably all possible entry points to skia should check if initialized and perform an initialization.

**Comment by olonho** [comment]
We'll try to make proper init sequence in Skiko, to avoid need for explicit init.

**Comment by olonho** [comment]
Skiko 0.1.18 shall work without workaround, appropriate Compose build will be available soon.

**Comment by igordmn** [comment]
In 0.2.0-build130 we don't need to call explicitly initCompose()

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5619">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
