### ISSUE TITLE
CompositionLocal's don't pass from application to Window, or from Window to Dialog

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1110]
After fixing the [issue of high CPU usage](https://github.com/JetBrains/compose-jb/issues/1054) we have to [disable passing composition locals](https://android-review.googlesource.com/c/platform/frameworks/support/+/1808776) from application to Window and from Window to Dialog.

High CPU usage was because we accidentally used the root application Recomposer, which has the high-rate busy-loop frame clock (instead of the vsync-based window frame-clock).
After we switched to individual Recomposer's (one for each Window), we lost ability to pass composition locals:
```
application {
    CompositionLocalProvider(LocalTest provides 42) {
        Window(...) {
            val test = LocalTest.current // fails
        }
    }
}
```

To fix that, we need to extend API for Recomposer to support passing composition local scope/context from another composition, or make a single Recomposer to be able to work with different frame clocks.

**Comment by igordmn** [comment]
[The issue in Google tracker](https://partnerissuetracker.corp.google.com/issues/197667189)

**Comment by igordmn** [comment]
We won't merge CL that disables passing CompositionLocal, we will fix the issue with high CPU usage and with composition locals in the single CL.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6297">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
