### ISSUE TITLE
Update samples to AGP 7.0

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#1117]
AGP = Android Gradle Plugin

I've seen a few conversations on the issue tracker here and on slack that JB compose doesn't support AGP 7.0, but there's no "official" issue for simply supporting AGP 7, which is why I'm creating this issue.

If you take the current multiplatform-template and upgrade to AGP 7.0 then the project does not build anymore. Since AGP 7.0 is stable, we should be able to use this. This is blocking me from adopting JB compose in one of my projects since we stick to stable AGP.

https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html

**Comment by ColtonIdle** [comment]
Looks like IDEA supports AGP 7 now. Probably a good time to update the samples.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6119">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
