### ISSUE TITLE
Support sendTextInputCommand/sendImeAction in DesktopComposeTestRule

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1127]
There are not implemented now (Compose 1.0.0-alpha3):

```
        override fun sendTextInputCommand(node: SemanticsNode, command: List<EditCommand>) {
            TODO()
        }

        override fun sendImeAction(node: SemanticsNode, actionSpecified: ImeAction) {
            TODO()
        }
```

**Comment by PedroStrabeli** [comment]
Do we have a prevision on this? It would be great to have this functionality in the testing lib...
I tried a workaround of 

`.performSemanticsAction(SemanticsActions.SetText) { it.invoke(AnnotatedString("text to be inputted")) }` 

but it's not the same and it's still giving me some headaches

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6110">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
