### ISSUE TITLE
Dead lock between Snapshot.sendApplyNotifications() and composition.dispose() in ComposeSceneTest

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1136]
[Here](https://android-review.googlesource.com/c/platform/frameworks/support/+/1815119/7) we discovered, that this test:
```
ComposeSceneTest.`focus management by keys`
```
causes deadlock in the end of the test between `ComposeScene.dispose()` and `Snapshot.sendApplyNotifications()` inside GlobalSnapshotManager

**Comment by igordmn** [comment]
Also encountered in the test `ImageComposeSceneTest.run multiple ImageComposeScene`(TODO link). Deadlock is between `ComposeScene.dispose()` -> `Composition.dispose()` and `Snapshot.sendApplyNotifications()` -> `Composition.recordModificationsOf`

**Comment by igordmn** [comment]
See https://issuetracker.google.com/issues/202967533

**Comment by igordmn** [comment]
Fixed, the test is enabled again in androidx-main branch

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6136">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
