### ISSUE TITLE
Please make `DropdownMenu` more customizable

### ISSUE THREAD

**Issue by AzimMuradov** [JetBrains/compose-jb#1138]
# The problem

Make a semi-transparent drop-down menu.

![expected](https://user-images.githubusercontent.com/31899809/132033108-c7436d10-97c5-4f40-9307-4043b6fa7043.png)

## Using `Modifier`

Currently, if we try to modify the background of a `DropdownMenu` (**with some levels of transparency**), we will fail:

![white](https://user-images.githubusercontent.com/31899809/132031535-bf6a7584-60fd-4ec9-9213-7eb8e501f53b.png)

```kotlin
var expanded by remember { mutableStateOf(false) }

Box(modifier) {
    TextButton(modifier = Modifier.matchParentSize(), onClick = { expanded = true }) {
        Text(text = "Menu")
    }
    DropdownMenu(
        expanded = expanded,
        onDismissRequest = { expanded = false },
        modifier = Modifier.background(color = Color.Transparent)
    ) {
        repeat(times = 5) {
            DropdownMenuItem(
                onClick = {},
                modifier = Modifier.background(color = Color.Transparent),
            ) {
                Text(
                    text = "item $it",
                    modifier = Modifier.background(color = Color.Transparent),
                    color = Color.Black,
                )
            }
        }
    }
}
```

## Using `DesktopMaterialTheme`

The only actual way to make it transparent is to change **theme** colors (to be precise the **surface** color):

![transparent](https://user-images.githubusercontent.com/31899809/132031495-617863d2-46c0-4795-8082-49fe7b2141c2.png)

```kotlin
var expanded by remember { mutableStateOf(false) }

Box(modifier) {
    TextButton(modifier = Modifier.matchParentSize(), onClick = { expanded = true }) {
        Text(text = "Menu")
    }
    DesktopMaterialTheme(colors = lightColors(surface = Color.Transparent)) {
        DropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false },
            modifier = Modifier.background(color = Color.Transparent)
        ) {
            repeat(times = 5) {
                DropdownMenuItem(
                    onClick = {},
                    modifier = Modifier.background(color = Color.Transparent),
                ) {
                    Text(
                        text = "item $it",
                        modifier = Modifier.background(color = Color.Transparent),
                        color = Color.Black,
                    )
                }
            }
        }
    }
}
```

### But we get another problem (elevation effects?)

This leads to the possible root of this problem:

After looking into the source code I saw that it uses the `Card` composable inside the `DropdownMenu`:

https://github.com/JetBrains/androidx/blob/jb-main/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Menu.kt#L116

Sadly, it uses default `Card` parameters:

https://github.com/JetBrains/androidx/blob/jb-main/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Card.kt#L57

# Possible solutions

Please, make `DropdownMenu` more customizable. I know this is how it was implemented in Jetpack Compose, but this is really a missing feature.

For example, the `DropdownMenu` might just provide ways to customize the `Card` inside it, or you might just get rid of it and reimplement the `DropdownMenu`, possibly fixing other issues like #587 or #841.

**Comment by AzimMuradov** [comment]
Could the last problem (with elevation) be related to #55?

**Comment by AzimMuradov** [comment]
After some thought, I don't think this is big a problem.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6142">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
