### ISSUE TITLE
Compose Web compiler error with build 328 and 331

### ISSUE THREAD

**Issue by BinaryEnigma01** [JetBrains/compose-jb#1139]
After updating a multiplatform project from version 310 to 331, running a compose web gradle task results in the following compilation error:
```
Execution failed for task ':web:compileKotlinJs'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

java.lang.IllegalStateException: Symbol for public androidx.compose.runtime.internal/DecoyImplementation.<init>|-3967080163744633727[0] is unbound
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.getOwner(IrPublicSymbolBase.kt:52)
        ...
```
(Whole error [here](https://pastebin.com/raw/inT3gH9p))

The same error occurs in version 328, but not in 321 (although for 310..321 the kotlin version was downgraded to 1.5.21)

**Comment by eymar** [comment]
Hi @BinaryEnigma01 ,
Is it possible to provide a sample project that can reproduce the issue? That might really help to find the cause. 
Thanks!

**Comment by BinaryEnigma01** [comment]
> do you use some libraries built on top of compose? what are their versions?

Ah, that was my bad, the problem was exactly that, I was using an old version of [Routing-Compose](https://github.com/hfhbd/routing-compose), for some reason I assumed the error would be more clear if that was the case.
Thanks for the help, sorry for the trouble.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6298">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
