### ISSUE TITLE
How to draw multi-line text? Like StaticLayout

### ISSUE THREAD

**Issue by XJianfei** [JetBrains/compose-jb#1140]
How to draw multi-line text? Like StaticLayout.

**Comment by akurasov** [comment]
Default Text component is multiline. 
E.g.

```
    singleWindowApplication {
        Box(Modifier.width(200.dp)) {
            Text(
                "Long long long Long long longLong long longLong long longLong long longLong long longLong long longLong long longtext"
            )
        }
    }

```

**Comment by XJianfei** [comment]
@akurasov Thanks, but I mean draw text in Canvas. drawIntoCanvas

**Comment by XJianfei** [comment]
I found TextLayoutResult, but it is hard to used

**Comment by XJianfei** [comment]
MultiParagraph is the answer

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6288">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
