### ISSUE TITLE
Make packageName and packageVersion accessible from code

### ISSUE THREAD

**Issue by felixdivo** [JetBrains/compose-jb#1141]
When specifying distribution fromats, one has a piece of code like the following. It would be helpful to be able to read parameters like the `packageName` and the `packageVersion` from the application code (e.g. to show it in an about/info dialog).

```kotlin
compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Msi, /* ... */)
            packageName = "My Neat Tool"
            packageVersion = "1.0.0"
        }
    }
}
```

EDIT: The date of compilation might be useful too. Overall, this feature would be very similar to Android's [`BuildConfig`](https://developer.android.com/studio/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code).

**Comment by AlexeyTsvetkov** [comment]
I don't think such functionality is necessary to have in Compose Gradle plugin.
There are plenty of ways you can take some values from a buildscript and make them available at app's runtime.

It's easy to generate a Kotlin file similar to Android's `BuildConfig`. 
To do so, you need to create a custom task, which generates a simple Kotlin class/object,
then to add the generated file to the list of compiled sources.
Here's how we do a similar thing in the Compose plugin itself:
1. The custom task, generating Kotlin code (in our case it is defined under buildSrc, but can be defined locally in script as well) https://github.com/JetBrains/compose-jb/blob/master/gradle-plugins/buildSrc/src/main/kotlin/GenerateBuildConfig.kt#L16
2. The task is registered here https://github.com/JetBrains/compose-jb/blob/master/gradle-plugins/compose/build.gradle.kts#L25
3. `compileKotlin` must depend on the generator task https://github.com/JetBrains/compose-jb/blob/master/gradle-plugins/compose/build.gradle.kts#L31
4. Finally, a dir with generated sources is added to source sets https://github.com/JetBrains/compose-jb/blob/master/gradle-plugins/compose/build.gradle.kts#L34

Alternatively, you can use a third party plugin for that. A couple examples:
* https://github.com/yshrsmz/BuildKonfig
* https://github.com/gmazzo/gradle-buildconfig-plugin

Also, here are the relevant discussions from Kotlinlang Community Slack:
* https://kotlinlang.slack.com/archives/C01D6HTPATV/p1627331496160000
* https://kotlinlang.slack.com/archives/C01D6HTPATV/p1627367094163000

**Comment by felixdivo** [comment]
Thanks @AlexeyTsvetkov for pointing me to these options! I think it is not controversial to not include it then!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6305">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
