### ISSUE TITLE
The IDE support artifacts included in `compose-jb` are incompatible with current Android Studio versions

### ISSUE THREAD

**Issue by chris-hatton** [JetBrains/compose-jb#1143]
## Affected versions
JB-Compose `v1.0.0-alpha4-build331`
...in combination with...
Android Studio `Arctic Fox 2020.3.1`

## Context

The `compose-jb` _Multiplatform Gradle plugin_ provides variables to reference a whole family of **Compose** artifacts.
Relevant to this issue are the references for IDE Preview support, being:
- `compose.preview`
- `compose.uitooling`

For **Desktop** targets, these artifacts work as expected, however for **Android** targets the referenced artifacts are not compatible with current or recent versions of Android Studio; namely Arctic Fox 2020.3.1 (Patch 1 & 2).  This problem has been raised in the community a number of times and is clearly a big pain point for anyone trying to use Multiplatform Compose with both **Desktop** and **Android**, at this time (see the Slack links below).

### Action taken

- Include these tooling artifacts in the top-level application module of an Android project.
- Create a valid `@Composable` function and further annotate it with `@Preview`.

### Expected behaviour

The code editing window adopts the **Code / Split / Design** view and a visual preview of the `@Composable` function is shown.

### Actual behaviour

**Code / Split / Design** view is shown but within it the IDE only shows errors that it cannot find class `ComposeViewAdapter`.

## References

Related Slack links: [[1](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1630995132171800)], [[2](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1621266031218600)], [[3](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1630070094019200)], [[4](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1630944789355600?thread_ts=1630944582.354900&cid=CJLTWPH7S)]

There are also reports of the same issue affecting plain 'Google' Compose artifacts back in July; so possibly JetBrains Artifacts are inheriting this bug from Compose trunk at around about that time, and should now rebase on a later version?

**Comment by akurasov** [comment]
Tried in Bumblebee Canary 11 - it worked fine. Will check in AF.

**Comment by akurasov** [comment]
Played with it a bit. Intermediate results:
in AF preview is not working. I tried with wizard-generated project "Empty Compose activity" and got errors. So I switched back to BumbleBee. 

When preview is working, it still says "The following classes could not be found:
- androidx.compose.ui.tooling.preview.ComposeViewAdapter", but it doesn't impact preview run. 

However if I replace 
id 'org.jetbrains.kotlin.android'
with
id 'org.jetbrains.kotlin.multiplatform'
it stops working and I don't see the reason so far.

**Comment by akurasov** [comment]
To sum up: 
1. Currently Google interactive preview feature doesn't work with Compose MPP Android libraries. Dedicated preview works fine. 
2. AGP doesn't work well with kotlin.mpp. So it is not possible to run 'Google' preview of common code, whatever Android libraries are used. 

For now the only possible option is the following: 
1. Use Compose MPP template for MPP projects.
2. Use JB preview for common code. 
3. Enable AGP for android module and use dedicated (by button) 'Google' preview there

We are working on tooling improvement at the moment. Maybe we could also improve preview somehow.

**Comment by akurasov** [comment]
Starting with 1.0.0-beta5 (Beta release) Compose MPP uses Jetpack compose library for Android, so it should be fine now. Let me know if there are still any issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6238">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
