### ISSUE TITLE
Using javax.audio.* at common/src/desktopmain in compose multiplatform?

### ISSUE THREAD

**Issue by devingryu** [JetBrains/compose-jb#1145]
Pardon me for this basic question, but I couldn't find solution for this.

I want to use javax.audio.* package to play audio in compose desktop.
Importing javax.audio.* is available in `desktop/src/jvmMain`, but not in `common/src/desktopMain`.

Is there any way to achieve that, or is it available to call jvmMain functions(which can use javax.audio)  in desktopMain?

Thanks in advance.

**Comment by darvld** [comment]
This is outside the scope of Compose, but you could mark your function as `expect` in the common code and provide the JVM implementation in the correspoding source set. This is necessary because the common module is platform-agnostic and thus does not know of the existence of Java APIs. I would suggest you to look around the documentation for [Kotlin Multiplatform](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjbg731qe_yAhXjQzABHc4UB0gQFnoECAMQAQ&url=https%3A%2F%2Fkotlinlang.org%2Fdocs%2Fmultiplatform.html&usg=AOvVaw0GJZbHykYq2MCHuh6nkvYO) and the Kotlin Slack, it can be very helpful in this topic.

**Comment by akurasov** [comment]
Why do you want to use platform-dependent code in common module?

**Comment by devingryu** [comment]
@darvld Thanks for replying!
Is using `expect` in `desktopMain` and implementing `actual` function in `jvmMain` available? If so, my problem is solved! 

@akurasov The intention of my question was what I mentioned above. Sorry for my poor English.

**Comment by darvld** [comment]
@devingryu I can't tell without taking a look at your project, but if `desktopMain` is a common or intermediate source set you should be able to use expect/actual declarations.

**Comment by devingryu** [comment]
My project structure is just as same as default-created project in Intelllij. It looks like this:

![image](https://user-images.githubusercontent.com/79868575/132739419-ad60cc58-c9dc-4ab9-b127-a6d1b3577e44.png)

I can't use full JVM features in common-desktopMain. So I need to create expect/actual function to desktop-jvmMain, but it isn't available because those are in different modules.
I can import jvmMain fuction in desktopMain, but it seems to be not right for me. What is the best soultion for this?

**Comment by kirill-grouchnikov** [comment]
Are you going to have the matching implementation in androidMain? If not, why go through the trouble of doing this in commonMain?

**Comment by devingryu** [comment]
@kirill-grouchnikov Of course I will! I already implemented audio system for android using exoplayer. Now I need to implement it on desktop system.
Why choose multiplatform system if you won't use android?

**Comment by akurasov** [comment]
@devingryu 
I tried to reproduce your case and I could use java API in common/desktopMain and can't in common/commonMain. 

Can you share some reproducer, so I could take a look at it?

**Comment by devingryu** [comment]
@akurasov I found that it might be a IDE issue, because it seems that gradlew seems to run well when I import javax.audio.* manually.
My java11 is broken right now, so I will recheck and tell the result soon.

**Comment by devingryu** [comment]
@akurasov Confirmed, it is a linter bug of Android Studio.
My intellij doesn't recognize androidx.compose.*, and now Android Studio doesn't recognize javax.audio.*. Both IDE are too unstable for compose since it is in alpha state.
Anyway, thanks for helping me find this bug. I'll report this on youtrack.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6303">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
