### ISSUE TITLE
How to nest "JxBrowser"

### ISSUE THREAD

**Issue by xiao-cao-x** [JetBrains/compose-jb#1147]
I need to use the "WebView" function on the desktop platform to complete the login operation.

**Comment by akurasov** [comment]
We don't support any embedded browser frameworks at the moment, however it is in our plans (not nearest through)

**Comment by akurasov** [comment]
Diplicate of https://github.com/JetBrains/compose-jb/issues/668

**Comment by hakanai** [comment]
Someone should have also noted that using an embedded browser to show a login page is bad security practice.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6091">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
