### ISSUE TITLE
How to add JNI to Compose using gradle

### ISSUE THREAD

**Issue by dragossusi** [JetBrains/compose-jb#1150]
Hello,

I want to use JNI with compose but I fail to set things up, I have created the files needed but don't know how to link the library.

In another `application` module, I use this:

```kotlin
application {
    mainClassName = "de.schwarzrot.app.LinuxCNCClient"
    applicationDefaultJvmArgs = listOf("-Djava.library.path=$nativePath:$nativePath/lc/lib")
}
```

and it works.

For the compose module I use this:

```kotlin
compose.desktop {
    application {
        mainClass = "MainKt"
        jvmArgs("-Djava.library.path=$nativePath:$nativePath/lc/lib")
        nativeDistributions {
            targetFormats(TargetFormat.Deb)
        }
    }
}
```
And it doesn't work

**Comment by akurasov** [comment]
@dragossusi could you write you solution here, please, in case other people faces the same issue?

**Comment by dragossusi** [comment]
Sorry, this was a problem in our project, we didn't call `System.loadLibrary` in the compose module

**Comment by dragossusi** [comment]
```kotlin
jvmArgs("-Djava.library.path=${your_path_here}")
```
is enough to link the libraries

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5281">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
