### ISSUE TITLE
ClassNotFoundException: java.sql.DriverManager

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1153]
hello every one this error only occurs when i run gradle command  (runDistributable ) but this works fine in JVM
when its reached runDistributable so it issue occurred

Caused by: java.lang.ClassNotFoundException: java.sql.DriverManager

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5280">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
