### ISSUE TITLE
Failed to Start JVM

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1154]
i already submitted this issue but no some help me again i wrote it 
when i add external lib like mysql connector j in JVM all works but when i run gradle command runDistributable 
an exception throw java.lang.ClassNotFoundException: java.sql.Driver

but this works great inside JVM , this issue only occurs outside from JVM what is cause

**Comment by FlyingYu-Z** [comment]
add the following code to nativeDistributions in build.gradle.kts

modules("java.compiler", "java.instrument" , "java.sql", "jdk.unsupported")

like：
![image](https://user-images.githubusercontent.com/23566361/133068464-019e6663-5ab1-4ecd-8b66-9178e326f010.png)

also,you can run the command to get the modules
![image](https://user-images.githubusercontent.com/23566361/133068561-eb797804-b972-4432-bc95-3321c365ff68.png)

close the issue if you solve the problem please

**Comment by memonahmedanees** [comment]
ok thanks

**Comment by ArystanK** [comment]
@FlyingYu-Z , when I try to run suffestRuntimeModules I am getting a MultiReleaseException, but I have only one single release block

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5279">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
