### ISSUE TITLE
Ability to map "Jetpack Compose for Desktop" version to "Jetpack Compose" version

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#116]
I.e.:

0.1.0-m1-build62 -> 1.0.0-alpha07
0.2.0-build124 ->1.0.0-alpha08

It will be helpful to align with Jetpack Compose documentation/tutorials.

**Comment by c5inco** [comment]
Is there a way to know this now? That is what version of Jetpack Compose from Google is being used in CD?

**Comment by igordmn** [comment]
> Is there a way to know this now? That is what version of Jetpack Compose from Google is being used in CD?

See https://github.com/JetBrains/compose-jb/issues/272#issuecomment-765230424

**Comment by igordmn** [comment]
We post this information in the stable release notes now ([example](https://github.com/JetBrains/compose-jb/blob/master/CHANGELOG.md#updated-dependencies))

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5615">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
