### ISSUE TITLE
Preview Painter resources not working

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/compose-jb#1160]
It does nothing when you click the button to preview and the preview stops working until you reboot the IDE.

**Comment by ialokim** [comment]
I have encountered the same issue as soon as some image resource has been used. The following example code leads to a blocking preview which can only be made to work again after reloading (deactivating + activating) the plugin or after an IDE restart.

```kotlin
@Preview
@Composable
fun Example() {
    Image(painterResource("example.png"), "image")
}
```

This is with Kotlin 1.5.21, Compose for Desktop version 1.0.0-alpha3 and the plugin in version 1.0.0-alpha4-build366.

**Comment by olonho** [comment]
Need to improve general stability and diagosability of Preview plugin,

**Comment by AlexeyTsvetkov** [comment]
Seems to be fixed with https://github.com/JetBrains/compose-jb/pull/1458 after all

**Comment by JavierSegoviaCordoba** [comment]
I still see this issue with 1.0.1 when using Android vector drawables

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5274">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
