### ISSUE TITLE
  a duplicate but no duplicate handling strategy has been set --Demo codeviewer

### ISSUE THREAD

**Issue by CMingTseng** [JetBrains/compose-jb#1162]
Dear Sir

if use the resources font will get 

Entry font/jetbrainsmono_bold.ttf is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

https://youtrack.jetbrains.com/issue/KT-46165

**Comment by akurasov** [comment]
@olonho should we have a default duplicates resolution strategy, what do you think?

**Comment by akurasov** [comment]
It looks like a Kotlin issue, not a Compose one.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5273">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
