### ISSUE TITLE
Render loop stops when using dropdown menus in resource intensive applications

### ISSUE THREAD

**Issue by AzimMuradov** [JetBrains/compose-jb#1168]
# Bug (render loop stops when using dropdown menus in resource intensive applications)

I sometimes (randomly) have issues using dropdown menus in resource intensive applications, **but I don't see any exceptions thrown inside the IDE**, so I can't catch them. It just stops render loop similar to #663, **but without any exception thrown**. The only way to workaround this issue is to restart the app or close the window.

## When happens:

I am currently working on a fairly resource intensive application, so this error appears quite often (only when I use the dropdowns or when I use dropdowns rewritten from scratch, which makes me think that this error might be related to the popups or the other parts of the dropdown menu).

I saw a correlation between the frequency of these issues and how much resources were left on my computer.

I even started to notice that when I don't use any screen recording apps, the frequency of this error drops (but it still happens).

## Reproduced on a new clean project

To prove that this error can occur in any project, I tried to reproduce it in a newly created application.

**NOTE:** Since this application was not really resource intensive, it took quite a long time before the crash occurred, to trigger it I run a bunch of resource intensive applications in the background.

Recorded user-friendly crush:

**NOTE:** Screen glitches due to screen recording software (only appear in video, probably due to low fps).

![user-friendly-crush](https://user-images.githubusercontent.com/31899809/133455050-98cef633-d079-4e92-aae6-dd1d80ebc9eb.gif)

As you can see, the render loop stops at the end of this video.

You can even see that the left button is still lighter in color, like when it was pressed.

### Main.kt

```kotlin
/* imports */

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        DesktopMaterialTheme {
            Row {
                repeat (times = 3) {
                    var expanded by remember { mutableStateOf(false) }

                    Box(Modifier.weight(1f)) {
                        Button(onClick = { expanded = true }) {
                            Text("Click me", fontSize = 32.sp)
                        }
                        DropdownMenu(
                            expanded = expanded,
                            onDismissRequest = { expanded = false },
                            modifier = Modifier.requiredHeightIn(max = 300.dp)
                        ) {
                            for (c in 'A'..'Z') {
                                DropdownMenuItem(
                                    onClick = {},
                                    modifier = Modifier.wrapContentSize()
                                ) { Text(text = "$c") }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

### Software and Hardware:

- Compose version: 1.0.0-alpha4-build348
- Kotlin version: 1.5.30
- JVM target: 16
- OS: Linux x86_64
- CPU: Intel i5-8400
- GPU: Intel UHD Graphics 630

**Comment by AzimMuradov** [comment]
I was unable to catch this issue on **Windows** even when I tried really hard (so it might be a **Linux** issue, but I'm not sure).

**Comment by AzimMuradov** [comment]
Update on Linux: I also notice this issue in animations (not related to dropdown menus).

**Comment by akurasov** [comment]
@igordmn Looks like another performance issue on linux

**Comment by igordmn** [comment]
It is probably will be fixed in a week. I have fixed it in [skiko](https://github.com/JetBrains/skiko/pull/211)

This issue helped me to narrow the freezes, thanks :).

**Comment by igordmn** [comment]
>narrow the freezes

BTW, I only experienced it after 2 minutes of clicking on virtual machine with Ubuntu

**Comment by AzimMuradov** [comment]
> It is probably will be fixed in a week. I have fixed it in [skiko](https://github.com/JetBrains/skiko/pull/211)

I've been testing this for several days, this bug really doesn't occur anymore. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5270">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
