### ISSUE TITLE
DropdownMenu is neither scrollable nor showing up when list is large

### ISSUE THREAD

**Issue by atsushieno** [JetBrains/compose-jb#1178]
When a DropdownMenu has quite a lot of items to show, the list is shown as much space as it can (or some measure like that) and it is scrollable on Android. Current Desktop implementation, on the other hand, is not scrollable, and it does not appropriately show the list content. It somehow goes "up" and seem to render to negative (upward) direction.

----

Attaching sshots on Android and Desktop, from [my example repro application](https://github.com/atsushieno/kmmk):

Android, Dropdown not shown:
![dropdownmenu-android-1](https://user-images.githubusercontent.com/53929/133907440-8cfdd80b-eddf-49c8-8156-925def773d17.png)

Android, Dropdown shown (short of space for everything):
![dropdownmenu-android-2](https://user-images.githubusercontent.com/53929/133907441-ee3e855d-661c-4776-9720-aa4f58704dc6.png)

Android, scrolled down to bottom:
![dropdownmenu-android-3](https://user-images.githubusercontent.com/53929/133907442-7c8285e2-0139-49bb-9556-ffbabf574e14.png)

Desktop, Dropdown not shown:
![dropdownmenu-desktop-1](https://user-images.githubusercontent.com/53929/133907445-082b01b4-beed-4954-b644-11ad4153d05b.png)

Desktop Dropdown shown, but it only renders slight shadow **above** the text button.
![dropdownmenu-desktop-2](https://user-images.githubusercontent.com/53929/133907477-ee8cbfd8-03a2-421e-8527-5cd33ac15d14.png)

Desktop, Dropdown shown correctly **only if** the window has enough space.
![dropdownmenu-desktop-3](https://user-images.githubusercontent.com/53929/133907446-2b9ab085-1e56-4525-906d-258dd6d76402.png)

----

Confirmed with Compose plugin: id("org.jetbrains.compose") version "1.0.0-alpha3"

**Comment by akurasov** [comment]
Hi! Am I correct that minimal reproducer should be TextField + context menu larger than screen size?

**Comment by atsushieno** [comment]
> Am I correct that minimal reproducer should be TextField + context menu larger than screen size?

Yes! To be precise, not picky, if you mean Android then yes. If you mean Desktop, I think it is "larger than the window size".

**Comment by akurasov** [comment]
I tried to create simple reproducer and it worked fine: 

```
import androidx.compose.desktop.DesktopMaterialTheme
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.Text
import androidx.compose.material.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication


@OptIn(ExperimentalComposeUiApi::class)
fun main() {
    singleWindowApplication() {
        contextMenuDemo()
    }
}


@ExperimentalComposeUiApi
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun contextMenuDemo() {
    DesktopMaterialTheme {
        val text = remember {mutableStateOf("Hello!")}
        ContextMenuDataProvider(
            items = {
                listOf(ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" },
                    ContextMenuItem("Clear") { text.value = "" }
                    )
            }
        ) {
            TextField(
                value = text.value,
                onValueChange = { text.value = it },
                label = { Text(text = "Input") }
            )
        }
    }
}

```

Could you check if worked fine on your env too?

**Comment by atsushieno** [comment]
ContextMenu seems to work fine, so I guess DropdownMenu is a different beast.

**Comment by igordmn** [comment]
This should be fixed in 1.0.0-rc3. Let us know, if you still have issues with scrolling

**Comment by atsushieno** [comment]
Verified it is fixed. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5263">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
