### ISSUE TITLE
API for creation windows with round corners

### ISSUE THREAD

**Issue by TONY-All** [JetBrains/compose-jb#1179]
I tried my best, but it still has 3 buttons like this:
 <img width="504" alt="image" src="https://user-images.githubusercontent.com/39231698/133917835-48848d1f-1792-497d-83ec-cda5773db798.png">.
But Jetbrains Toolbox don't have them...
<img width="552" alt="image" src="https://user-images.githubusercontent.com/39231698/133917859-01f7ba6d-beb2-4f0e-9620-740fa475a551.png">

**Comment by akurasov** [comment]
Doesn't Window(undecorated = true) work for you?

**Comment by FlyingYu-Z** [comment]
> Doesn't Window(undecorated = true) work for you?

but how to make round corner for window?

**Comment by akurasov** [comment]
@FlyingYu-Z 
We don't have compose api for this. But it could be done using native API's passing them window.windowHandle

**Comment by Rsedaikin** [comment]
You can do this with transparency support (coming soon) or modifying `NSWindow` via JNI and using `ComposeWindow` directly. Something like this (not tested):
Kotlin part:
```
fun main() {
    val window = ComposeWindow()
    window.preferredSize = Dimension(800, 600)
    window.pack()
    if (org.jetbrains.skiko.hostOs == org.jetbrains.skiko.OS.MacOS) {
      removeTitleBar(window.windowHandle)
    }
    window.setContent {
      // content
    }
    window.isVisible = true
}

external fun removeTitleBar(window: Long)
```

Native Object-C part:
```
JNIEXPORT void JNICALL Java_MyApplication_MainKt_removeTitleBar(
    JNIEnv * env, jobject object, jlong windowHandle)
{
  dispatch_async(dispatch_get_main_queue(), ^{
      NSWindow *window = (NSWindow*)windowHandle;
      window.styleMask = (window.styleMask | NSWindowStyleMaskFullSizeContentView) &
              ~(NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable | NSWindowStyleMaskClosable);
      window.titleVisibility = NSWindowTitleHidden;
      window.titlebarAppearsTransparent = YES;
  });
}
```

**Comment by akurasov** [comment]
I meant via transparency support. I believe it is better way, since we have it now.

**Comment by rylexr** [comment]
@TONY-All hey I'm trying to do something similar to your example. How did you achieve it? Could you please share a snippet of your code?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5262">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
