### ISSUE TITLE
Move Web to Skia

### ISSUE THREAD

**Issue by JimeFuture** [JetBrains/compose-jb#1182]
As i was seeing development in SKIKO on js Platform via Wasm has started.
My question is if there is the plan to provide Web implementation of the current Desktop Widgets based on Skia in the near future?
Should not be a struggle ones SKIKO for js is ready or not? 
Using same structure and data as Desktop is nice, but even Useing same UI Widgets would be even better. And in my opinion Web and Desktop are closer in needed UI functionality than Desktop and Android. 

Best Regards
Jim

**Comment by akurasov** [comment]
Hi! It is one of the ways we are going to follow. However as always in real life, there could be significant obstacles there, and at the moment it is hard to predict if this future will be near or distant.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5259">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
