### ISSUE TITLE
Crashed when I instantiated the java class in Button's onClick{}

### ISSUE THREAD

**Issue by tzSharing** [JetBrains/compose-jb#1183]
I have a util class which is written in java. But it crashes when I call and instantiate it in compose>Button's onClick{}.
The program compiles and runs normally, and it crashes only when the button is clicked.
exception details：
![error](https://user-images.githubusercontent.com/90680948/134151652-f867adaf-2bef-4481-b6ad-fd28ba6b9607.jpg)

**Comment by igordmn** [comment]
It is probably because you have placed `Util` in `kotlin` folder.

To fix, move Util to `java` folder or apply `java` plugin explicitly and add `main/kotlin` to `java.srcDirs`:
```
plugins {
    kotlin("jvm") version "1.5.30"
    java
    id("org.jetbrains.compose") version "1.0.0-alpha4-build328"
}
...
sourceSets.main {
    java.srcDirs("src/main/kotlin")
}
```

**Comment by tzSharing** [comment]
@igordmn    Yeah, I solved it by creating a java folder to place it. Thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5258">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
