### ISSUE TITLE
1.0.0-alphaX requires androidx annotation on desktop (linux)

### ISSUE THREAD

**Issue by gandrewstone** [JetBrains/compose-jb#1186]
I'm trying to move from 0.2.0 to 1.0.0-alphaX but I get a dependency failure on androidx annotation (1.2.0).  This is weird because this is not an android (or multiplatform) app.  I dropped down to 0.5.0-build270 and it works fine.

relevant build.gradle.kts portion:

"""
import org.jetbrains.compose.compose
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

repositories {
    gradlePluginPortal()
    mavenCentral()
    mavenLocal()
    google()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev") }
}

plugins {
    kotlin("jvm") version "1.5.21"
    // (doesn't work) id("org.jetbrains.compose") version "1.0.0-alpha2"
    id("org.jetbrains.compose") version "0.5.0-build270"
    application
    distribution
}

...
"""

The exact error is:

"""
> Could not resolve all files for configuration ':app:compileClasspath'.
   > Could not find androidx.annotation:annotation:1.2.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/androidx/annotation/annotation/1.2.0/annotation-1.2.0.pom
       - https://repo.maven.apache.org/maven2/androidx/annotation/annotation/1.2.0/annotation-1.2.0.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/androidx/annotation/annotation/1.2.0/annotation-1.2.0.pom
     Required by:
         project :app > org.jetbrains.compose.desktop:desktop-jvm-linux-x64:1.0.0-alpha2 > org.jetbrains.compose.desktop:desktop:1.0.0-alpha2 > org.jetbrains.compose.desktop:desktop-jvm:1.0.0-alpha2 > org.jetbrains.compose.ui:ui-tooling-preview:1.0.0-alpha2 > org.jetbrains.compose.ui:ui-tooling-preview-desktop:1.0.0-alpha2
"""

**Comment by igordmn** [comment]
I suppose desktop target don't need it.

Found it [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-tooling-preview/build.gradle;l=52;drc=f656a15b17e0ff8f3ac11c670a0e57a2063a111a)

After we remove it, we won't need  `google()` repository, and can remove it from our examples/templates

**Comment by gandrewstone** [comment]
Thanks!

**Comment by igordmn** [comment]
`google()` repo shouldn't be required anymore in `1.0.0-beta6-dev464`

**Comment by gandrewstone** [comment]
Verified!  Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5256">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
