### ISSUE TITLE
how to focus autometically 

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1188]
hi to all .  i have to say that tried many times . through focusRequest handler modifier  , and in event listener but cant focus my button auto when i open certain window if any one know to please update me

**Comment by memonahmedanees** [comment]
solved thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5255">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
