### ISSUE TITLE
(question) is ios support planned?

### ISSUE THREAD

**Issue by RedStoneCats101** [JetBrains/compose-jb#1189]
I am new so am sorry if this is in the incorrect spot

One of the main advantages of Kotlin over Java is Kotlin Multiplatform and the ability to share common code for all targets (android, iOS, web, native and JVM ) now that compose-jb supports Web as well as JVM and native(i think) the only obvious thing missing is iOS

## The Issue
It is now conceivable to to have a program that targets android, iOS, wed and native and use compose-jb for all UI except iOS witch would need to use swiftUI so if  compose-jb could be used instead of SwiftUI ( so that the same @Composable fun can display UI on iOS as well to avoid also having to learn SwiftUI to target iOS ​) this is a problem because as seen in this exaple

### common.kt
```kotlin

@Composable
fun ui() {
   profileImage()
}


@Composable
expect fun profileImage()
```

### jvm.kt
```kotlin
@Composable
 actual fun profileImage() {
     Image("path/to/image") 
}
```

but on iOS this will not work and will need to use SwiftUI (or other) so it is not possible to share the common navigation code, general UI layouts ect 

### iOS.kt (ideally this would be possible)
```kotlin
@Composable
 actual fun profileImage() {
     Image("iOS/path/to/image") 
}
```

Skia seems to support iOS (flutter appears to use Skia for something very similar and supports iOS) if it is pposable to port compose-jb to iOS how would  this be achieved ?

Thanks this is a question and suggestion only

**Comment by akurasov** [comment]
Hi! Yes, we understand importance of this platform support and are investigating our options here.

**Comment by RedStoneCats101** [comment]
Thank you

**Comment by Ndrocchietto** [comment]
community is preying

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5254">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
