### ISSUE TITLE
Apps have a black bar on Wayland/Gnome until window is moved

### ISSUE THREAD

**Issue by bjonnh** [JetBrains/compose-jb#119]
You can see a screenshot here: https://imgur.com/a/O5N4gwO

moving the window make that black bar disappears. 

(This doesn't happen with GTK, QT, SWING, JAVAFX…)
I'm using Wayland with Intel GPU using Gnome 3.38.1

**Comment by Rsedaikin** [comment]
Hi! Could you please give me information about OS (name + version)?

**Comment by olonho** [comment]
And JVM vendor and version, please. Also, could you please try with some other JVM implementation.

**Comment by bjonnh** [comment]
I'll close that as I did see that also on a JavaFX application today (but not all its windows). So it is not a Compose specific bug.

JDK is OpenJDK 14.0.2, tested on two wayland/gnome installs with Intel and AMD Gpus.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5612">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
