### ISSUE TITLE
How to disable build warning ?

### ISSUE THREAD

**Issue by Shabinder** [JetBrains/compose-jb#1191]
I dont use Compose-Web and the said issue #738 doesn't affect me, so how can I disable following Warning ?

```

>>> COMPOSE WARNING
>>> Project `providers` has `compose` and `kotlinx.serialization` plugins applied!
>>> Consider using these plugins in separate modules to avoid compilation errors
>>> Check more details here: https://github.com/JetBrains/compose-jb/issues/738
```

**Comment by darvld** [comment]
I believe the warning was removed in #1167. The next release will probably include those changes.

**Comment by Shabinder** [comment]
Gr8

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5253">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
