### ISSUE TITLE
Force dark mode on desktop

### ISSUE THREAD

**Issue by allquixotic** [JetBrains/compose-jb#1192]
Hi, is there any way to force dark mode on Desktop? If it detects system dark mode, it is detecting it wrong on Windows 11, but I want to be able to specify it anyway. Searched the examples and couldn't find anything.

**Comment by darvld** [comment]
Compose doesn't detect the system theme by default. You can use `MaterialTheme(darkColors())` to use a fixed dark mode for your app. If you need it to fit the system theme you can use [this library](https://github.com/Dansoftowner/jSystemThemeDetector) to update a `MutableState` and react to it (by passing `lightColors()` or `darkColors()` respectively to your `MaterialTheme` call).

**Comment by allquixotic** [comment]
It doesn't work. I'm using the default "Hello World" app that IDEA creates when you make a new Desktop Compose project, and it always displays light theme even when I add `darkColors()`. Here's the code:

```
@Composable
@Preview
fun app() {
    var text by remember { mutableStateOf("Hello, World!") }

    DesktopMaterialTheme(darkColors()) {

            Button(onClick = {

                text = "Hello, Desktop!"
            }) {
                Text(text)
            }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        app()
    }
}
```

If I change `DesktopMaterialTheme` to `MaterialTheme`, there is no change in the output.

**Comment by darvld** [comment]
You need to use a `Surface` to fill all available space, and then insert your content. Otherwise the default window background is shown, and the content color remains unchanged. Something like:
```kotlin
DesktopMaterialTheme(darkColors()) {
    Surface(Modifier.fillMaxSize()){
        // your content here...
    }
}
```

**Comment by akurasov** [comment]
@allquixotic does it answer you question?

**Comment by allquixotic** [comment]
It certainly helps, but now the button fills up the entire space of the window, instead of being a default-sized button. I assume I need to stick elements in a grid, vertical box, or other sort of container to make them take up their minimum size. The difficulty I am having is that most of the docs out there are about the upstream Compose, not compose-jb. I'm struggling with the learning curve for compose-jb despite significant past experience with GTK 2/3, Swing, SWT, and WinForms.

**Comment by allquixotic** [comment]
I will take my questions to Slack. Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5252">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
