### ISSUE TITLE
Clicking stops working when moving a window to different monitor with different scaling setting on Windows

### ISSUE THREAD

**Issue by ktkahkon** [JetBrains/compose-jb#1193]
OS: Windows 10
Compose version: 1.0.0-alpha4-build348

I have my laptop connected to an external monitor which has 100% scaling set in the display options that Windows 10 provides. The laptop screen, on the other hand, has scaling set to 125%. When I drag a window from the main monitor to the laptop screen, clicking on a composable that has a clickable modifier stops working. 

If I set my laptop screen to have 100% scaling, so that both monitors have the same scaling, then everything works fine.

Also, if I add a row of buttons to a lazy list and scroll the button away from the screen and back, then the button works again after being moved across the monitors. So recomposing the button seems to make clicking work properly again.

**Comment by willflier** [comment]
same in mac

**Comment by jan222ik** [comment]
States are also not updated, e.g I have a hover that changes the background colour of an already displayed element.

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta6-dev455.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5251">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
