### ISSUE TITLE
javax.naming.NamingException during JDBC Usage

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1194]
hi to all , i rename it during JDBC because when i use statement like create create statement or retrieved data from mysql  otherwise ok ,  i already add modules in gradle  (java.sql) what should i do . in JVM works perfect . this error only show outside from JVM

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5250">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
