### ISSUE TITLE
How to get AWT Frame of current window using new Compose Window API?

### ISSUE THREAD

**Issue by ggoraa** [JetBrains/compose-jb#1195]
Self explanatory

**Comment by akurasov** [comment]
Copying answer from telegram - the second example here https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new#swing-interoperability

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5249">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
