### ISSUE TITLE
Why I can't use a library in commonMain of Jetpack Compose Multiplatform ?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#1197]
1、I introduced OkHttp `implementation("com.squareup.okhttp3:okhttp:4.9.0")` to `${projectDir}/common/build.gradle.kts`

![image](https://user-images.githubusercontent.com/23566361/134793604-91fd2933-da93-4c7a-8494-e6a823019b76.png)

2、But I can't use it in `${projectDir}/common/commonMain/kotlin/cn/beingyi/sckit/App.kt`

![image](https://user-images.githubusercontent.com/23566361/134793669-e875cc39-44ae-4e03-a9e4-4898027ad31f.png)

3、However,I can use OkhttpClient in `${projectDir}/common/androidMain/kotlin/cn/beingyi/sckit/AndroidApp.kt`

![image](https://user-images.githubusercontent.com/23566361/134793715-4155544a-00d9-4da3-819a-235d579a6e76.png)

Why I can't use OkHttpClient in commonMain,and how to solve it?

**Comment by EvgeniyKu** [comment]
In common code you should use common libraries https://github.com/AAkira/Kotlin-Multiplatform-Libraries

**Comment by FlyingYu-Z** [comment]
> In common code you should use common libraries https://github.com/AAkira/Kotlin-Multiplatform-Libraries

but i only want make app for desktop and android, and i want use other .jar file in commonMain,Is there any solution?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5248">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
