### ISSUE TITLE
Code viewer hangs when clicking on a picture

### ISSUE THREAD

**Issue by bjonnh** [JetBrains/compose-jb#120]
I tried to click on compose-logo.png (a 44kb png) and the application hanged.

**Comment by Rsedaikin** [comment]
Hi! Please, try to reproduce with version `0.3.0-build138`. I can open a png image with a size of 66kb.

**Comment by olonho** [comment]
Seems no longer reproducible.

**Comment by bjonnh** [comment]
It doesn't seem to hang anymore, I agree, however it hangs randomly now when navigating directories. Will try to take a stacktrace to understand what happens and make a new issue.

**Comment by bjonnh** [comment]
Please see #514 as it may have been related to what I experienced.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5611">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
