### ISSUE TITLE
Status for Desktop looks pretty broken

### ISSUE THREAD

**Issue by elect86** [JetBrains/compose-jb#1209]
I wanted to try Compose, but it looks like from the whole repo, I can only run `coreviewer` (`:desktop:run`)

I tried to sync multiple times, but only few things improved.

![Screenshot from 2021-09-28 16-58-15](https://user-images.githubusercontent.com/5020626/135112835-07e70772-8858-46b4-aea5-d53dbba9cb5d.png)

In particular I wanted to run the `widgetsgallery` but it keeps complaining

> Executing Gradle tasks as part of a build without a settings file is not supported. Make sure that you are executing Gradle from a directory within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root directory.

**Comment by elect86** [comment]
I deleted everything and re-clone the whole project, now sources are not even load
![Screenshot from 2021-09-28 17-14-10](https://user-images.githubusercontent.com/5020626/135115588-a64dad90-91ff-4501-9d3a-8ecd10ee8580.png)
ed

**Comment by elect86** [comment]
Opening `compose-jb/examples/widgets-gallery/settings.gradle.kts` worked

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5243">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
