### ISSUE TITLE
Unsupported OS arch: x86

### ISSUE THREAD

**Issue by Nico-kun1316** [JetBrains/compose-jb#1213]
I get this error while trying to run/package my app under a 32bit jvm (windows).
Are there any plans to support 32bit JVMs or is that out of the question?

**Comment by olonho** [comment]
32-bit Windows is not supported and unlikely will

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5239">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
