### ISSUE TITLE
Support performMouseInput in tests

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1216]
```
rule.onNodeWithTag("scrollbar").performMouseInput {
    click(Offset(0f, 26f))
}
```

We need to implement androidx.compose.ui.test.DesktopInputDispatcher for that:

![image](https://user-images.githubusercontent.com/5963351/135595775-4b84428e-84f4-41a3-a680-c1f3ce3a2ce1.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5236">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
