### ISSUE TITLE
Scrollbar's hover stuck after we hover the window title

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1218]
Compose 1.0.0-alpha4-build366

1. Drag scrollbar to the middle
2. Press mouse on the scrollbar
3. Move mouse to the container
4. Move mouse to the titlebar
5. Move mouse to the container
6. Release mouse

Expected:
Scrollbar isn't hovered

Actual:
Scrollbar is hovered

https://user-images.githubusercontent.com/5963351/135604860-d1b61327-1474-481e-a089-67cbea4499f0.mp4

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-rc3

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5234">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
