### ISSUE TITLE
Moving window across screens causes composable interactions to stop working

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-jb#1223]
I have two displays on my Win10 machine. They have different UI scaling factors as they have different resolutions, but the same physical size. When I start an app from the IDE, it starts on one screen and all works well. If I move it to the other screen, the app interactions (clicking, focus, typing) stop working entirely. Menus still work.

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta6-dev455.

**Comment by rock3r** [comment]
Can confirm it now works fine :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6223">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
