### ISSUE TITLE
Codeviewer. Selection doesn't work when we drag from a line to the line above

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1234]
Compose 0.0.0-sync-2010-10-01-build378

https://user-images.githubusercontent.com/5963351/136254174-51f12bc7-58e4-4071-840d-e3dd3b8e46a5.mp4

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6257">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
