### ISSUE TITLE
Composable Type mismatch Found Any

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#1253]
I'm using Kotlin `1.5.31`
compose desktop `1.0.0-alpha4-build398`
Gradle `7.1`
IntelliJ IDEA Ultimate:
```
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 12
Non-Bundled Plugins: Batch Scripts Support (1.0.12), co.anbora.labs.firebase-syntax-highlighting (2.6.6), mobi.hsz.idea.gitignore (4.2.0), CMD Support (1.0.5), PlantUML integration (5.6.1), Pythonid (212.5284.44), intellij.prettierJS (212.5080.8), com.jetbrains.php (212.5284.49), com.github.iguissouma.nxconsole (0.33.0), com.intellij.nativeDebug (212.5284.19), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), org.jetbrains.compose.desktop.ide (1.0.0-alpha4-build398), com.squareup.sqldelight (1.5.2)
Kotlin: 212-1.5.31-release-546-IJ4638.7
```

Here is an error that I think is happening due to the `@Composable` in the type system.

```Kotlin
class Test(val flow: Flow<BufferedImage?>)

@Composable
private fun Screen(test: Test) {
    val capture: ImageBitmap = test.flow
        .map { it?.toComposeBitmap() }
        .collectAsState(Dispatchers.Default).value ?: return

    Image(capture, "")
}
```

Here is the error:
```
Type mismatch.
Required:
ImageBitmap
Found:
Any
```

<img width="1121" alt="Screen Shot 2021-10-12 at 9 40 04 PM" src="https://user-images.githubusercontent.com/871169/137052111-adf6a16b-0952-49e8-959a-d23378a63ff7.png">

When I break down  the code further you can see that the type problem is happening with the Composable function.

<img width="1196" alt="Screen Shot 2021-10-12 at 9 43 38 PM" src="https://user-images.githubusercontent.com/871169/137052410-63f2e58e-d807-4fe1-91ae-4fee21d7a4dd.png">

The work around  is to  cast:
```Kotlin
class Test(val flow: Flow<BufferedImage?>)

@Composable
private fun Screen(test: Test) {
    val flow: Flow<BufferedImage?> = test.flow
    val imageBitmapFlow: Flow<ImageBitmap?> = flow.map { it?.toComposeImageBitmap() }
    val capture: ImageBitmap = imageBitmapFlow.collectAsState(Dispatchers.Default).value as ImageBitmap? ?: return

    Image(capture, "")
}
```

**Comment by ScottPierce** [comment]
Nevermind. I see now that I've passed Dispatchers.Default as the initial state fort he `collectAsState` function which is what's  causing  this problem.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6285">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
