### ISSUE TITLE
Unable to switch input method, (Ubuntu20.04, unity, fcitx)

### ISSUE THREAD

**Issue by xing2387** [JetBrains/compose-jb#1258]
Tested in [example "notpad"](https://github.com/JetBrains/compose-jb/tree/master/examples/notepad), which using plugins `kotlin("jvm") version "1.5.21"` and `id("org.jetbrains.compose") version ("1.0.0-alpha1")`.

I can't switch to other input method (Mozc, Rime etc.) by pressing Ctrl+Space or Shift which works in other programs. Therefore i can only input English.

But after i clicked an item in MenuBar, "File" or "Settings", then is able to switch IME.

This happend in my app, and what should i do?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6131">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
