### ISSUE TITLE
Issue al compile compose web

### ISSUE THREAD

**Issue by carlosgub** [JetBrains/compose-jb#1259]
I download the template (https://github.com/JetBrains/compose-jb/tree/master/templates/web-template) and follow all the steps, and always I have the same problem, after run ./gradlew jsBrowserRun the terminal show me this error

![image](https://user-images.githubusercontent.com/30916886/137533272-6b7ee31d-7ea9-4d77-b0cf-d3a64d780d63.png)

**Comment by scottkruse** [comment]
I added this to my afterEvaluate block 

`    rootProject.plugins.withType(org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin::class.java) {
        rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().versions.webpackCli.version = "4.9.0"
    }`
    see: https://github.com/webpack/webpack-cli/issues/2990

**Comment by eymar** [comment]
the workaround is not needed anymore when using compose-for-web 1.0.1-rc2 with kotlin 1.6.10

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6164">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
