### ISSUE TITLE
tutorials/Context_Menu/README.md

### ISSUE THREAD

**Issue by allenli178** [JetBrains/compose-jb#1260]
I found an error in the README.md .
In the last case of "Context menu for an arbitrary area",I can not find "ContextMenuArea" API in your code and the "MaterialTheme" can not support context menu.I think we should use "DesktopMaterialTheme" just like in the last code.
![image](https://user-images.githubusercontent.com/53218750/137578116-10dd919b-f4af-43f0-8955-9a24150f01fe.png)

**Comment by allenli178** [comment]
1.0.0-alpha3

**Comment by akurasov** [comment]
Tested with 1.0.0-beta5(beta Release build) - everything is fine

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6261">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
