### ISSUE TITLE
Tray

### ISSUE THREAD

**Issue by allenli178** [JetBrains/compose-jb#1263]
How can I reopen window via doubleclick the tray icon?

**Comment by allenli178** [comment]
I found there is no modifier parameter in Tray so that I can't  use combinedClickable to realize doubleclick event.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6150">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
