### ISSUE TITLE
Notepad: StringIndexOutOfBoundsException when typing in Chinese

### ISSUE THREAD

**Issue by drakeet** [JetBrains/compose-jb#1264]
The input field is full of serious problems in the process of inputting Chinese:

https://user-images.githubusercontent.com/5214214/137617949-7229c000-15f1-4a69-93db-db7cf236fe6f.mp4

Input method: macOS native Pinyin input method

**Comment by akurasov** [comment]
It definitely works in 1.0.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6171">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
