### ISSUE TITLE
Closing child Dialog/Window causes parent to misbehave

### ISSUE THREAD

**Issue by sproctor** [JetBrains/compose-jb#1265]
I'm using build398 on Ubuntu. When I open a Dialog or Window from another window, it causes very strange behavior on parent window when the child window is closed. Some boxes will only show their background, some show only white.

**Comment by sproctor** [comment]
I switched back to alpha3, and the issue doesn't exist there.

**Comment by sproctor** [comment]
Sorry for the slow reply. I'm not experiencing this anymore, thank you.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6108">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
