### ISSUE TITLE
Clickable/tap gestures don't work when using layer translations.

### ISSUE THREAD

**Issue by Cybermaxke** [JetBrains/compose-jb#127]
When using a layer translation, the position of the click and tap areas don't get moved, they will remain at their original position. 

E.g. initial position. (translation is still (0,0)), double click on Testing turns it into a text field and allows the title to be modified.
![image](https://user-images.githubusercontent.com/1364375/99811746-d9198c00-2b45-11eb-8f1f-b27bf43b7e4c.png)
After moving the Testing node (by dragging), clicking on Testing doesn't trigger any events, so the title can't be modified, the tap animation is still visible.
![image](https://user-images.githubusercontent.com/1364375/99811882-06fed080-2b46-11eb-9d8c-3b1e029e3da3.png)
If the node is moved back to its original position, the events work again.

Code for ref: https://github.com/LanternPowered/Porygen/blob/77cacbb071415c211929326105a2db20d47c3b60/graph-editor/src/commonMain/kotlin/org/lanternpowered/porygen/editor/Editor.kt#L189

**Comment by igordmn** [comment]
Reproducer:
```
Box(Modifier.drawLayer(translationX = 100f)) {
    var value by remember { mutableStateOf("") }
    TextField(value, { value = it })
}
```

On Android it also doesn't work as expected

**Comment by igordmn** [comment]
Bug in the google tracker:
https://partnerissuetracker.corp.google.com/issues/174022372

**Comment by igordmn** [comment]
Isn't reproducible in 0.3.0-build150

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5605">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
