### ISSUE TITLE
Program Crashed when i use SelectionContainer in a LazyColumn

### ISSUE THREAD

**Issue by virogu** [JetBrains/compose-jb#1280]
Use SelectionContainer in a LazyColumn, it will crash
here is my exsample code:

`val state = rememberLazyListState()
    val adapter = rememberScrollbarAdapter(
        scrollState = state // TextBox height + Spacer height
    )
    val logList = remember {
        SnapshotStateList<String>()
    }
    val s = "QWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEE"
    for (i in 0..100) {
        logList.add("$i$s$s$s")
    }
    Box {
        LazyColumn(Modifier.fillMaxSize(), state) {
            items(logList) { log ->
                //SelectionContainer {
                    Text(
                        text = log,
                        modifier = Modifier.fillMaxWidth()
                    )
               // }
            }
        }
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
            adapter = adapter
        )
    }`

**Comment by akurasov** [comment]
Regretfully you code is one line with comments and I can't unpack it. Could you please paste here like a normal code, that can be copied?

**Comment by igordmn** [comment]
Is the issue exist on 1.0.0-beta5? I checked the code and it doesn't crash.

**Comment by virogu** [comment]
> Regretfully you code is one line with comments and I can't unpack it. Could you please paste here like a normal code, that can be copied?

`@Composable
fun SelectionContainerTest() {
    val state = rememberLazyListState()
    val adapter = rememberScrollbarAdapter(
        scrollState = state // TextBox height + Spacer height
    )
    val logList = remember {
        SnapshotStateList<String>()
    }
    val s = "QWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEE"
    for (i in 0..3333) {
        logList.add("$i$s")
    }
    Box {
        SelectionContainer {
            LazyColumn(Modifier.fillMaxSize(), state) {
                items(logList) { log ->
                    SelectionContainer {
                        Text(
                            text = log,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }
        }
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
            adapter = adapter
        )
    }
}`

**Comment by virogu** [comment]
> Regretfully you code is one line with comments and I can't unpack it. Could you please paste here like a normal code, that can be copied?

```
@Composable
fun SelectionContainerTest() {
    val state = rememberLazyListState()
    val adapter = rememberScrollbarAdapter(
        scrollState = state // TextBox height + Spacer height
    )
    val logList = remember {
        SnapshotStateList<String>()
    }
    val s = "QWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEE"
    for (i in 0..3333) {
        logList.add("$i$s")
    }
    Box {
        SelectionContainer {
            LazyColumn(Modifier.fillMaxSize(), state) {
                items(logList) { log ->
                    SelectionContainer {
                        Text(
                            text = log,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }
        }
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
            adapter = adapter
        )
    }
}
```

**Comment by virogu** [comment]
> Is the issue exist on 1.0.0-beta5? I checked the code and it doesn't crash.
It will crash when selecting text back and forth multiple times,  when the "item" count in LazyColumn is very large and the "text" is wrapped by "SelectionContainer".

**Comment by virogu** [comment]
> Regretfully you code is one line with comments and I can't unpack it. Could you please paste here like a normal code, that can be copied?

```
@Composable
fun SelectionContainerTest() {
    val state = rememberLazyListState()
    val adapter = rememberScrollbarAdapter(
        scrollState = state // TextBox height + Spacer height
    )
    val logList = remember {
        SnapshotStateList<String>()
    }
    val s = "QWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEE"
    for (i in 0..3333) {
        logList.add("$i$s")
    }
    Box {
            LazyColumn(Modifier.fillMaxSize(), state) {
                items(logList) { log ->
                    SelectionContainer {
                        Text(
                            text = log,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
            }
        }
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
            adapter = adapter
        )
    }
}

```

**Comment by virogu** [comment]
> SelectionContainer

Now I use the "SelectionContainer " wrapp whole "LazyColumn" rather than every "Text" item, it won`t crash, but the LazyColumn will trigger compose operation frequently when I select text

```
SelectionContainer {
    LazyColumn(Modifier.fillMaxSize(), state) {
                items(logList) { log ->
                        Text(
                            text = log,
                            modifier = Modifier.fillMaxWidth()
                        )
            }
}
```

**Comment by akurasov** [comment]
Please, open a new ticket for this topic to not mix the contexts. I close this one, as there is no crushes anymore.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6170">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
