### ISSUE TITLE
Crash when closing second window

### ISSUE THREAD

**Issue by Klurige** [JetBrains/compose-jb#1286]
The following code crashes with the attached core dump when using the window's close button (the x in the corner) but not when closing from button's onClick.
```
@Composable
@Preview
fun First(isOpen: MutableState<Boolean>) {
    MaterialTheme {
        Button(onClick = {
            isOpen.value = true
        }) {
            Text("Open second window")
        }
    }
}

@Composable
@Preview
fun Second(isOpen: MutableState<Boolean>) {
    MaterialTheme {
        Button(onClick = {
            isOpen.value = false
        }) {
            Text("Dismiss")
        }
    }
}

fun main(args: Array<String>) {
    application {
        val isOpen = remember { mutableStateOf(false) }
        Window(title = "First", onCloseRequest = { exitProcess(0) }) {
            First(isOpen)
        }

        if (isOpen.value) {
            Window(title = "Second", onCloseRequest = { isOpen.value = false }) {
                Second(isOpen)
            }
        }
    }
}

```
Running on Ubuntu 20.04.
Kotlin version 1.5.31
Compose Desktop version 1.0.0-alpha4-build398

[hs_err_pid388138.log](https://github.com/JetBrains/compose-jb/files/7385808/hs_err_pid388138.log)

**Comment by akurasov** [comment]
We have fixed crash during window closing on linux under some conditions in beta. Could you try if the crash still happens on your system on 1.0.0-beta5?

**Comment by Klurige** [comment]
Not crashing anymore in my tests. (1.0.0-beta5)

Well done!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6260">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
