### ISSUE TITLE
Scale problem after version 0.2.0-build124

### ISSUE THREAD

**Issue by cfkloss** [JetBrains/compose-jb#130]
Something is broken in version 0.2.0-build124 with respect to the scale factor when we move the application window from one monitor to another that has a different scale factor.

In version 0.1.0-build113 everything was fine as you can see in the images:

![Capture_113-1 75](https://user-images.githubusercontent.com/7118911/99860127-e009c400-2b70-11eb-832f-803b1f20de02.PNG)

![Capture_113-1 0](https://user-images.githubusercontent.com/7118911/99860145-f283fd80-2b70-11eb-8df4-928f32a9e4c7.PNG)

In version 0.2.0-build124 the problem appears:
![Capture_124-1 75](https://user-images.githubusercontent.com/7118911/99860223-337c1200-2b71-11eb-8050-26fa7d70b9ca.PNG)

![Capture_124-1 0](https://user-images.githubusercontent.com/7118911/99860231-3840c600-2b71-11eb-910c-a1cb880618ee.PNG)

This is the code I'm using

```import androidx.compose.desktop.AppManager
import androidx.compose.desktop.Window
import androidx.compose.desktop.WindowEvents
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.IntSize

fun main() {
    val scaleFactor = mutableStateOf(0.0)

    Window(
        size = IntSize(400, 300),
        events = WindowEvents(onRelocate = {
            val sf = getScaleFactor()
            if (scaleFactor.value != sf) scaleFactor.value = sf
        })
    ) {
        var text by remember { mutableStateOf("Hello, World!") }

        scaleFactor.value = getScaleFactor()
        MaterialTheme {
            Box(
                modifier = Modifier.fillMaxSize(),
                alignment = Alignment.Center
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Button(onClick = {
                        text = "Hello, Desktop!"
                    }) {
                        Text(text)
                    }

                    Text("Scale: ${scaleFactor.value}")
                }
            }
        }
    }
}

fun getScaleFactor(): Double {
    val current = AppManager.focusedWindow ?: return 0.0
    return current.window.graphicsConfiguration.defaultTransform.scaleX
}

**Comment by cfkloss** [comment]
There is also a small difference in the spacing of the letters in the texts from one version to the other.

**Comment by olonho** [comment]
Is it still reproducible with `0.2.0-build128`?

**Comment by cfkloss** [comment]
> Is it still reproducible with `0.2.0-build128`?

No, the scale problem is gone with `0.2.0-build128`.

The only thing different now is the spacing beetween the letters after `0.1.0-build113`. 

with `0.1.0-build113`:
![Capture_113-1 0](https://user-images.githubusercontent.com/7118911/100008319-09fafa80-2dac-11eb-90f7-d5702beb7b33.PNG)

with `0.2.0-build128`:
![Capture_128-1 0](https://user-images.githubusercontent.com/7118911/100008353-1aab7080-2dac-11eb-8f70-af0628b9ba0c.PNG)

I don't know which one should be considered the correct one. To me, it seems that the one from `0.1.0-build113` is better.

Should I open an issue for this spacing difference?

**Comment by olonho** [comment]
Yes, it seems to be a different problem, if problem at all.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5603">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
