### ISSUE TITLE
Memory leak when using Crossfade and loading images using skia.

### ISSUE THREAD

**Issue by timo-drick** [JetBrains/compose-jb#131]
Here is a simple code to reproduce the problem (I am using XUbuntu 20.04) Compose version: 0.2.0-build127
https://gitlab.com/compose1/minimal-compose-desktop/-/blob/crossfade_skia_image_memory_leak/src/main/kotlin/main.kt
To reproduce the problem start the app and click on the loaded image. Than an other image will be loaded. Click many times and see that the memory consumption of the app increases. When commenting the Crossfade in line 55 and uncommting line 56 clicking the images will not increase the memory consumption of the app over time.

**Comment by olonho** [comment]
Could you please provide additional analysis and check what object exactly are leaking? And does it happen with other effects?

**Comment by timo-drick** [comment]
I was able to reproduce the memory leak without using any effect. It looks like that it is a problem of the underlying compose caching maybe?
Please see current code:
https://gitlab.com/compose1/minimal-compose-desktop/-/blob/crossfade_skia_image_memory_leak/src/main/kotlin/main.kt

**Comment by timo-drick** [comment]
Maybe also interesting. I see the same problem in Compose for Android. So maybe i should file this bug to the jetpack compose issue tracker?

**Comment by timo-drick** [comment]
Ok i did some further investigation and when i add System.gc() after loading new image the memory do not increase.
 At least not so much. So i think we can close this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5602">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
