### ISSUE TITLE
`Modifier.pointerHoverIcon` resets icon to default on click

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1314]
Compose 1.0.0-beta3, Windows 11

https://user-images.githubusercontent.com/5963351/138863295-b61da859-54f5-4d1a-9cad-fa20de126886.mp4

1. Run `run1` example from Compose sources
2. Hover `Base` button
3. Press Left mouse button

Actual:
Cursor icon changes to Default

Expected:
Cursor icon stays as Hand icon

**Comment by aeab13** [comment]
For some reason, I thought that we had a version where the buttons icon hover was changed to the hand by default. Probably got confused, ignore my previous comment.

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta6-dev474

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5223">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
