### ISSUE TITLE
Modifier.pointerHoverIcon has no effect on BasicTextField

### ISSUE THREAD

**Issue by alexjpwalker** [JetBrains/compose-jb#1315]
## Environment
Operating System: MacOS v11 Big Sur
Target Platform (Web/Desktop): Desktop
Compose Version: 1.0.0-beta1

## Reproducible Steps
Add the following composable to your application:
```kt
BasicTextField(modifier = Modifier.pointerHoverIcon(PointerIcon(Cursor(Cursor.HAND_CURSOR))),
    value = "Hello World",
    onValueChange = {})
```

## Expected Behaviour
When hovering over the text field, the cursor should change to a hand

## Actual Behaviour
The cursor is always a Text cursor for this BasicTextField

## Additional Information
In Compose v1.0.0-alpha3, we were able to change the pointer icon of `BasicTextField` using the `pointerIcon` modifier.

**Comment by prepor** [comment]
TextFields define their own cursor. If you want to override it you need to set overrideDescendants = true in pointerHoverIcon. Indeed, it's a change in behavior in comparison with alpha. 

I'm closing the issue, feel free to reopen if there are still problems.

**Comment by alexjpwalker** [comment]
To confirm, adding `overrideDescendants = true` did indeed solve the problem.

Also, for anyone else who comes across this issue: the use of `PointerIcon(Cursor(Cursor.HAND_CURSOR))` resulted in an issue where the cursor would "flash", alternating between a hand cursor and a text cursor. I fixed this by using `PointerIconDefaults.Hand` instead.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5222">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
