### ISSUE TITLE
Desktop: Customizable title bar

### ISSUE THREAD

**Issue by viktorisacenko** [JetBrains/compose-jb#1318]
Are there any plans to make the title bar customizable?
Not only displaying a name string? Maybe making the content of the title bar Composable.

**Comment by akurasov** [comment]
Closing the issue. Reopen it, if you have more questions.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5220">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
