### ISSUE TITLE
Library not loaded: @rpath/libjvm.dylib

### ISSUE THREAD

**Issue by gnawf** [JetBrains/compose-jb#1319]
When I try to run a fresh project created via IntelliJ using OpenJDK 11 I get this error:

```
Cannot open /usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home/lib/libjawt.dylib: dlopen(/usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home/lib/libjawt.dylib, 9): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home/lib/libjawt.dylib
  Reason: image not found
```

I switched to Oracle JDK 17 and it seems to work fine now. Any suggestions or insights? I'm on `1.0.0-beta3` and also tried `1.0.0-alpha3`

Also posting so that others with the same issue can find it. I wasn't been able to find anything useful.

**Comment by akurasov** [comment]
So it is a JDK issue. Oracle JDK 11 indeed is the most stable now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5219">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
