### ISSUE TITLE
ClassCastException when using Popup in certain conditions

### ISSUE THREAD

**Issue by Cybermaxke** [JetBrains/compose-jb#132]
Affects: `0.2.0-build127`

https://gist.github.com/Cybermaxke/2644a824f2e947a7ee334a07bbd65ed1

Not idea why it's happening, more information can be found in my code (and a temporary workaround):
https://github.com/LanternPowered/Porygen/blob/5305ef03588798ad5b86a68b23b2846db3959f7a/graph-editor/src/commonMain/kotlin/org/lanternpowered/porygen/editor/MenuBar.kt#L87

**Comment by Rsedaikin** [comment]
You can try this:
```kotlin
if (active == index && item.subItems != null) {
    Popup(
        isFocusable = true,
        alignment = Alignment.TopStart,
        onDismissRequest = { active = null }
    ) {
        InnerMenuBar(
            items = item.subItems,
            offset = popupOffset
        )
    }
}
````

**Comment by Cybermaxke** [comment]
This solution is not really an option. My solution prevents the need to click multiple times to close the menu, because each opened `Popup` would require an extra click.

**Comment by Rsedaikin** [comment]
Perhaps this only works in the latest version coming soon. I am still investigating this issue.

**Comment by Cybermaxke** [comment]
Still occurs in `0.2.0-build129`

**Comment by olonho** [comment]
Looks like general Compose plugin issue, please try not use delegates in lambdas to work it around.

**Comment by Rsedaikin** [comment]
It looks like this issue is not related to popups, it is an issue with the Compose plugin. Try to avoid using delegates for now:
```kotlin
@Composable
fun MenuBar(
    modifier: Modifier = Modifier,
    items: List<MenuItem>
) {
    Row(modifier) {
        var active: MutableState<Int?> = remember { mutableStateOf(null) }

        for ((index, item) in items.withIndex()) {
            var popupOffset = remember { mutableStateOf(Offset.Zero) }
            Button(
                onClick = {
                    active.value = index
                    item.onClick?.invoke()
                },
                modifier = Modifier
                    .onGloballyPositioned { coordinates ->
                        popupOffset.value = coordinates.boundsInRoot.bottomLeft
                    },
            ) {
                item.content()
            }

            if (active.value != index || item.subItems == null)
                continue

            Popup(
                isFocusable = true,
                alignment = Alignment.TopStart,
                onDismissRequest = { active.value = null }
            ) {
                InnerMenuBar(
                    items = item.subItems,
                    offset = popupOffset.value
                )
            }
        }
    }
}
```

**Comment by olonho** [comment]
https://issuetracker.google.com/174056197 is an issue to track.

**Comment by jimgoog** [comment]
I believe we've fixed this in upstream Compose, and I assume this now works in `0.3.2`.  Please re-open if you are still experiencing this issue with the latest release of Compose for Desktop.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5601">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
