### ISSUE TITLE
Support material, foundation, ui for JS target

### ISSUE THREAD

**Issue by mariuszmarzec** [JetBrains/compose-jb#1320]
Is there any plan to support material, foundation, ui? It would be great if those ones packages will be targeting JS, projects could have more common code between desktop, mobile nad web targets. Current api for web is different than common for Android/Desktop.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5218">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
