### ISSUE TITLE
targetSdk = 31 causes crash on Android

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#1326]
targetSdk was updated, which crashes because the activity isn't exported

**Comment by akurasov** [comment]
Could you please clarify, what the issue is? Probably small reproducer would be the best.

**Comment by ColtonIdle** [comment]
Sorry for the terrible bug report. 🤦 

If you run the android app in the multiplatform template in the repo then the app crashes on launch.

**Comment by akurasov** [comment]
Already fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5216">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
