### ISSUE TITLE
onPreview key event stuck if dropdown menu expended

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1332]
hi to all , it is confusing to checkout that when i add onPreviewKeyEvent to my button . when i press my desired key a dropdownmenu expended but when press an other key for expended set values for false that key did not worked

 val isExpended = remember { mutableStateOf(false) }
    var isHover by remember { mutableStateOf(false) }
    val buttonPress = remember { mutableStateOf(false) }
    val onClick  = remember {  mutableStateOf( value = {isExpended.value = true})}
    val interaction = remember { MutableInteractionSource() }

    val buttonOneFocusRequester = remember { FocusRequester() }
    val colors = ButtonDefaults.buttonColors(
        backgroundColor = if (interaction.collectIsFocusedAsState().value) {
            if (buttonPress.value)
                BUTTONS.PRESSED_COLOR
            else
                BUTTONS.HOVER_COLOR
        } else {
            BUTTONS.CLICKABLE_BOX_BACKGROUND
        }
    )
    Button(
        onClick = onClick.value,
        interactionSource = interaction,
        modifier = Modifier.size(size.width.dp, size.height.dp)
            .onPreviewKeyEvent {
                if (
                    (it.key == key) ||
                    (it.isAltPressed && it.key == key) || (it.key == Key.Enter)
                ) {
                    isExpended.value = true

                } else if (it.key == Key.Escape) { println("ok")}
                false
            }
            .focusRequester(buttonOneFocusRequester)
            .onFocusEvent { if (it.isFocused) println("is Focused")
                            if (it.isCaptured) println("onCap")
                            }
            .focusable(interactionSource = interaction)
        ,
        colors = colors
    ){
                Column(modifier = Modifier.padding(4.dp) , horizontalAlignment = Alignment.CenterHorizontally , verticalArrangement = Arrangement.Center) {
                    Image(
                        painter = painterResource(iconPath) ,
                        contentDescription = null,
                        modifier = Modifier.height(36.dp).width(36.dp) ,
                        colorFilter = ColorFilter.tint(color = if (isHover || interaction.collectIsFocusedAsState().value) Color.White else Color.Black)
                    )

                    //space between image and text
                    Spacer(modifier = Modifier.height(5.dp))
                    Row {
                        Text(text = shortcutKey , color = if (isHover || interaction.collectIsFocusedAsState().value) Color.White else Color.Black , fontWeight = if (isHover) FontWeight.Bold else FontWeight.Normal , textDecoration = TextDecoration.Underline)

                        Spacer(modifier = Modifier.width(3.dp))
                        Text(text = menuName , color = if (isHover || interaction.collectIsFocusedAsState().value) Color.White else Color.Black , fontWeight = if (isHover) FontWeight.Bold else FontWeight.Normal)
                    }

                }
        println(interaction.collectIsFocusedAsState().value)

            }

    //DropDown Menu
    Box(

    ) {
        DropdownMenu(
            expanded = isExpended.value ,
            onDismissRequest = {isExpended.value = false} ,
            modifier = Modifier.onPreviewKeyEvent {
                if (it.key == Key.Escape) {
                    isExpended.value = false
                }
                false
            }
        ) {

            dropDownMenuList.forEach {
                //change hover color state
                val changeColor = remember { mutableStateOf(false) }
                DropdownMenuItem(
                    onClick = {isExpended.value = false} ,
                    modifier = Modifier
                        .width(150.dp).height(24.dp)
                        .background(color = if (changeColor.value) Color.LightGray else Color.White)
                        .onFocusEvent {
                            if (it.hasFocus) println("drp focus")
                        }
                        .pointerMoveFilter(onEnter = { changeColor.value = true ; false} , onExit = { changeColor.value = false ; false})
                    ,
                ) {

                    Image(
                        painter = painterResource(it.iconPath) ,
                        contentDescription = null ,
                        modifier = Modifier.width(20.dp).height(20.dp)
                    )

                    //Space between Menu Icon and Label
                    Spacer(modifier = Modifier.width(10.dp))

                    Text(text = it.name)
                }

                Divider(color = Color.LightGray , thickness = 0.5.dp)
            }

        }
    }

**Comment by akurasov** [comment]
Could you please create a smaller reproducer for it and share with imports?

**Comment by akurasov** [comment]
Closing as dormant

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5211">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
