### ISSUE TITLE
Add support for material 3

### ISSUE THREAD

**Issue by purofle** [JetBrains/compose-jb#1335]
Jetpack compose has been support Material You. And I also saw the https://github.com/androidx/androidx/tree/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3 can run on compose-jb.
So when compose-jb can use the Material you?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5209">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
