### ISSUE TITLE
Add TextInput inputMode attribute and enum

### ISSUE THREAD

**Issue by brianguertin** [JetBrains/compose-jb#1338]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

E.g.:

```kotlin
TextInput {
   inputMode(InputMode.url)
}
```

**Comment by eymar** [comment]
should be available in the future build

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5206">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
