### ISSUE TITLE
Use icon defined in build.gradle as the taskbar icon (macOs) 

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1342]
macOs doesn't support icons for individual windows, so when we set icon in `singleWindowApplication` or in `Window`, we don't change anything. 

To change the icon, we should change it inside build.gradle. It changes the icon for native distribution, but doesn't change it for the debug mode (we have a default java icon).

To fix that, we need to pass this:
```
jvmArgs("-Xdock:icon=src/jvmMain/resources/ic_launcher.png")
```

Also, we need to write a warning into the log, if user uses `singleWindowApplication(icon=` attribute on macOs.

[Message in Slack](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1628278121193700?thread_ts=1628271680.187000&cid=C01D6HTPATV)

**Comment by igordmn** [comment]
> Also, we need to write a warning into the log, if user uses singleWindowApplication(icon= attribute on macOs.

Decided not to write warning into the log, as it pollutes the log with unnecessary information. But added more info about [icon] parameter to KDoc

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5203">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
