### ISSUE TITLE
Don't scroll outside of context menu when it is open

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1346]
1.0.0-beta5

1. Select text
2. Open context menu
3. Move cursor outside of the context menu
4. Scroll the mouse wheel

Expected:
Content behind the context menu shouldn't scroll

**Comment by igordmn** [comment]
Fixed in 1.0.0-rc3

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5199">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
