### ISSUE TITLE
Remove syncLoop from AccessibilityControllerImpl if it causes battery drain

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1347]
1.0.0-beta5

See the [line](https://github.com/JetBrains/androidx/blob/8cb55dd524114e6002ddf25afb55a945181eef46/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/Accessibility.desktop.kt#L156)

**Comment by akurasov** [comment]
Compose CodeViewer consumes 0.2-0.3% CPU in foreground mode when nothing is done with it. MacOS 11. Looks like syncLoop is not an issue. Closing the ticket. Could be reopened in case further findings.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5198">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
