### ISSUE TITLE
File copied to resources directory as part of build, not inside of build resources directory

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#1349]
In my build I'm copying an exported file to ensure it's placed in the resources directory, but the file seems to appear in the resources directory, it's not in the running applications resource directory when I run `./gradlew :app:run`.

```Kotlin
val composeProject = project
val dependencyProject = project(":dependency-project")

dependencyProject.afterEvaluate {
    val inputFile = File("${dependencyProject.buildDir}/bin/native/debugExecutable/dependency-executable.kexe")

    val resourceFolder = File("${composeProject.projectDir}/resources/common/mac/x86_64/")
    val resourceBuildFolder = File("${composeProject.buildDir}/compose/tmp/main/resources/mac/x86_64/")

    val copyExecutable = composeProject.tasks.create<Copy>("copyExecutable") {
        dependsOn(dependencyProject.tasks["linkDebugExecutableNative"])

        inputs.file(inputFile)
        outputs.file(File(resourceFolder, "dependency-executable.dylib"))

        from(inputFile)
        into(resourceFolder)
        rename {
            if (it.endsWith(".kexe")) {
                it.replace(".kexe", ".dylib")
            } else it
        }
    }

    composeProject.tasks["jvmMainClasses"].dependsOn(copyExecutable)
}
```

My work around for now is to add a second `Copy` task that copies the file to `/compose/tmp/main/resources/mac/x86_64/` too.

**Comment by ScottPierce** [comment]
I resolved this by depending on the `prepareAppResources` instead of `jvmMainClasses`. Gradle warnings helped me figure this out.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5196">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
