### ISSUE TITLE
How can I utilize @Preview when using Android Studio?

### ISSUE THREAD

**Issue by xetra11** [JetBrains/compose-jb#136]
I am fairly new to UI stuff with Kotlin and wanted to start with Jetpack Compose for Desktop now. However building the UI just by Code and rerunning the App everytime to see changes is a no go.

So I found out about this @Preview Annotation (here: https://developer.android.com/jetpack/compose/preview) that seems to be utilized in Android Studio to start a Preview of the hacked UI.

However what is missing in this documentation is in what dependency the `@Preview` annotation can be found. Cause it's not build in since it can't resolved in my project.

I'd love to have a small guidance to figure out how to get this to work!

**Comment by olonho** [comment]
This mode of operations is not yet supported.

**Comment by JavierSegoviaCordoba** [comment]
Is there a way to get Preview working only in an Android application module which implements common modules?

Should be great we can use there until it works for all Compose variants

**Comment by Shabinder** [comment]
Any update on this?

**Comment by akurasov** [comment]
Preview is implemented since build 0.5.0-build235. See https://github.com/JetBrains/compose-jb/issues/865#issuecomment-878109997

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5597">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
