### ISSUE TITLE
README for templates/examples

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#1361]
We should make sure all the templates/examples have a README file.  In particular, I noticed https://github.com/JetBrains/compose-jb/tree/master/templates/web-template lacks a README

**Comment by igordmn** [comment]
README added for [the 1.2 Release](https://github.com/JetBrains/compose-jb/tree/release/1.2/templates/web-template) (will be merged soon)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5187">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
