### ISSUE TITLE
Change alpha wording on landing page.

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#1362]
https://www.jetbrains.com/lp/compose-mpp/ still says alpha all over the page.  Should say Beta today.  After 1.0, we will need to change it to stable or remove the wording.

Same with https://www.jetbrains.com/lp/compose/ and https://compose-web.ui.pages.jetbrains.team/

**Comment by akurasov** [comment]
done

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5186">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
