### ISSUE TITLE
Accessibility support

### ISSUE THREAD

**Issue by kaushalyap** [JetBrains/compose-jb#1366]
It seems Compose Desktop still do not support accessibility (Keyboard navigation, Screen reader) as I tried out in JetBrain's Toolbox app. It is very important to support accessibility as GUI kit.

So I am opening this issue as a placeholder.

**Comment by aeab13** [comment]
By keyboard navigation do you mean [this](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Keyboard#focus-related-events)?

**Comment by jimgoog** [comment]
Also what screen reading technology are you using?  Because Compose for Desktop should now support, among other things, Apple’s VoiceOver (the screen reader built into macOS).  It is possible Toolbox is using an older build of Compose for Desktop.

If you can provide details on exactly what you tried that didn't work (eg. What is the code, which screen reader, what is the expected result, what is the actual result), that will help us give a more meaningful solution.  Otherwise, we're just guessing as to what you might be perceiving as the problem.

**Comment by kaushalyap** [comment]
> By keyboard navigation do you mean [this](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Keyboard#focus-related-events)?

Not only those, I mean using Tab for navigation, Enter for clicking.

**Comment by kaushalyap** [comment]
Glad team care about accessibility, strange but I did not found any docs on accessibility.

> It is possible Toolbox is using an older build of Compose for Desktop.

1.21

> What is the code, which screen reader?

Gnome 41, Orca screen reader

> what is the expected result?

Read out labels of UI widgets (links, buttons, etc)

**Comment by aeab13** [comment]
> > By keyboard navigation do you mean [this](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Keyboard#focus-related-events)?
> 
> @aeab13 Not only those, I mean using Tab for navigation, Enter for clicking.

It's explained in the link I provided

**Comment by aeab13** [comment]
Ah sorry, I posted the wrong link, I meant this one https://github.com/JetBrains/compose-jb/tree/master/tutorials/Tab_Navigation (however, the other link is still useful to handle enter events as you mentioned).

**Comment by akurasov** [comment]
@kaushalyap 
Beta release supports accessibility on Mac. It works out of the box. It is mentioned in the beta announcement, but indeed these is no documentation on it yet. 

It is planned to support Voice-Over for Windows in 1.0.

**Comment by akurasov** [comment]
Ticket for a11y on Windows is #1344 So I close this one as duplicate

**Comment by kaushalyap** [comment]
@akurasov What about accessibility on Linux?

**Comment by kaushalyap** [comment]
@akurasov I look at the Toolbox app gain, now keyboard navigation seems to work but not the screen reader.

**Comment by akurasov** [comment]
@kaushalyap which OS do you use? 

We currently rely on JDK support for a11y and for Linux it is not that good. So it will take much more time for Linux.

**Comment by kaushalyap** [comment]
@akurasov I use Fedora

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6166">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
