### ISSUE TITLE
Wrong selector for function `sibling()` in `CSSSelectors.kt`

### ISSUE THREAD

**Issue by thubalek** [JetBrains/compose-jb#1377]
It looks like there is bug in function `sibling()` in `CSSSelectors.kt` file. See screenshot

![image](https://user-images.githubusercontent.com/1260262/140956229-35e058ce-1906-455e-a638-3c50ed7ec58b.png)

I think there should be 

`fun sibling(sibling: CSSSelector, selected: CSSSelector) = CSSSelector.Sibling(sibling, selected)`

**Comment by thubalek** [comment]
I forgot to mention, it is related to Jetpack Compose for Web.

**Comment by eymar** [comment]
fixed in 1.0.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6173">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
