### ISSUE TITLE
Module support? `module not found`

### ISSUE THREAD

**Issue by camdenorrb** [JetBrains/compose-jb#1378]
I'm trying to use Compose in a modular project but it seems to be unable to find the modules requested by my usage of the Compose api

### Example of Intellij requesting a module:
![image](https://user-images.githubusercontent.com/5360339/140984334-f3e25dc1-75db-4edd-82ef-c2638646b226.png)

### `module-info.java` After adding all required modules:
```
module SoftwareOverlay.main {
    requires PoderTech.overlay;
    requires material.desktop;
    requires ui.desktop;
    requires runtime.desktop;
    requires material.icons.core.desktop;
    requires ui.graphics.desktop;
    requires ui.unit.desktop;
    requires foundation.layout.desktop;
    requires foundation.desktop;
    requires ui.text.desktop;
    requires kotlin.stdlib;
    requires java.desktop;
    requires java.net.http;
    requires kotlinx.serialization.core;
    requires ktor.client.core.jvm;
    requires kotlin.stdlib.jdk7;
    requires kotlinx.serialization.json;

}
```

### Errors on build with `module-info.java`:
![image](https://user-images.githubusercontent.com/5360339/140984600-857b0e51-778c-4a8d-af75-e8ee0fd69259.png)

**Comment by jimgoog** [comment]
What does this have to do with Project Jigsaw?  Are you a contractor hired by the Google Jigsaw team?  Or what is your connection?

This issue doesn't seem to contain enough information for us to meaningfully understand your project setup.  Presumably your build file is missing some dependencies, but you didn't even share your build file let alone a minimal repro.

If you are just getting started with Compose, I would strongly suggest starting with the Desktop Template (https://github.com/JetBrains/compose-jb/tree/master/templates/desktop-template) to get a feel for Compose and iterate from there.

If you are running into a specific issue, providing a minimal repro as well as a description of exactly what you are trying to accomplish and why - would allow us to better address your questions.

**Comment by camdenorrb** [comment]
@jimgoog Alright apologies, I'll try to make a minimal example repo and get back to you.

**Comment by kirill-grouchnikov** [comment]
I think it's reference to https://openjdk.java.net/projects/jigsaw/

**Comment by Moocow9m** [comment]
> What does this have to do with Project Jigsaw? Are you a contractor hired by the Google Jigsaw team? Or what is your connection?
> 
> This issue doesn't seem to contain enough information for us to meaningfully understand your project setup. Presumably your build file is missing some dependencies, but you didn't even share your build file let alone a minimal repro.
> 
> If you are just getting started with Compose, I would strongly suggest starting with the Desktop Template (https://github.com/JetBrains/compose-jb/tree/master/templates/desktop-template) to get a feel for Compose and iterate from there.
> 
> If you are running into a specific issue, providing a minimal repro as well as a description of exactly what you are trying to accomplish and why - would allow us to better address your questions.

It is Project Jigsaw related. Due to Project Panama, we need jigsaw to safely open native access to specific modules, rather than ALL_UNNAMED.

**Comment by camdenorrb** [comment]
This is more of an Intellij issue than a Compose issue, closing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6236">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
