### ISSUE TITLE
Close ContextMenu, AlertDialog on Esc key by default

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1379]
Native context menus and alert dialogs usually close if we press Esc key.

P.S. should we close DropdownMenu too?

**Comment by igordmn** [comment]
Fixed in 1.0.0-rc5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6205">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
