### ISSUE TITLE
Scrollbars do not appear at all on MacOS 11.0.1

### ISSUE THREAD

**Issue by CarsonRedeye** [JetBrains/compose-jb#138]
Steps to reproduce:
Open Todo example
Add 20 items
Expected: Scrollbar appears on right
Actual: No scrollbar is visible

Have tried on my other app and cannot get VerticalScrollbar to display

**Comment by olonho** [comment]
![image](https://user-images.githubusercontent.com/2600522/99962779-d7e49b00-2da1-11eb-85d5-2e8efb4e5c2a.png)
That's how it looks on my macOS machine with 18afa24fe0b24cc998eade489bda78357d78c866. Could it be that your monitor is too dark to see scrollbars?

**Comment by igordmn** [comment]
Also try to resize the window. Will scrollbar appear?

**Comment by CarsonRedeye** [comment]
Also on 18afa24fe0b24cc998eade489bda78357d78c866. It seems like it isn't even allowing space for it (adding a border to VerticalScrollbar doesn't show either)

<img width="824" alt="Screen Shot 2020-11-24 at 9 43 57 am" src="https://user-images.githubusercontent.com/44560503/100027965-f601d800-2e41-11eb-8ec7-df790faea8ed.png">

**Comment by CarsonRedeye** [comment]
I think I wasn't on the latest commit sorry. It is working now.

**Comment by CarsonRedeye** [comment]
I did notice that sometimes I needed to resize the window for the scollbar to appear yes

**Comment by igordmn** [comment]
>  I needed to resize the window for the scollbar to appear

Scrollbar should appear if there is more items than can be displayed in the list.

Also there is another bug:
https://github.com/JetBrains/compose-jb/issues/47

**Comment by CarsonRedeye** [comment]
Steps to reproduce:
1. Change to use ScrollableColumn in Todo app sample.
2. Run Todo app
3. Add 30 items
4. Close app.
5. Run Todo app again.
Expected: Scrollbar is visble
Actual: No scrollbar appears. Scrolling the list does not make the scrollbar appear. Resizing the window makes it appear.

**Comment by igordmn** [comment]
Thanks! I reproduced the issue. Will look at it.

**Comment by igordmn** [comment]
Fixed in 0.2.0-build132

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5595">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
