### ISSUE TITLE
Changing screen densities does not update LocalDensity or cause recomposition

### ISSUE THREAD

**Issue by ryanmitchener** [JetBrains/compose-jb#1383]
Compose 1.0.0-beta5, MacOS Monterey, JDK11

When moving the application window between two monitors of different densities the LocalDensity does not update appropriately and the UI does not scale properly. This was working in alpha.

In the video below, the density is initially 2.0 and should change to 1.0 when the application is moved to the screen, but it stays at 2.0. The UI does not scale appropriately for the 1.0 density and all UI elements' size are doubled.

https://user-images.githubusercontent.com/6433145/141177350-326eb1ca-a9d1-4440-ad9e-3caf5fbf0a36.mov

**Comment by igordmn** [comment]
Probably will be fixed in the next build (https://github.com/JetBrains/androidx/pull/71)

**Comment by ryanmitchener** [comment]
I can confirm that this has been fixed as of `beta6-dev455`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6234">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
