### ISSUE TITLE
Build failure: Space Repo exceeded monthly outgoing traffic

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#1385]
It looks like the Space repo containing the artifacts served to much traffic this month...
https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime/1.0.0-beta6-dev450/runtime-1.0.0-beta6-dev450.pom
Results into 429: `{"error":"Packages monthly outgoing traffic limit of 1.4 TB exceeded"}`

Because Gradle cannot download the runtime artifact, it is impossible to build any Compose projects.

**Comment by akurasov** [comment]
We are looking into it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6233">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
