### ISSUE TITLE
Failed to build from cmd in Windows

### ISSUE THREAD

**Issue by Klurige** [JetBrains/compose-jb#1387]
When building from command line in Windows 10 Enterprise, I'm getting the following:
```
C:\compose-jb\templates\desktop-template>gradlew.bat tasks
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\compose-jb\templates\desktop-template\build.gradle.kts' line: 22

* What went wrong:
Unsupported OS arch: x86

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 25s
```

Building from within idea works fine.

**Comment by Klurige** [comment]
Shouldn't be tagged as a question. I'm not asking how to build with gradle from cmd, I'm reporting that it doesn't work.

**Comment by akurasov** [comment]
It looks you are building on windows 10 32 bit. Is it correct?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6148">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
