### ISSUE TITLE
mpp branch with iOS demo

### ISSUE THREAD

**Issue by b95505017** [JetBrains/compose-jb#1393]
Excited to see a working iOS demo. But I'm not sure what it can/can't do currently. For example, modifier with `fillMaxSize()`, AppBar, lots of stuff can't work normally. I'm using xcode 13.1.
I would like to help trying latest features.
 
![Simulator Screen Shot - iPhone 13 - 2021-11-13 at 09 38 12](https://user-images.githubusercontent.com/320815/141600981-c7124712-0b81-4094-a546-64dfde40fd99.png)

**Comment by jimgoog** [comment]
iOS is not currently a supported/documented platform.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6226">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
