### ISSUE TITLE
Option to specify license for deb packages

### ISSUE THREAD

**Issue by sebkur** [JetBrains/compose-jb#1405]
It seems to be possible to specify a license for RPM linux packages, but there is no option for deb. I think there should probably be such an option. Existing rpm option:
```
rpmLicenseType = "TYPE_OF_LICENSE" — a type of license for the rpm package;
```
proposed deb option:
```
debLicenseType = "TYPE_OF_LICENSE" — a type of license for the deb package;
```
At the moment I do get this file located at `share/doc/copyright` when installing a `*.deb` file produced using `./gradlew packageDeb`:
```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Files: *
Copyright: Copyright (C) 2021
License: Unknown
```

**Comment by AlexeyTsvetkov** [comment]
@sebkur does existing `copyright` property not work for you?

```
compose.desktop {
    application {
        nativeDistributions {
            packageName = "ExampleApp"
            version = "0.1-SNAPSHOT"
            description = "Compose Example App"
            copyright = "© 2020 My Name. All rights reserved."
            vendor = "Example vendor"
        }
    }
}
```

https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution#customizing-metadata

**Comment by sebkur** [comment]
thanks @AlexeyTsvetkov for your quick response. Copyright does help a bit indeed for changing the content after the `Copyright: ` line, however I am more concerned about the content after the `License: ` line and my goal would be to change "Unknown" to something like "MIT License"

**Comment by sebkur** [comment]
I gave it a try to fix this, see the PR above

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6208">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
