### ISSUE TITLE
Window {} code is called twice during startup

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-jb#141]
The code:
```
val cnt = AtomicInteger(0)

fun main() = Window {
    println("Tick!")
    cnt.addAndGet(1)
    Text("Hello: $cnt")
}
```

outputs:
```
Tick!
Tick!
```

and displays:
![obraz](https://user-images.githubusercontent.com/34739613/100238175-2e7fdf80-2f30-11eb-9980-5daafd6492ff.png)

For a state that cannot be scoped inside the Window {} block, this complicates things a little bit.
Is this intended behavior?

**Comment by atoktoto** [comment]
Seems like it is, sorry for the noise.

**Comment by igordmn** [comment]
We fixed this in 0.1.0-build119 (https://github.com/JetBrains/compose-jb/issues/87). Is it still called twice?

**Comment by atoktoto** [comment]
On 0.1.0-build119 it runs once! 🎉

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5592">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
