### ISSUE TITLE
Compose-Desktop : TextField cursor acts weird when used for multiline text

### ISSUE THREAD

**Issue by Vshnv** [JetBrains/compose-jb#1415]
TextField cursor acts weird when used for multiline text, specifically when attempting to move the cursor up and down
![image](https://s8.gifyu.com/images/ezgif.com-gif-makerce2af5bab49746c2.gif)

**Comment by akurasov** [comment]
It is fixed in the last build. Try 1.0.0-beta6-dev464

**Comment by Vshnv** [comment]
Yes, seems to be working fine in this version. Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6217">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
