### ISSUE TITLE
can not supported one build everywhere run

### ISSUE THREAD

**Issue by pc859107393** [JetBrains/compose-jb#1427]
what happened？i found some jni method，i don't know detail，but i want compose-jb can one build everywhere run.

eg: we can try some thing to deal with it when we build a native app in macos , i want the app can run everywhere( x86_64 / arm ).
but now i need build in m1 ,build in intel to save Diffrent CPU Core. at now, i'm writing a SerialCom program, i package all native component in a module, when i use it, it can found system detail to choose current component.

**Comment by akurasov** [comment]
Regretfully I can't understand your question :( Could you try to reformulate it please?

**Comment by christoph-grimm** [comment]
I think he targets a container that is compiled on a platform X (e.g. MacOS) and runs also on other platforms X, Y, Z, (e.g. also Windows, Linux, MacOS on M1, ....). This was possible with JVM -- but I think Skija adds binary dependencies that are platform-dependent. 

Technically this would mean we would have to
1) add also Skija binaries for all platforms in the resulting container. 
2) have a platform-independent container-format -- or a number of different containers, one for each platform. 
3) maybe some adaptions in the compose plugin to deal with 1 and 2 (?)

**Comment by pc859107393** [comment]
add all binary dependencies in the resulting container is a good idea

**Comment by akurasov** [comment]
Each platform has it's own distribution format. You can't install Mac package on Windows and vice versa. It is not a matter of Compose, but a matter of different formats.

For a specific OS you, in theory, could package different Skia binaries into one package - just replace 
`implementation(compose.desktop.currentOs)`
with a desktop-jvm-macos-arm64 and desktop-jvm-macos-x64 dependencies (for Mac) for example. This will make sure both binaries are packed into the distribution. But I'm not sure this will work - never saw bundles that works on both OSes

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6159">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
