### ISSUE TITLE
Disable text selection by default

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#143]
On Android it was disabled in https://android-review.googlesource.com/c/platform/frameworks/support/+/1416219

**Comment by igordmn** [comment]
Fixed.

Verified in 0.4.0-build190

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5590">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
