### ISSUE TITLE
Scrolling lazy list with scrollbar doesn't work well

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1430]
Compose 6cd37067

https://user-images.githubusercontent.com/5963351/142721231-7005d0d4-c8cf-4d1e-8eb5-de13f1696aee.mp4

**Comment by igordmn** [comment]
It is a regression after https://github.com/JetBrains/androidx/pull/101

**Comment by igordmn** [comment]
Fixed in 1.0.0-rc4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5181">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
