### ISSUE TITLE
Scroll on LazyColumn cause JRE crash.

### ISSUE THREAD

**Issue by ghost** [JetBrains/compose-jb#1435]
Click on any row item to display 2nd window, scroll on list, then close 2nd window, JRE crashes.
I'm new to compose. Tested with java 11 and java 17.
```
    application {
        val list = remember { mutableStateListOf(*Array(20) { "$it" }) }
        val windowList = remember { mutableStateMapOf<String, Unit>() }

        for ((k, _) in windowList) {
            key(k) {
                Window(onCloseRequest = { windowList.remove(k) }) {
                    Text(k)
                }
            }
        }
        Window(onCloseRequest = ::exitApplication) {
            LazyColumn {
                items(list) {
                    Text(it, modifier = Modifier.fillMaxSize().height(60.dp).clickable {
                        windowList[it] = Unit
                    })
                    Divider(color = Color.Black)
                }
            }
        }
    }
```

**Comment by akurasov** [comment]
Hello! I tried you code (with some changes to adopt it to the latest API) and didn't get any crashes. Could you try it with 1.0.0-beta6-dev474 ? 

Please note, that items function takes not collection, but it's size as a parameter now.

**Comment by archlinux1124** [comment]
> Hello! I tried you code (with some changes to adopt it to the latest API) and didn't get any crashes. Could you try it with 1.0.0-beta6-dev474 ?

Oh yes, move from alpha version to beta version and it works! Thanks for your help!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5177">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
