### ISSUE TITLE
Replace androidx.compose.ui.platform.DesktopSelectionContainer by common androidx.compose.ui.selection.SelectionContainer

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#144]
And make SelectionContainer behave on the desktop as it was DesktopSelectionContainer.

**Comment by arkivanov** [comment]
Looks like it is already done?

**Comment by igordmn** [comment]
Yes, thanks for reminder.

Verified in 0.4.0-build190.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5589">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
