### ISSUE TITLE
Throw a runtime error while trying to concatenate CSSSelector with String

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#1440]
We've tried to  have an syntax sugar for combining selector via plus operator:

```
operator fun String.plus(selector: CSSSelector)
```

However the problem is that this approach still wont work due to the very design of Kotlin language.

```kotlin
class Something  {
	override fun toString(): String {
		return "Something"
	}
    
    fun asString(): String {
		return "::As::Something"
	}
}

operator fun String.plus(s: Something) = this + s.asString()


fun main() {
    println("HEY!!! " + Something())
}
```

Here we we always have Something::toString called.

That said, selectors like this:
```kotlin
  "h1" + self { ... } 
```

just don't work as expected. 
We need to address this in a more thorough fashion (in other words we should completely redesign our CSS API) 
however as of now suggestion is to do following: toString for self should throw an Exception with a short explanation what is the current workaround (which, fortunately, exists).

**Comment by Skolotsky** [comment]
https://github.com/JetBrains/compose-jb/pull/1462

**Comment by eymar** [comment]
the PR was merged. closing this issue

**Comment by LouisCAD** [comment]
Making `toString()` throw isn't super nice 😕 . It's in the `CSSSelfSelector` (internal) class.

I'm unable to find how to do what I could do before:
```kotlin
"$self.some-class"
```

Which function does the equivalent?

Also, the `desc` CSS operator has this in its code, where parent could be `self`:
```kotlin
override fun toString(): String = "$parent $selected"
```

It means `self`'s throwing `toString()` will be called. I'm in a dead end.

The error message doesn't help me much:
> You can't concatenate `String + CSSSelector` which contains `self` or `root`. Use `selector(<your string>)` to convert `String` to `CSSSelector` for proper work. https://github.com/JetBrains/compose-jb/issues/1440

I'm reverting from `1.0.1` back to `1.0.0-alpha1-rc4` because of that.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5174">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
