### ISSUE TITLE
Could not find material3 on android

### ISSUE THREAD

**Issue by serbelga** [JetBrains/compose-jb#1442]
On `build.gradle.kts`

```kotlin
    sourceSets {
        val commonMain by getting {
            @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
            dependencies {
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material3)
            }
        }
```

```
Could not find androidx.compose.material3:material3:1.1.0-beta02.
Required by:
    project :common > org.jetbrains.compose.material3:material3:1.0.0-beta6-dev474

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Version for androidx.compose.material3 should be 1.0.0-alpha01

**Library version**
v1.0.0-beta6-dev474

**OS**
Mac OS 11 Big Sur

**Comment by dragossusi** [comment]
happens to me as well

**Comment by akurasov** [comment]
Thank you for reporting. It will be fixed in nearest future

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-rc3

**Comment by Raju5120** [comment]
> On `build.gradle.kts`
> 
> ```kotlin
>     sourceSets {
>         val commonMain by getting {
>             @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
>             dependencies {
>                 api(compose.runtime)
>                 api(compose.foundation)
>                 api(compose.material3)
>             }
>         }
> ```
> 
> ```
> Could not find androidx.compose.material3:material3:1.1.0-beta02.
> Required by:
>     project :common > org.jetbrains.compose.material3:material3:1.0.0-beta6-dev474
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> ```
> 
> Version for androidx.compose.material3 should be 1.0.0-alpha01
> 
> **Library version** v1.0.0-beta6-dev474
> 
> **OS** Mac OS 11 Big Sur

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5173">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
