### ISSUE TITLE
Help using Compose for Web in ktor server

### ISSUE THREAD

**Issue by dragossusi** [JetBrains/compose-jb#1451]
Hello

I need some help porting my desktop app to the web, I have a ktor rest API that I want to host the compose frontend as well.

If possible, how can I do that?

**Comment by tom-pratt** [comment]
This tutorial does a nice job of explaining how to combine kotlin/js frontend and ktor backend into a single application. It was a bit hard to find this when i kept including "compose for web" in my searches :D

https://play.kotlinlang.org/hands-on/Full%20Stack%20Web%20App%20with%20Kotlin%20Multiplatform

**Comment by akurasov** [comment]
Link to the article added to the list of CfW tutorials. Thank you, @tom-pratt!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5167">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
