### ISSUE TITLE
OutlinedTextField causes system lag

### ISSUE THREAD

**Issue by Dominaezzz** [JetBrains/compose-jb#146]
When I run this program.

```kotlin
import androidx.compose.desktop.Window
import androidx.compose.material.MaterialTheme
import androidx.compose.material.OutlinedTextField
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.unit.IntSize

fun main() {
	Window(title = "Laggy App", size = IntSize(300, 300)) {
		MaterialTheme {
			val boh = remember { mutableStateOf("") }
			OutlinedTextField(
				value = boh.value,
				onValueChange = { boh.value = it }
			)
		}
	}
}
```

It runs fine until I click on the text field and then `DesktopPlatformInput.showSoftwareKeyboard` is printed and `/usr/lib/Xorg :0 vt1 -nolisten tcp -br -config nvidia-xorg.conf -configdir nvidia-xorg.conf.d` starts using 70% CPU (from usual 1.1%). My cursor starts to lag a lot.

I'm running on Arch Linux.

**Comment by Dominaezzz** [comment]
Same as #23 after doing some testing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5588">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
