### ISSUE TITLE
Cursor jumps to the next line when we click in the end of the previous line

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1463]
Compose 1.0.0-rc3

https://user-images.githubusercontent.com/5963351/143472913-5a8c4c12-059d-496e-a117-a8d0130955e2.mp4

```
import androidx.compose.material.TextField
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    TextField((1..100).joinToString(" ") { "word" }, {})
}
```

**Comment by igordmn** [comment]
On Android it works correctly

https://user-images.githubusercontent.com/5963351/143473635-533735c2-f2d6-4edd-9ec0-be303f403bcb.mp4

I assume it is because on Android we skip spaces

**Comment by eymar** [comment]
fixed in https://github.com/JetBrains/androidx/pull/284

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5162">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
