### ISSUE TITLE
NoSuchMethod painterResource

### ISSUE THREAD

**Issue by aeab13** [JetBrains/compose-jb#1466]
With 1.0.0-rc4 using painterResource fails complaining about the method not existing (works fine with rc3).

Demo code:
```
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        MaterialTheme {
            Icon(
                painter = painterResource("bug.svg"),
                contentDescription = null,
                modifier = Modifier.fillMaxSize(),
            )
        }
    }
}

```

Stacktrace:
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'androidx.compose.ui.graphics.painter.Painter androidx.compose.ui.res.PainterResources_desktopKt.painterResource(java.lang.String, androidx.compose.ui.res.ResourceLoader, androidx.compose.runtime.Composer, int, int)'
	at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:14)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:12)
	...
```

I have noticed that I'm also getting a compiler warning with the following message: 

> This API is experimental and is likely to change in the future.

However, when checking at PainterResources.desktop.kt with Intellij IDEA I couldn't find the annotation anywhere so I compared the differences between rc3 and rc4 in the github repo. I've noticed that the class has been changed to have a loader as a parameter ([this commit to be more precise](https://github.com/JetBrains/androidx/commit/a8c7d5bff670668f6ebd183169d0f9df0c26e684)). So the issue is: Why is it picking up the old painterResource (without the loader) instead of the new one (with the loader) when I'm building with rc4?

**Comment by aeab13** [comment]
Nevermind, after clearing IDEA's cache and restarting, it worked without a problem. Closing this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5159">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
