### ISSUE TITLE
Selection in SelectionContainer { LazyList } doesn't work correctly

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1471]
Compose 1.0.0-rc1, 1.0.0-rc4, Codeviewer

https://user-images.githubusercontent.com/5963351/143580045-eb6fc21c-b360-4a56-8669-2f2540550699.mp4

Probably it is a regression after https://github.com/JetBrains/androidx/pull/99

**Comment by igordmn** [comment]
Fixed in 1.0.0-rc5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5156">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
