### ISSUE TITLE
how to check for internet connection?

### ISSUE THREAD

**Issue by KonstantinKonshu** [JetBrains/compose-jb#1478]
Hello! My project is Desktop Compose app,
I would like to know if it is possible to check the Internet connection when starting the application, as it is done in the android application using the ConnectivityManager

**Comment by aeab13** [comment]
That's not a compose related question, check google/[stackoverflow](https://stackoverflow.com/questions/1402005/how-to-check-if-internet-connection-is-present-in-java).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1478">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
