### ISSUE TITLE
"End" key moves cursor to the end of the last line instead of the end of the current line when selecting

### ISSUE THREAD

**Issue by JetpackDuba** [JetBrains/compose-jb#1479]
When having a multiline TextField and you click on "end" key of your keyboard, it moves the cursor to the end of the current line, however with text selected it moves to the end of the last line, therefore selecting all the lines from the start of the selection. That's not how it should work, the end key should move just to the end of the current line, not the whole text.

Example of the bug (I keep "shift" clicked, move the cursor with the keyboard arrows a couple of times and then click the "end" key):
![text_selection_end](https://user-images.githubusercontent.com/16917468/143668907-32db5533-555c-4e04-bc0d-260b639242a8.gif)

Same test with Intellij IDEA (where the cursor goes to the end of the current line) :
![text_selection_end_intellij](https://user-images.githubusercontent.com/16917468/143668918-183ee65a-3fb9-4471-846b-8442ba32e87c.gif)

Edit:
Using v1.0.0-rc5 & Ubuntu 20.04

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5150">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
