### ISSUE TITLE
TextField does not vertically align Text and Leading/Trailing icons like in android

### ISSUE THREAD

**Issue by brolicious12** [JetBrains/compose-jb#1481]
ANDROID
![Unbenannt2](https://user-images.githubusercontent.com/89709434/143689464-330010c8-9c4c-4e4e-8e53-1212a46b3cf6.PNG)

DESKTOP
![Unbenannt](https://user-images.githubusercontent.com/89709434/143689476-cec874dc-457a-4795-ba93-572bb7448953.PNG)

```
id("org.jetbrains.kotlin.jvm") version ("1.5.31")
id("org.jetbrains.compose") version ("1.0.0-rc5")

windows 10 desktop (tested) -> not aligned
android (tested) -> aligned
```

```
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material.Icon
import androidx.compose.material.OutlinedTextField
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowForward
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
	var text by remember { mutableStateOf("TEXT") }
	
	OutlinedTextField(
		value = text,
		onValueChange = { text = it },
		modifier = Modifier.fillMaxWidth(),
		leadingIcon = {
			Icon(
				contentDescription = null,
				imageVector = Icons.Default.ArrowForward
			    )
		},
		trailingIcon = {
			Icon(
				contentDescription = null,
				imageVector = Icons.Default.ArrowForward
			    )
		})
}
```

**Comment by igordmn** [comment]
Probably on Android it is accidentally happened, that it is aligned.

I checked on my Android emulator.

With the default text size:
![image](https://user-images.githubusercontent.com/5963351/143689915-d5ae54ff-aab2-4308-be43-802d00a9f065.png)

With size=7.sp:
![image](https://user-images.githubusercontent.com/5963351/143689927-28f440be-e050-4bd6-98fc-7413f8ea85df.png)

To align your text, use `singleLine = true`

**Comment by brolicious12** [comment]
yes, i get the same as you. it happened accidentally. thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5148">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
