### ISSUE TITLE
Clicks doesn't work in non-focusable popup

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1486]
Compose 1.0.0-rc5

```
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.size
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Popup
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    Box(Modifier.fillMaxSize()) {
        Popup {
            Box(
                Modifier
                    .size(200.dp)
                    .background(Color.Red)
                    .clickable {
                        println("CLICK")
                    }
            )
        }
    }
}
```

https://user-images.githubusercontent.com/5963351/143776551-e9b24da8-5169-435a-af8d-c78e5c2dafb6.mp4

Click only triggered after we move the mouse, not when we release it

**Comment by aeab13** [comment]
Not sure if the PR handles it, but in my case clicks were working keyboard input wasn't.

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-rc6

**Comment by igordmn** [comment]
>  keyboard input wasn't

Keyboard input only works if you pass `focusable = true` to popup

**Comment by aeab13** [comment]
Got it, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5144">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
