### ISSUE TITLE
web-compose-bird example. Impossible to win the game

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1493]
Compose 1.0.0-rc5

There are too many obstacles. We need to reduce their count.

https://user-images.githubusercontent.com/5963351/143785099-b7047b6c-dfac-4c64-8cf8-d9bef9841a8c.mp4

**Comment by igordmn** [comment]
Fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5137">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
