### ISSUE TITLE
Blinking tooltip if it can't be showed in the bottom of the window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1497]
Compose 1.0.0-rc6

https://user-images.githubusercontent.com/5963351/143847198-d3603b0b-63bc-40f2-86ec-a22a59023198.mp4

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-rc10

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6195">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
