### ISSUE TITLE
Free: Invalid pointer on start-up

### ISSUE THREAD

**Issue by shynline** [JetBrains/compose-jb#1498]
It is reproducible with a new project immediately following compose release v1.0.0-beta6-dev474.
The app crashes Before the debugger can connect to it.
It only occurs in my colleague's system. We are both using Ubuntu 20.04 LTS-3.
Exact same dev environment,

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-rc6

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6201">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
