### ISSUE TITLE
todoapp: The minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-30).

### ISSUE THREAD

**Issue by asuraphel** [JetBrains/compose-jb#1501]
When trying to run the `todoapp`, I get the following error: 

> The minCompileSdk (31) specified in a
> dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
> is greater than this module's compileSdkVersion (android-30).
> Dependency: androidx.compose.material:material:1.1.0-beta01.
> AAR metadata file: /Users/alexander/.gradle/caches/transforms-3/137251a10d2c5151ea1d3a5bd29928e0/transformed/jetified-material-1.1.0-beta01/META-INF/com/android/build/gradle/aar-metadata.properties.
> 

It's been discussed on [#compose channel in slack](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1638106531197000). 

The solution that worked for me is to:

> In android/build.gradle.kts set
>     compileSdkVersion(31)
>         targetSdkVersion(30)

**Comment by akurasov** [comment]
It is 31 now

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6175">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
