### ISSUE TITLE
AppWindow.setWindowCentered probably doesn't work on multiple monitors

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#151]
Because it is using Toolkit.getDefaultToolkit().getScreenSize().

Probably the correct way will be:
```
    override fun setWindowCentered() {
        val screenWidth = window.graphicsConfiguration.device.displayMode.width
        val screenHeight = window.graphicsConfiguration.device.displayMode.height
        val x = screenWidth / 2 - width / 2
        val y = screenHeight / 2 - height / 2
        window.setLocation(x, y)
    }
```

**Comment by Rsedaikin** [comment]
Fixed: https://android-review.googlesource.com/c/platform/frameworks/support/+/1547595

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5583">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
