### ISSUE TITLE
Send the real commit of the build to GitHub

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1522]
GitHub marks the commit only at the moment we create release on GitHub.

And if we push some commits between the moment we start the build and the moment the build is ended and "uploaded" to GitHub, GitHub will create a Git tag on the wrong commit:

![image](https://user-images.githubusercontent.com/5963351/144255370-2f5aee41-d38b-496e-9904-07c44bf14a93.png)

1 - the real commit, on which we start the build
2 - tag, which is created by GitHub at the moment when we call API for creating GitHub release

**Comment by igordmn** [comment]
Fixed on CI:

```
BRANCH=%build.vcs.number%
...
API_JSON=$(printf '{"tag_name": "v%s","target_commitish": "%s","name": "v%s","body": "%s","draft": %s,"prerelease": %s}' "$VERSION" "$BRANCH" "$VERSION" "$MESSAGE" "$DRAFT" "$PRE" )
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6192">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
