### ISSUE TITLE
Suggestion: Provide svgpath Element

### ISSUE THREAD

**Issue by Jeansen** [JetBrains/compose-jb#1525]
Maybe I missed it (because I am very new to the compose library), but I could not finde something I know from JavaFX that is similar to https://docs.oracle.com/javase/8/javafx/api/javafx/scene/shape/SVGPath.html.

I find the possibility to load SVG-Paths (instead of SVG files) for icons etc very comforting because it does not clutter a project with files.

I'd be happy to see something like the above linked SVGPath in this library.

**Comment by igordmn** [comment]
Will `PathParser` be suitable for you?
```
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    val path = remember {
        PathParser().parsePathString("M40,60 C42,48 44,30 25,32").toPath()
    }
    Canvas(Modifier.fillMaxSize()) {
        drawPath(path, Color.Red, style = Stroke(2.dp.toPx()))
    }
}
```

![image](https://user-images.githubusercontent.com/5963351/144277365-2ffcb691-eeab-4fa8-a117-395712f131cf.png)

**Comment by Jeansen** [comment]
@igordmn: Oh, great. Somehow I've overlooked that one. Thanks for the insight. That will do, of course! ;-)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6193">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
