### ISSUE TITLE
Web: CheckboxInput cannot be used with MDC Checkbox component

### ISSUE THREAD

**Issue by OliverO2** [JetBrains/compose-jb#1528]
Using the controlled `CheckboxInput` to create a wrapper for an [MDC Checkbox](https://github.com/material-components/material-components-web/tree/v13.0.0/packages/mdc-checkbox) produces this exception: 

```
Uncaught Error: Checkbox component requires a .mdc-checkbox__native-control element
MDCCheckbox.getNativeControl                    	component.js:233
hasNativeControl                                	component.js:136
MDCCheckboxFoundation.transitionCheckState      	foundation.js:121
MDCCheckboxFoundation.handleChange              	foundation.js:118
set                                             	component.js:186
_no_name_provided__184.invoke_8ohztc_k$         	sandbox.js:64912
eval                                            	sandbox.js:64941
updateProperties                                	sandbox.js:68539
_no_name_provided__190.invoke_7q0vyf_k$         	sandbox.js:68648
l                                               	sandbox.js:68802
_no_name_provided__85.invoke_472icx_k$          	sandbox.js:40578
eval                                            	sandbox.js:42928
CompositionImpl.applyChanges_sv8swh_k$          	sandbox.js:44082
_no_name_provided__117.invoke_wiekkq_k$         	sandbox.js:45878
eval                                            	sandbox.js:48457
_no_name_provided__155.invoke_okcceq_k$         	sandbox.js:63086
eval                                            	sandbox.js:63194
Async call from requestAnimationFrame
$withFrameNanosCOROUTINE$4.doResume_0_k$        	sandbox.js:63125
[...]
```

This is caused by the following code invoking `checked(checked)` before applying attributes:
https://github.com/JetBrains/compose-jb/blob/db53b95a3174f985f067ef0620dd0ca8369ecb95/web/core/src/jsMain/kotlin/org/jetbrains/compose/web/elements/InputElements.kt#L25-L33

MDC Checkbox requires a class "mdc-checkbox__native-control" to be present before dealing with state changes. Reversing the order to `this.attrs()`, then `checked(checked)` would fix it:

```kotlin
        attrs = {
            this.attrs()
            checked(checked)
        }
```

**Comment by eymar** [comment]
Hi @OliverO2 !
Do you have a branch somewhere where we can reproduce this?

if the order really matters, then you can try:

```kotlin
Input(
    type = InputType.CheckBox,
    attrs = {
         yourAttrs()
         checked(checked)
    }
)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6140">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
