### ISSUE TITLE
Update  1.0.0 to androidx compose 1.1.0-beta04+ for support 1.6.0 compiler

### ISSUE THREAD

**Issue by slavonnet** [JetBrains/compose-jb#1529]
> Task :app:kspMinApi30DebugKotlin FAILED
e: This version (1.1.0-beta01) of the Compose Compiler requires Kotlin version 1.5.31 but you appear to be using Kotlin version 1.6.0 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

**Comment by akurasov** [comment]
It is on the top of our current task list

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6194">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
