### ISSUE TITLE
Will there be a code/richtext editor widget?

### ISSUE THREAD

**Issue by ice1000** [JetBrains/compose-jb#1530]
I believe this is what JetBrains is very good at.

**Comment by habibg1232191** [comment]
You can do it yourself, as I understand it is not a particularly difficult task, if you are interested I can throw off an example code of how to do this

**Comment by ice1000** [comment]
> You can do it yourself, as I understand it is not a particularly difficult task, if you are interested I can throw off an example code of how to do this

Phase do! I'm extremely curious

**Comment by habibg1232191** [comment]
here's an example(it's not finished yet): [HomeScreenUi.kt](https://github.com/habibg1232191/AniJin/blob/main/src/main/kotlin/shared/screen/home/HomeScreenUi.kt#L180). Selection of text does not work quite correctly. 
According to this scheme, you can easily make a text editor

**Comment by akurasov** [comment]
There is no RichText component at the moment and yes, it is possible to create it with current API. There is already an issue about it - #1477 , so I'll close this one as a duplicate

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6172">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
