### ISSUE TITLE
Compatibility Table

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#1537]
The `compose-jb` repository readme should probably contain an explanation of the Jetbrains versioning scheme, how it relates to the Google versioning scheme.  It should also have a quick compatibility table, which shows the latest recommended builds of Compose Multiplatform, the associated version of Kotlin, and the associated version of the Android artifacts.  This way, people can choose a version of Compose MPP based on their Android version or Kotlin version or vice versa.

**Comment by akurasov** [comment]
Done in https://github.com/JetBrains/compose-jb/tree/master/tutorials/Development_for_Android

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6183">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
