### ISSUE TITLE
CSS nth-child(an+b) cannot be used

### ISSUE THREAD

**Issue by mee1080** [JetBrains/compose-jb#1538]
Nth.Functional doesn't inherit Nth, and `nthChild(Nth.Functional(2,1))` is an error.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6145">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
