### ISSUE TITLE
How to load many images

### ISSUE THREAD

**Issue by Yoke0** [JetBrains/compose-jb#1554]
The sample of imageview can‘t fulfil requirements，please tell me how to deal with it，thanks.

**Comment by akurasov** [comment]
Could you please clarify, what is the issue with loading many images comparing to load few of them in your case?

**Comment by akurasov** [comment]
Closing as dormant

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6147">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
