### ISSUE TITLE
[Web application] Input with type InputType.Radio is not update ui

### ISSUE THREAD

**Issue by antranvn** [JetBrains/compose-jb#1556]
Let's say I have an Input with type Radio, but when onChange is called, I try to check/ uncheck the checkbox, but it is not successful.

Below is my code. Please help check it.

`Input(
                type = InputType.Radio,
                attrs = {
                    classes("filled-in")
                    checked(true)
                    onChange {
                        checked(it.value)
                    }
                }
            )`

**Comment by antranvn** [comment]
Expected: when clicking check box, the check box is checked/ unchecked.

Actual: checkbox keep checked state.

**Comment by simonegiacomelli** [comment]
There are two issues with your code.

1. You need to use InputType.Checkbox
2. You need to implement the reactive pattern (if you are going down this direction)

This is a mvc that I wrote from what I think you want:

```  
    val checkboxState = remember { mutableStateOf(true) }

    Input(type = InputType.Checkbox,  attrs = {
        classes("filled-in")
        checked(checkboxState.value)
        onChange { checkboxState.value = it.value }
    })
```

To clarify what's going on, the [documentation](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Web/Controlled_Uncontrolled_Inputs/README.md) can help you

**Comment by eymar** [comment]
@simonegiacomelli  you're right that in this case one needs to use `MutableState<...>` in order to update checked(...) state of the input.

But I'm not sure I understand your 1st point -  "You need to use InputType.Checkbox".
In your opinion, why can't one use `InputType.Radio` ?

**Comment by simonegiacomelli** [comment]
@eymar good point. The issue arises from the difference between the title, the first post and the second post.

In the second post we have:

> Expected: when clicking check box, the check box is checked/ unchecked.
>
> Actual: checkbox keep checked state.

So, I did not mention before this discrepancy (radio vs checkbox) and I went straight for what I though was the intent of the issue.

With only one radio control you could get confused observing the behaviour: the usual user expectation of a click on a single checked radio control is not to uncheck it.
So I wrote an example with a checkbox, that was an answer to the second post (also the first post mention the checkbox)

**Comment by antranvn** [comment]
Thank you guys

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6174">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
