### ISSUE TITLE
How to set an app icon on package-time, not runtime?

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#156]
I wanted to set a custom icon for my app, but here is the problem. For macOS I can just edit some files inside of the package, but with Windows or Linux that will not work.

So, how to set an app icon on package-time?

**Comment by GGorAA** [comment]
Oh, sorry, I found it in the docs. Im blind XD

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5579">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
