### ISSUE TITLE
Can't use vendor or copyright in end package

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#157]
As In the title, I can't specify copyright on vendor, because jpackage just dies.

**Comment by olonho** [comment]
It's not an issue to report in this issue tracker, please report to your JDK vendor.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5578">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
