### ISSUE TITLE
EditText/BAsicEditText scroll support broken

### ISSUE THREAD

**Issue by sergeych** [JetBrains/compose-jb#1575]
Impossible to correcly connect vertical scrollbar to EditText or BasicEditText. If the scllbar is connected, then when caret goes below the visible part of the text it just disspears. It is expected that the text editor automatically scrolls as the caret moves.

If the line makred below as (1) is commented out, the eritor properly scrolls to make caret always visible, but the scrollbar is no more connected and does not function.

~~~kotlin
    var text by remember { mutableStateOf(TextFieldValue("some multiline text")) }
    val ss = rememberScrollState()

    Column(
        modifier = Modifier.fillMaxSize().background(Color.White)
    ) {
        Box(Modifier.weight(1f).padding(4.dp).fillMaxWidth()) {
            BasicTextField(
                text, { text = it },
                Modifier.fillMaxSize()
                    .verticalScroll(ss) // (1) with this like cursor goes off screen, with it no scrollbar is dsiplayed
                    .padding(0.dp)
                    .focusRequester(fr),
                textStyle = TextStyle(fontFamily = FontFamily.Monospace, fontSize = 1.em)
            )
            VerticalScrollbar(
                rememberScrollbarAdapter(ss), Modifier.align(Alignment.CenterEnd),
                style = defaultScrollbarStyle().copy(hoverDurationMillis = 700)
            )
        }
   }
~~~

project settings:
~~~
    kotlin("jvm") version "1.5.31"
    id("org.jetbrains.compose") version "1.0.0"
~~~

**Comment by NeroSong** [comment]
meet it too. 
after a TextField combined  with VerticalScrollbar, it will lose auto-scroll when cursor move out of view.

**Comment by radicaled** [comment]
Does anyone have a workaround for this? I've hacked for a few hours but it seems like the only real solution is to modify the source code directly, which I'd like to avoid.

**Comment by sergeych** [comment]
as of 1.2.2 it is still here. A year ago a critical bug has been reported. Looks like the platform is about to be abandoned. I suppose they have fired their Russian dev team just then and hardly could ever substitute it ;)

@radicaled did you find any idea how to fix it? I'm really disappointed as our plans were to use the platform, we switched to kotlin for a reason, and it seems to be dying and self-cancelling...

**Comment by sergeych** [comment]
I've created test project to show it and probably create a workaround: https://github.com/sergeych/EditScrollBarBug

**Comment by radicaled** [comment]
> @radicaled did you find any idea how to fix it?

Afraid not. 

This issue + some others in the repository + discovering that Fleet not using Compose for Desktop has kind of shaken my confidence in using Compose Multiplatform as a solution for desktop applications, so I don't think I'll be expending much more effort in this direction.

**Comment by sergeych** [comment]
What a pity the only cross platform solution with the more it less usable
programming language seems to be abandoned. Jetbrains shouldn't fire off
their russian team. Without them guys are just salesmen with nothing more
to sell. Real pity.

**Comment by igordmn** [comment]
It is not correct to add `verticalScroll` to `TextField`, because `TextField` is already scrollable by itself. The correct way is impossible right now (at least with simple code).

We need to extend `BasicTextField`, adding ability to manipulate its internal scroll state. It will look something like this after we add that:
```
val ss = rememberScrollState()
BasicTextField(
    text, { text = it },
    scrollState = ss
)

VerticalScrollbar(
    rememberScrollbarAdapter(ss), Modifier.align(Alignment.CenterEnd),
    style = defaultScrollbarStyle().copy(hoverDurationMillis = 700)
)
```
It is a design flaw, not a bug. But nevertheless it isn't nice that Compose Multiplatform still does not have this ability.

**Comment by m-sasha** [comment]
The new (experimental) API can be used like this (once released):

```
Box(...){
    val scrollState = rememberTextFieldVerticalScrollState()
    BasicTextField(
       text = ...,
       onValueChange = ...,
       scrollState = scrollState
    )

    VerticalScrollbar(
        adapter = rememberScrollbarAdapter(scrollState),
        modifier = ...
    )
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6070">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
