### ISSUE TITLE
How to understand which version of Compose should be used with which version of Kotlin?

### ISSUE THREAD

**Issue by SerVB** [JetBrains/compose-jb#1581]
Imagine someone wants to add Compose to their Kotlin project.

For now, it's unclear which version of Compose is compatible with Kotlin version of the project. They can try of course, but the process is tedious because there are just errors in console after each try:

> e: This version (1.1.0-beta01) of the Compose Compiler requires Kotlin version 1.5.31 but you appear to be using Kotlin version 1.6.0 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

There are two solutions I see now:

1. Provide a table of matching Compose and Kotlin versions.
2. Do like in https://github.com/Kotlin/kotlinx.serialization#using-the-plugins-block: use Kotlin version for Compose Plugin version.

**Comment by akurasov** [comment]
Yes, there is a need in such document. Compose Multiplatform 1.0.0 works with Kotlin 1.5.31

**Comment by akurasov** [comment]
Information added to https://github.com/JetBrains/compose-jb/blob/master/FEATURES.md

**Comment by SerVB** [comment]
Thanks! Could you please clarify what `+` (plus) means in Compose versions?

Compose version | Kotlin version
--- | ---
1.0.0+ | 1.5.31
1.0.1-rc2+ | 1.6.10

Am I right that there is no version that is compatible with Kotlin 1.6.0? Not handy...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5134">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
