### ISSUE TITLE
how can print jetpack compose canvas  in windows desktop app or print any jetpack  UI like LazyColumn

### ISSUE THREAD

**Issue by helmysaeed** [JetBrains/compose-jb#1585]
how can print jetpack compose canvas 
in windows desktop app or print any
jetpack  UI like LazyColumn

**Comment by akurasov** [comment]
I'm sorry, I don't understand what do you want to do

**Comment by kirill-grouchnikov** [comment]
Probably something like https://docs.oracle.com/javase/tutorial/2d/printing/index.html

**Comment by helmysaeed** [comment]
w

> Probably something like https://docs.oracle.com/javase/tutorial/2d/printing/index.html

it does not support jetpack compose   like canvas

**Comment by helmysaeed** [comment]
> I'm sorry, I don't understand what do you want to do

I need to print Invoice created by jetpack compose canvas or print lazyColumn directly
like when print  canvas in android

**Comment by kirill-grouchnikov** [comment]
My comment was not to suggest that Java2D printing somehow magically works for a completely different toolkit that is Compose. It was to clarify the request.

Probably given the multi-platform aspirations of this framework, the simplest would be to provide a functionality to export canvas content to a PDF and have the underlying platform handle the PDF-to-print pipeline.

**Comment by helmysaeed** [comment]
> My comment was not to suggest that Java2D printing somehow magically works for a completely different toolkit that is Compose. It was to clarify the request.
> 
> Probably given the multi-platform aspirations of this framework, the simplest would be to provide a functionality to export canvas content to a PDF and have the underlying platform handle the PDF-to-print pipeline.

@kirill-grouchnikov  thank you

**Comment by akurasov** [comment]
Currently there is no such possibility. What probably could be tried is the following: 
1. Create test Window with the same content
2. Grab its bitmap
3. Find some java printing engine that accepts bitmap and pass the bitmap to it

Steps 1-2 are described in https://github.com/JetBrains/compose-jb/issues/368

**Comment by mcpiroman** [comment]
Couldn't `ComposeScene` be used? With it you can draw to canvas instead of window.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5131">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
