### ISSUE TITLE
Make LazyListState.visibleItemsCount public

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-jb#1593]
Hi, is it possible for you guys to change `LazyListState.visibleItemsCount` from `internal` to `public`? It's a very useful API that we have to currently workaround by calculating it ourselves, in a very convoluted way, as we have no reach to the internals.

https://github.com/JetBrains/androidx/blob/bc4f98ccbba27171f1bc419f2fb5b920401bc781/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/LazyListState.kt#L125-L128

**Comment by akurasov** [comment]
@jimgoog what do you think about it?

**Comment by haikalpribadi** [comment]
Or am I meant to use this API instead? 🤔 https://github.com/JetBrains/androidx/blob/bc4f98ccbba27171f1bc419f2fb5b920401bc781/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/LazyListLayoutInfo.kt

**Comment by AtriusX** [comment]
I could be wrong but wouldn't it be possible to calculate the value from the lazy list state by just doing `state.layoutInfo.visibleItemsInfo.size`? I would assume the visible items info amount would match the corresponding value you're hoping to get, but I could be wrong.

**Comment by haikalpribadi** [comment]
Yes, that's what my question above was implying. I just found out about `state.layoutInfo`, which returns `LazyLayoutListInfo`. I didn't know about it when I was posting this issue.

So I assume `state.layoutInfo.visibleItemsInfo.size` is the way to go, right? I'll close this issue now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5130">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
