### ISSUE TITLE
Composite build fails when using `withJava` in jvm platform

### ISSUE THREAD

**Issue by rocketraman** [JetBrains/compose-jb#1596]
Have two builds that use compose-jb.

Build A has a JVM platform as well as a JS platform. This build does `includeBuild` on Build B. It has compose-jb in commonMain.

Build B has a JS platform. It has compose-jb in jsMain.

If Build A has `jvm() { withJava() }` then the build fails -- the presence of `withJava` appears to create a `main` source set, which creates a `compileClasspath` configuration, which then results in this error:

```
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all task dependencies for configuration ':compileClasspath'.
   > Could not resolve androidx.compose.runtime:runtime:1.1.0-beta02.
     Required by:
         project : > org.jetbrains.compose.runtime:runtime:1.0.0-rc1
      > No matching variant of androidx.compose.runtime:runtime:1.1.0-beta02 was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'releaseVariantReleaseApiPublication' capability androidx.compose.runtime:runtime:1.1.0-beta02 declares an API of a library, and its dependencies declared externally:
              - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, preferably in the form of class files
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
          - Variant 'releaseVariantReleaseRuntimePublication' capability androidx.compose.runtime:runtime:1.1.0-beta02 declares a runtime of a library, and its dependencies declared externally:
              - Incompatible because this component declares a component, with the library elements 'aar' and the consumer needed a component, preferably in the form of class files
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
          - Variant 'sourcesElements' capability androidx.compose.runtime:runtime:1.1.0-beta02 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
```

If Build A does not include build B it works fine (i.e. it pulls B in via a package dependency instead), even with `withJava()`.

Here is a reproduction:

https://github.com/innertech/kmdc/blob/composite-with-java/sandbox/build.gradle.kts

Run the `sandbox` build, which includes the kmdc parent project. Note the failure. Comment out the `withJava` and note the build succeeds.

**Comment by akurasov** [comment]
I'm not sure it is the correct way to organize the project. You have common module with java support and JS target. So basically you want to compile Java code to JS - this doesn't seem correct. 

What is the reason for such project organization?

**Comment by akurasov** [comment]
BTW, I took web project template, extended it with 
    jvm {
        withJava()
    }

and still don't have any issues. Probably you have java code in common sourceset or something like it. Can you put the whole reproducer somewhere?

**Comment by rocketraman** [comment]
> I'm not sure it is the correct way to organize the project. You have common module with java support and JS target. So basically you want to compile Java code to JS - this doesn't seem correct.
> 
> What is the reason for such project organization?

The reproducer doesn't show this, but the actual project in which I encountered this is structured like a kvision project -- the JVM platform code is the backend code, the JS platform code is the frontend code, and the common code is shared data models and business logic.

With this setup, there is no reason why the backend code cannot have java code in it -- the backend deploys and runs on a JVM.

> Probably you have java code in common sourceset or something like it.

No, that is not the case.

> Can you put the whole reproducer somewhere?

I linked to the reproducer project in the original post. Here are the full instructions:

```
git clone https://github.com/innertech/kmdc.git
cd kmdc
git checkout composite-with-java
cd sandbox
./gradlew build
```

**Comment by akurasov** [comment]
The issue was that you used old Kotlin plugin: 
kotlin("multiplatform") version "1.5.31"

Replace it with kotlin("multiplatform") version "1.6.10" and everything will be fine. This is an issue of Kotlin Mpp Gradle plugin, so it needs to be updated.

**Comment by rocketraman** [comment]
Thank you. I was on 1.5.31 for compatibility with Compose but I see some recent commits related to compat with 1.6.10 so that's great.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5127">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
