### ISSUE TITLE
Docs/Samples for adding Compose Web into a legacy JS/TS app migration

### ISSUE THREAD

**Issue by StokeMasterJack** [JetBrains/compose-jb#1602]
Greenfields apps are great. But many users (myself included) have large legacy JavaScript (or TypeScript) apps.

I have a large legacy app with webpack, typescript, react and mui on the client. 

It would be great if there were docs or samples that show how one might gradually introduce Compose Web into this existing web app.

**Comment by eymar** [comment]
@StokeMasterJack 

We've added an example here https://github.com/JetBrains/compose-jb/tree/master/examples/web-compose-in-js 
Please let us know if it helps or not.

**Comment by akurasov** [comment]
Closing as done

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5123">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
