### ISSUE TITLE
Sample TodoApp Web app does not compile 

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#1606]
```
Could not determine the dependencies of task ':common:utils:jsTestPackageJson'.
> Could not resolve all dependencies for configuration ':common:utils:jsTestNpm'.
   > Could not find org.jetbrains.kotlin:kotlin-test-common:null.
```

Looks like it was broken in #1511. I will try to fix it in the coming days.

**Comment by igordmn** [comment]
Should be fixed in https://github.com/JetBrains/compose-jb/pull/1607#issuecomment-995253256

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5119">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
