### ISSUE TITLE
Add option to set macOS build version

### ISSUE THREAD

**Issue by Thomas-Vos** [JetBrains/compose-jb#1611]
Add option to set macOS build version in addition to the release version.

Currently you can set the version using `packageVersion`, which will set both `CFBundleShortVersionString` and `CFBundleVersion`. There is no way to set the build version (`CFBundleVersion`) to a different number.

The build version is useful for TestFlight. This way you can increment the build version (`CFBundleVersion`) without incrementing the release (public) version (`CFBundleShortVersionString`) for updates on TestFlight. (And once there is a stable build it can be pushed to the App Store and users only see the release version).

I will create a PR which adds support for setting the build version to a different version.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5117">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
