### ISSUE TITLE
Add unit test example for web

### ISSUE THREAD

**Issue by eiswind** [JetBrains/compose-jb#1617]
As with any serious framework I was searching for an example to create a unit test with web (the same would go for desktop).
I found that the desktop implementation is still incomplete, but I did not find anything related to web.

**Comment by eymar** [comment]
there is a basic tutorial covering unit testing of compose-for-web components based on DOM: https://github.com/JetBrains/compose-jb/blob/master/tutorials/Web/Using_Test_Utils/README.md

Please let us know if that's what you're looking for.

**Comment by eiswind** [comment]
Thanks. I think this will help getting started.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5114">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
