### ISSUE TITLE
Recomposition is not scheduled on SnapshotList change

### ISSUE THREAD

**Issue by metametamoon** [JetBrains/compose-jb#1618]
The following code is an example of a simple ui list which support deletion on button press.
```kotlin
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material.Text
import androidx.compose.material.TextButton
import androidx.compose.material.TextField
import androidx.compose.runtime.*
import androidx.compose.runtime.snapshots.SnapshotStateList
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.WindowState
import androidx.compose.ui.window.singleWindowApplication

data class Man(var surname: String)

@Composable
fun ShowMan(man: Man) {
    Row {
        var surname by remember { mutableStateOf(man.surname) }
        TextField(
            surname,
            onValueChange = { newAgeString: String ->
                man.surname = newAgeString
                surname = newAgeString
            })
    }
}


@Composable
fun <T> UiList(
    list: SnapshotStateList<T>,
    DisplayElement: @Composable (T) -> Unit,
) {
    @Composable
    fun DisplayRow(element: T, Button: @Composable () -> Unit) {
        Row { DisplayElement(element); Button() }
    }

    Column {
        list.forEach {
            DisplayRow(it) {
                TextButton(onClick = { list.remove(it); println(list[0]) }) {
                    Text("X", color = Color.Red)
                }
            }
        }
    }
}

@Composable
fun ManExample() {
    val men = mutableStateListOf(Man("Anne"), Man("Chris"))
    UiList(men) { man -> ShowMan(man) }
}

fun main() = singleWindowApplication(
    state = WindowState(width = 900.dp, height = 600.dp)
) { ManExample() }
```

On button presses, the list is updated (as the element is deleted) and thus the recomposition of UiList function must be scheduled (as it reads form list). This, however, does not happen.
This application displays two rows for people named Anne and Chris:
![image](https://user-images.githubusercontent.com/64495509/146640616-76dedff5-d5f4-45a0-9a4f-4b7ce1701059.png)

On pressing the first cross (to delete the person named "Anne"), the console prints "Chris" (as the first element of the remaining list); however, on the window Chris is deleted instead:
![image](https://user-images.githubusercontent.com/64495509/146640653-2b7867ce-f4ce-492c-9bc9-e35a9598829f.png)

**Comment by shenliuyang** [comment]
change   var surname by remember { mutableStateOf(man.surname) } to var surname by remember { mutableStateOf(man.surname) }.apply { value = man.surname }  will fix .

**Comment by Maxr1998** [comment]
Inside the `forEach`, add a  `key(it) {}` around your content (and while unrelated, ideally use a specific name instead of `it`).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5113">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
