### ISSUE TITLE
Remove "kotlin-android-extensions" from templates and Project Wizard in IDEA

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#162]
Because it is deprecated:

https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html

**Comment by igordmn** [comment]
See also https://github.com/JetBrains/compose-jb/issues/158

**Comment by igordmn** [comment]
Templates in this github repository doesn't contain "kotlin-android-extensions".

In wizard templates it will be removed in https://youtrack.jetbrains.com/issue/KTIJ-730

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5574">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
