### ISSUE TITLE
Is there a good webview solution for jb?

### ISSUE THREAD

**Issue by fendo8888** [JetBrains/compose-jb#1622]
Based on the implementation of chrome or Firefox, although currently swing has jcef and javafx has webview, can jb provide a webview component similar to electron? The main reason is that the compatibility of the two is not very optimistic.

**Comment by akurasov** [comment]
At the moment no. You could try to use some Swing WebView solution via Compose-Swing interop

**Comment by akurasov** [comment]
Duplicate of https://github.com/JetBrains/compose-jb/issues/668

**Comment by KevinnZou** [comment]
I would recommend this library https://github.com/KevinnZou/compose-webview-multiplatform. It supports WebView on the desktop side using JCEF.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5109">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
