### ISSUE TITLE
Can jb integrate miniblink?

### ISSUE THREAD

**Issue by fendo8888** [JetBrains/compose-jb#1623]
a lighter, faster browser kernel of blink to integrate HTML UI in your app：
https://miniblink.net/  https://github.com/weolar/miniblink49

**Comment by akurasov** [comment]
it is not on our nearest plans. But you can try to integrate it yourself.

**Comment by fendo8888** [comment]
In your plan, is there any support for the browser component? Can you reveal it?

**Comment by akurasov** [comment]
There are no specific plans on integrating WebView. You can use Swing components that do it via interop.

**Comment by fendo8888** [comment]
Ok

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5108">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
