### ISSUE TITLE
[Web App] Build failed with an exception(Could not find org.nodejs:node:14.17.0.).

### ISSUE THREAD

**Issue by bingerz** [JetBrains/compose-jb#1625]
When I tried the first JetBrains Compose For Web project, I encountered the following problems when compiling, indicating that the Arm version of the node could not be found. I probably located it from the Internet because the current default configuration of the node version does not support the M1 chip. I checked the website of Node, and the M1 chip will be supported after v16.0.0. Thank you very much. Can I manually set the version of node used from there?

Apple MBP 2021 M1 Max
MacOS Monterey v12.1
IntelliJ IDEA 2021.3 Version #IU-213.5744.223
Runtime: 11.0.13+7-b1751.19 aarch64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.

./gradlew jsBrowserRun
> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':kotlinNodeJsSetup'.
> Could not resolve all files for configuration ':detachedConfiguration2'.
   > Could not find org.nodejs:node:14.17.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/nodejs/node/14.17.0/node-14.17.0.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/nodejs/node/14.17.0/node-14.17.0.pom
       - https://dl.google.com/dl/android/maven2/org/nodejs/node/14.17.0/node-14.17.0.pom
       - https://nodejs.org/dist/v14.17.0/node-v14.17.0-darwin-arm64.tar.gz
     Required by:
         project :

**Comment by eymar** [comment]
yes, please have a look at this workaround https://github.com/JetBrains/compose-jb/commit/abc6d1f60aee1edae898e6a5cdd7c207618d2a90

**Comment by bingerz** [comment]
Thank you, the issue is solved. @eymar

**Comment by akurasov** [comment]
@eymar am I correct, that we can do nothing with it besides this WA?

**Comment by eymar** [comment]
> @eymar am I correct, that we can do nothing with it besides this WA?

@akurasov  This is the only option for now. But afaik this should fixed in kotlin 1.6.20

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5107">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
