### ISSUE TITLE
About idea plugin support

### ISSUE THREAD

**Issue by weili71** [JetBrains/compose-jb#1627]
How to use compose to write the UI of the idea plugin

**Comment by akurasov** [comment]
There is an example of IDEA plugin - https://github.com/JetBrains/compose-jb/tree/master/examples/intellij-plugin

**Comment by weili71** [comment]
Thank you. I see

**Comment by weili71** [comment]
How compose refers to the icon in the resource directory

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5105">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
