### ISSUE TITLE
Textfield cannot handle IME's select all, copy and paste actions

### ISSUE THREAD

**Issue by weili71** [JetBrains/compose-jb#1628]
compose:
<img src="https://user-images.githubusercontent.com/59408438/146899237-b1fa0204-ec96-4e48-9f5b-ca445593c6ae.gif" width = "200px"  alt="compose" align=center />

EditText:
<img src="https://user-images.githubusercontent.com/59408438/146899464-b4e06bba-1ee4-4eca-9d96-07af30dc6113.gif" width = "200px"  alt="EditText" align=center />

**Comment by akurasov** [comment]
Hello! What is IME? Am I correct that these are some built-in actions on some Android phones?

**Comment by weili71** [comment]
> 你好！什么是输入法？这些是某些 Android 手机上的一些内置操作，我是否正确？

**Comment by weili71** [comment]
> IME such as Baidu and Sogou, the select all copy and paste button that comes with IME can work normally on EditText, but not on compose Textfeild.

**Comment by weili71** [comment]
Gboard IME also has this problem, you can try it with Gboard
<img src="https://user-images.githubusercontent.com/59408438/146936556-dd906433-5e6a-496b-9128-844e3c4bd933.gif" width = "200px"  alt="compose" align=center />

**Comment by akurasov** [comment]
If this is an android issue, then it should be reported to google here - https://issuetracker.corp.google.com/u/0/issues?q=componentid:612128%20status:open#

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5104">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
