### ISSUE TITLE
Project Wizard fails to generate the project

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [JetBrains/compose-jb#163]
I ran the project wizard choosing Desktop template as mentioned in this tutorial. However it failed to generate and threw this error:
```
Plugin [id: 'org.jetbrains.compose', version: '0.2.0-build131'] was not found in any of the following sources.
```

Config:
```
IntelliJ IDEA 2020.3 (Community Edition)
Build #IC-203.5981.155, built on December 1, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
```

**Comment by SaifurRahmanMohsin** [comment]
Ok, I figured out what the issue was. The project wizard had failed to add the `settings.gradle.kts` file with it's contents and that is why I faced this error.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5573">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
