### ISSUE TITLE
Release 1.0.1-rc2 as 1.0.1

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#1630]
Hey, would it possible to publish `1.0.1-rc2` as `1.0.1`? Currently, if you use the `rc-2` version and use dependabot, it tries to update this version to the latest nightly alpha versions (because you use a rc version). This results into weekly PRs for each repository promoting a nightly version.
You want to use this RC version (1.0.1-rc2), because it supports Kotlin 1.6.10.

**Comment by akurasov** [comment]
We are going to release 1.0.1 very soon(few days), unless some critical issues are found in 1.0.1-rc2

**Comment by olonho** [comment]
Done

**Comment by felixdivo** [comment]
@akurasov Is there deliberately no changelog for the version or was it forgotten?

**Comment by akurasov** [comment]
@felixdivo thank you, nice point. There are no major changes besides switching to a new Kotlin. But anyway I added it to CL.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5102">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
