### ISSUE TITLE
Arm32 support

### ISSUE THREAD

**Issue by rno** [JetBrains/compose-jb#1644]
I see that Jetpack Compose supports Linux arm64 and x64 but it doesn't seem to support Linux arm32. Is there a plan to support Linux arm32?

Sorry if that got mentioned somewhere, I couldn't find anything related to not supported ABIs.

Thank you.

**Comment by olonho** [comment]
arm32 support is not planned.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5096">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
