### ISSUE TITLE
imageviewer example is very slow on linux mint

### ISSUE THREAD

**Issue by ronsmits** [JetBrains/compose-jb#165]
Desktop environment:
- linux mint 20
- Nvidia GTX1050TI 
- 8Gb memory
Ryzen 5 1600X CPU

When the imageview comes up, as soon as the mouse moves into it, it becomes slow. Clicking on one of the elements shows a very clear delay in the response from the application. I made a small video on youtube to show it: https://youtu.be/k2R9ud94QEo

If more information is needed, or if I can assist in debugging this please let me know

**Comment by olonho** [comment]
What is the JDK version? Can you try another JDK?

**Comment by igordmn** [comment]
I created a special build of Compose to test what is actually slow:
`org.jetbrains.compose:compose-gradle-plugin:0.0.0-renderinglog-build16` (it is in maven repo)
This build will log into console some points of the rendering process.

Can you launch imageviewer, click on text of item and show what log will be after "[FrameDispatcher] mousePressed"?
(I attached imageviewer with changed version).

[imageviewer_log.zip](https://github.com/JetBrains/compose-jb/files/5658311/imageviewer_log.zip)

**Comment by igordmn** [comment]
The lags probably because of the two connected displays. Will be fixed as part of https://github.com/JetBrains/compose-jb/issues/23

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5571">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
