### ISSUE TITLE
[Web] Make AttrsBuilder<T> extendable

### ISSUE THREAD

**Issue by mpetuska** [JetBrains/compose-jb#1651]
Currently `AttrsBuilder<T>` is declared as an `open class` as opposed to an `interface` like `ElementScope<T>`. Not only this breaks consistency, but also prevents from extending `AttrsBuilder<T>` via delegated implementation to inject your own custom scope.

Consider this scenario, where as a compose library developer, I want to make certain extensions available in `attrs = {}` argument for my custom composable which is then proxied into an HTML composable. My extensions should only be available for my custom composable as opposed to all `Button()` composables.
```kotlin
class MyCustomAttrsBuilder: AttrsBuilder<HTMLButton>() {
  fun onCustomEvent(listener: () -> Unit) {
    addEventListener("MyCustomEventName") { listener() }
  }
}

@Composable
fun MyCustomComponent(attrs: MyCustomAttrsBuilder.() -> Unit) {
  Button(
    attrs = {
      val custom = MyCustomAttrsBuilder().apply(attrs) // Consumer's attrs are applied to my own instance of AttrsBuilder with no way to proxy them onto `this` AttrsBuilder instance.
      this.copyFrom(custom) // <------- Potential solution
    }
  )
}
```

Now since `ElementScope<T>` is an interface, the above problem can be solved quite easily with delegated implementation
```kotlin
class MyCustomElementScope(originalScope: ElementScope<HTMLButton>): ElementScope<HTMLButton> by originalScope {
  @Composable
  fun CustomSubComponent() {
    Div()
  }
}

@Composable
fun MyCustomComponent(content: @Composable MyCustomElementScope.() -> Unit) {
  Button(
    content = {
      MyCustomElementScope(this).content() // Works just fine, because all base methods will be delegated to `this`
    }
  )
}
```

Ideally, both, `AttrsBuilder` and `ElementScope` should be exposed to HTML composable argument builder lambdas as interfaces.

On a side note, `AttrsBuilder` should probably be renamed to `AttrsScope` to be more discoverable and consistent with `ElementScope`. This rename would also allow keeping the current `AttrsBuilder` class untouched (except for making it implement the new interface) and in-use behind the scenes, only changing the types at the HTML composables, therefore making all old code using `AttrsBuilder` still valid as it implements the new `AttrsScope` interface.

**Comment by eymar** [comment]
Hi @mpetuska !
We finally discussed your proposal.

As we understood the proposed change, it would introduce a new interface `AttrsScope` with methods/functions currently defined in AttrsBuilder.
Then AttrsBuilder will implement this new AttrsScope interface.
 And finally, all places using AttrsBuilder as a parameter (or extension) type should  change it for `AttrsScope` instead.
 
 
 In a slack chat you mentioned, you could send a PR for this change. We think your PR would be beneficial. But it's okay if you can't send a PR - we'll try to make this change then. The proposed change makes sense and  should be useful. Thank you for pointing it out.

**Comment by mpetuska** [comment]
Great, I'll raise a PR this weekend.

**Comment by mpetuska** [comment]
Got a bit too excited... https://github.com/JetBrains/compose-jb/pull/1694

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1651">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
