### ISSUE TITLE
Outdated Gradle versions

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-jb#1654]
Many examples (I haven't checked them all) are still not usable with Java 17 because you have still configured an outdated Gradle version which results in the following error message.

JDK 17.0.1 isn't compatible with Gradle 7.1.1. Please fix JAVA_HOME environment variable.

The real fix is NOT to fiddle with the JAVA_HOME as suggested but instead to update the Gradle version to (currently) 7.3.3.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1654">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
