### ISSUE TITLE
Regression in ContextMenuArea documentation

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#1657]
Looks like https://github.com/JetBrains/compose-jb/commit/929b28787d023010413bdcf2a85657c2765725bd#diff-1a44483ab5e62db5e679c0638bc668218cbbca8f41fcedb34648a7f43aa88126R133 accidentally regressed the example such that the section titled "Context menu for an arbitrary area" no longer demonstrates the usage of `ContextMenuArea` and no longer matches the description in the section.

cc @olonho

**Comment by akurasov** [comment]
To check tutorials/Context_Menu/README.md

**Comment by igordmn** [comment]
Thanks!

[It is fixed some time ago](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Context_Menu/README.md#context-menu-for-an-arbitrary-area)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1657">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
