### ISSUE TITLE
How to execute onClick event when ripple finished on Modifier.clickable ?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#1667]
I want to execute the onClick when ripple **'finished'**,but it always execute onClick when ripple is **'in progress'**.
I am doing a file manager for Android.When I clicked the file item,the ripple showoed as I wish.But when I clicked the directory item,the ripple not showed and the screen go to a new directory.

video:
click file item:
https://user-images.githubusercontent.com/23566361/148474290-47a5dae4-1de2-4043-93ed-b4b35596ae09.mp4

click direectoryy item:
https://user-images.githubusercontent.com/23566361/148474331-8c2f7769-0b19-46fc-a03b-602669e4adef.mp4

code:
![image](https://user-images.githubusercontent.com/23566361/148474944-50c79f58-b474-41e3-9bfd-b88b19de4ed2.png)

I want to show ripple when click directory item,and go to new directory when ripple finished.
How to do it?

And by the way,how to set the ripple'time or speed?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1667">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
