### ISSUE TITLE
Swing interoperability 

### ISSUE THREAD

**Issue by etiennept** [JetBrains/compose-jb#167]
Hello 
Does it exits a UI like androidView of [android](https://developer.android.com/jetpack/compose/interop)  for jecpack compose desktop

**Comment by kirill-grouchnikov** [comment]
https://github.com/JetBrains/compose-jb/tree/master/tutorials/Swing_Integration

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6511">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
