### ISSUE TITLE
Windows IME position is wrong

### ISSUE THREAD

**Issue by taodongl** [JetBrains/compose-jb#1670]
Environment: 

+ Windows 11
+ Windows default chinese IME
+ Graphics Card: NVIDIA GTX 750 Ti
+ Compose version: id("org.jetbrains.compose") version "1.0.1"
+ JDK 11

## issue 1: IME candidate window is at Top-Left of Desktop:
![1](https://user-images.githubusercontent.com/1430663/148631824-7088bc5b-04e9-4eb0-80e1-b9ec4b148d98.png)

## issue 2: The position of input character of IME is wrong:
![3](https://user-images.githubusercontent.com/1430663/148631891-deccb1cf-60ab-49a4-b4e9-9fe5198061ae.png)

After press the "Windows" button of keyboard mutiple times, the right IME position is restored:
![4](https://user-images.githubusercontent.com/1430663/148632062-a87652ee-1dcb-4088-bcfa-12945b001be5.png)

**Comment by igordmn** [comment]
Should be fixed in 1.1.0
