### ISSUE TITLE
How to exclude few META-INF files for packageUberJarForCurrentOS

### ISSUE THREAD

**Issue by amank22** [JetBrains/compose-jb#1675]
Hi,
I would like to know how can I exclude few files from packageUberJarForCurrentOS?
These include signature files files which causes issue in final jar.

Steps:
- Add any dependency which has signature files in it (*.SF etc)
- Execute `packageUberJarForCurrentOS`
- Run with `java -jar file.jar`
- You will get `Error: Could not find or load main class app.MainKt Caused by: java.lang.ClassNotFoundException: app.MainKt`
- Run `jdeps file.jar` and you can see exception stating what is the issue. (Signature invalid in this case)
- Run with `zip -d file.jar 'META-INF/*.SF' 'META-INF/*.RSA' 'META-INF/*.DSA'`
- Program will run properly.

This could also happen if duplicate LICENSE  file is present and we need to pickOne.

**Comment by amank22** [comment]
For now I have to remove it with another task like this:

```
tasks.register<Zip>("repackageUberJar") {
    val packageUberJarForCurrentOS = tasks.getByName("packageUberJarForCurrentOS")
    dependsOn(packageUberJarForCurrentOS)
    val file = packageUberJarForCurrentOS.outputs.files.first()
    val output = File(file.parentFile, "${file.nameWithoutExtension}-repacked.jar")
    archiveFileName.set(output.absolutePath)
    destinationDirectory.set(file.parentFile.absoluteFile)
    exclude("META-INF/*.SF")
    exclude("META-INF/*.RSA")
    exclude("META-INF/*.DSA")
    from(project.zipTree(file))
    doLast {
        logger.lifecycle("The repackaged jar is written to ${archiveFile.get().asFile.canonicalPath}")
    }
}
```

Still I am hoping if their is a better way to do this.
Also for native distribution, this is still an issue I think.

**Comment by Syer10** [comment]
For my app I just do this, it works well
```kotlin
    tasks.withType<Jar> {
        exclude("META-INF/*.RSA", "META-INF/*.SF", "META-INF/*.DSA")
    }
```

**Comment by amank22** [comment]
Hi @Syer10 ,
Thanks for the snippet. Although I tried this before and now also, but not working for me. 
Jdeps shows following error:
```
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
```
Also on extracting the jar, I could see the files with your code.
Although I have fixed this in jar by using the snippet I added in the last comment.

Also, does you code work for native distribution also?

I have a desktop only app.  [Build gradle](https://github.com/amank22/LogVue/blob/main/build.gradle.kts)

**Comment by Syer10** [comment]
The code I sent works for me on native distributions and the uber jar. I have no idea why it didnt work in your gradle script.

**Comment by amank22** [comment]
Thank you :)
I was able to run on native, it was some issue in my code which was causing some issue.

I think above comments give enough details to anyone who might have similar issue in future.
Will close this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1675">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
