### ISSUE TITLE
TextField registers tab as character on Android

### ISSUE THREAD

**Issue by dragossusi** [JetBrains/compose-jb#1684]
```kotlin
OutlinedTextField(
        value = username.value,
        label = { Text("username") },
        onValueChange = {
            username.value = it
        },
        modifier = Modifier.fillMaxWidth()
            .autofill(
                listOf(
                    if (isNew) AutofillType.NewUsername
                    else AutofillType.Username
                ),
                onFill = { username.value = it }
            ),
        singleLine = true
    )
```

Tried without `singleLine = true` and it worked on android and did not work on desktop.
When using `singleLine = true` it works on desktop but doesn't work on android.

**Comment by akurasov** [comment]
Android issues should be reported to Google, as their binaries are used there.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1684">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
