### ISSUE TITLE
Empty Preview Pane in Intellij

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#1686]
Probably we should never show an empty preview pane in Intellij.

See this conversation: https://twitter.com/jlengrand/status/1480820656178708481

Rather than showing an empty preview pane, we could display a nice message explaining what is wrong (functions marked with `@Preview` should have zero parameters, text cursor is not within a function marked as `@Preview`, etc).  Maybe link out to some documentation about the purpose of the `@Preview` function and how it is intended to be used.

Whatever we do, we should probably show something, because just showing an empty pane looks kinda like it's broken or buggy.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1686">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
