### ISSUE TITLE
OutlinedTextField error

### ISSUE THREAD

**Issue by githubzaibao** [JetBrains/compose-jb#170]
OutlinedTextField set singleLine = true and maxLines = 1, but input can still enter the line break behavior, and the result is a line break

**Comment by tieskedh** [comment]
had the same issue.
Worked around it by the modifier `shortcuts{on(Key.Enter){...}}`

**Comment by olonho** [comment]
Is Android behaviour different? If it's the same - please report an issue in https://issuetracker.google.com and paste link here.

**Comment by akurasov** [comment]
Seems it is working now. Does anyone still have this issue?

**Comment by akurasov** [comment]
Not-reproducible in latest builds

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6295">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
