### ISSUE TITLE
Web Compose - Drawing

### ISSUE THREAD

**Issue by ynsok** [JetBrains/compose-jb#1709]
Is there any possibility of drawing objects?

**Comment by akurasov** [comment]
You can use either html or svg. Please open your questions as a discussions, not as an issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1709">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
