### ISSUE TITLE
Notifications don't work with JDK 16/17 on macOs

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1717]
Compose 1.0.1, macOs BigSur 11.6.1, OpenJDK 16/17 (on OpenJDK 15/11 it works).

Try to run the example from https://github.com/JetBrains/compose-jb/tree/master/tutorials/Tray_Notifications_MenuBar_new#menu-tray-notifications and click on "Send notification"

A pure JDK code doesn't send notifications too:
```
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.swing.Swing
import java.awt.SystemTray
import java.awt.TrayIcon
import java.awt.image.BufferedImage

fun main() {
    runBlocking(Dispatchers.Swing) {
        val trayIcon = TrayIcon(BufferedImage(1, 1, BufferedImage.TYPE_INT_RGB)).apply {
            isImageAutoSize = true

            addActionListener {

            }
        }
        SystemTray.getSystemTray().add(trayIcon)
        delay(2000)
        trayIcon.displayMessage("Title", "Message", TrayIcon.MessageType.INFO)
        delay(200000)
    }
}
```

There two ways to fix the issue:
1. report a bug to JDK (or/and create a patch)
2. move from JDK API to native OS API

The second way probably will be easier, and we will fix some of the issues:
- notifications will work on Linux
- we can send notifications without a tray icon
- we can add some complex elements into notifications (buttons, images, etc)

**Comment by igordmn** [comment]
Sorry, it seems it is nothing to do with JDK 16/17.

In my notifications settings I have disabled notifications for one of the `java`:
<img width="479" alt="Screenshot 2022-01-19 at 17 03 49" src="https://user-images.githubusercontent.com/5963351/150148461-0d565b22-aeec-4c08-89cc-29f6c0340fde.png">

Even after using another, freshly downloaded version of JDK (never used before), macOs seems recognized it as already used java.

**Comment by igordmn** [comment]
Closing this, as it is not reproducible.

There is also [one reported case](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1642586089168000) when notifications haven't work. Move to native notifications instead of JDK ones may solve this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1717">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
