### ISSUE TITLE
Question:  How do i stimulate keyevent or mouse event ?

### ISSUE THREAD

**Issue by GoldTest** [JetBrains/compose-jb#1720]
Have seen this: https://github.com/JetBrains/compose-jb/tree/master/tutorials/Keyboard
And this:https://developer.android.com/reference/kotlin/androidx/compose/ui/input/key/package-summary#keyinputfilter
Only have receive keyboard event.
Do you have any solution or tutorial?

**Comment by GoldTest** [comment]
cr: MacOs or Window

**Comment by GoldTest** [comment]
Never mind, just findout we are in jvm runtime, i can use Robot.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1720">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
