### ISSUE TITLE
Cannot build falling-balls-mpp

### ISSUE THREAD

**Issue by warting** [JetBrains/compose-jb#1723]
Looks like you are using a plugin that is not yet released (for us) org.jetbrains.compose 1.1.0.beta04

FAILURE: Build failed with an exception.
* Where:
Build file '/home/stefan/git/compose-jb/examples/falling-balls-mpp/build.gradle.kts' line: 16
* What went wrong:
Plugin [id: 'org.jetbrains.compose', version: '1.1.0-beta04'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.compose:org.jetbrains.compose.gradle.plugin:1.1.0-beta04')
  Searched in the following repositories:
    MavenLocal(file:/home/stefan/.m2/repository/)
    Gradle Central Plugin Repository
    MavenRepo
    maven(https://maven.pkg.jetbrains.space/public/p/compose/dev)
    Google

**Comment by olonho** [comment]
It's not supported at the moment, moved sample to `experimental`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1723">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
