### ISSUE TITLE
能不能把这个源码依赖改成 gradle implement依赖?

### ISSUE THREAD

**Issue by liupeng110** [JetBrains/compose-jb#1726]
能不能把这个源码依赖改成 gradle implement依赖?

**Comment by olonho** [comment]
Please use English in bug reports. 请在报告中使用英文

**Comment by liupeng110** [comment]
Can you make a dependency using  like this :  implement  "xxx.xxx.xx:xx:1.0.0"

**Comment by liupeng110** [comment]
@olonho

**Comment by liupeng110** [comment]
Using source code dependency is very inconvenient

**Comment by Skaldebane** [comment]
Can you please clarify the issue a bit more?

**Comment by igordmn** [comment]
You can use
```
implementation("org.jetbrains.compose.desktop:desktop-jvm-windows-x64")
```
instead of
```
implementation(compose.desktop.currentOs)
```
(you can see what `currentOs` is, if you go to the definition of it in IDE)

**Comment by liupeng110** [comment]
> 

thks

**Comment by akurasov** [comment]
@liupeng110 
Could you clarify, what is inconvenient with implementation(compose.desktop.currentOs) ? 

I was done in order to simplify dependencies, so you don't need to remember and input all that long strings.
