### ISSUE TITLE
textIndent parameter has no effect on the Text composable.

### ISSUE THREAD

**Issue by Skaldebane** [JetBrains/compose-jb#1733]
Hi!
Apparently setting the textIndent parameter in the TextStyle of a Text composable has no effect, so it is essentially broken. On Android, it works just fine, but on desktop (Fedora Linux 35 / Windows 10) it doesn't add the indent.

**Comment by akurasov** [comment]
reproduced on Mac /1.0.1

**Comment by igordmn** [comment]
Should be fixed in 1.1.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1733">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
