### ISSUE TITLE
Requesting suggestions on upstreaming my Compose Plugin

### ISSUE THREAD

**Issue by thelumiereguy** [JetBrains/compose-jb#1737]
Hey guys! 
So, I wrote an IntelliJ/Android Studio plugin for Compose. [Jim Sproch actually suggested that I ask you guys](https://twitter.com/JimSproch/status/1483884768567885824?s=20) whether you could upstream this.

Basically, with this plugin you can
1. Wrap composable with another
2. Unwrap a parent composable
3. Completely delete a composable

This works on any composables, including UI Composables, Side effects, properties, etc. 

Link - https://plugins.jetbrains.com/plugin/18323-compose-helper

**Comment by olonho** [comment]
Feel free to send PR to this plugin: https://github.com/JetBrains/compose-jb/tree/master/idea-plugin

**Comment by thelumiereguy** [comment]
@olonho Thank you very much! Yes, I'll do that ^_^

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1737">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
