### ISSUE TITLE
Preview like in Android Studio?

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#174]
As in the title, when the preview functionality (like in Android Studio Canary) will appear in Compose for Desktop?

**Comment by olonho** [comment]
Duplicate of https://github.com/JetBrains/compose-jb/issues/136, please avoid creating duplicated issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6510">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
