### ISSUE TITLE
How to use ktor with Compose Web?

### ISSUE THREAD

**Issue by rossedwardsus** [JetBrains/compose-jb#1745]
I have been able to get the starter project working and now i want to play around with connecting with a backend using ktor client.  I added the implementation and the project builds but when i add import io.ktor i get an error that io is not found.

Am i doing something wrong?

Thank you.

**Comment by akurasov** [comment]
I would suggest you to go through https://play.kotlinlang.org/hands-on/Full%20Stack%20Web%20App%20with%20Kotlin%20Multiplatform/01_Introduction tutorial to create pair of client(JS)-server(ktor) apps and after this enhance client with Compose for Web support.

**Comment by rossedwardsus** [comment]
I was referring to ktor on the client.  The problem with that tutorial is there is an issue with using kotlinx.serialization.  I was only able to get it working using a specific version that is mentioned in an issue where the person had a the same problem.  Otherwise it wont work.

**Comment by suslovsergey** [comment]
@rossedwardsus  Maybe my setup will help you

in sourceSets

```gradle 
 val commonMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-core:1.6.7")
                implementation("io.ktor:ktor-client-serialization:1.6.7")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2")
            }
        }

val jsMain by getting {
            dependencies {
                implementation(compose.web.core)
                implementation(compose.runtime)
                implementation("io.ktor:ktor-client-js:1.6.7")
                implementation("io.ktor:ktor-client-json-js:1.6.7")
            }
        }
```

in plugins section:

```gradle
kotlin("plugin.serialization") version "1.6.10"
```

and httpclient object

``` kotlin
val httpClient = HttpClient {
    install(JsonFeature) {
        serializer = KotlinxSerializer(json = kotlinx.serialization.json.Json {
            isLenient = true
            ignoreUnknownKeys = true
        })

        accept(ContentType.Application.Json)
    }
}

```

**Comment by rossedwardsus** [comment]
@suslovsergey Thanks.  Are you also including compose in the plugin section?

**Comment by suslovsergey** [comment]
@rossedwardsus yeah - 

``` gradle
    kotlin("multiplatform")
    id("org.jetbrains.compose")
```

**Comment by rossedwardsus** [comment]
Hello.  What versions are you using?

**Comment by suslovsergey** [comment]
@rossedwardsus 

kotlin.version=1.6.10
compose.version=1.0.1

**Comment by rossedwardsus** [comment]
Right.  The problems seems to have been with a previous version of compose.  Which is the one i tried initially.

**Comment by suslovsergey** [comment]
@rossedwardsus I am glad to help

**Comment by akurasov** [comment]
@rossedwardsus are there any questions left here?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1745">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
