### ISSUE TITLE
Web: How to do multi-page development

### ISSUE THREAD

**Issue by korilin** [JetBrains/compose-jb#1746]
How do I configure to develop multiple Web pages, instead of just having one index html?

**Comment by rossedwardsus** [comment]
You have to use a router.

**Comment by korilin** [comment]
Is there an example or document for reference? I can't find relevant API in the project.

**Comment by rossedwardsus** [comment]
I haven't tried this yet.  I found it by doing a search the right keywords.

https://github.com/hfhbd/routing-compose

**Comment by csotiriou** [comment]
Decompose seems also promising https://arkivanov.github.io/Decompose

**Comment by korilin** [comment]
I could try using HashRouter from routing-compose or Decompose to solve this problem temporarily, but it's still a SPA project and required more configuration at deployment time if using the history model.

**Comment by Ayfri** [comment]
What other solution have you used @korilin to solve this problem?

**Comment by korilin** [comment]
> What other solution have you used @korilin to solve this problem?

I didn't try any other solutions.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1746">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
