### ISSUE TITLE
OnKeyboardlistener on window

### ISSUE THREAD

**Issue by abdullo211** [JetBrains/compose-jb#175]
Can I add listener to keyboard. The task is to listen to the keyboard  in the background. Or how set autofocus to TextField in first launch.

**Comment by prepor** [comment]
How to listen key events for window is described here https://github.com/JetBrains/compose-jb/tree/master/tutorials/Keyboard

**Comment by olonho** [comment]
Feel free to ask general question on the Slack channel, see bottom of https://www.jetbrains.com/lp/compose/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6509">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
