### ISSUE TITLE
Call system Explorer/Finder to select files in Compose

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#176]
How does that achievable?

**Comment by igordmn** [comment]
We can use java.awt.FileDialog:
```
import androidx.compose.desktop.AppWindowAmbient
import androidx.compose.desktop.Window
import androidx.compose.material.Button
import androidx.compose.material.Text
fun main() = Window {
    val window = AppWindowAmbient.current!!
    Button(onClick = {
        java.awt.FileDialog(window.window).isVisible = true
    }) {
        Text("Button")
    }
}
```

**Comment by GGorAA** [comment]
Thanks!

**Comment by pnogas** [comment]
Figured I would post what I did to have file open files using the menu bar / keyboard shortcuts in case anyone else arrived here looking to do the same thing

    AppManager.setMenu(
        MenuBar(
            Menu(
                name = "File",
                    MenuItem(
                        name = "Open",
                        shortcut = KeyStroke(Key.O),
                        onClick = { windowActionManager.handleAction(MenuBarActions.OpenFile) }, // ...more stuff

and that eventually leads to

    fun openLogFile() {
        var result: File?
            JFileChooser(System.getProperty("user.home")).apply {
                showOpenDialog(null)
                result = selectedFile
            } // ...more stuff

**Comment by v79** [comment]
> import androidx.compose.desktop.AppWindowAmbient

No longer seems to be available; this is what worked for me:

```kotlin
Button(onClick = {
	java.awt.FileDialog(AppManager.focusedWindow!!.window).isVisible = true
}) {
	Text("File Picker")
}
```

**Comment by igordmn** [comment]
> > import androidx.compose.desktop.AppWindowAmbient
> 
> No longer seems to be available; this is what worked for me:
> 
> ```kotlin
> Button(onClick = {
> 	java.awt.FileDialog(AppManager.focusedWindow!!.window).isVisible = true
> }) {
> 	Text("File Picker")
> }
> ```

It was renamed to LocalAppWindow (I changed my comment). 

Better to use it instead of focusedWindow. focusedWindow works, but probably not in all cases (we can "click" without taking  the window into focus, for example in tests)

**Comment by jposes22** [comment]
Updated:

```
Button(onClick = {
    java.awt.FileDialog(ComposeWindow()).isVisible = true
}) {
    Text("File Picker")
}
```

**Comment by sebkur** [comment]
> Updated:
> 
> ```
> Button(onClick = {
>     java.awt.FileDialog(ComposeWindow()).isVisible = true
> }) {
>     Text("File Picker")
> }
> ```

If I'm not mistaken, `ComposeWindow()` doesn't give you the current window, instead it just creates a new one.

@igordmn it seems `LocalAppWindow` isn't available any longer? Do you have a different solution?

**Comment by igordmn** [comment]
We should pass the parent window instead of the new Window (so the parent window will be blocked while dialog is opened). In 1.0 we can do that this way:

```
fun WindowScope.openFileDialog() {
    java.awt.FileDialog(window).isVisible = true
}
```

`WindowScope` is the scope provided by `Window` or `singleWindowApplicaion`, so you can use `openFileDialog` only inside them, or passing down `WindowScope` or `ComposeWindow` via parameter/receiver/CompositionLocal manually.

There is also [`Composable` way](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new#swing-interoperability) to open a file dialog.

**Comment by sebkur** [comment]
awesome, thanks for the quick reply!

A small detail I noticed is, you need to actually use `FrameWindowScope` instead of `WindowScope`, as the former provides the more specific `javax.swing.JFrame` while the latter provides `java.awt.Window` as the `window`. It matters because `FileDialog` requires a `java.awt.Frame` (or `Dialog`) in its constructor of which `JFrame` is a subclass but `Window` isn't.

Anyway, also thanks for the pointer to the Composable way, that's sounds like it is the way one really wants to integrate this.

**Comment by igordmn** [comment]
> use FrameWindowScope instead of WindowScope

Good point, thanks. I changed the comment.

**Comment by shuijingyue** [comment]
I can't select a dir in this way

**Comment by shuijingyue** [comment]
> Updated:
> 
> ```
> Button(onClick = {
>     java.awt.FileDialog(ComposeWindow()).isVisible = true
> }) {
>     Text("File Picker")
> }
> ```

I can't select a dir in this way

**Comment by sebkur** [comment]
wow, indeed, looks like `FileDialog` doesn't support picking directories (at least not on all operating systems). Probably a disappointing workaround, but you could use ``:
```kotlin
    val f = JFileChooser()
    f.fileSelectionMode = JFileChooser.DIRECTORIES_ONLY
    f.showSaveDialog(null)
```

**Comment by sebkur** [comment]
probably worth a separate issue

**Comment by mahozad** [comment]
To get a native look and feel (tested on Windows) I called this at the start of the program:

```kotlin
UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
```

To open directories only, opened a dialog like this:

```kotlin
val fileChooser = JFileChooser("/").apply {
    fileSelectionMode = JFileChooser.DIRECTORIES_ONLY
    dialogTitle = "Select a folder"
    approveButtonText = "Select"
    approveButtonToolTipText = "Select current directory as save destination"
}
fileChooser.showOpenDialog(window.window /* OR null */)
val result = fileChooser.selectedFile
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6105">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
