### ISSUE TITLE
`onClick` not called after `Modifier.rotate(90f)` applied to button

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#177]
When I apply a rotate to a button, the button is successfully rotated, and I can trigger the ripple when clicked, but `onClick` isn't called when I click.

Removing `modifier = Modifier.rotate(90f),` allows everything to work again.

```Kotlin
LazyColumn {
    item {
        OutlinedButton(
            modifier = Modifier.rotate(90f),
            onClick = { if (isStarted) vm.stop() else vm.start() },
        ) {
            Text(
                text = if (isStarted) "STOP" else "START",
                style = typography.button,
            )
        }
    }

    items(state.value.products) { productState: ProductState ->
        Product(vm, productState)
    }
}
```

**Comment by olonho** [comment]
Looks like a dup of https://github.com/JetBrains/compose-jb/issues/127

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
