### ISSUE TITLE
Input fields retian focus on exit: Desktop

### ISSUE THREAD

**Issue by BreimerR** [JetBrains/compose-jb#1776]
Input fields do not lose focus on clicking on other components. Visible in the TODO app multiplatform application for desktop.

**Comment by akurasov** [comment]
Could you describe the whole reproduction scenario?

**Comment by BreimerR** [comment]
Was setting focusable to false. Fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1776">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
