### ISSUE TITLE
BasicTextField doesn't render blank lines correctly

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-jb#1781]
If you create a multiline `BasicTextField` (`singleLine = false`), and enter a "blank line" (an empty line without any character, or a line with just whitespace), `BasicTextField` will nor render the text correctly.

For example, let's take this text (you can put a space in the empty line if you want):
```
abcd

hijk
```
 
And compare it against this text:
```
abcd
x
hijk
```

**First of all**, you will see that the empty line will not have the same height as the others -- it will be shorter. See example below.

See screenshot below. The pink border represents the `BasicTextField`.

![BasicTextField bug](https://user-images.githubusercontent.com/567679/152157257-0bc0d910-59ba-481f-9a45-7ff6838d3be6.png)

**Second**, in the scenario above, if you enter any number of white space (e.g. 3 spaces), when you move your cursor to the end of the next/previous line that is also longer (e.g. 6 characters), then using the keyboard you move the cursor up/down ONTO that line with the whitespaces, the cursor on the line with only whitespaces will not be shown correctly. The height will be wrong (I suspect because of the first issue above), but also the position is wrong as it always start at position 0, even though it has 3 characters. It should be placed at the end of the 3 whitespace, when moving from another line at a longer position, e.g. 6 chars.

**Comment by haikalpribadi** [comment]
By the way, this is turning into a critical and blocking bug for us now :( . The problem is even worse when you enter 2 or more "blank lines" -- they don't get rendered at all. It's really breaking our UI to the point of being dysfunctional. Any chance we can get this patched anytime soon? We really don't want to have implement our own `BasicTextField`, and we can't use `TextField()` from Material package as it provides no access to `TextLayoutResult` (which we need). Thank you!

**Comment by igordmn** [comment]
Thanks for reporting!

Video:

https://user-images.githubusercontent.com/5963351/152497387-fc17614b-346b-47be-bc81-cfa2a4a54b45.mov

Let's move cursor placing to [a separate issue](https://github.com/JetBrains/compose-jb/issues/1791)

**Comment by haikalpribadi** [comment]
Thanks, @igordmn ! do you have an idea on when you think a patch / minor released can be published for the fix?

**Comment by igordmn** [comment]
I will try to investigate this next week, then it depends on complexity. As this issue is partially "fixed" (the first empty line is with the right height), I think there won't be huge obstacles to fix it.

**Comment by haikalpribadi** [comment]
I don't think the first blank line has the right height, btw. See my screenshot above. The line gaps are missing. However, it's true that the second (or more) blank lines are worse.

**Comment by milan1201** [comment]
TextField() has the same Issue. Here you can work around it with increasing the `lineHeight` attribute until blank lines occupy the same amount of space as non-blank ones. The ploblem is that it is different on different screen resolutions. 
Maybe you can try the same thing with the `style` attribute of BasicText() until there is a better solution.

**Comment by akurasov** [comment]
Fixed in 1.1.0-alpha04

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1781">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
