### ISSUE TITLE
Implement DesktopUriHandler

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#18]

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5627">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6243">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
