### ISSUE TITLE
Scrollbar. get rid of `itemCount` and `averageItemSize` from rememberScrollbarAdapter

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#181]
Now we have to manually pass them:
```
fun rememberScrollbarAdapter(
    scrollState: LazyListState,
    itemCount: Int,
    averageItemSize: Dp
)
```

After https://android-review.googlesource.com/c/platform/frameworks/support/+/1517920 it is possible to determine average size of the items by the current displaying items in the lazy list.

**Comment by Dominaezzz** [comment]
Any idea how to calculate average item size from `LazyListState`?

**Comment by Dominaezzz** [comment]
I think this is as good as an `averageItemSize` calculation gets, while still being lazy.

```
class CustomScrollAdapter(
    private val scrollState: LazyListState
) : ScrollbarAdapter {
    val itemCount: Int get() = scrollState.layoutInfo.totalItemsCount
    val averageItemSize: Float by derivedStateOf {
        val items = scrollState.layoutInfo.visibleItemsInfo
        items.sumBy { it.size }.toFloat() / items.size
    }

    override val scrollOffset: Float
        get() {
            return scrollState.firstVisibleItemIndex * averageItemSize +
                    scrollState.firstVisibleItemScrollOffset
        }

    override fun maxScrollOffset(containerSize: Int): Float {
        return averageItemSize * itemCount - containerSize
    }

    override suspend fun scrollTo(containerSize: Int, scrollOffset: Float) {
        val scrollOffsetCoerced = scrollOffset.coerceIn(0f, maxScrollOffset(containerSize))

        val index = (scrollOffsetCoerced / averageItemSize)
            .toInt()
            .coerceAtLeast(0)
            .coerceAtMost(itemCount - 1)

        scrollState.scrollToItem(
            index = index,
            scrollOffset = (scrollOffsetCoerced - index * averageItemSize).toInt()
        )
    }
}
```

**Comment by c5inco** [comment]
Not sure this is related, but it would also be nice not to need to have to pass `averageItemSize` or at least make the scrollbar implementations handle it. I have a `LazyColumn` that uses the sticky header and draws a Divider as a secondary item (after using `items`, which is causing strange measurements since the majority of the items are `120.dp` in height except for the sticky headers and the Divider.

```kotlin
LazyColumn(modifier = Modifier
    .fillMaxSize()
    .padding(end = 32.dp),
    state = scrollState
) {
    chunkedGroupsMap.forEach { (group, chunkedIcons) ->
        stickyHeader {
            IconGroupHeader(group, chunkedIcons)
        }

        items(chunkedIcons) { iconsChunk ->
            IconsRow(iconsChunk, chunkSize.value, isDarkTheme, group)
        }

        item(group) {
            Spacer(modifier = Modifier.height(8.dp))
            Divider(thickness = 1.dp)
        }
    }
}
VerticalScrollbar(
    modifier = Modifier
            .align(Alignment.CenterEnd)
            .fillMaxHeight(),
    adapter = rememberScrollbarAdapter(
        scrollState = scrollState,
        itemCount = totalRows,
        averageItemSize = 120.dp
    )
)
```

**Comment by c5inco** [comment]
Strange measurements -> the scrollbar goes beyond the viewport and keeps scrolling off screen. If I comment out the stickyHeader and separate Divider item above, the scrollbar positioning is correct.

**Comment by c5inco** [comment]
So I tried using the CustomAdapter snippet above. It sorta worked in that the scrollbar thumb doesn't go off the screen, but when trying to scroll up with click+drag, there seems to be some strange resistance. This resistance doesn't occur if I just use the mouse wheel. GIF below:

![custom-adapter](https://user-images.githubusercontent.com/1253402/111388585-c8e56980-866c-11eb-80ff-2c79a05b47a2.gif)

**Comment by igordmn** [comment]
Was implemented in https://android-review.googlesource.com/c/platform/frameworks/support/+/1715676

Video:

https://user-images.githubusercontent.com/5963351/119162010-91c37800-ba62-11eb-9963-6de588bae122.mp4

**Comment by Dominaezzz** [comment]
Awesome! :tada:

The `averageItemSize` calculation could probably be smoothed out with some state to remember total size of previously visited items, but that can be in another iteration.

**Comment by igordmn** [comment]
> smoothed out with some state to remember total size of previously visited items

Thanks for the idea!

Not sure how it will look, but worth to try / think about.

**Comment by c5inco** [comment]
Nice!! So this means we no longer need to pass those two values if I read the test on the AOSP CL correctly?

**Comment by igordmn** [comment]
>  we no longer need to pass those two values
Yes, the old method is deprecated and uses the method without values underhood.

it works perfectly for lists with the same item height, and ok for lists with a different item height (there are some ideas how to improve scrollbars for the them, but they are for the future :) )

**Comment by igordmn** [comment]
Fixed in 0.4.0-build210

**Comment by Dominaezzz** [comment]
Sorry for commenting on a closed issue but I had a go at implementing my suggestion.

https://github.com/Dominaezzz/FunWithScrollbars/blob/010feec56b8eb7dcfdf7a4c1a0d4258beefa6fe9/src/main/kotlin/Scrollbars.kt#L204

The scrollbar is pretty smooth.
The only thing I haven't tried yet is items of changing (or animating) size, although the results *should* be good.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6397">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
