### ISSUE TITLE
SVG Support (desktop only)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#182]
Skija now supports SVG drawing (https://github.com/JetBrains/skija/commit/94d2141b37e1e87af036422f0f61c1d24389c31c)

So we can integrate SVG in Compose as well. We can implement something like this:

```
vectorSvgResource(resourcePath: String): Painter
```
and use it like this:
```
Image(vectorSvgResource("image.svg"))
```

Note that internally we should probably cache drawing into bitmap (using DrawCache, similar to androidx.compose.ui.graphics.vector.VectorComponent). It depends on performance.

**Comment by olonho** [comment]
@igordmn what left here?

**Comment by igordmn** [comment]
>what left here?

Support of Composable SVG isn't merged yet

**Comment by alialbaali** [comment]
Is there any timestamp on when will this get merged?

**Comment by igordmn** [comment]
Soon I suppose (https://android-review.googlesource.com/c/platform/frameworks/support/+/1575164).

The changes are ready for review, but not reviewed yet.

You can copy-paste code from there to be able to use SVG.

**Comment by ragunathjawahar** [comment]
Should this be closed because M3 is out?

**Comment by igordmn** [comment]
Thanks for the reminder! Yes, this should be closed.

SVG is working in 0.3.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6454">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
