### ISSUE TITLE
Support plain kotlin("js") project

### ISSUE THREAD

**Issue by SerVB** [JetBrains/compose-jb#1821]
For now, only `kotlin("multiplatform")` plugin is supported, but I have a project with `kotlin("js")` plugin and I don't want to switch it to multiplatform with a single source set.

**Comment by SerVB** [comment]
Reasons why I don't want to switch my subproject from `kotlin("js")` to `kotlin("multiplatform")`:

1. Paths for source roots become different, I have to move sources that can cause some git conflicts since there are multiple simultaneous contributors to the project. Another option is to configure paths manually to make them like old ones, but it makes the configuration more complex.
2. Names of tasks now have `js` prefix, so I need to rewrite some of my buildscripts that reference tasks from this project that is quite tedious. Another option is to create wrapper tasks with old names that will call new tasks with the prefix, but it again adds boilerplate in the configuration.
3. Configuration of a multiplatform module is itself a bit more wordy that the one of a similar js module.
4. The project isn't intended to be multiplatform (at least for now), so there is no need of making the builder support multiplatform features.

Probably some other reasons that I will formulate later, not without thinking.

Also, some other plugins like `kx.serialization` support any kotlin plugin, not only multiplatform, and it's handy. So Compose plugin could provide the same experience.

**Comment by JakeWharton** [comment]
Are there a list of reasons that the plain Kotlin JVM plugin is supported? Surely anyone targeting the JVM could use the multiplatform plugin with a JVM target. I would expect the justifications for the JVM plugin being supported are similar to those which advocate for the JS plugin being supported.

And if support of the JS plugin is to be rejected, does that mean we can expect the support for the JVM plugin to also be removed for symmetry?

While I echo the reasons that @SerVB listed, I also think simple symmetry with the support for the JVM plugin is itself a strong enough argument.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1821">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
