### ISSUE TITLE
Screen Density isn't adjusted when plugging in an external monitor

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#183]
Here is a simple app:

![Screen Shot 2020-12-09 at 3 08 18 PM](https://user-images.githubusercontent.com/871169/101681710-95bd8980-3a30-11eb-827f-f27fa2761d05.png)

When I have it loaded on my Retina 15" MacBook Pro screen, and then plug it in to my 1080p external monitor (different screen density), the widgets become enlarged:
![Screen Shot 2020-12-09 at 3 08 12 PM](https://user-images.githubusercontent.com/871169/101682024-0ebce100-3a31-11eb-867d-e1f8b8aedd08.png)

The widget size goes back to normal when I move the app to the MBP screen, and then back to the external monitor.

**Comment by igordmn** [comment]
Is the issue still exist in 0.3.0-build146?

**Comment by akurasov** [comment]
Looks like no. Closing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6384">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
