### ISSUE TITLE
BasicTextField: The cursor jumps to the previous line when typing at the beginning of a empty line

### ISSUE THREAD

**Issue by drakeet** [JetBrains/compose-jb#1834]
```
compose.version=1.1.0-alpha04
```

The cursor jumps to the previous line when typing at the beginning of a blank line. See demo:

https://user-images.githubusercontent.com/5214214/153717861-4f121afd-1f3e-42e2-9ba7-70aee803262d.mp4

Steps to reproduce:

1. Input the text into the BasicTextField:
```
Line 1
Line 3
```
2. Put the cursor after "Line 1" and press enter to get a new empty line
3. Switch input method to Chinese input mode
4. Enter some Chinese content
5. Delete all Chinese content so that the current line is empty
6. At this point, keep the Chinese input mode, and enter new Chinese, when the keyboard key is pressed, the cursor will jump to the previous line, and our empty line is automatically deleted.

**Comment by drakeet** [comment]
Seems to be the same issue as #672.

**Comment by drakeet** [comment]
TODO: recheck this bug after https://github.com/JetBrains/androidx/pull/193 is merged.

**Comment by akurasov** [comment]
Can be reproduced even easier:
Input English test, switch to Chinese, press enter, start typing. Cursor will jump back.

**Comment by drakeet** [comment]
still happen with compose.version=1.1.0-alpha05

**Comment by drakeet** [comment]
@VeselovAlex It looks like this bug has been fixed on v1.1.0-rc01. So I am closing this issue...

**Comment by drakeet** [comment]
Good job! Thank you so much @VeselovAlex
