### ISSUE TITLE
LazyVerticalGrid - Composable

### ISSUE THREAD

**Issue by dkim19375** [JetBrains/compose-jb#1836]
In the `content` parameter of LazyVerticalGrid, it isn't marked as `@Composable`, so I can't put any items in it.
Code:
```kt
LazyVerticalGrid(
    cells = GridCells.Adaptive(128.dp),
    content = {
        Card() {
            Text(text = "test")
        }
    }
)
```
I just followed this: https://foso.github.io/Jetpack-Compose-Playground/foundation/lazyverticalgrid/
and I get this error: `MainWindow.kt: (79, 21): @Composable invocations can only happen from the context of a @Composable function`
Line 79 is `Card() {`

**Comment by kirill-grouchnikov** [comment]
https://developer.android.com/jetpack/compose/lists

You put items, not direct composables

**Comment by kirill-grouchnikov** [comment]
You can also see the in the example you linked

**Comment by dkim19375** [comment]
ohhhhhhhhhh I see, thanks!
