### ISSUE TITLE
How to open Window/Dialog on the same screen as launcher/trigger, when working with multiple screen

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-jb#1845]
Say you have 2 screens -- Screen 1 and Screen 2, and the "main/default" screen is Screen 1. When you launch the application from Screen 2 (via terminal, or application icon, or IDE), the application `Window` will always start in Screen 1. Even after you drag the application window to Screen 2, when you click any button that opens a `Dialog`, that dialog will always open in Screen 1, and you have to drag it manually to Screen 2 again.

Effectively, how can we get Compose to recognise that you're working on multiple screens, and that it should focus on working on just the one screen that the application sits in the moment?

**Comment by haikalpribadi** [comment]
Hey guys, @igordmn and @akurasov any updates on this? Seems like it's removed from you milestone 4 days ago now? We actually start having customers complaining to us about this issue. Is there anything we can do to help from our side?

**Comment by haikalpribadi** [comment]
Can you tell me which what's the key requirement in the code above, @igordmn ?

**Comment by haikalpribadi** [comment]
Okay, I think I understand the essence of what you're doing there: you're passing `GraphicsConfiguration` from `java.aw.Window.getWindows()` that `isActive` into `ComposeWindow()`. Am I right?

However, right now we construct our windows using `Window()` from `androidx.compose.ui.window.Window.desktop.kt`, which seems to manage a lot of things such as: title, resizing, icon, focus, alwaysOnTop, closeRequest, minimization, decoration, placement, position, etc. If we go with your suggestion above, does that mean we will loose all these functionalities? @igordmn

**Comment by igordmn** [comment]
> I think I understand the essence of what you're doing there: you're passing GraphicsConfiguration from

Yes, GraphicsConfiguration defines, on which display the window should be shown.

> However, right now we construct our windows using Window()

Yes, it is unfortunate, but you can copy-paste [this file](https://github.com/JetBrains/androidx/blob/jb-main/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Window.desktop.kt) (temporarily), and pass graphicsConfiguration [here](https://github.com/JetBrains/androidx/blob/33a03071b24069be9a421e7923b016baff98386d/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Window.desktop.kt#L161)

We will add this feature into the official release, but before that we should be sure that this code won't break other cases (aligning in the center of the screen, positioning, etc).

**Comment by haikalpribadi** [comment]
I did think of doing that, but as I expected, copying the file over is not possible as it depends on `internal` APIs:
```
Error:(33, 33) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(34, 33) cannot access 'makeDisplayable': it is internal in 'androidx.compose.ui.util'
Error:(35, 33) cannot access 'setIcon': it is internal in 'androidx.compose.ui.util'
Error:(36, 33) cannot access 'setPositionSafely': it is internal in 'androidx.compose.ui.util'
Error:(37, 33) cannot access 'setSizeSafely': it is internal in 'androidx.compose.ui.util'
Error:(38, 33) cannot access 'setUndecoratedSafely': it is internal in 'androidx.compose.ui.util'
Error:(144, 19) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(195, 21) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(196, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(197, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(197, 17) cannot access 'setIcon': it is internal in 'androidx.compose.ui.util'
Error:(198, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(198, 17) cannot access 'setUndecoratedSafely': it is internal in 'androidx.compose.ui.util'
Error:(199, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(200, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(201, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(202, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(203, 17) cannot access 'ComponentUpdater': it is internal in 'androidx.compose.ui.util'
Error:(206, 24) cannot access 'setSizeSafely': it is internal in 'androidx.compose.ui.util'
Error:(210, 24) cannot access 'setPositionSafely': it is internal in 'androidx.compose.ui.util'
Error:(384, 20) cannot access 'makeDisplayable': it is internal in 'androidx.compose.ui.util'
```

Did you anticipate this? Or is there a workaround, @igordmn ?

**Comment by haikalpribadi** [comment]
Also,m @igordmn when you said "We will add this feature into the official release" do you mean 1.2.0? Or not yet known?

**Comment by igordmn** [comment]
Probably it will be in 1.2.0, if there won't be major issues with the code above.

**Comment by haikalpribadi** [comment]
Any updates on this @igordmn ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1845">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
