### ISSUE TITLE
Ged rid of SkiaRootForTest/TestPointerInputEventData

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1846]
Compose 1.1-alpha03

These classes was added to implement basic functionality of Compose UI tests.

They have limited functionality, and doesn't provide the right event routing.

Events should go through `ComposeScene`, not through `SkiaBasedOwner`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1846">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
