### ISSUE TITLE
Make DesktopOwner/DesktopOwners/SkijaLayer internal

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#185]
Because Owner (and AndroidOwner) will be internal in the near future:
https://issuetracker.google.com/issues/175103944

**Comment by olonho** [comment]
Shall we close it?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6482">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
