### ISSUE TITLE
Rename classes and packages to align with Jetpack Compose for Android code style

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#186]
~SomeAmbient -> LocalSome~ (fixed in https://android-review.googlesource.com/c/platform/frameworks/support/+/1684198)
androidx.compose.desktop -> androidx.compose.ui.platform
golden/ui/ui-desktop -> golden/compose/ui-desktop

**Comment by akurasov** [comment]
@igordmn do we still want to do it? I yes, it should be done in Alpha, I believe.

**Comment by igordmn** [comment]
Fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6245">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
