### ISSUE TITLE
How to call 32 bit dll file?

### ISSUE THREAD

**Issue by Richyeoh** [JetBrains/compose-jb#1862]
Compose is 64 bit, But thridparty provider some 32 bit and 64 bit dll file，i try call 32 bit dll throw a This program not a 32 bit app.

**Comment by akurasov** [comment]
Why don't you use 64-bit dll?

**Comment by Richyeoh** [comment]
> Why don't you use 64-bit dll?

Because, thridparty can't provide 64 bit dll file.

**Comment by Richyeoh** [comment]
What makes me speechless is that compose does not support JVMs below 11.

**Comment by akurasov** [comment]
Then you should contact that thirdparty, I guess. 

Windows doesn't allow 64bit apps to use 32bit dlls.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1862">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
