### ISSUE TITLE
Why keyboard  action will invoke twice but i only trigger once?

### ISSUE THREAD

**Issue by RubiTree** [JetBrains/compose-jb#1871]
When i test keyboard simple example, i find a problem that the action will invoke twice but i only trigger once.

My code is simple and from:  https://github.com/JetBrains/compose-jb/blob/master/tutorials/Keyboard/README.md
```kotlin
fun main() = Window {
    MaterialTheme {
        var text by remember { mutableStateOf("") }
        Column(Modifier.fillMaxSize(), Arrangement.spacedBy(5.dp)) {
            TextField(
                value = text,
                onValueChange = { text = it },
                modifier = Modifier.onPreviewKeyEvent {
                    when {
                        (it.isCtrlPressed && it.key == Key.Minus) -> {
                            println("on enter")
                            true
                        }
                        else -> false
                    }
                }
            )
        }
    }
}
```

here is the recording, you can see the "on enter" print twice when i trigger once
![Screen Recording 2022-02-19 at 3 13 01 AM](https://user-images.githubusercontent.com/13551681/154747843-5aebc2c0-d575-4219-9e8d-478f66f0a06b.gif)

**Comment by ryanmitchener** [comment]
@RubiTree I believe you are getting the KeyDown and KeyUp events. Add a check for keydown or keyup depending on when you want the event to trigger.

```
when {
    (it.type == KeyEventType.KeyDown && it.isCtrlPressed && it.key == Key.Minus) -> {
        println("on enter")
        true
    }
    else -> false
}
```

**Comment by RubiTree** [comment]
> @RubiTree I believe you are getting the KeyDown and KeyUp events. Add a check for keydown or keyup depending on when you want the event to trigger.
> 
> ```
> when {
>     (it.type == KeyEventType.KeyDown && it.isCtrlPressed && it.key == Key.Minus) -> {
>         println("on enter")
>         true
>     }
>     else -> false
> }
> ```

thank your for giving solution, really works !
But i wonder why not add the condition "it.type == KeyEventType.KeyDown" to sample?

**Comment by bassstorm** [comment]
Also was puzzled a bit about that. Thanks for the hint @ryanmitchener!
Agree that would be great to see in tutorial.

**Comment by akurasov** [comment]
Yes, worth to be added. Will do later or someone can add it too.

**Comment by ryanmitchener** [comment]
@akurasov I have added a PR for this here: https://github.com/JetBrains/compose-jb/pull/1877

**Comment by akurasov** [comment]
@ryanmitchener thank you!

**Comment by RubiTree** [comment]
> @akurasov I have added a PR for updating the keyboard tutorial here: #1877

good job!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1871">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
