### ISSUE TITLE
Room Database Support

### ISSUE THREAD

**Issue by brucieW** [JetBrains/compose-jb#1884]
Could you please add Room Database support in your library.

**Comment by akurasov** [comment]
How is it related to UI?

**Comment by brucieW** [comment]
I'm trying to integrate Room Library with a Compose Desktop application. Sent from my Galaxy
-------- Original message --------From: akurasov ***@***.***> Date: 22/2/22  9:27 pm  (GMT+10:00) To: JetBrains/compose-jb ***@***.***> Cc: Bruce Edgerton ***@***.***>, Author ***@***.***> Subject: Re: [JetBrains/compose-jb] Room Database Support (Issue #1884) 
How is it related to UI?

**Comment by kirill-grouchnikov** [comment]
Room has a lot of dependencies on Android APIs. It's quite likely going to be a significant effort to remove such dependencies, and certainly not as a part of what Compose is (a UI toolkit).

**Comment by hfhbd** [comment]
Just use sqldelight

**Comment by brucieW** [comment]
Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1884">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
