### ISSUE TITLE
Text Edit: can not place a cursor inside a ligature

### ISSUE THREAD

**Issue by VeselovAlex** [JetBrains/compose-jb#1891]
Reproduce: in `TextField`
1) Type `ff`
2) Try to move cursor one character left
3) Cursor moves to the beginning of the line (`|ff`) instead of `f|f`

**Comment by igordmn** [comment]
Should be fixed in 1.1.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1891">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
