### ISSUE TITLE
Text Edit: Wrong cursor size if line height is set and `return` pressed

### ISSUE THREAD

**Issue by VeselovAlex** [JetBrains/compose-jb#1892]
In `TextField`:
1) Set `textStyle = TextStyle(lineHeight = 360.sp)`
2) Press `Enter` (`⏎`)
3) Cursor is too large

**Comment by eymar** [comment]
fixed  in https://github.com/JetBrains/androidx/pull/277

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1892">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
