### ISSUE TITLE
Forbid using the `classes` function inside `style` blocks

### ISSUE THREAD

**Issue by SerVB** [JetBrains/compose-jb#1893]
Currently, both of the following lines are valid and work the same:

```kt
Div({ classes("abc", "def") })
Div({ style { classes("abc", "def") } })
```

However, it's better to avoid having multiple ways of doing something to make code more consistent, so I suggest forbidding specifying `classes` inside `style`. Probably adding [`@DslMarker`](https://kotlinlang.org/docs/type-safe-builders.html#scope-control-dslmarker) will help.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1893">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
