### ISSUE TITLE
Implement "actual fun ActualDialog" and "actual fun ActualPopup"

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#19]
We can move already implemented Dialog/Popup from desktop to ui module

from:
support\compose\desktop\desktop\src\jvmMain\kotlin\androidx\compose\ui\window\AppDialog.kt
to:
support\compose\ui\ui\src\desktopMain\kotlin\androidx\compose\ui\window\DesktopDialog.kt

from:
support\compose\desktop\desktop\src\jvmMain\kotlin\androidx\compose\ui\window\Popup.kt
to:
support\compose\ui\ui\src\desktopMain\kotlin\androidx\compose\ui\window\DesktopPopup.kt

(DesktopPopup is in ui module, so we can't use Box, we have to use Layout (as in support\compose\ui\ui\src\androidMain\kotlin\androidx\compose\ui\window\AndroidPopup.kt)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5626">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6521">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
