### ISSUE TITLE
How to show an image from the remote url in my app?

### ISSUE THREAD

**Issue by 1832086967** [JetBrains/compose-jb#190]
I get an error when I run the image() function in a coroutine.

I try to run the code
```kotlin
Box {
    GlobalScope.launch(Dispatchers.Unconfined) {
        // suspend function with the context of Dispathers.IO
        val bitmap = imageFromUrl("https://aurora-image.oss-cn-beijing.aliyuncs.com/background/personal_card_bg.png")
        Image(bitmap=bitmap)
    }
}
```
but it is bad

```
@Composable invocations can only happen from the context of a @Composable function
```

**Comment by lsanotes** [comment]
Image can‘t be used in  `GlobalScope.launch(Dispatchers.Unconfined) {}`, you can only use a Composable function in  another one.

**Comment by lsanotes** [comment]
https://github.com/JetBrains/compose-jb/tree/master/examples/imageviewer

**Comment by 1832086967** [comment]
> https://github.com/JetBrains/compose-jb/tree/master/examples/imageviewer

老哥，这个例子我到处都找不到哪里有用到异步加载图片，并且我之前没有学过安卓开发，你能简单给我讲讲吗

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6505">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
