### ISSUE TITLE
[question] what's the best way to do Internationalization now

### ISSUE THREAD

**Issue by lovehzj** [JetBrains/compose-jb#1904]
what's the best way to do Internationalization now?
Is there some examples to look?

Thanks, any help will be greatful

**Comment by akurasov** [comment]
i18n is beyond Compose scope. You can use any approach suitable for Kotlin development

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1904">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
