### ISSUE TITLE
Desktop: RTL empty TextField, incorrect cursor direction on focus gain

### ISSUE THREAD

**Issue by Romixery** [JetBrains/compose-jb#1915]
Hi,
On desktop, when layout direction has been set to the RTL, empty text fields have incorrect cursor position when focus gain. But when start typing, the cursor has placed in the right direction.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/11367383/156190976-c94a55c9-eaab-4fe9-86b6-78d54e24d70f.png">

Expected behavior: When the layout direction is RTL, the cursor should be in the right direction even text field is empty.

**Comment by eymar** [comment]
fixed in https://github.com/JetBrains/compose-jb/issues/1950

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1915">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
