### ISSUE TITLE
Can't view/download jetbrains compose sources

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#192]
When I click on download sources when trying to inspect compose jb source files, I get the following error, and can never view sources: 

![Screen Shot 2020-12-14 at 3 11 31 PM](https://user-images.githubusercontent.com/871169/102130304-aef27b80-3e1e-11eb-8935-7abd4a9567fa.png)

```
Initialization script '/private/var/folders/5h/wqw3wlf50m7_c5tm89ldzqb00000gp/T/ijmiscinit.gradle' line: 20

* What went wrong:
Execution failed for task ':app:DownloadSources'.
> Could not resolve all files for configuration ':app:downloadSources_50239793-808d-4dc3-b7f0-55f43db04c99'.
   > Could not find org.jetbrains.compose.material:material-android-debug:0.2.0-build132@aar.
     Required by:
         project :app
```

**Comment by olonho** [comment]
How did you create a project?

**Comment by olonho** [comment]
See https://youtrack.jetbrains.com/issue/KTIJ-737

**Comment by akurasov** [comment]
@ScottPierce is this topic still actual?

**Comment by akurasov** [comment]
Is not reproducible in IDEA 212.2. The referenced issue is fixed. Closing this one.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6292">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
