### ISSUE TITLE
[Q/Compose for web] How to include a custom font in app written with compose for web?

### ISSUE THREAD

**Issue by y9san9** [JetBrains/compose-jb#1930]

**Comment by Colorata** [comment]
You can do it with `androidx.compose.ui.text.platform.Font` like this:
```kotlin
var fontFamily by remember { mutableStateOf<FontFamily?>(null) }
LaunchedEffect(true) {
    fontFamily = FontFamily(
        androidx.compose.ui.text.platform.Font(
            "unique_font_name",
            loadBytesFromPath("font.ttf")
        )
    )
}
Text("...", fontFamily = fontFamily)
```
And put`font.ttf` in resources folder.
P.S. this code was tested with version `1.2.0-alpha01-dev753` with [this sample](https://github.com/JetBrains/compose-jb/tree/3129fa1d53c2f6a305a2f2a42fc60230fbe0db54/experimental/examples/chat-mpp) in `commonMain` module

**Comment by y9san9** [comment]
thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1930">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
