### ISSUE TITLE
Don't depend on kotlinx-coroutines-swing

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#1943]
Compose 1.1.0

We need to use Swing dispatcher inside Compose, but when we depend on `kotlinx-coroutines-swing` library, we override `Dispatchers.Main`. This can lead to undefined behaviour, if application requires a different `Dispatchers.Main`. For example, see https://youtrack.jetbrains.com/issue/IDEA-285839

The solution:
- copy `Dispathcer.Swing` to skiko library, use this copied dispatcher inside Compose
- remove `kotlinx-coroutines-swing` from skiko and  Compose dependencies

**Comment by igordmn** [comment]
Should be fixed in 1.1.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1943">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
