### ISSUE TITLE
DropdownMenus cut off by the Window

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#195]
```
fun main() {
    Window (
        title = "Drop Demo",
        size = IntSize(500, 200)
    ) {
        var expanded by remember { mutableStateOf(false) }

        val iconButton = @Composable {
            IconButton(modifier = Modifier.background(Color.Green),
                onClick = { expanded = true }) {
                Icon(Icons.Default.MoreVert)
            }
        }
        Column {
            Spacer(modifier = Modifier.height(32.dp))
            DropdownMenu(
                expanded = expanded,
                onDismissRequest = { expanded = false },
                toggle = iconButton,
                toggleModifier = Modifier.size(width=50.dp, height = 50.dp).wrapContentSize(Alignment.TopStart)
            ) {
                DropdownMenuItem(onClick = { /* Handle refresh! */ }) {
                    Text("Refresh")
                }
                DropdownMenuItem(onClick = { /* Handle settings! */ }) {
                    Text("Settings")
                }
                Divider()
                DropdownMenuItem(onClick = { /* Handle send feedback! */ }) {
                    Text("Send Feedback")
                }
            }
        }
    }
}
```

Looks like the code is trying to display the popup under the toggle, sees there's not enough vertical space, and then displays it above the toggle. Except that it's all hosted as a layer inside the window, and it's getting cut off.

Swing has the concept of heavyweight popups that are used when popup content cannot fit in the window bounds - in which case they are displayed as separate floating windows. Compose for Desktop needs the same.

**Comment by kirill-grouchnikov** [comment]
On the Android side, starting from https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/window/AndroidPopup.kt#199 there's code that computes the popup position and registers the popup content at the level of window manager.

There needs to be something similar in https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/DesktopPopup.kt that integrates with Swing's `JWindow` like in the `javax.swing.Popup` class.

**Comment by olonho** [comment]
Please reopen if still reproducible.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6481">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
