### ISSUE TITLE
Text Field: Wrong position of a cursor for RTL text direction

### ISSUE THREAD

**Issue by VeselovAlex** [JetBrains/compose-jb#1950]
If text field is empty cursor is placed on the left side, even if `textDirection=Rtl`

**Comment by eymar** [comment]
closing. It has been already fixed https://github.com/JetBrains/androidx/pull/215

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1950">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
