### ISSUE TITLE
packageMsi and packageExe: IOException if rememberScope is used

### ISSUE THREAD

**Issue by TheMrCodes** [JetBrains/compose-jb#196]
An java.io.IOException gets thrown when trying to pack an compose application that uses the androidx.compose.runtime.rememberCoroutineScope() function.

Test structure:
 - Created default project wizzard "Desktop uses Kotlin 1.4.20" project
 - typed to run packageMsi -> Working
 - added "val scope = rememberCoroutineScope()" in line 11 of generated Main
 - typed to run packageMsi -> Error

![image](https://user-images.githubusercontent.com/28106561/102528859-6b5a7480-409f-11eb-9a79-2b03b3756762.png)

**Comment by xetra11** [comment]
I have the same error message but could not follow it down to your case since I am using a Debian Distribution.

https://github.com/JetBrains/compose-jb/issues/203

**Comment by alexella1** [comment]
Can confirm that in my case the problem only appears in the windows destibution (*.exe, *.msi)

**Comment by xetra11** [comment]
Big bump. Impossible to release a windows build with this bug existing.

**Comment by JamesMcL13** [comment]
I'm struggling with this as well. Any work arounds while waiting on a fix? Thanks :)

**Comment by xetra11** [comment]
> I'm struggling with this as well. Any work arounds while waiting on a fix? Thanks :)

Yeah a workaround would be really needed! Didn't thought about that :dancers:

**Comment by TheMrCodes** [comment]
My workaround at the moment was to only use _LaunchEffect_ and avoid using _rememberCoroutineScope_. I know it's not very scalable approach but for my simple usecase it worked floorless.

**Comment by xetra11** [comment]
@TheMrCodes 

Never heard of `LaunchEffect` due the fact I am new to compose. Can you clarify what it is and how it is an alternative?

**Comment by TheMrCodes** [comment]
In the words of the Android Documentation:

```
@Composable
fun fetchImage(url: String): ImageBitmap? {
    // This holds our current image, and will be updated by the
    // launchInComposition lambda below
    var image by remember(url) { mutableStateOf<ImageBitmap?>(null) }

    **// LaunchedEffect will automatically launch a coroutine to execute
    // the given block. If the `url` changes, any previously launched coroutine
    // will be cancelled, and a new coroutine launched.
    LaunchedEffect(url) {
        image = loadImage(url)
    }**

    // Return the state-backed image property
    return image
}
```

Reference: https://developer.android.com/jetpack/compose/interop

https://developer.android.com/jetpack/compose/interop

**Comment by xetra11** [comment]
@AlexeyTsvetkov will this be in .build142?

**Comment by AlexeyTsvetkov** [comment]
@xetra11 yes

**Comment by xetra11** [comment]
fixed for me thx!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6479">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
