### ISSUE TITLE
Certain imports not found in common module (PainterResource, AlertDialog..)

### ISSUE THREAD

**Issue by matrixor411** [JetBrains/compose-jb#1966]
So, I've created a project, similar to the multiplatform example, but I'm having trouble using certain functionalities. I'm developing for desktop and android.

First of all, I'm aware that I can use these in the seperate android and desktop modules, but most of my implementations (Java and Compose specific) are in the common module.

And because the desktop and android module call code in the common module, I cannot call functions from them (it would create circular dependencies)

My question is - am I having the wrong approach to this? I'd like to load and display images located in the shared resources folder in common, but I can't achieve this without having access to PainterResource. Same goes with displaying dialogues (AlertDialog)

**Comment by igordmn** [comment]
Common resource management still isn't supported by Compose Multiplatform. But you can implement [this workaround](https://github.com/JetBrains/compose-jb/issues/1255#issuecomment-1102501138). Also, please follow that issue for [painterResource]. and [this issue for AlertDialog](https://github.com/JetBrains/compose-jb/issues/762)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1966">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
