### ISSUE TITLE
File chooser support

### ISSUE THREAD

**Issue by userquin** [JetBrains/compose-jb#197]
Is there any chance to include file chooser implementation for desktop?

**Comment by Dominaezzz** [comment]
https://github.com/JetBrains/compose-jb/issues/176

**Comment by userquin** [comment]
AWT, really? 
is the awt FileDialog decorated? 
If not, then it is not a good solution, neither using swing file chooser, if both just use "plain" components.
awt is very old and ugly, and swing has its own theme, that will not match material design in all its variants (in fact I have a swing theme for material design done, very old, around 2015). 
will Compose desktop replace awt, swing and javafax or not?
Anyway, maybe I can make a contribution and create a chooser file for compose (if I find time to do so).

**Comment by kirill-grouchnikov** [comment]
It depends on how you define a "good solution". Your users will probably expect that file chooser to have all the features the native file chooser has on their specific platform (drag and drop, favorite location, different grid views, sorting, filtering, history, and who knows what else). I don't think I have a single desktop app on my machine (macOS) that does its own thing with file choosers. They all use the system one (which is what AWT gives you), no matter how finely "themed" that app is.

**Comment by olonho** [comment]
Feel free to try to make your own file chooser, but first check if https://docs.oracle.com/javase/7/docs/api/javax/swing/JFileChooser.html is not doing what you want.
Also see https://docs.oracle.com/javase/tutorial/uiswing/components/filechooser.html for more information.

**Comment by userquin** [comment]
How about using kotlin native and call plataform code???

**Comment by Phaestion** [comment]
> How about using kotlin native and call plataform code???

You don't need Kotlin Native for this, because that is exactly what java.awt.FileDialog does...

**Comment by userquin** [comment]
@Phaestion you are right, awt delegates to native implementation peer and so there is no need to add this component.

Do you know why IntelliJ does not resolve any link to classes or methods on any package (crtl + left mouse button click)? I'm testing this on imageviewer sample from the repo:

![compose-jb-197](https://user-images.githubusercontent.com/6311119/102638999-ab316280-4158-11eb-84d1-7875414a0a3c.png)

**Comment by changfeng1050** [comment]
now you can use this  https://github.com/Wavesonics/compose-multiplatform-file-picker

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6043">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
