### ISSUE TITLE
Splitpanel should not depend on Material

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-jb#1975]
The SplitPanel library depends on the Material Compose library, but only to get a default colour. This makes it impossible to use the component in a project that doesn't include Material.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1975">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
