### ISSUE TITLE
Customize Look of ContextMenu

### ISSUE THREAD

**Issue by ryanmitchener** [JetBrains/compose-jb#1991]
It would be great to be able to customize the look of the ContextMenus provided by desktop. This can normally be avoided by implementing my own popups, however `SelectionContainer` uses `ContextMenuArea` with no way to override its use or look. I would like for all menus to look consistent across the app or at least look like the platform specific context menus. The provided context menu does neither.
![Screen Shot 2022-04-07 at 10 33 15 AM](https://user-images.githubusercontent.com/6433145/162224553-d88e8ccf-1c86-4701-87b8-2b1b92a4f905.png)

 I see there is a `LocalContextMenuRepresentation` but it is marked as internal.

**Comment by igordmn** [comment]
> I see there is a LocalContextMenuRepresentation but it is marked as internal.

Yes, you should use `LocalContextMenuRepresentation`. It was made public in 1.2.0-* versions. This won't be backported to 1.1.* unfortunately.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1991">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
