### ISSUE TITLE
When to expect update up to kotlin 1.6.20?

### ISSUE THREAD

**Issue by InsanusMokrassar** [JetBrains/compose-jb#1993]
Hello :) I develop several libraries and some of them depend on that awesome library, but I can't update them until `JB/Compose` will start support kotlin `1.6.20`. Is there any hope in the near future to get update with that kotlin version support?

**Comment by eymar** [comment]
We'll likely cherry-pick the support for 1.6.20 from the upstream - https://android-review.googlesource.com/c/platform/frameworks/support/+/2020776 (It's in progress at the moment)

**Comment by InsanusMokrassar** [comment]
Thanks for your answer :) we could pin this issue or show somehow to avoid additional similar questions on it

**Comment by beyondeye** [comment]
This issue should be closed already

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1993">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
