### ISSUE TITLE
Closing a window from code

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#200]
I want to create a "splash screen", like in IntelliJ IDEA. And I want that splash screen to disappear when loading is finished. How can I close the window from the code?

EDIT: I do not want to shut down the whole app, I just want to close the splash window

**Comment by Merpyzf** [comment]
You can use AppManager.windows to get the application that contains all windows by calling the close method to complete the closing action.

like this:
```
val windows = AppManager.windows
windows[0].close()
```

**Comment by Rsedaikin** [comment]
You can close the window by `AppManager.focusedWindow?.close()` or you can keep a reference to the AppWindow instance:
```
fun main() {
    SwingUtilities.invokeLater { // necessary if you are using AppWindow instead of Window/Dialog
        val splashWindow = AppWindow()
        splashWindow.show {
            // content
            ...
            splashWindow.close()
            ...
        }
    }
}
```
If I understand correctly, you create a "splash screen" and when loading is finished you close the "splash screen" and the whole app is closed. By default if you close the last window - application closed. You can control that behaviour:
```
fun main() {
    SwingUtilities.invokeLater {
        // disable the action of closing the application if all windows are closed
        AppManager.setEvents (
            onWindowsEmpty = null
        )

        val splashWindow = AppWindow(title = "Splash Screen")
        splashWindow.show {
            // content
            ...
            // loading finished
            splashWindow.close()
            showMainWindow()
            ...
        }
    }
}

fun showMainWindow() {
    // enable the action of closing the application if all windows are closed
    AppManager.setEvents (
        onWindowsEmpty = AppManager.defaultActionOnWindowsEmpty
    )

    // main window
    Window(title = "MainWindow") {
        // content
        ...
    }
}
```

**Comment by GGorAA** [comment]
Thanks everyone! I used the first solution, worked flawlessly! Thanks everyone!
And yes, this should be definitely added to documentation :D

**Comment by GGorAA** [comment]
wait, I haven't noticed
the window is not closing when I invoke `AppManager.windows[0].close()`. The `AppManager` assumes that the window is closed, but it is wrong, the window is still shown. Note: I am on macOS Big Sur 11.1

**Comment by GGorAA** [comment]
Update: instead of closing it or does nothing, or clears the window content. That is totally strange

**Comment by Rsedaikin** [comment]
Could you give a simple example of how exactly the situation arises when the window does not close when calling the `close ()` method of AppWindow? Example below works fine:
```
import androidx.compose.desktop.AppManager
import androidx.compose.desktop.AppWindow
import androidx.compose.material.Text
import javax.swing.SwingUtilities

fun main() = SwingUtilities.invokeLater {
    AppManager.setEvents()

    println(AppManager.windows.isEmpty())  // output: true

    AppWindow().show {
        Text("Empty content")
    }

    println(AppManager.windows.size) // output: 1
    AppManager.windows[0].close()
    println(AppManager.windows.size) // output: 0

    AppManager.defaultActionOnWindowsEmpty.invoke() // exip app
}
```

**Comment by GGorAA** [comment]
![image](https://user-images.githubusercontent.com/61655029/103083807-04304900-45e6-11eb-9132-df3f45b6a8c4.png)
well, it works, the window closes, and the app shuts down. Also this is how it works with my method:

https://t.me/compose_mpp/1012

**Comment by Rsedaikin** [comment]
In this video you have created 2 windows with the same size (500 x 300) and title ("OKSM loading..."). In `main()` and `SplashScreen()` inside the `if - else` block. You must remove the `Window` in the `if - else` block of `SplashScreen()`. By the way, if you test a real progress bar from 0 to 100 with step 1, you will open 100 additional `SplashScreen`s because `Window` is not composable function. Also in your case, you must disable the `onWindowsEmpty` event before the `SplashScreen()` window appears, and re-enable the `onWindowsEmpty` event after the `SplashScreen()` window is closed.

Try this template:
```
fun main() {
    // disable event
    AppManager.setEvents(
        onWindowsEmpty = null
    )
    val progress = mutableStateOf(0f)
    Window(
        title = "LOADING...",
        size = IntSize(500, 300)
    ) {
        SplashScreen(
            progressLoading = progress,
            afterLoadingAction = {
                Window(
                    title = "MainWIndow"
                ) {
                    Text("MAIN WINDOW")
                }
                // restore event
                AppManager.setEvents(
                    onWindowsEmpty = AppManager.defaultActionOnWindowsEmpty
                )
            }
        )
    }
    GlobalScope.launch {
        while( progress.value != 100F) {
            delay(20)
            progress.value += 1f
        }
    }
}

@Composable
fun SplashScreen(
    progressLoading: MutableState<Float>,
    afterLoadingAction: () -> Unit
) {
    if (progressLoading.value != 100F) {
        Text("LOADING: ${progressLoading.value}%")
    } else {
        AppManager.focusedWindow?.close()
        afterLoadingAction.invoke()
    }
}
```

**Comment by GGorAA** [comment]
Thanks, that worked! Thank you very much! :D

**Comment by p2kr** [comment]
`AppManager` is not available anymore.

**Comment by FlorianMarsch** [comment]
https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new

Found this. you can just
 _if(visible){ window }else{ not }_ it 
as every other component. very straight forward ;)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6168">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
