### ISSUE TITLE
[Question] Compose JB LTS?

### ISSUE THREAD

**Issue by Elec0** [JetBrains/compose-jb#2004]
Looking around, I can find no information on what kind of LTS exists for compose-jb. Compose for Android appears to be the new thing, but they don't appear to have LTS information either, unless it falls under the Android umbrella or something.

Essentially, is there any guarantee for updates (even just security updates) for any timeframe?

**Comment by igordmn** [comment]
There is no LTS for compose-jb at the moment. The strategy is to make hotfixes for the latest stable versions until the new version is released. For example, if the latest stable version is 1.1, we make hotfixes for it (1.1.1, 1.1.2) until we release 1.2. The first hotfixes can contain minor bugfixes, but after some time we release hotfixes only for critical bugs.

The current plan of releases is to release 1-2 versions per year. Usually the release cycle follows the Jetpack Compose releases for Android.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2004">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
