### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by suyashjoshi** [JetBrains/compose-jb#201]
Hello,

Can I use Java with compose-jb instead of Kotlin?

Thanks,
Suyash

**Comment by GGorAA** [comment]
No, you can't
Compose is specifically made for Kotlin. There is no way of using Compose in Java.

**Comment by suyashjoshi** [comment]
Ok, however I prefer Java over Kotlin, any plans for supporting java in the future?

**Comment by GGorAA** [comment]
nope
it is strictly a Kotlin framework

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6503">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
