### ISSUE TITLE
ScrollbarAdapter for LazyGridState is missing

### ISSUE THREAD

**Issue by Thomas-Vos** [JetBrains/compose-jb#2029]
I cannot find a way to add a scrollbar to a `LazyVerticalGrid` as there is no scrollbar adapter for `LazyGridState`. Could this be added?

**Comment by Syer10** [comment]
I made a quick and dirty implementation of this for my application, if you need it feel free to copy/improve upon my implementation.
https://github.com/Suwayomi/Tachidesk-JUI/blob/master/ui-core/src/desktopMain/kotlin/ca/gosyer/jui/uicore/components/DesktopScrollbar.kt#L80

**Comment by The-TNT-Guy** [comment]
I was just looking for this exact feature, adding this would be really nice

**Comment by StefanOltmann** [comment]
This currently prevents me from updating to the current version because I need to offer a scrollbar in my desktop app.

**Comment by StefanOltmann** [comment]
Thank you, @m-sasha !

**Comment by StefanOltmann** [comment]
@m-sasha Is there a way how I can use this already with the latest 1.3.0 release?

It looks like that the changes to androidx are not included in the latest release.

**Comment by m-sasha** [comment]
@StefanOltmann 
It didn't make it into 1.3.0, so I think you'll need to either wait for 1.4.0, or build compose yourself from latest source.
Sorry I don't have better news.

**Comment by m-sasha** [comment]
@StefanOltmann You can also try using `1.4.0-alpha` as soon as we start releasing them.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2029">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
