### ISSUE TITLE
Desktop UI testing error on sendTextInputCommand on JUnit4

### ISSUE THREAD

**Issue by PedroStrabeli** [JetBrains/compose-jb#2059]
I'm using:
- kotlin 1.6.10
- compose 1.1.0
- compose.ui:ui-test-desktop 1.1.0

with a Desktop application.
I have the following UI test:

    @get:Rule
    val compose = createComposeRule()

    @Test
    fun `login button on start is disabled`() {
        runBlocking(Dispatchers.Main) {
            compose.setContent {
                AuthView()
            }
            compose.awaitIdle()

            compose.onNodeWithTag("auth-login-button").assertIsNotEnabled()
            val email = compose.onNodeWithTag("auth-email")
            email.performClick()
            email.performTextInput("sbc@hfdjs.com")
            compose.onNodeWithTag("auth-login-button").assertIsEnabled()
        }
    }

I'm experimenting with this simple UI test where I get a node with a testTag and try to fill it with a text value. The actions result in a `kotlin.NotImplementedError: An operation is not implemented.` exception from the `performTextInput()` as shown below:

![image](https://user-images.githubusercontent.com/6330907/168169149-5f4b1c31-3f63-4bbf-ba9a-e523105ef3f3.png)

When I follow the stacktrace up to `DesktopComposeTestRule.desktop.kt`, I find that the performTextInput() method is actually not implemented:

![image](https://user-images.githubusercontent.com/6330907/168174084-01223ac3-0f01-472c-b28f-a1b3bac525bf.png)

I need these validations on my test suite, and I am not aware of other methods of testing UI with Desktop Compose, can I expect these to be implemented anytime soon? Or is there a workaround to my problem?

Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2059">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
