### ISSUE TITLE
Options(in build.gradle.kts) to bundle JRE with the native installation

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#207]
Kotlin apps, especially in Compose, are great. But it requires users to install `JRE` to run our Kotlin app. I've heard that `jpackage` is able of bundling `JRE` with our app. But I haven't found any Compose for Desktop options to enable `JRE` bundling. **How to enable it? Or if there is no such option for now, when it will be available?**

**Comment by olonho** [comment]
Please read https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution

**Comment by GGorAA** [comment]
I haven't found any documentation about including JRE in a native distribution. if there IS any docs about it, please show it, I can't find it 😆

**Comment by olonho** [comment]
Native distribution automatically contains JRE, and is fully self-contained.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6497">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
