### ISSUE TITLE
Crash when we integrate Compose into IDEA 2022.1

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#2070]
1. https://github.com/JetBrains/compose-jb/tree/master/examples/intellij-plugin
2. set `version.set("2022.1")` in build.gradle.kts
3. `./gradlew runIde`

![image](https://user-images.githubusercontent.com/5963351/170068706-ab0c8188-941c-4144-815a-54c2ea030011.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2070">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
