### ISSUE TITLE
Proposal: Clean up milestones

### ISSUE THREAD

**Issue by felixdivo** [JetBrains/compose-jb#2073]
There are [quite a few milestones open](https://github.com/JetBrains/compose-jb/milestones?state=open) for already released versions. It might be less confusing if some were closed.

**Comment by igordmn** [comment]
Thanks! Done.

We will release 1.1.2, if there will be new critical issues, and 1.2 in someday in the future. It will be after Jetpack Compose 1.2 release, but the gap between it and Compose Multiplatform 1.2 is still unknown.

Which fixes/features from https://github.com/JetBrains/compose-jb/issues will be in 1.2 also isn't decided.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2073">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
