### ISSUE TITLE
add function drawText() on @Composable Canvas

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#2077]
I want to draw text on Canvas by following code
``
Canvas(modifier = Modifier.fillMaxSize()){
                drawText("Hello World",x,y,font,paint)
            }
``

Anyway to make it?

**Comment by kirill-grouchnikov** [comment]
This should be filed on https://issuetracker.google.com/issues/new?component=612128&template=1253476 - the core Compose tracker

**Comment by igordmn** [comment]
Let's keep [this issue](https://github.com/JetBrains/compose-jb/issues/2117) as more informative.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2077">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
