### ISSUE TITLE
When many images are loaded from the remote URL and displayed to LazyColumnForIndexed, there will be a stutter problem when sliding

### ISSUE THREAD

**Issue by Merpyzf** [JetBrains/compose-jb#208]
When the remote image is loaded asynchronously from the network and displayed in LazyColumnForIndexed, the problem of sliding and freezing will occur. This problem will not only appear on the desktop platform, but also on the Android platform. I suspect that there is a problem with the ImageLoader I wrote, but similar problems also occur when I use other image loading libraries. I spent too much time on this issue and couldn't solve it. So I want to know if this is because the current Compose is still in the Alpha version, so there are some shortcomings in performance?

**running result：**

![](https://blog-1252413502.cos.ap-shanghai.myqcloud.com/compose%20.gif)

I use onCommit to perform asynchronous image loading in the Image component. This project is a demo written during my test. you guys can review my code and help me solve the problem. 🥺

[ImageLoaderSample](https://github.com/Merpyzf/ImageLoaderSample)

I also did the same test using this library below.

[accompanist](https://github.com/chrisbanes/accompanist)

thanks 😺!

**Comment by Dominaezzz** [comment]
The stutter happens because you only compose the image after it has been loaded. So it literally just appears out of nowhere.

You should show a placeholder of the same size as the image before it's loaded, if you want less stuttering.

**Comment by Merpyzf** [comment]
> The stutter happens because you only compose the image after it has been loaded. So it literally just appears out of nowhere.
> 
> You should show a placeholder of the same size as the image before it's loaded, if you want less stuttering.

Thank you ! 🎉, according to your suggestion, I have solved the problem of sliding and stuck, at least to a large extent to reduce the stuck.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6501">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
