### ISSUE TITLE
Only packageMsi can be executed!!! 

### ISSUE THREAD

**Issue by huangshengling** [JetBrains/compose-jb#2090]
![2022-06-02_11-57](https://user-images.githubusercontent.com/12929764/171550199-25150e37-ecf6-427d-b02e-8b3601ff8944.png)
![2022-06-02_11-57_1](https://user-images.githubusercontent.com/12929764/171550210-1bf8c619-d991-4b22-9222-58eb814387a4.png)

Could not find any valid exception information, but execution skipped

**Comment by ctadlock** [comment]
You can only build the package for the OS of the system you are running the build on. A windows PC cant produce a build for Mac or Linux, ...

**Comment by igordmn** [comment]
> You can only build the package for the OS of the system you are running the build on

That is unfortunately true. This is a limitation of the official native distribution mechanism.

You can also look at https://conveyor.hydraulic.dev. It claims that you can build the application for all OS'es. I haven't tried it yet though, so if you will have any experience with this, we would like to hear feedback.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2090">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
