### ISSUE TITLE
pointerHoverIcon changes only after pointer event

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#2091]
```kotlin
fun main() {
    var isCtrlPressed: Boolean by mutableStateOf(false)

    singleWindowApplication(
        onPreviewKeyEvent = {
            isCtrlPressed = it.isCtrlPressed
            false
        }
    ) {
        Box(modifier = Modifier
            .size(100.dp)
            .background(Color.Blue)
            .pointerHoverIcon(if (isCtrlPressed) PointerIconDefaults.Hand else PointerIconDefaults.Default)
        ) 
    }
}
```
If we hover the box and press Ctrl, the cursor icon won't change until we move the cursor. 
From the name of a function `pointerHoverIcon` it's not obvious that it's necessary that pointer should move in order to get updated.

Also SkiaBasedOwner calls commitCursor() only in processPointerInput(). Can we call commitCursor() in PointerIconService implementation?

Like this:
```
object : PointerIconService {
            override var current: PointerIcon
                get() = getPointerIcon(component)
                set(value) {
                    setPointerIcon(component, value)
                    commitPointerIcon(component) // add this call?
                }
        }
```

I guess it was not added here for some reason.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2091">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
