### ISSUE TITLE
onLongClick event not working

### ISSUE THREAD

**Issue by TheMrCodes** [JetBrains/compose-jb#211]
Steps to recreate to Error:
 - Created default 'compose for desktop' project in project wizzard
 - Copied first tutorial code for 'Mouse event listeners' mouse event tutorial (https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events)
 - Run and tried long pressing

Tested on Windows with a PC mouse

**Comment by olonho** [comment]
Please retry with example at 872b9e0. Currently, text selection is special, and cannot do long clicks.

**Comment by TheMrCodes** [comment]
Working now 👍
I also found the error in my usecase: A Text composable can't be long pressed because of the selection feature

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6499">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
