### ISSUE TITLE
Suggestion to make onClick lambda parameter in Modifier.clickable optional

### ISSUE THREAD

**Issue by TheMrCodes** [JetBrains/compose-jb#212]
Today I've got a usecase where I only needed the onLongClick callback of the Modifier.clickable funnction. But to add just a LongClick or DoubleClick callback you have to also define the onClick callback which provided not the wanted result

**Comment by olonho** [comment]
This is shared API with Android, please report at https://issuetracker.google.com/issues and post number here.

**Comment by TheMrCodes** [comment]
Thanks for the reply
Wasn't sure if this was an compose for desktop thing or not

That means this issue was a missunderstanding and is not meant to be in this repository

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6500">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
