### ISSUE TITLE
Text with any font as default as custom, does not visible in Text function on Windows 10

### ISSUE THREAD

**Issue by alexmaryin** [JetBrains/compose-jb#214]
On clear IDEA 2020.3.1 Preview, kotlin 1.4.21, compose 0.3.0-build136 as well as 0.2.0-build132 with same effect, Windows 10 x64 (with Russian default), starting new project for desktop compose with simple function as follow:
```
fun main() = Window(title = "Compose for Desktop", size = IntSize(300, 300)) {
    MaterialTheme {
        Column(Modifier.fillMaxSize(), Arrangement.spacedBy(5.dp)) {
            Text("Default text")
            Text(fontFamily = fontFamily(font("Calibri", "calibri.ttf")), text =  "Calibri text!")
            Text(text ="Segoe text", fontFamily = fontFamily(font("Segoe UI", "segoeui.ttf")))
        }
    }
}
```
![screenshot](https://github.com/alexmaryin/selenium_homework/blob/master/Clipboard%201.jpg?raw=true)
Project has built and started but without any text on screen (as default font as well as custom from resources), only standard windows header is visible. Catched error in log:
`SkIcuLoader: datafile missing: C:\Users\maryin\.jdks\openjdk-15.0.1\bin\icudtl.dat.`
JDK 11, JDK 15 have the same result.

**Comment by olonho** [comment]
Seems to depend on hardware/driver, in this case it's oldish Gigabyte ATI Radeon HD 4200, 128MB card. Need to recheck how software rendering works on this machine.

**Comment by olonho** [comment]
@Rsedaikin please update this issue once software rendering fallback is implemented in Skiko.

**Comment by igordmn** [comment]
@alexmaryin, could you please run this example?

[software-text-rendering.zip](https://github.com/JetBrains/compose-jb/files/5741798/software-text-rendering.zip)

("gradlew run" from command line)

It should create a file "1.png":
![1](https://user-images.githubusercontent.com/5963351/103133019-0b745700-46b9-11eb-82ad-9576d6864854.png)

**Comment by alexmaryin** [comment]
@igordmn Yes, it works!

**Comment by igordmn** [comment]
Thanks!

So it is not a font loading problem.

Something wrong with OpenGL text rendering in Skia on this PC configuration 🤔.

My guess - 128mb is too small to store glyphs in video memory.
Maybe we need to properly configure the size of the text cache in Skia, or switch to software rendering completly.

**Comment by alexmaryin** [comment]
@igordmn Changed to 512Mb but app also runs with blank screen.

**Comment by olonho** [comment]
Please check with 0.3.0-rc1.

**Comment by alexmaryin** [comment]
Works with 0.3.0-rc1 and 0.3.0 now! Perfomance also improved.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6468">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
