### ISSUE TITLE
Add support for IntelliJ IDEA 2022.2 EAP release

### ISSUE THREAD

**Issue by sureshg** [JetBrains/compose-jb#2144]
[Compose MPP IDE plugin](https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support) support for IJ 2022.2 EAP. Not sure if EAP releases are officially supported, but it worked in the past releases.

**Comment by igordmn** [comment]
Fixed in 1.1.1.1 some time ago

**Comment by igordmn** [comment]
Future EAP releases will be supported, but there can be issues because of EAP status

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2144">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
