### ISSUE TITLE
Gradle createDistributable on Windows creates write-protected EXE

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-jb#2158]
I wonder why the executable file for Windows produced by Gradle command `createDistributable` is write protected and if I can turn that off. Further steps in my CI now need to take measures to remove that flag again and I would like to don't have that flag to start with.

Is this intentional? If yes, why? Can you make an option to turn if off? Thank you.

**Comment by StefanOltmann** [comment]
After some research I wasn't able to find out the cause. So having a build step to remove the flag seems justified.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2158">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
