### ISSUE TITLE
Add support for right click(or if it already exists, add it to documentation)

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#216]
As in the title, how to use the right click functionality?

**Comment by igordmn** [comment]
Unfortunately it is not possible with current version of Compose (0.3.0-build136).

You can track progress here:
https://github.com/JetBrains/compose-jb/issues/129

Proper mouse handling is in high priority.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6498">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
