### ISSUE TITLE
Could not resolve 1.2.0 alpha release dependencies

### ISSUE THREAD

**Issue by LAP2** [JetBrains/compose-jb#2165]
Hi folks.

Faced a following problem during sync of components subprojects.
gradle could not resolve aplha dependencies:
```
:SplitPane:library:commonMain: Could not resolve org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev686.
Required by:
    project :SplitPane:library
```
But repository was provided.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2165">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
