### ISSUE TITLE
Unresolved reference: AdapterList

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-jb#217]
Compose version: 0.3.0-build136
`AdapterList` was added in Version 0.1.0-dev15 of Compose UI. When we can expect it to be available in Compose for Desktop?

**Comment by Dominaezzz** [comment]
I'm fairly certain that was replaced with `LazyColumn`.

**Comment by olonho** [comment]
Yes, we share API (MPP) with the Jetpack Compose, so it's likely there.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6496">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
