### ISSUE TITLE
constraintlayout

### ISSUE THREAD

**Issue by WngYilei** [JetBrains/compose-jb#2210]
about compose desktop ,why not support  constraintlayout ？ 
 I'm used to using it。
Do you have plan  to support it  in the compose desktop ?

**Comment by igordmn** [comment]
It would be great, but we don't plan to do that in the near future. We need to coordinate that with Google.

Please, follow [this issue](https://github.com/JetBrains/compose-jb/issues/858) and add `thumbs up` reaction

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2210">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
