### ISSUE TITLE
Compose plugin incompatible with Idea 222.*

### ISSUE THREAD

**Issue by Klurige** [JetBrains/compose-jb#2216]
`Plugin 'Compose Multiplatform IDE Support' (version '1.1.1') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is IC-222.3345.118`

**Comment by Omico** [comment]
You can actually go to its plugin home page and use the dev version.
https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support/versions/snapshots

**Comment by igordmn** [comment]
It is fixed some time ago (we released 1.1.1.1 version). To prevent such situations in the future, we increased until version significantly in https://github.com/JetBrains/compose-jb/pull/2318 and plan to run compatibility checks for the latest IDEA on CI.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2216">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
