### ISSUE TITLE
Compose idea plugin fails Jetbrains market review

### ISSUE THREAD

**Issue by wilinz** [JetBrains/compose-jb#2223]
Display is not compatible, as shown in the figure
![IMG_20220803_143425](https://user-images.githubusercontent.com/59408438/182540941-11e43d03-e0f3-4753-8426-d40de3a4b3a0.jpg)

**Comment by wilinz** [comment]
But I am compatible normally in the actual test
Idea version: IU-2022.2 , After installing the plugin, it will prompt to download the compose dependencies, and then run normally

**Comment by igordmn** [comment]
It is fixed some time ago (we released 1.1.1.1 version). To prevent such situations in the future, we increased until version significantly https://github.com/JetBrains/compose-jb/pull/2318 and plan to run compatibility checks for the latest IDEA on CI.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2223">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
