### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.2)

### ISSUE THREAD

**Issue by ahmedhnewa** [JetBrains/compose-jb#2227]
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.2)

Please Update [Compose Multiplatform IDE Support](https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support) plugin to be compatible with the latest version on IntelliJ

**Comment by igordmn** [comment]
It is fixed some time ago (we released `1.1.1.1` version). To prevent such situations in the future, we increased `until` version significantly [here](https://github.com/JetBrains/compose-jb/pull/2318) and plan to run compatibility checks for the latest IDEA on CI.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2227">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
