### ISSUE TITLE
Keyboard short cut in main AppWindow

### ISSUE THREAD

**Issue by jeancharles-roger** [JetBrains/compose-jb#223]
Hi,

I want to add a global Window shortcut on the main window of my app as shown [here](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Keyboard/README.md#window-scoped-events) but I haven't found any access to the instance of `AppWindow` when creating one like this:

```kotlin
fun main() = Window(
        title = "Calculator",
        size = IntSize(300, 328),
        events = WindowEvents(),
    ) {
        val state = mutableStateOf(CalculatorState())

        DesktopMaterialTheme {
           ...
        }
}
```

`WindowEvents` doesn't offert access to keyboard shortcuts either.

Is there a way to add them ?

Thanks 😁

**Comment by GGorAA** [comment]
Please, use a new GitHub feature called Discussions to ask those questions. It is a better way for asking questions :D

**Comment by jeancharles-roger** [comment]
Sorry, I don't have the habit yet 😉.

Here is the topic: https://github.com/JetBrains/compose-jb/discussions/225

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5570">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
