### ISSUE TITLE
ui-graphics is not published for android

### ISSUE THREAD

**Issue by luca992** [JetBrains/compose-jb#2238]
Not sure if this is intentional, ui-graphics isn't being published for android

https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-graphics-android/

**Comment by igordmn** [comment]
Yes, that is intentional. We don't publish android artifacts. When someone writes MPP application, the application reuses the build of Jetpack Compose, published by Google.

**Comment by luca992** [comment]
So I've figured out my actual issue is that intellij fails to recognize all compose imports in the androidMain source set after updating to the android gradle plugin 7.2.2 . All compose imports using the 7.1 plugin are correctly resolved by intellij. I'm using the latest alpha build. I probably should make a separate issue. But is there any workaround for using 7.2+ ?

**Comment by LandryNorris** [comment]
@luca992 There was a [discussion](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1659630211722659) about this in the Kotlin Slack. It appears that using Dolphin or Electric Eel (with 7.3 rc or 7.4 beta gradle versions respectively) can recognize the compose imports, but compose-jb is currently not recognized by gradle 7.2.

**Comment by igordmn** [comment]
>  intellij fails to recognize all compose imports in the androidMain source set after updating to the android gradle plugin 7.2.2

This issue is fixed in AGP 7.3.0.

AGP 7.3.0 is supported by IDEA 2022.3 EAP (223.4884.69) and Android Studio Dolphin 2021.3.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2238">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
