### ISSUE TITLE
Modules missing for desktop preview in recent alphas

### ISSUE THREAD

**Issue by dsvoronin** [JetBrains/compose-jb#2240]
```
Could not determine the dependencies of task ':myProject:configureDesktopPreview'.
> Could not resolve all task dependencies for configuration ':myProject:detachedConfiguration4'.

     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/preview-rpc/1.2.0-alpha01-dev755/preview-rpc-1.2.0-alpha01-dev755.pom
```

https://repo.maven.apache.org/maven2/org/jetbrains/compose/preview-rpc/ has dev620 as most recent

I believe this repo is not configurable via project settings

IntelliJ IDEA 2022.1.4 (Ultimate Edition)
Build #IU-221.6008.13, built on July 19, 2022

**Comment by beyondeye** [comment]
repositories {
        maven(url="https://maven.pkg.jetbrains.space/public/p/compose/dev/")
    }

**Comment by dsvoronin** [comment]
> ```
> repositories {
>     maven(url="https://maven.pkg.jetbrains.space/public/p/compose/dev/")
> }
> ```

I have this repo configured already, problem is that preview-rpc repo hardcoded somewhere in IDE plugin

**Comment by dsvoronin** [comment]
That was my project configuration problem.
`preview-rpc` should be successfully resolved from `https://maven.pkg.jetbrains.space/public/p/compose/dev/`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2240">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
