### ISSUE TITLE
about compose desktop application logo icon problem

### ISSUE THREAD

**Issue by WngYilei** [JetBrains/compose-jb#2241]
Android Studio version： Chipmunk 2021.2.1 path1 
Compose version : 1.1.0 
kotlin version:1.6.10 

code 
```  
  Window(
        onCloseRequest = ::exitApplication,
        title = "iBox",
        resizable = false,
        icon = BitmapPainter(useResource("drawable/ic_jetquotes_logo.png", ::loadImageBitmap)),
    ) {
        App(window)
//        test()
    }
```
when i build package dmg  ,the application is the  default logo icon , i want use my icon。 
i use the example project  "codeviewer " ，to build the package dmg , i  meet the same problem。

How should I do it ？

**Comment by darvld** [comment]
Check [this section](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution#app-icon) of the documentation for information about customizaing the launcher icon and more.

**Comment by WngYilei** [comment]
think you ,With your help, my problem was solved

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2241">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
