### ISSUE TITLE
Web: Insert raw HTML on page

### ISSUE THREAD

**Issue by winter-yuki** [JetBrains/compose-jb#2248]
Hello,

Is there a possibility to render raw html and place it on page? Something similar to [this](https://vhudyma-blog.eu/render-raw-html-in-react/) in react.

I'm trying to place markdown article on my Compose website. The idea is to convert markdown to html and display it somehow.

Thank you!

**Comment by winter-yuki** [comment]
Used this workaround, but it does not look very obvious:
```kotlin
val elementId = "content"
val rendered = render(content)
P(attrs = {
    id(elementId)
}) {
      LaunchedEffect(content) {
          val element = window.document.getElementById(elementId)
          requireNotNull(element) { "Content element is not rendered" } // Not needed?
          element.innerHTML = rendered.html
      }
}
```

**Comment by hfhbd** [comment]
What about using `ref`?
```kotlin
P(attrs = {
    ref {
        it.innerHTML = """<a href="https://google.com">google</a>"""
        onDispose {
            it.innerHTML = ""
        }
    }
})
```

**Comment by winter-yuki** [comment]
This is the solution I looked for! Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2248">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
