### ISSUE TITLE
Are we going to have a 1.2.0 stable?

### ISSUE THREAD

**Issue by CoronelGlober** [JetBrains/compose-jb#2254]
Hi!
One of my favorite times of the day is when I go with great excitement to the [Jetbrains maven's repo ](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/compiler/compiler/)to see if there is a new version to be tested, now I've realized that there is a brand new 1.3.0-alpha01 🎉 ! instead of a new version for the 1.2.XXX.

In fact it jumped from **1.2.0-alpha01-dev755** to **1.3.0-alpha01**.

What are the plans for the 1.2.0 version and what exciting things are you planning to bring us on the 1.3.0?

![Screen Shot 2022-08-20 at 9 37 37 PM](https://user-images.githubusercontent.com/69470506/185772939-b2e58aa4-630c-4098-b4f3-3fb9c75a8523.png)

Will this 1.3.0 version allow us to use small UI sections embedded into iOS storyboards #2211  🤔 ?

Thanks!

CC: @arkivanov and @dima-avdeev-jb 😃

**Comment by arkivanov** [comment]
I'm eagerly waiting for a stable version of Compose for Desktop based on Kotlin 1.7.x. This would unblock releasing a stable version of Decompose.

Also if I understand it correctly, MPP Compose has its versions aligned with Jetpack Compose. E.g. one can use a library that depends on MPP Compose `v1.1.x` in a pure Android project with Jetpack Compose `v1.1.x`. Such a project wouldn't be able to migrate to Jetpack Compose `v1.2.0`, because the library would have to wait for MPP Compose `v1.2.0`.

**Comment by igordmn** [comment]
Yes, we already decided the release date of Compose Multiplatform 1.2.0, which will be based on Jetpack Compose 1.2.1 and probably on Compose Compiler 1.3.0.

Targets other than Desktop and Web DOM will still be experimental.

The version `1.3.0-alpha01` in Maven repo is just for `Compose Compiler 1.3.0-alpha01`. Google recently switched to a separate release cycle of Compose Compiler, and we are also experimenting with that now.

1.3.0-alpha version of the main Compose (ui, foundation, material) will be built near or after the Compose Multiplatform 1.2.0 release.

**Comment by CoronelGlober** [comment]
Ok, that makes sense, thanks @igordmn!

**Comment by mipastgt** [comment]
If it is "based on Jetpack Compose 1.2.1" why isn't it also called then Compose Multiplatform 1.2.1? I wouldn't like such a confusion on version numbers.

**Comment by igordmn** [comment]
Compose Multiplatform depends on Jetpack Compose, but it can have its own bugs, so we need our own hotfix versioning. Keeping first two versions aligned is easier.

We can name our versions 1.2.1.1 though, but for now we stick to the usual versioning, and just write corresponding Jetpack Compose versions in [CHANGLOG/Updated Dependences](https://github.com/JetBrains/compose-jb/blob/master/CHANGELOG.md#updated-dependencies).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2254">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
