### ISSUE TITLE
Automatic check that examples in compose-jb tutorials are compilable

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#226]
We need to add a task/script in CI that will check if our examples in tutorials can compile with a new version of Compose

**Comment by olonho** [comment]
Fixed with https://github.com/JetBrains/compose-jb/pull/237

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5569">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
