### ISSUE TITLE
feature : falling-balls-mpp : android sample request

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-jb#2274]
Why [falling-balls-mpp](https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/falling-balls-mpp) doesn't have an Android sample in it? Can I add one and raise a PR?

**Comment by eymar** [comment]
Thank you for your PR! It was merged.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2274">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
