### ISSUE TITLE
Runtime: Darwin: Support watchOS and tvOS

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#2288]
We would like to use molecule for composing StateFlows but we need watchos support too.

I think adding it here should be enough: https://github.com/JetBrains/androidx/blob/401ee9ca0e3b2509041c3178e9e5ca5aaa2a992f/buildSrc/private/src/main/kotlin/androidx/build/AndroidXComposeMultiplatformExtensionImpl.kt#L75

**Comment by eymar** [comment]
Do I get it right, that you need watchOs and tvOS only in compose runtime?

**Comment by hfhbd** [comment]
Yes

**Comment by hfhbd** [comment]
The compiler (not UI) already supports watchos, doesn't it?

**Comment by eymar** [comment]
> The compiler (not UI) already supports watchos, doesn't it?

yes, the compiler plugin doesn't require any amendments for watchOs tvOs, since they're k/native targets.

**Comment by whyoleg** [comment]
So may be we can have all other native targets? At least linuxX64 and mingwX64. So basically all targets supported by coroutines

**Comment by eymar** [comment]
https://github.com/JetBrains/compose-jb/pull/2307

**Comment by hfhbd** [comment]
@eymar Do you need to update the TeamCity build configuration to publish the new targets too?

**Comment by hfhbd** [comment]
Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2288">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
