### ISSUE TITLE
jetpack compose out of memory when use coil + jetpack navigation+ jetpack paging

### ISSUE THREAD

**Issue by wangjunqiangongithub** [JetBrains/compose-jb#2301]
When I use compose, I use navigation to handle the migration of different pictures, paging is used in the picture, lazycolumn and lazyrow are used in paging, and item is used to handle the loading of network pictures.  But every time I migrate, the memory increases and finally lmk is triggered

**Comment by igordmn** [comment]
Compose Multiplatform reuses Jetpack Compose developed by Google on Android target. If you have any issue with Android target, please create the issue in the Google issue tracker as described [here](https://developer.android.com/jetpack/androidx/releases/compose#feedback).

Also, it would be helpful for the developers to have a reproducer and memory profiler logs to understand this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2301">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
