### ISSUE TITLE
Data class not work with Gson after packageMsi

### ISSUE THREAD

**Issue by TianJieYouYue** [JetBrains/compose-jb#2310]

**Comment by TianJieYouYue** [comment]
"com.google.code.gson:gson:2.9.0"

**Comment by TianJieYouYue** [comment]
![image](https://user-images.githubusercontent.com/108406921/189946758-667629a2-feda-48b6-b5a0-c4a398e62824.png)
The Menus show different from run in idea

**Comment by TianJieYouYue** [comment]
![image](https://user-images.githubusercontent.com/108406921/189947023-607fec81-8e4a-42d2-8be7-7c22968acea0.png)

**Comment by succlz123** [comment]
```
compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            ...
            modules("java.sql", "jdk.unsupported")
        }
    }
}
```

To add the above modules to your build.gradle may fix your problem. Also, you can run `suggestRuntimeModules` to know which modules you need to include in the project.

**Comment by TianJieYouYue** [comment]
@succlz123 Thanks for your help! It does work for data class.

But for "The Menus show different from run in idea" still not work
