### ISSUE TITLE
How to create single binary?

### ISSUE THREAD

**Issue by onyn** [JetBrains/compose-jb#2312]
I know that [jetbrains toolbox created using compose multiplatform](https://blog.jetbrains.com/kotlin/2021/12/compose-multiplatform-toolbox-case-study/). Also linux version of toolbox distributes as single self-contained ready to run binary file. Not deb/rpm package.

Also I read [native distribution and local execution](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution) tutorial and which don't answers how to achieve this goal.

So my question is: how to compile application alongside jvm and resources into single binary file? Is this involves graalvm magic?

**Comment by Winterreisender** [comment]
In Linux, you could try [AppImage](https://appimage.org/). This tool can make single self-contained ready to run binary program for Linux , or [deb2appimage](https://appimage.github.io/deb2appimage/) which can convert a deb package to AppImage
In Windows, you could try [Enigma Virtual Box](https://enigmaprotector.com/en/aboutvb.html) (Freeware, Non-OpenSource),

**Comment by onyn** [comment]
Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2312">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
