### ISSUE TITLE
How to request access to camera in mac os ? 

### ISSUE THREAD

**Issue by joseluiskuuc** [JetBrains/compose-jb#2320]

**Comment by kirill-grouchnikov** [comment]
Seems to be outside of the scope of a UI toolkit

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2320">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
