### ISSUE TITLE
IDEA plugin. Get rid of deprecation API calls

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#2321]
IDEA plugin 1.1.1.1

See IDEA Compatibility [verification](https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support/versions/stable/223899) results:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/5963351/190488536-1581963e-7b10-42fb-9392-249be0626fe3.png">

**Comment by igordmn** [comment]
We should do that before 2023.1, which introduces incompatibility change for `FloatingToolbarComponentImpl` . See the internal [discussion](https://jetbrains.slack.com/archives/C025CV5A7PZ/p1670487686365139)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2321">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
