### ISSUE TITLE
Wheres the compiler source

### ISSUE THREAD

**Issue by AyanoYuugiri** [JetBrains/compose-jb#2341]
I want to maintain a fork for compiler that works on java 8 instead of using some stupid ASM hack to patch the class file, but I failed to find the src in this repository.   
Can someone tell me wheres the source of `org.jetbrains.compose.compiler:compiler`

**Comment by igordmn** [comment]
We build it from [AOSP sources](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/compiler/) with this script:
```
export ANDROIDX_PROJECTS=COMPOSE
export COMPOSE_CUSTOM_GROUP=org.jetbrains.compose
export COMPOSE_CUSTOM_VERSION=%version%

cd androidx-main/frameworks/support

./gradlew \
  compose:compiler:compiler:publishMavenPublicationToMavenRepository \
  compose:compiler:compiler-hosted:publishMavenPublicationToMavenRepository \
  --no-daemon -Pandroidx.versionExtraCheckEnabled=false -Pandroidx.alternativeProjectUrl=https://github.com/JetBrains/compose-jb  -Pandroidx.validateProjectStructure=false
```

See more steps in [TeamCity](https://teamcity.jetbrains.com/admin/editBuildRunners.html?id=buildType:JetBrainsPublicProjects_Compose_Compiler_2) (requires an account)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2341">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
