### ISSUE TITLE
Build setup of experimental examples not compatible with Compose 1.2.0-beta01

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-jb#2345]
When I try to build the falling-balls-mpp example (https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/falling-balls-mpp) with the latest Compose (1.2.0-beta01) I get a build failure saying "Cannot add task 'packageRelease' as a task with that name already exists.". This was not the case with previous versions. Here is a list of various variants of the settings and their results:
```
#https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/falling-balls-mpp
#IntelliJ IDEA 2022.2.2 (Community Edition)

# Original (works)
#compose.version=1.2.0-alpha01-dev725
#kotlin.version=1.6.21
#agp.version=7.0.4

# Update AGP (works)
#compose.version=1.2.0-alpha01-dev725
#kotlin.version=1.6.21
#agp.version=7.2.2

# Update Compose and Kotlin (Compiler error)
#compose.version=1.2.0-alpha01-dev774
#kotlin.version=1.7.10
#agp.version=7.2.2

# Update Compose/Kotlin/AGP to latest (Cannot add task 'packageRelease' as a task with that name already exists.)
# Keeping agp.version=7.2.2 does not make a difference.
compose.version=1.2.0-beta01
kotlin.version=1.7.10
agp.version=7.3.0
```
Is there anything wrong with the combination of versions? What would be needed to make this work again?

**Comment by Syer10** [comment]
I beleive both the Compose plugin and the Android plugin are trying to add tasks with this name. Compose uses packageRelease for the proguard packaging, and Android uses it for building releases.

**Comment by mipastgt** [comment]
So why did this work in the past then and what can be done to fix it?

**Comment by Syer10** [comment]
Proguard packaging was added in beta01, so the packageRelease task wasn't added until it was added. I guess you could seperate out the desktop and android into seperate modules to fix it for now. But its also a bug that they conflict so it should be fixed eventually.

**Comment by AlexeyTsvetkov** [comment]
The fix will be included in the next build

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2345">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
