### ISSUE TITLE
Add support for assertIsDisplayed, assertIsNotDisplayed

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-jb#2370]
Writing even the most basic tests for any UI interaction is difficult at the moment, as we can't even check whether a node is displayed.

```kotlin
class MainUiTest {
    // XXX: Forced to use JUnit 4 for UI tests because Compose only provides a JUnit 4 Rule
    @get:Rule
    val compose = createComposeRule()

    @Before
    fun setUp() {
        compose.setContent {
            MainUi()
        }
    }

    @Test
    fun `options are not open by default`() {
        compose.onNodeWithTag("Options").assertIsNotDisplayed()
    }

    @Test
    fun `opening options`() {
        compose.onNodeWithTag("OptionsButton").performClick()
        compose.onNodeWithTag("Options").assertIsDisplayed()
    }
}
```

Tests fail with:

```
An operation is not implemented.
kotlin.NotImplementedError: An operation is not implemented.
	at androidx.compose.ui.test.DesktopAssertions_desktopKt.checkIsDisplayed(DesktopAssertions.desktop.kt:23)
```

Someone elsewhere suggested trying `assertDoesNotExist()` instead, but my main UI uses the scaffold, and the component being tested is the drawer for the scaffold, which apparently always "exists", but is not "displayed".

**Comment by igordmn** [comment]
Fixed in https://github.com/JetBrains/androidx/pull/351 (

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2370">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
