### ISSUE TITLE
checkIsDisplayed(DesktopAssertions.desktop.kt) is not implemented

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#2372]
User report: https://twitter.com/HakanaiVR/status/1578335941864787969

**Comment by igordmn** [comment]
Thanks! Let's keep [this issue](https://github.com/JetBrains/compose-jb/issues/2372)

**Comment by jimgoog** [comment]
I'm confused, did you mark this issue as a duplicate of itself?

**Comment by jimgoog** [comment]
Perhaps you intended for this to be a duplicate of #2370

**Comment by igordmn** [comment]
Or, sure. Fixed :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2372">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
