### ISSUE TITLE
AbstractConfigureDesktopPreviewTask is not compatible with Gradle configuration cache

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-jb#2376]
See: https://docs.gradle.org/7.5.1/userguide/configuration_cache.html

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/1361086/194786887-9a1778d4-a4c4-403e-bca2-7b2739b58ea7.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2376">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
