### ISSUE TITLE
Getting Key modifiers onClick/onSelection

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-jb#2378]
Hi,

what is the recommended way to get key modifiers in click/selection/toggle actions. I tried saving the status in a MutableState and changing it in a key listener, but it does not get actions done outside the window and so it is not always correct.

**Comment by eymar** [comment]
you may try to use `windowInfo.keyboardModifiers.isCtrlPressed` - https://blog.jetbrains.com/kotlin/2022/10/compose-multiplatform-1-2-is-out/#Accessing_keyboard_modifiers

Please let us know if it helps with your use case

**Comment by Burtan** [comment]
Thanks, this works :-)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2378">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
