### ISSUE TITLE
Where I can find the source code of this project?

### ISSUE THREAD

**Issue by hexleo** [JetBrains/compose-jb#238]
Where I can find the source code of this project?

**Comment by olonho** [comment]
Please read the first line at https://github.com/JetBrains/compose-jb/README.md

**Comment by hexleo** [comment]
thank!

**Comment by hexleo** [comment]
Ignore me, I found it under the compose directory.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5565">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
