### ISSUE TITLE
"Compose for desktop" cannot be used for X86 applications. How to configure the JVM environment to support the win32 system

### ISSUE THREAD

**Issue by nadyboy** [JetBrains/compose-jb#2388]
"Compose for desktop" cannot be used for X86 applications. How to configure the JVM environment to support the win32 system

**Comment by igordmn** [comment]
This support will add burden for us (we have to test and fix bugs on these platforms).

Considering a very low current market share that will be even more low in the future, we don't have plans to support 32-bit systems.

See, for example [this statistics](https://www.pcbenchmarks.net/os-marketshare.html). It is biased, but shows the whole trend.

**Comment by xiaobailong24** [comment]
@igordmn Is it possible to support win32 by replacing skiko canvas with awt canvas?

**Comment by m-sasha** [comment]
Unfortunately no. AWT is missing significant parts of the required API.

**Comment by xiaobailong24** [comment]
> Unfortunately no. AWT is missing significant parts of the required API.

Could you explain to miss what significant parts?

**Comment by m-sasha** [comment]
Most significantly, in text rendering API.

**Comment by xiaobailong24** [comment]
> Most significantly, in text rendering API.

Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2388">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
