### ISSUE TITLE
Can we support "Windows 32 bit"?

### ISSUE THREAD

**Issue by nadyboy** [JetBrains/compose-jb#2389]
I need to develop a program that runs on "Windows 32 bit". Unfortunately, we have too many old devices and cannot upgrade every device to "Windows 64 bit". Can we support "Windows 32 bit"?

**Comment by igordmn** [comment]
See https://github.com/JetBrains/compose-jb/issues/2388#issuecomment-1274785770

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2389">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
