### ISSUE TITLE
Question: Relation between Jetbrains Compose and Jebrains Kotlin Multiplatform (which is gone beta)

### ISSUE THREAD

**Issue by ThraaxSession** [JetBrains/compose-jb#2397]
Hi together,

I am a bit confused about the purposes and the relations between those projects.
Is it possible to mix up Jetbrains Compose (for desktop/web) and Kotlin Multiplatform Beta (Android/ios)?
If yes, will be there any example how to? It would be awesome if I could develop for Desktop/Web/Android with one UI/Business code.

(I think about to move away from Flutter)

**Comment by igordmn** [comment]
> Jetbrains Compose (for desktop/web) and Kotlin Multiplatform Beta

To be precise, these are Compose Multiplatform and Kotlin Multiplatform Mobile. Kotlin Multiplatform itself is still in Alpha, but the more narrow solution (Mobile) on top of it is already in Beta.

KMM is a platform and tooling that allows you to write an application that works on Android and iOS, and share a lot of code between them. It provides ability to write shared Kotlin code, but it doesn't provide the whole toolset (UI, resource management, device access) to write cross-platform applications. This toolset is provided by the other solutions on top of KMM and they form [KMM ecosystem](https://kotlinlang.org/lp/mobile/static/multiplatform-mobile-app-wizard-63ba67b440498ffb774bdb0e112b1ce6.svg). Like any programming language provides ability to write code and basic functions (math, data structures, etc), and the other solutions provide everything else (databases, UI frameworks).

"By default", when you use KMM, you write common business logic once and UI for each platform separately, using their native API's and widgets. It has advantage that your application looks fully native, but disadvantage that you have to do the same work twice.

And here Compose Multiplatform can help. It allows you to write UI once. Currently we have a stable release that allows to write cross-platform UI for Desktop, for Web (manipulating DOM elements), and for Android. Android target is developed and supported by Google (it goes by the name `Jetpack Compose`). As for iOS, it is in "work-in-progress" stage.

There is [an experimental example](https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/falling-balls-mpp) that supports Desktop, Android, iOS, and Web Canvas.

Note that support for iOS and Web Canvas is in very experimental stage right now. We have big hopes, but it is early to make any promises.

**Comment by ThraaxSession** [comment]
thank you @igordmn! So I should take a look on Compose platform, if I want to target (mostly) all platforms. :)

**Comment by ThraaxSession** [comment]
@igordmn sorry, I am confused again:
Is this true that I can't use KMP for UI?
https://www.raywenderlich.com/books/kotlin-multiplatform-by-tutorials/v1.0/chapters/1-introduction#toc-chapter-006-anchor-001 (Scroll to bottom)
![image](https://user-images.githubusercontent.com/3085830/195873138-fd6597d5-a19c-4599-a210-36f14803ed6c.png)

**Comment by igordmn** [comment]
KMP by itself doesn't provide any UI solution, and have nothing to do with UI. "By default" you have to use native widgets, if you want UI. But it doesn't mean that solutions on top of KMP can't provide cross-platform UI.

So, if we refer to this tutorial, the more correct sentence would be "KMP doesn't provide UI solution out of the box. You'll need to write UI yourself using native frameworks or any other cross platform UI framework available at the moment". 

As, I said before, Compose Multiplatform provides cross-platform UI solution, but at the moment it is stable only for Desktop, Android and Web DOM. Support for the others targets (iOS, Web Canvas) is experimental right now (you can try them, but I don't recommend to use it in production in the current state).

**Comment by ThraaxSession** [comment]
Thank you very much @igordmn for your patient and explanations. It is clear now. :) I promise!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2397">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
