### ISSUE TITLE
script publishWebComponentsToMavenLocal version not work

### ISSUE THREAD

**Issue by linxuebin1990** [JetBrains/compose-jb#2399]
commit (#2365 ) change `COMPOSE_WEB_VERSION` to  `compose.version` , `COMPOSE_WEB_VERSION` is too.
So, we must change 
```
./gradlew publishToMavenLocal -PCOMPOSE_CORE_VERSION="$COMPOSE_CUSTOM_VERSION" -PCOMPOSE_WEB_VERSION="$COMPOSE_CUSTOM_VERSION" || exit 1
```
to 
```
./gradlew publishToMavenLocal  -Pcompose.version="$COMPOSE_CUSTOM_VERSION" || exit 1
```

in https://github.com/JetBrains/compose-jb/blob/master/compose/scripts/publishWebComponentsToMavenLocal

**Comment by igordmn** [comment]
Thanks for fixing!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2399">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
