### ISSUE TITLE
Implement LazyScrollbarAdapter that works with LazyGridState

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-jb#2401]
Since Compose Multiplatform v1.2 the `LazyVerticalGrid` has a `LazyGridState` instead of a `LazyListState`. To use the `VerticalScrollbar` we need a `LazyScrollbarAdapter` version that takes a `LazyGridState`. We only have a version that works with `LazyListState` so far.

This means that right now the `LazyVerticalGrid` can't have a vertical scrollbar which is unfortunate on desktop environments.

[Here](https://github.com/Suwayomi/Tachidesk-JUI/blob/master/ui-core/src/desktopMain/kotlin/ca/gosyer/jui/uicore/components/DesktopScrollbar.kt#L105) someone implemented a `GridScrollbarAdapter` which is unfortunately broken for `GridCells.Adaptive`, but may serve as a starting point for a implementation.

**Comment by igordmn** [comment]
Thanks for reporting! Yes, we plan to add this adapter.

Let's keep [this issue](https://github.com/JetBrains/compose-jb/issues/2029).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2401">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
