### ISSUE TITLE
Update `compose-multiplatform` project wizard samples to use latest versions.

### ISSUE THREAD

**Issue by sureshg** [JetBrains/compose-jb#2408]
The `Compose-Multiplatform` plugin generated samples are still using the older versions of the plugin and doesn't contain `js` as part of the common module.

**Comment by eymar** [comment]
The wizard is a part of IDEA and therefore it's updated with new IDEA versions. IDEA 2022.3 contains an updated wizard.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2408">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
