### ISSUE TITLE
Remove Effect

### ISSUE THREAD

**Issue by tmxdyf** [JetBrains/compose-jb#2410]
Describe the problem:
Dear Compose developer, I am an ink screen（similar to kindle） APP developer, I hope that the click effect can be removed globally,Because it affects refresh performance, I hope to get your help.

Describe the solution
Remove Effect via Theme?

**Comment by DavideCannizzo** [comment]
@tmxdyf, for your information, the click effect in Compose is called an “indication” and the `LocalIndication` composition local holds an `Indication` object that draws the indication.

I can't test it right now, but you should be able to remove that effect by using an `Indication` object that draws no indication, as follows:
```
CompositionLocalProvider(
    LocalIndication provides NoIndication
) {
    // Contents
}
```

What's left now is the `NoIndication` object. Internally, Compose has a `NoIndication` object that unfortunately is not exposed — you can find it [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/Indication.kt;l=133?q=NoIndication).
You may want to just copy-paste it, for as crappy a solution as it may seem. Luckily it is very short:
```
private object NoIndication : Indication {
    private object NoIndicationInstance : IndicationInstance {
        override fun ContentDrawScope.drawIndication() {
            drawContent()
        }
    }

    @Composable
    override fun rememberUpdatedInstance(interactionSource: InteractionSource): IndicationInstance {
        return NoIndicationInstance
    }
}
```

**Comment by tmxdyf** [comment]
@DavideCannizzo Thank you very much for your kind reply! Good luck.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2410">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
