### ISSUE TITLE
Compose UI test not working on Desktop

### ISSUE THREAD

**Issue by oianmol** [JetBrains/compose-jb#2432]
<img width="504" alt="Screenshot 2022-10-27 at 9 45 04 AM" src="https://user-images.githubusercontent.com/4393101/198189929-c13bc568-4085-4c76-826c-31b56e488631.png">

This is a minimal test and fails with

`Failed to inject mouse input.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'some' (ignoreCase: false))`

**Comment by oianmol** [comment]
This works fine when I Don't wrap the composable with Window 🤷🏻‍♂️

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2432">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
