### ISSUE TITLE
Why Kotlin Desktop has so high memory usage?

### ISSUE THREAD

**Issue by BusyZzZz** [JetBrains/compose-jb#2436]
Why does Kotlin Desktop use so much memory, for example in the standard "Hello World" project ganerated by IDEA?
I tested it only on Windows 10 and use compose version = 1.2.0, kotlin version = 1.7.20 and openjdk-19. I builded it with gradle to .exe app
```kotlin
import androidx.compose.material.MaterialTheme
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("Hello, World!") }

    MaterialTheme {
        Button(onClick = {
            text = "Hello, Desktop!"
        }) {
            Text(text)
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```
![image](https://user-images.githubusercontent.com/90100550/198830384-a1f953a4-6785-425a-b589-4f004134788a.png)
App at start:
![image](https://user-images.githubusercontent.com/90100550/198831018-b0deec55-5b9e-40d7-9c8f-e6c929fbb38d.png)
134Mb
Just clicked the button and draged the window:
![image](https://user-images.githubusercontent.com/90100550/198831458-2b436705-eaae-4adb-b392-d0a8b47276de.png)
234Mb
Am I do something wrong or its just not optimized? 
Seen same issue bellow: https://github.com/JetBrains/compose-jb/issues/1632, but kotlin updated since that time and I was hoping that situation was changed

**Comment by igordmn** [comment]
Let's keep discussion inside a single issue (https://github.com/JetBrains/compose-jb/issues/1632)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2436">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
