### ISSUE TITLE
Compose Web Canvas

### ISSUE THREAD

**Issue by abueide** [JetBrains/compose-jb#2437]
(see here for a reproducible example) https://github.com/abueide/compose-kmm-template

Hello, I'm trying to run my compose application on web with the ComposeTarget canvas. However, I'm trying to resize the size of the canvas to  the size of the viewport whenever it gets resized. Currently the code works when the page  loads, but no matter what I try I can't seem to automatically resize the canvas using the window.onresize function. Here are some pictures of my results:

![image](https://user-images.githubusercontent.com/19354425/198852000-2cb34f12-609d-4bc0-9868-740eb737ee07.png)
(Works perfectly on page load)

![image](https://user-images.githubusercontent.com/19354425/198852025-d16b5806-7be2-43c3-863d-cb094d3d3e5f.png)
(doesn't resize)

it seems the canvas.width and canvas.height resizes but not the canvas.clientwidth or canvas.clientheight. I've also tried updating canvas.style.width and canvas.style.height.

Any suggestions? also is this a known bug? I only see in the examples there are fix-sized canvases

**Comment by mipastgt** [comment]
Is this Compose-Web-Canvas example doing what you want to do? https://www.mpmediasoft.de/test/PolySpiralMpp/
The code can be found here: https://github.com/mipastgt/JavaForumStuttgartTalk2022/tree/main/PolySpiralMpp
It works for me but the performance could be better.

**Comment by abueide** [comment]
@mipastgt thanks for the example that was exactly what I was trying to do!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2437">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
