### ISSUE TITLE
Use AlertDialog title also as window title

### ISSUE THREAD

**Issue by tkuenneth** [JetBrains/compose-jb#244]
Currently the AlertDialog title is part of the content:

![image](https://user-images.githubusercontent.com/13284437/103347867-87471880-4a98-11eb-882b-f2a02b2386aa.png)

This may be quite alright, but the current window title is (IMHO) not useful. Possible alternatives:

- If the window decoration for the AlertDialog is present, the title of the AlertDialog should be the window title
- Make the window title configurable (maybe through a new class `DesktopDialogProperties` which implements `DialogProperties`

**Comment by Rsedaikin** [comment]
Yes, you can configure the window via `DesktopDialogProperties`:
```kotlin
import androidx.compose.ui.window.DesktopDialogProperties

...

val dialogState = remember { mutableStateOf(false) }

...

val dismiss = { dialogState.value = false }
AlertDialog(
    onDismissRequest = dismiss,
    modifier = Modifier.fillMaxSize(),
    confirmButton = {
        Button(text = "Delete", onClick = dismiss)
    },
    text = {
        Text(text = "kotlin-reflect.jar")
    },
    properties = DesktopDialogProperties(title = "Confirm deletion")
)
```

**Comment by tkuenneth** [comment]
Thanks. Sorry that I missed that class. Thought I had searched. Anyway, works as expected. Guess we can close this. Should I do so?

**Comment by Rsedaikin** [comment]
Yes, I think you can close this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5563">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
