### ISSUE TITLE
No updated tutorial with wizard

### ISSUE THREAD

**Issue by abelardolg** [JetBrains/compose-jb#2450]
Hi there,
I installed IntelliJ IDEA 2022.2.3 (Ultimate Edition).
Pictures here showed don't illustrate current windows from IDEA.
Take a look:
![image](https://user-images.githubusercontent.com/22522883/200178414-b5d0f75e-0ad5-41ba-aeec-2dfe53941fe7.png)

Pictures and text should be updated.
Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2450">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
