### ISSUE TITLE
Size of pixels too small in Linux

### ISSUE THREAD

**Issue by eaceto** [JetBrains/compose-jb#2456]
I have created a desktop app using IntelliJ and compose, and when running the recently created app I see it too small. I know my display is 4K, but all the other apps (including Flutter on linux) works ok and their size is correct. But every app, including the sample ones, that run with Compose for Desktop, they all look really small.

Let me know if there is something I can do so you have the correct information in order to fix this error.

![Screenshot from 2022-11-07 19-28-05](https://user-images.githubusercontent.com/870528/200387408-7ae0ea91-a3f4-4800-8bb8-cb75b250da98.png)

Regards.

**Comment by igordmn** [comment]
Follow this [thread](https://github.com/JetBrains/compose-jb/issues/188) for this issue.

> Let me know if there is something I can do so you have the correct information in order to fix this error.

The names and version of the distro and of the window system (X11, Wayland) will be helpful.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2456">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
