### ISSUE TITLE
[macOS] compose.desktop.application.nativeDistributions.packageName only used for menu title, not menu items

### ISSUE THREAD

**Issue by tkuenneth** [JetBrains/compose-jb#246]
When configuring

```kotlin
compose.desktop {
    application {
        mainClass = "com.thomaskuenneth.tkdupefinder.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg,
                    TargetFormat.Msi)
            packageName = "TKDupeFinder"
            version = "0.1-SNAPSHOT"
```

the package name is picked up nicely for the menu title, but not for **About** and **Quit** menu items, as seen in the following screenshot:

![image](https://user-images.githubusercontent.com/13284437/103436110-8b01a900-4c18-11eb-886a-56aa84c21c92.png)

The usual behavior on macOS that the application name (package name) is also used for this two menu items.

**Comment by SaifurRahmanMohsin** [comment]
Is there a way to set this even during debug i.e. not just packaging options? For example, I'm [building this](https://github.com/SaifurRahmanMohsin/Playstation-Notifier) and when I run it on my mac it shows MainKt as the menu bar title.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5561">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
