### ISSUE TITLE
Transparent SwingPanel on Windows

### ISSUE THREAD

**Issue by yaroslavkulinich** [JetBrains/compose-jb#2461]
According to current documentation for [Swing Integration / Layouting with SwingPanel and ComposePanel](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Swing_Integration#layouting-with-swingpanel-and-composepanel) we can overlay Swing components (common cases for maps, video players, etc.) by placing SwingPanel that wraps ComposePanel on top in the Box composable. It works ok if used with care according to the side effects described in the documentation. 
But it has one major problem that was partially mentioned in other issues of this repository that limits developers - transparency of SwingPanel for Windows. 

There is no problem to make transparent SwingPanel overlay wrapping ComposePanel with actual overlay's content on MacOS. But after a big number of experiments with Java LookAndFeel, JPanel.setOpaque() and UIManager, I haven’t found the solution to make SwingPanel transparent on Windows. 

This problem leads to an inability to implement super-basic things like placing FloatingActionButton (or any composable with rounded corners) on top of the Swing Map component (think about the circular "my location" button in GoogleMaps app). 

It limits us to use only RECTANGULAR  NON-TRANSPARENT overlays on Windows. 

It would be great to know the proper ways to achieve transparent SwingPanel on Windows. 
Or maybe someone knows some workarounds?

I think this information would be very helpful for many devs.
Thanks.

**Comment by igordmn** [comment]
Thanks! Let's keep [this issue](https://github.com/JetBrains/compose-jb/issues/1061).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2461">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
