### ISSUE TITLE
Undecorated Dialog

### ISSUE THREAD

**Issue by Elblassy** [JetBrains/compose-jb#247]
I can't make dialog undecorated and disable window until dialog dismiss , i want to make progress dialog

**Comment by tkuenneth** [comment]
Here is a very brief implementation:

![image](https://user-images.githubusercontent.com/13284437/104189576-2665fb80-541b-11eb-9ca0-7e5753baaae7.png)

```kotlin
Dialog(onDismissRequest = {},
    properties = DesktopDialogProperties(
        undecorated = true,
        resizable = false
    )) {
  Box(modifier = Modifier.border(width = 1.dp,
      MaterialTheme.colors.primary),
      contentAlignment = Alignment.Center
  ) {
    CircularProgressIndicator(modifier = Modifier.padding(8.dp))
  }
}
```

You need to add some code to close the dialog.

**Comment by Elblassy** [comment]
Thank you 🖤

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5560">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
