### ISSUE TITLE
Package msi 

### ISSUE THREAD

**Issue by Elblassy** [JetBrains/compose-jb#248]
In last version of "0.3.0-build138" get error when build package msi it said 
"Illegal char <	> at index 42"

**Comment by Fabian-K** [comment]
I have the same issue using 0.3.0-build139 with a project that builds fine on mac os.

C:\Repositories\t2-interceptor>gradlew :ui:packageExe

```
> Task :ui:createRuntimeImage FAILED
untime Illegal char <   > at index 14: C:Repositories   2-interceptoruibuildcompose     mpmain

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ui:createRuntimeImage'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot\bin\jlink.exe'' finished with non-zero exit value 1
```

**Comment by gbaldeck** [comment]
I'm experiencing the same issue on Windows. Were either of you able to resolve it?

**Comment by Elblassy** [comment]
I didn't solve it ,i think it's very early to work with this library , so i convert to flutter desktop, if you don't need any connection with any external hardware like printer it will be good choice

**Comment by gbaldeck** [comment]
Look like build 136 works. I reverted to that for now.

**Comment by ghasem-79** [comment]
I have the same issue in last version of "0.3.0-build140" 

Illegal char <	> at index 36: D:KotlinProjectsSubtitlebuildcompose	mpmain
untime

Execution failed for task ':createRuntimeImage'.
> Process 'command 'C:\Program Files\Java\jdk-15.0.1\bin\jlink.exe'' finished with non-zero exit value 1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5559">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
