### ISSUE TITLE
Does compose-ios support webp?

### ISSUE THREAD

**Issue by ltttttttttttt** [JetBrains/compose-jb#2480]
Recently, we are working on a kmp project, which is compatible with Android and Desktop. However, we have a problem with images. We want to use webp format, but we are afraid that ios does not support webp format images. We want to ask, will the subsequent addition of painterResource() in ios support webp?

**Comment by eymar** [comment]
It looks like ios 14+ supports webp - https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/3551599-webp

So I think it should be supported with compose as well at some point (please, keep in mind: the compose-ios is still experimental).

**Comment by ltttttttttttt** [comment]
Thanks for your reply, then we will use png temporarily

**Comment by dima-avdeev-jb** [comment]
@ltttttttttttt Comming soon: 
https://github.com/JetBrains/compose-jb/pull/2483#discussion_r1028004043

**Comment by ltttttttttttt** [comment]
@dima-avdeev-jb Does it support versions below IOS 14?

**Comment by dima-avdeev-jb** [comment]
I am not tested yet, but I think the answer is no.

**Comment by dima-avdeev-jb** [comment]
Will be supported after this PR for iOS 14+
https://github.com/JetBrains/compose-jb/pull/2483#discussion_r1028004043
