### ISSUE TITLE
trayState.sendNotification invalid, in macOS 13

### ISSUE THREAD

**Issue by ltttttttttttt** [JetBrains/compose-jb#2489]
trayState.sendNotification invalid, in macOS 13

system version:macOS 13.0.1 (22A400) M1
compose version:1.2.1 and 1.3.0-beta03

But it is available in Win11 and Win10

**Comment by ltttttttttttt** [comment]
Try the version 1.3.0-alpha01-dev862 is not available too

github: https://github.com/ltttttttttttt/TestSendNotification

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2489">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
