### ISSUE TITLE
SVG/XML Vector on IOS/Web

### ISSUE THREAD

**Issue by abueide** [JetBrains/compose-jb#2498]
Is it possible to render an svg or xml vector on ios/web platforms?

**Comment by dima-avdeev-jb** [comment]
On stable Compose for Web, you may use DOM elements.
For iOS and Web with Canvas (experimental), it's not possible to render **svg** or Android like **xml** for now.
Soon it will be possible to render png and jpg

**Comment by abueide** [comment]
@dima-avdeev-jb ah okay, I was asking about ios and web with canvas. I'm able to render png icons with icons using makeFromEncoded, but was just wondering if there was any plans for svg's. I'm totally down to try and contribute support for it, let me know if you have any advice on how I might get started.

**Comment by dima-avdeev-jb** [comment]
We plan to add some vector graphics support on all platforms. Android does not support SVG without additional libraries.
XML vector may be a good solution. We have some code to parse XML vector on desktop here: https://github.com/JetBrains/androidx/blob/c894a470e1d0e2cf5f0a2208f046173163043359/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/res/vector/DesktopXmlVectorParser.desktop.kt#L72

Also, this is a good multiplatform library to parse xml structure: https://github.com/pdvrieze/xmlutil

Maybe in the future we will add XML vector graphics support to all platforms

**Comment by dhng22** [comment]
@dima-avdeev-jb So future plan might able all platform to render android xml vector right?

**Comment by dima-avdeev-jb** [comment]
> @dima-avdeev-jb So future plan might able all platform to render android xml vector right?

@dhng22 
Yes!
