### ISSUE TITLE
Need to render decoded video data, have control support?

### ISSUE THREAD

**Issue by daocaoren123** [JetBrains/compose-jb#2499]

**Comment by dima-avdeev-jb** [comment]
You can look at the experimental library here:
https://github.com/JetBrains/compose-jb/tree/master/experimental/components/VideoPlayer

**Comment by daocaoren123** [comment]
> 你可以在这里查看实验库： [https ://github.com/JetBrains/compose-jb/tree/master/experimental/components/VideoPlayer](https://github.com/JetBrains/compose-jb/tree/master/experimental/components/VideoPlayer)

Thank you for your advice. I have seen this example before, but my data is decoded in yuv format and I hope it can be rendered like opengl. At present, I have no specific strategy

**Comment by dima-avdeev-jb** [comment]
Sorry, but for now, we do not plan to add addition feature to support video playback.
You can use Swing interop to add specific video components.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2499">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
