### ISSUE TITLE
Breaks suspend usages of function.reflect

### ISSUE THREAD

**Issue by jeggy** [JetBrains/compose-jb#250]
When building a compose application it breaks all suspend usages of https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect.jvm/reflect.html

To reproduce:
1. Create a compose desktop application using the intellij wizard
2. add `implementation(kotlin("reflect"))` to your build.gradle
3. call reflect. Example below

```kotlin
fun <T> returnTypeString(fn: suspend () -> T): String {
    return fn.reflect()?.returnType?.toString() ?: "Failed to find return type"
}
fun main() {
    returnTypeString { "Hello" }.let(::println)
}
```

If I remove these lines from my build.gradle:
1. `id("org.jetbrains.compose") version "0.2.0-build132"`
2. `implementation(compose.desktop.currentOs)`

and re-run the application it will work as expected.

**Comment by olonho** [comment]
Yep, can reproduce this issue, investigating.

**Comment by olonho** [comment]
Unfortunately, it's Kotlin compiler limitation, see https://youtrack.jetbrains.com/issue/KT-40467, and cannot be fixed on Compose side.

**Comment by olonho** [comment]
But `.reflect` is generally an experimental API, which may not work in many cases. Maybe you could work it around by putting reflection code into separate module not using Compose compiler plugin.

**Comment by jeggy** [comment]
Hi @olonho. Thanks for you investigation 👍

**Comment by olonho** [comment]
Create issue in Google's tracker: https://partnerissuetracker.corp.google.com/u/1/issues/177340919

**Comment by zach-klippenstein** [comment]
@olonho That link is not publicly visible, is there a way to make it so?

**Comment by jeggy** [comment]
@zach-klippenstein I found a way to get access to it: https://issuetracker.google.com/issues/177340919

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5557">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
