### ISSUE TITLE
can't build examples (PKIX path validation failed)

### ISSUE THREAD

**Issue by wiiznokes** [JetBrains/compose-jb#2504]
I have this issues for a lot of .jar files.
```
Could not download dokka-core-1.4.32.jar (org.jetbrains.dokka:dokka-core:1.4.32)
      > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/dokka/dokka-core/1.4.32/dokka-core-1.4.32.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/dokka/dokka-core/1.4.32/dokka-core-1.4.32.jar'.
            > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```
I tried to build [todoapp](examples/todoapp) and [todoapp-lite](examples/todoapp-lite) and got this error on both.

I think this error is because https://jcenter.bintray.com has closed recently and should not be use but I can't see any link to it in build gradle files.

And I think this issue #2199 report the same problem.

**Comment by dima-avdeev-jb** [comment]
Thanks!
We will check it!

**Comment by dima-avdeev-jb** [comment]
@wiiznokes
Are you running Desktop JVM application?

**Comment by dima-avdeev-jb** [comment]
For now, samples work's good.
Can you please try to:
 - clone repository https://github.com/JetBrains/compose-jb from scratch
 - move to dir examples/todoapp-lite
 - run this gradle command: ./gradlew desktop:run --refresh-dependencies
 
Also, you may have custom gradle configuration in directory USER_HOME/.gradle/...
Like in file gradle.properties, or other gradle files. You may try to delete the whole .gradle directory and try again. (But in this case, all cached dependencies will be deleted)

**Comment by wiiznokes** [comment]
I don't know why but I was able to build the project today. Also I just cloned the example folder, that must be why it was buggy at first.
Thank you anyway.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2504">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
