### ISSUE TITLE
Shape property of AlertDialog doesn't work

### ISSUE THREAD

**Issue by Houvven** [JetBrains/compose-jb#2506]
![image](https://user-images.githubusercontent.com/74887628/204182707-cd9ac7ed-e5dc-440c-8051-3486d3a6e151.png)

**Comment by dima-avdeev-jb** [comment]
Same issue here: https://github.com/JetBrains/compose-jb/issues/1705

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2506">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
