### ISSUE TITLE
`SwingPanel` throws NPE on focus request if nothing focusable

### ISSUE THREAD

**Issue by jasonsparc** [JetBrains/compose-jb#2512]
**Kotlin:** 1.7.20
**Compose:** 1.2.1

If there's no component focusable inside a `SwingPanel` and you try to request focus to it via, e.g., tabbing, it'll crash the application.

Try the following sample code,

```kotlin
import androidx.compose.foundation.layout.*
import androidx.compose.material.OutlinedTextField
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.awt.SwingPanel
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication
import javax.swing.JPanel

fun main() = singleWindowApplication {
    val letsSetItToFocusable = false
    Column(
        modifier = Modifier.padding(50.dp).fillMaxSize(),
        verticalArrangement = Arrangement.spacedBy(8.dp),
    ) {
        SomethingToFocusOn()
        SwingPanel(
            factory = {
                JPanel().apply {
                    if (letsSetItToFocusable) isFocusable = true
                }
            },
            modifier = Modifier.fillMaxWidth().height(40.dp),
        )
        SomethingToFocusOn()
    }
}

@Composable
fun SomethingToFocusOn() {
    val text = remember { mutableStateOf("") }
    OutlinedTextField(value = text.value, onValueChange = { text.value = it }, singleLine = true, label = {
        Text("Try tab to switch focus")
    })
}
```

Outcome:

![Capture](https://user-images.githubusercontent.com/2899129/204340874-c4a73794-e29c-401c-b3d2-6bcf731c8839.PNG)

Relevant stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Component.requestFocus(java.awt.event.FocusEvent$Cause)" because the return value of "java.awt.FocusTraversalPolicy.getFirstComponent(java.awt.Container)" is null
	at androidx.compose.ui.awt.FocusSwitcher$Content$1.invoke(SwingPanel.desktop.kt:191)
	at androidx.compose.ui.awt.FocusSwitcher$Content$1.invoke(SwingPanel.desktop.kt:186)
	at androidx.compose.ui.focus.FocusChangedModifierKt$onFocusChanged$2$1.invoke(FocusChangedModifier.kt:47)
	at androidx.compose.ui.focus.FocusChangedModifierKt$onFocusChanged$2$1.invoke(FocusChangedModifier.kt:44)
	at androidx.compose.ui.focus.FocusEventModifierLocal.propagateFocusEvent(FocusEventModifier.kt:137)
	at androidx.compose.ui.focus.FocusTransactionsKt.sendOnFocusEvent(FocusTransactions.kt:279)
	at androidx.compose.ui.focus.FocusModifier.setFocusState(FocusModifier.kt:79)
	...
```

---

Now, in the above sample code, set `letsSetItToFocusable = true` instead, and it won't crash anymore. That's because the `SwingPanel` now has a focusable component.

Digging into the source code of `SwingPanel`, I found the following lines to be problematic:

```
info.container.focusTraversalPolicy
    .getFirstComponent(info.container)
    .requestFocus(FocusEvent.Cause.TRAVERSAL_FORWARD)
```

https://github.com/JetBrains/androidx/blob/release/1.2.1/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/SwingPanel.desktop.kt#L190

```
info.container.focusTraversalPolicy
    .getLastComponent(info.container)
    .requestFocus(FocusEvent.Cause.TRAVERSAL_FORWARD)
```

https://github.com/JetBrains/androidx/blob/release/1.2.1/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/SwingPanel.desktop.kt#L203

The problem is, both `getFirstComponent(…)` and `getLastComponent(…)` of the `FocusTraversalPolicy` interface are allowed to return `null`, and yet the kotlin code is treating it that it won't. This was confirmed via a debugger, and also if you use the IDE to look for implementations of the  `FocusTraversalPolicy` interface, you will find that it may indeed return null when no swing component is focusable.

**Suggestion:** Honor the nullability of those methods, and perhaps simply skip over the `SwingPanel` if it has no focusable components when looking for components to focus to.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2512">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
