### ISSUE TITLE
ModalDrawer does not prevent tab navigation in background

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-jb#2513]
See this example code:

```kotlin
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.DrawerValue
import androidx.compose.material.ModalDrawer
import androidx.compose.material.Text
import androidx.compose.material.TextButton
import androidx.compose.material.rememberDrawerState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.WindowState
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication(WindowState(size = DpSize(300.dp,100.dp))) {
    val drawerState = rememberDrawerState(DrawerValue.Open)
    ModalDrawer(
        drawerState = drawerState,
        drawerContent = {
            TextButton(onClick = {}) {
                Text("Focusable as expected")
            }
        }
    ) {
        Box(Modifier.fillMaxSize()) {
            TextButton(onClick = {}, modifier = Modifier.align(Alignment.TopEnd)) {
                Text("Should not be focusable")
            }
        }
    }
}
```

Mouse interaction with the items in the background is prevented, but keyboard interaction (via Tab navigation and, e.g., Enter to click) is not:

![image](https://user-images.githubusercontent.com/18088991/204348305-c7b7d54d-e8cc-4b9a-b263-4a80fb2a932c.png)

I guess this might not be limited to Compose for Desktop, since focus management is not platform specific from what I could tell from the source code. In case it also affects Jetpack Compose, I'm not sure where to raise the issue.

Also, I didn't find any way to conveniently disable all interaction (including tab navigation) of some composable including its children. Using `Modifier.focusProperties { canFocus = false }` on the first child in `content` did disable focus reception for some children, but not for all.

**Comment by dima-avdeev-jb** [comment]
Hello!
Do you test it on Linux?
Which Distro?

**Comment by ialokim** [comment]
Yes, this is Debian/Linux.

**Comment by dima-avdeev-jb** [comment]
It reproduces also on MacOS

**Comment by ialokim** [comment]
While we're at it, I strongly suspect this will affect accessibility services as well, e.g., VoiceOver on macOS. So it will probably not be enough the look into focus management, but also into a11y management (which also includes texts etc.).

**Comment by dima-avdeev-jb** [comment]
Also, add reproducer to GitHub:
https://github.com/dima-avdeev-jb/desktop-background-focus

**Comment by ialokim** [comment]
I was just able to reproduce the same bug on Android 12 (emulator) with the following code and using the tab-key on my computer keyboard. I strongly suspect this would also happen with an external keyboard connected to a real Android device, e.g., via Bluetooth:

```kotlin
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import com.example.composetest.ui.theme.ComposeTestTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ComposeTestTheme {
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    ComposeTest()
                }
            }
        }
    }
}

@Composable
fun ComposeTest() {
    val drawerState = rememberDrawerState(DrawerValue.Open)
    ModalDrawer(
        drawerState = drawerState,
        drawerContent = {
            TextButton(onClick = {}) {
                Text("Focusable as expected")
            }
        }
    ) {
        Box(Modifier.fillMaxSize()) {
            TextButton(onClick = {}, modifier = Modifier.align(Alignment.TopEnd)) {
                Text("Should not be focusable")
            }
        }
    }
}

@Preview(showBackground = true)
@Composable
fun DefaultPreview() {
    ComposeTestTheme {
        ComposeTest()
    }
}
```

![image](https://user-images.githubusercontent.com/18088991/206171180-1b953506-406b-4fb2-9f51-263a15f6e2dc.png)

Where should this be reported?

**Comment by dima-avdeev-jb** [comment]
@ialokim here Android bug tracker: https://partnerissuetracker.corp.google.com/issues?q=Android%2F

**Comment by dima-avdeev-jb** [comment]
It's an Android Compose related problem.
@ialokim After creating Issue on Android bug tracker, can you please also add a link here.

**Comment by ialokim** [comment]
Reported upstream: https://issuetracker.google.com/261572786

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2513">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
