### ISSUE TITLE
Compose Web 1.2.1 regression: unexpected recompositions

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#2539]
Originally reported in compose-web slack: https://slack-chats.kotlinlang.org/t/8070137/this-may-be-bigger-than-compose-for-web-but-i-m-noticing-tha

> This may be bigger than compose for web, but I'm noticing that starting in 1.2.1, that I'm getting recompositions that I shouldn't for methods which take a parameter from a library module. This seems like a huge regression, so I'm guessing it's already a KI?

> Basically, the behavior looks like this:
> sealed interface Justification {
>   object Left : Justification
>   object Center: Justification
>   object Right: Justification
> }
> 
```kotlin
@Composable
fun SpanText(text: String, just: Justification) {
     println("SpanText recomposed")
     // Use justification etc.
     Span { Text(text) }
 }
 ```
> If Justification is defined in the app module itself, it's fine. But if included from a library module, the println will get triggered every time.

> It was working in 1.2.0 as well

> If I annotate the class with `@Immutable` then the recompositions stop happening. But I shouldn't have to do that.

[recomposes-too-often-bug.zip](https://github.com/JetBrains/compose-jb/files/10164769/recomposes-too-often-bug.zip)

**Comment by eymar** [comment]
It's likely related to update from kotlin/js 1.7.10 to kotlin/js 1.7.20 (the compiler plugin didn't consider inferred  `@Immutable` from dependency modules)

**Comment by eymar** [comment]
Hey @bitspittle,
we published a new build of compose compiler plugin you may want to try with kotlin 1.7.20.

```kotlin
// in your build.gradle.kts
compose {
    kotlinCompilerPlugin.set("1.3.2.2-beta01")
}
```

The issue should be gone.

**Comment by eymar** [comment]
Hey @bitspittle,
we published a new build of compose compiler plugin you may want to try with kotlin 1.7.20.

```kotlin
// in your build.gradle.kts
compose {
    kotlinCompilerPlugin.set("1.3.2.2-beta01")
}
```

The issue should be gone.

**Comment by bitspittle** [comment]
Did this miss [the 1.2.2 release](https://github.com/JetBrains/compose-jb/releases/tag/v1.2.2)?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2539">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
