### ISSUE TITLE
Unknown Error Mac M1 Desktop Distribution

### ISSUE THREAD

**Issue by mehmetakify** [JetBrains/compose-jb#2551]
I can use run/runDistributable commands to start application without any error, but when I try to use packageDmg/packageReleaseDmg, although dmg file is successfully created, app gives unknown error after trying to install and run the app.

<img width="260" alt="Ekran Resmi 2022-12-09 07 40 40" src="https://user-images.githubusercontent.com/25617832/206625387-ea636f1c-7273-4a0d-a63a-ea246f77dd90.png">

Kotlin Version: 1.7.20
Compose Version: 1.2.1

Extra Information: I use Realm LocalDatabase, I couldn't realize any problem about realm but maybe it causes the problem.

**Comment by AlexeyTsvetkov** [comment]
@mehmetakify do I understand correctly, that the app installs, but does not run? 
If so, can you try to run the installed app in the command-line, and share the output?

```
/Applications/<PACKAGE_NAME>.app/Contents/MacOS/<PACKAGE_NAME>
```

**Comment by mehmetakify** [comment]
No app runs correctly but I couldnt create working dmg file with packageDmg. It creates a dmg file but it doesnt work

**Comment by mehmetakify** [comment]
I didnt know this method to check error more deeply. After try your advise I found the error. Opening Realm db file causes the error because of the lack of read/write permission. Thank you!

**Comment by ltttttttttttt** [comment]
Can Windows get the crash log? My computer can't reproduce the crash, but the customer's Windows will crash

**Comment by Kevin-Case** [comment]
I'm using SqlDelight with KMM project. The packaged app fails with the same error when start the application from generated *.app file (packageDMG). But if I start the app from Contents/MacOs/ it works. If I configure SqlDelight to use IN_MEMORY it works fine. It seems an issue with write permissions of the starting process.

**Comment by Taoaozw** [comment]
i can run  well with ` /Applications/<PACKAGE_NAME>.app/Contents/MacOS/<PACKAGE_NAME>` , but use applicaiton startup not working  when i use web request

**Comment by Taoaozw** [comment]
> @mehmetakify do I understand correctly, that the app installs, but does not run? If so, can you try to run the installed app in the command-line, and share the output?
> 
> ```
> /Applications/<PACKAGE_NAME>.app/Contents/MacOS/<PACKAGE_NAME>
> ```

if use /Applications/<PACKAGE_NAME>.app/Contents/MacOS/<PACKAGE_NAME> startup is well, but use application startup cant work well,and if i use web request, it will report unkown error, how can i get the log to check the error

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2551">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by BBOYGF** [comment]
Because of your resource path problem, please reset the relative path, I just solved the same problem as you
