### ISSUE TITLE
This Project is so big!

### ISSUE THREAD

**Issue by Hynsn** [JetBrains/compose-jb#2558]
This Project is so big! do we have plan to split it fair?

**Comment by igordmn** [comment]
No plans to split

**Comment by igordmn** [comment]
If you talk about not the repository itself, but about different pieces of Compose Multiplatform library, then it is already split. You can use only part of Compose, if don't need other parts.

Compose Runtime - if you need to manipulate state or compositions
Compose UI (depends on Runtime) - if you only need integration with platforms (to be able to use native windows and draw on them)
Compose Foundation - if you need basic tools to create UI's - layouts, gestures, effects, text
Compose Material - implementation of Material design system that contains opinionated widgets (Checkbox, Button, etc)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2558">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
