### ISSUE TITLE
TodoAppLite build failed

### ISSUE THREAD

**Issue by Hynsn** [JetBrains/compose-jb#2565]
CompileSwift normal arm64 /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/iosApp/iosApp/iosApp.swift (in target 'TodoAppLite' from project 'TodoAppLite')
    cd /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/iosApp
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -c -primary-file /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/iosApp/iosApp/iosApp.swift -emit-dependencies-path /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/Objects-normal/arm64/iosApp.d -emit-reference-dependencies-path /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/Objects-normal/arm64/iosApp.swiftdeps -serialize-diagnostics-path /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/Objects-normal/arm64/iosApp.dia -target arm64-apple-ios14.1 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk -I /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/Debug-iphoneos -F /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/Debug-iphoneos -F /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/shared/build/cocoapods/framework -no-color-diagnostics -enable-testing -g -module-cache-path /Users/hynson/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -serialize-debugging-options -enable-bare-slash-regex -empty-abi-descriptor -Xcc -working-directory -Xcc /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/iosApp -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/TodoAppLite-generated-files.hmap -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/TodoAppLite-own-target-headers.hmap -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/TodoAppLite-all-target-headers.hmap -Xcc -iquote -Xcc /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/TodoAppLite-project-headers.hmap -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/Debug-iphoneos/include -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/DerivedSources-normal/arm64 -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/DerivedSources/arm64 -Xcc -I/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/DerivedSources -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -module-name TodoAppLite -frontend-parseable-output -disable-clang-spi -target-sdk-version 16.1 -parse-as-library -o /Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/build/ios/TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/Objects-normal/arm64/iosApp.o -index-unit-output-path /TodoAppLite.build/Debug-iphoneos/TodoAppLite.build/Objects-normal/arm64/iosApp.o -index-store-path /Users/hynson/Library/Developer/Xcode/DerivedData/TodoAppLite-emnlkjiianqeskaamuaetkncpeks/Index.noindex/DataStore -index-system-modules
/Users/hynson/AndroidStudioProjects/compose-jb/experimental/examples/todoapp-lite/iosApp/iosApp/iosApp.swift:10:34: error: cannot find 'Main_iosKt' in scope
        let mainViewController = Main_iosKt.MainViewController()
                                 ^~~~~~~~~~

SwiftDriverJobDiscovery normal arm64 Emitting module for TodoAppLite (in target 'TodoAppLite' from project 'TodoAppLite')

**Comment by pjBooms** [comment]
Hello, we have made some changes in the project. Can you check again on a clean clone?

**Comment by Hynsn** [comment]
> Hello, we have made some changes in the project. Can you check again on a clean clone?

Hi, it fixed, I should run it on AndroidStudio ,and than build on Xcode.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2565">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
