### ISSUE TITLE
LAF of Intellij Idea gets modified due to ComposePanel usage

### ISSUE THREAD

**Issue by CeH9** [JetBrains/compose-jb#258]
Before:
![image](https://user-images.githubusercontent.com/7687412/104023829-e577a800-51ca-11eb-9ac0-5d5948b08d1e.png)

After:
![image](https://user-images.githubusercontent.com/7687412/104023850-ee687980-51ca-11eb-952a-4ec9ccc0337a.png)

Sample to reproduce: https://github.com/CeH9/IntellijPluginOnCompose/blob/main/src/main/kotlin/com/github/ceh9/intellijpluginoncompose/main/ShowComposeDialogAction.kt

Issue already discussed in telegram: https://t.me/compose_mpp/1061

**Comment by kirill-grouchnikov** [comment]
As good a place as any to start discussing a way for Compose Desktop to *not* force the system look-and-feel somewhere in Skiko

**Comment by olonho** [comment]
Yeah, it seems like the right thing to do.

**Comment by olonho** [comment]
Fixed with https://github.com/JetBrains/skiko/commit/b5864536c30d6e4ebeb27a7a8f22a3a210e2d0ce

**Comment by akurasov** [comment]
@CeH9 does the issue still exist after the skiko fix?

**Comment by CeH9** [comment]
> @CeH9 does the issue still exist after the skiko fix?
It works, well done.

0.3.0-build139 - reproduced.
0.5.0-build245 - not reproduced.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5553">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
