### ISSUE TITLE
Use kotlinx.serialization in Compose Desktop app

### ISSUE THREAD

**Issue by yantlord** [JetBrains/compose-jb#2583]
I have configured everything according to the docs, and the project builds, but my IDE (IDEA) is giving me this error when I use the Serializable annotation:

> This class does not have a constructor
> Cannot access 'Serializable': it is internal in 'kotlin.io'

Please advise, I need to digest JSON in my app

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2583">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
