### ISSUE TITLE
ExperimentalUnpackSkikoWasmRuntimeTask Gradle Configuration cache compatibility

### ISSUE THREAD

**Issue by aSemy** [JetBrains/compose-jb#2587]
When I run `./gradlew jsBrowserDevelopmentWebpack` I get errors relating to [Gradle Configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) in my console output

```none
7 problems were found storing the configuration cache, 2 of which seem unique.
- Task `:site2:unpackSkikoWasmRuntimeJs` of type `org.jetbrains.compose.experimental.web.tasks.ExperimentalUnpackSkikoWasmRuntimeTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:unpackSkikoWasmRuntimeJs` of type `org.jetbrains.compose.experimental.web.tasks.ExperimentalUnpackSkikoWasmRuntimeTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

> A task must not use any Project objects at execution time. This includes calling `Task.getProject()` while the task is running.

However, `ExperimentalUnpackSkikoWasmRuntimeTask` does use `Task.getProject()` during the execution phase:

https://github.com/JetBrains/compose-jb/blob/d6ff80c062e43395923d6da8c59b395c17c8478b/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/experimental/web/tasks/ExperimentalUnpackSkikoWasmRuntimeTask.kt#L26-L27

https://github.com/JetBrains/compose-jb/blob/d6ff80c062e43395923d6da8c59b395c17c8478b/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/experimental/web/tasks/ExperimentalUnpackSkikoWasmRuntimeTask.kt#L40-L41

https://github.com/JetBrains/compose-jb/blob/d6ff80c062e43395923d6da8c59b395c17c8478b/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/experimental/web/tasks/ExperimentalUnpackSkikoWasmRuntimeTask.kt#L46

https://github.com/JetBrains/compose-jb/blob/d6ff80c062e43395923d6da8c59b395c17c8478b/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/experimental/web/tasks/ExperimentalUnpackSkikoWasmRuntimeTask.kt#L47

Some of these usages [have drop-in replacements](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution)

<img width="740" alt="image" src="https://user-images.githubusercontent.com/897017/210182476-7806f3b8-7bc5-4432-816b-bf4cd07f60a0.png">

Fixing the use of `project.configurations` is slightly more tricky. The Gradle docs give examples:

* https://docs.gradle.org/7.6/userguide/more_about_tasks.html#sec:task_input_using_dependency_resolution_results
* https://docs.gradle.org/7.6/samples/sample_tasks_with_dependency_resolution_result_inputs.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2587">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
