### ISSUE TITLE
examples/web-landing: FormattedCodeSnippet incompatible with newer versions of highlight.js

### ISSUE THREAD

**Issue by aSemy** [JetBrains/compose-jb#2597]
### Summary

When I try and format a code snippet, following the example code in [examples/web-landing](https://github.com/JetBrains/compose-jb/tree/v1.2.2/examples/web-landing), the raw string content is not produced.

For example, this code

```kotlin
@Composable
fun example() {
  P {
    Code {
     FormattedCodeSnippet("""
       blah1

       blah2

       blah3
     """.trimIndent())
    }
  }
}
```

will produce something like 

```html
<pre>
  <code>
    "blah1"
    <br>
    "blah2"
    <br>
    "blah3"
  </code>
<pre>
```

I expect that it produces the raw string, exactly:

```html
<pre>
  <code>
    blah1

    blah2

    blah3
  </code>
<pre>
```

### Outcome

Because the text is formatted, highlight.js cannot format it properly

Example: 

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/897017/210448628-b68b65a0-5ab9-4d63-ae88-1f1e65a24810.png">

Also, highlight.js logs a lot of warnings in the console:

```
One of your code blocks includes unescaped HTML. This is a potentially serious security risk.
https://github.com/highlightjs/highlight.js/wiki/security
```

### Proposal

The formatting takes place in this function

https://github.com/JetBrains/compose-jb/blob/1a7d74461f3008c7440b04c788e54e64c126985b/examples/web-landing/src/jsMain/kotlin/com/sample/content/CodeSnippets.kt#L12-L15

Instead of using `innerText`, `textContent` should be used instead https://stackoverflow.com/a/35213639/4161471

<img width="521" alt="image" src="https://user-images.githubusercontent.com/897017/210448791-9c25b4f9-d7fb-4779-8a5d-f5936dcec050.png">

Much better!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2597">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
