### ISSUE TITLE
Scrolling doesn't work if cursor is over TextField

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#26]
1. Run ./gradlew compose:desktop:desktop:desktop-samples:run1

2. Move cursor over TextField

3. Try to scroll with mouse wheel

**Comment by zacharee** [comment]
Setting `singleLine = true` fixes scrolling, but that only works if you can use a single-line TextField.

**Comment by atoktoto** [comment]
Is there any other workaround? `singleLine = true` will not work for me.

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta6-dev474

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6214">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
