### ISSUE TITLE
Can't include files in the final package

### ISSUE THREAD

**Issue by wiiznokes** [JetBrains/compose-jb#2618]
I'm trying to include some files in the final package.
I added this line in my gradle file `fromFiles(project.fileTree("include/"))`.

This is the structure of the project: 

![include 2](https://user-images.githubusercontent.com/78230769/211516942-e36a99ba-4650-4894-b414-ea8bdb33ce8e.png)

But when I look in the package, there is no such files.
I'm doing that on Windows, with the version 1.2.0.
And this is the [repo](https://github.com/wiiznokes/IncludeDemoTest) I made to test that.

**Comment by AlexeyTsvetkov** [comment]
@wiiznokes `fromFiles` is not designed as a generic assets/resources API. It was added just in case you need to include jar files from unusual place. To include images, configuration files or other data, please take look at the relevant section in the docs https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution#adding-files-to-packaged-application

**Comment by wiiznokes** [comment]
@AlexeyTsvetkov Thanks, I finally used `appResourcesRootDir.set(project.layout.projectDirectory.dir("include"))`.
But I have another problem, I want to add a folder to java library path witch is in include directory. So I use `jvmArgs += listOf("-Djava.library.path=include/windows/app")`, but this is not the real path when I package the app.

**Comment by AlexeyTsvetkov** [comment]
@wiiznokes why do you need to add `java.library.path`?
AFAIK, `java.library.path` is only needed for searching libraries like `System.loadLibrary("mylib.dll")`. However, it should be possible to load the library directly by full path like:
```
// assuming the library is located at include/windows/app/mylib.dll

import java.io.File

val resourcesDir = File(System.getProperty("compose.application.resources.dir"))

fun main() {
    System.load(resourcesDir.resolve("app/mylib.dll"))
}
```

**Comment by wiiznokes** [comment]
@AlexeyTsvetkov Yes, you're right, I don't need `java.library.path`. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2618">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
