### ISSUE TITLE
Windows version looks blurry

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-jb#2622]
Edit: Nevermind.

I needed to use hinted fonts and better align my images to fit the grid.

Seemingly no special Compose problem.

**Comment by serrg1994** [comment]
If it's a laptop, from which vendor it is ?

**Comment by StefanOltmann** [comment]
> If it's a laptop, from which vendor it is ?

For Windows it's a PC with RTX 2080 graphics card and 27" WQHD Monitor, which results in 108 ppi.

Of course I don't expect the crisp view I have with 227 ppi on my MacBook M1 Air, but it should be close to the level as other apps.

If it was just the text I would say it related to the missing ClearText support mentioned in #875, but that does not explain the blurry icons.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2622">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
