### ISSUE TITLE
Tab is printed as unknown glyph

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#2626]
OS: win11 (haven't tested on MacOs yet)
Compose: 1.3.0-rc02, 1.2.2, 1.0.0
Example: https://github.com/JetBrains/compose-jb/tree/master/examples/notepad

![Screenshot 2023-01-12 115451](https://user-images.githubusercontent.com/7372778/212049332-971b809d-cd7c-4b03-8939-9b8d527aaa85.png)

Perhaps, it's related to default fonts. (?)

**Comment by m-sasha** [comment]
On Mac OS X (Ventura 13.1) TAB shows similarly to a SPACE.

<img width="106" alt="image" src="https://user-images.githubusercontent.com/5230206/212723561-eab284b2-b15b-4f2c-9c8a-11b5681bc45d.png">

**Comment by igordmn** [comment]
Let's keep [this issue](https://github.com/JetBrains/compose-jb/issues/615) in our tracker.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2626">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
