### ISSUE TITLE
supportingText slot missing in TextField MaterialApi3

### ISSUE THREAD

**Issue by TonicArtos** [JetBrains/compose-jb#2632]
I was porting a form to jetbrains compose and noticed the slot 
```supportingText: (@Composable () -> Unit)?,```
is missing from the mpp implementation of material3

**Comment by pjBooms** [comment]
What version of jetbrains compose do you use?
`supportingText` was added to compose 1.3 that is not released by JetBrains yet.

**Comment by TonicArtos** [comment]
Ah. I am using jbcompose 1.2.2 and porting from jetpack compose 1.6. Just a toy thing to try things out.

I checked the version numbers before posting and saw Material3 v1.0.0 is the version that got the slots added. I thought it was in jbcompose 1.2.2.

Is there a doc that has the jetbrains -> jetpack compose version support? E.g. jbcompose v1.2.2 has; XYZ v1.2, ABC v1.0, etc...

**Comment by esafak** [comment]
> Is there a doc that has the jetbrains -> jetpack compose version support? E.g. jbcompose v1.2.2 has; XYZ v1.2, ABC v1.0, etc...

The [CHANGELOG](https://github.com/JetBrains/compose-jb/blob/master/CHANGELOG.md#dependencies) has those: 

> This version of Compose Multiplatform is based on the next Jetpack Compose libraries:

[Compiler 1.3.2](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.3.2)
[Runtime 1.2.1](https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.2.1)
[UI 1.2.1](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.2.1)
[Foundation 1.2.1](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.2.1)
[Material 1.2.1](https://developer.android.com/jetpack/androidx/releases/compose-material#1.2.1)
[Material3 1.0.0-alpha14](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.0.0-alpha14)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2632">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
