### ISSUE TITLE
Unable to use default @Composable function arguments 

### ISSUE THREAD

**Issue by Queatz** [JetBrains/compose-jb#2637]
I have a simple loading indicator and want to supply an optional argument, however then the build fails:

```
Module "<module>" has a reference to symbol components/Loading$composable|-3628430242021199886[0]. Neither the module itself nor its dependencies contain such declaration.

This could happen if the required dependency is missing in the project. Or if there is a dependency of "day.gooddaybad:ui" that has a different version in the project than the version that "<module>" was initially compiled with. Please check that the project configuration is correct and has consistent versions of all required dependencies.
```

My function:

```
@Composable
fun Loading(onBackground: Boolean = false) {
    // ...
}
```

**Comment by pjBooms** [comment]
May you send a reproducible example?

Usually we have such problems for public composables in a shared module natively compiled to a static library.  The fix was declaring such a composable as internal.

**Comment by Queatz** [comment]
@pjBooms 

Here is the line I had to change. I can see if I can reproduce it in an isolated project if needed.

https://github.com/Queatz/GoodDayBadDayUI/blob/main/src/jsMain/kotlin/components/PromptPackPage.kt#L117

The `fun` could be internal/private to this file, I can try doing that and see what happens.

**Comment by Queatz** [comment]
Here is the [code](https://github.com/Queatz/GoodDayBadDayUI/blob/main/src/jsMain/kotlin/components/Components.kt#L53).  I can try to repro it in an isolated project if needed. This project has no modules, it's fairly small.

**Comment by mykytaknyzevkiy** [comment]
Hello, @Queatz. Kotlin native cannot build "@Compose" annotation to a static library, so just set your compose function as internal.

For example 

```
@Composable
internal fun Loading(onBackground: Boolean = false) {
    // ...
}
```

**Comment by Queatz** [comment]
@pjBooms maybe we can call this out in the docs. 

@mykytaknyzevkiy is there a reason it works without the argument being default?

**Comment by mykytaknyzevkiy** [comment]
@Queatz Yes, currently Kotlin C interop couldn`t read "@Compose" translate to c, so when you make this function internal, that means you can use it inside your Kotlin library but not outside, is you want to create "Multi-platform" screens for example for IOS, you have to run compose in "native.Application" class that could be public and uses outside

**Comment by Queatz** [comment]
Ah, so basically it wouldn't work with no arguments either.  I will close this, maybe for compose-jb we can call it out somewhere or update the error message.

**Comment by mykytaknyzevkiy** [comment]
@Queatz If u create a function without "Compose" annotation that function couldn`t be used as compose

**Comment by Queatz** [comment]
@mykytaknyzevkiy Right, my curiosity was just that:

```
@Composable
internal fun Loading(onBackground: Boolean) {
    // ...
}
```

was compiling okay.

**Comment by mykytaknyzevkiy** [comment]
@Queatz OK. It was a pleasure to help you. Good luck to you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2637">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
