### ISSUE TITLE
TypeError: n is not a function

### ISSUE THREAD

**Issue by Queatz** [JetBrains/compose-jb#2638]
I have the following function:

```kotlin
@Composable
fun PersonName(name: String, color: String) {
    Span({
        style {
            fontWeight("bold")
            color(Color(color))
            property("border-bottom", "2px solid $color")
        }
    }) {
        Text("Person $name")
    }
}
```

When running with `jsBrowserRun` everything is okay.  However when deployed, I am getting an error:

```
TypeError: n is not a function
```

It's hard to tell exactly where it's coming from, but the line it highlights is `fontWeight("bold")`

**Comment by Queatz** [comment]
replacing `color(Color(color))` with `property("color", color)` fixes this error.  FWIW the value of `color` in my case is `#c582da`

**Comment by pjBooms** [comment]
We need a reproducible example with detailed steps to reproduce to deal with this.

**Comment by eymar** [comment]
I tried to reproduce the issue in your project, but it works fine.

The code:
```kotlin
@Composable
fun PersonName(name: String, color: String) {
    B({
        style {
            color(Color(color))
            property("border-bottom", "2px solid $color")
        }
    }) {
        Text("Person $name")
    }
}
```

![Screenshot 2023-01-19 143031](https://user-images.githubusercontent.com/7372778/213455458-b39f1b00-1d16-477c-97b0-dab3dc717c84.png)


Can you reproduce it constantly, or only with some extra steps/conditions?

**Comment by eymar** [comment]
What also helps is changing the name of a parameter:

```kotlin
fun PersonName(name: String, color: String) {
```
to

```kotlin
fun PersonName(name: String, textColor: String) {
```

It's rather a bug in k/js - it gets confused by the same of an extension function `fun StyleScope.color` and the parameter name `color` (which a minifed in release build to `n`)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2638">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
