### ISSUE TITLE
KeysSet

### ISSUE THREAD

**Issue by jakode2020** [JetBrains/compose-jb#265]
In the last version of "0.3.0-build140" keysSet dos'nt work with operator "+" or "plus"

> AppWindow(...).also {
>            it.keyboard.setShortcut(Key.CtrlLeft.plus(Key.A)) { ... }
>        }.show {
>            ....
>        }

**Comment by prepor** [comment]
Did you import `androidx.compose.ui.input.key.plus`?

**Comment by prepor** [comment]
or define "doesn't work" in more details, please

**Comment by ghasem-79** [comment]
yes i'm import that but it just work on one key not key set

**Comment by olonho** [comment]
By "does not work" you mean that after pressing the key handler is not invoked, or you see some kind of exception? Please provide a reproducer.

**Comment by ghasem-79** [comment]
Infact when i use shortcut, key handler is not invoked

**Comment by prepor** [comment]
Yes, it's regression, fix will be soon. Thank you for reporting.

**Comment by prepor** [comment]
@jakode2020 could you please try it with 0.3.0-build143? Please, feel free to reopen this issue if the problem is still here

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5548">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
