### ISSUE TITLE
FileChooser in Jetpack Compose for Dextop 

### ISSUE THREAD

**Issue by etiennept** [JetBrains/compose-jb#266]
May you  make  a  compose function which has the same goal then   [filechooser](https://docs.oracle.com/en/java/javase/15/docs/api/java.desktop/javax/swing/filechooser/package-summary.htmll)

**Comment by olonho** [comment]
Why cannot you just use regular file chooser from AWT/Swing?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5547">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
