### ISSUE TITLE
TextField causes instant crash on Android

### ISSUE THREAD

**Issue by thennothinghappened** [JetBrains/compose-jb#2661]
I had a look around and found the [issue report for this on Jetpack's side](https://issuetracker.google.com/issues/265172081), moving to the latest alpha of material3 fixed it there, but that isn't available here - I tried moving to `1.3.0-rc05` to see if it'd be fixed there but that doesn't seem to be the case.
[crash.log](https://github.com/JetBrains/compose-jb/files/10486171/crash.log)

**Comment by thennothinghappened** [comment]
I should've looked a bit more on the issues page here, workaround on #2176 fixes this

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2661">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
