### ISSUE TITLE
VideoPlayer component local file support

### ISSUE THREAD

**Issue by jarvis1801** [JetBrains/compose-jb#2665]

**Comment by mahozad** [comment]
I think it's possible to play local videos with the URL syntax.

Here is my example video player (which also has some basic controls):  
https://github.com/mahozad/compose-video-player/tree/vlcj/src/main/kotlin

**Comment by dima-avdeev-jb** [comment]
@jarvis1801 
Do you mean this experimental component?
https://github.com/JetBrains/compose-jb/blob/b9b9e3438b520a5d0d58c295286e9d38d2a8506d/experimental/components/VideoPlayer/demo/src/jvmMain/kotlin/org/jetbrains/compose/videoplayer/demo/Main.kt#L16

**Comment by jarvis1801** [comment]
As mahozad said, the video player support local file as I tested yesterday.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2665">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
