### ISSUE TITLE
Click works outside of Button

### ISSUE THREAD

**Issue by lbensaad** [JetBrains/compose-jb#267]
For my first try with Compose Desktop, I tested your tutorial on my Ubuntu 20.04.1 and GNOME 3.36.3
`fun main() = Window(title = "Compose for Desktop", size = IntSize(300, 300)) {
    val count = remember { mutableStateOf(0) }
    MaterialTheme {
        Column(Modifier.fillMaxSize(), Arrangement.spacedBy(5.dp)) {
            Button(modifier = Modifier.align(Alignment.CenterHorizontally),
                   onClick = {
                       count.value++
                   }) {
                Text(if (count.value == 0) "Hello World" else "Clicked ${count.value}!")
            }
            Button(modifier = Modifier.align(Alignment.CenterHorizontally),
                   onClick = {
                       count.value = 0
                    }) {
                Text("Reset")
            }
        }
    }
}`

I see there are two issues:
1) Buttons don't show on the window , only part of the second button is visible. They start to show only when I reduce the height of the window.
2) The click on both buttons is offset, if you click on the upper half of the button it does nothing, clicking on the bottom part of the button works. Clicking below the button (under it and outside of it) also works and increments/reset the counter.

**Comment by kirill-grouchnikov** [comment]
What is the version of Compose Desktop you're using? Along with OS and Java versions.

**Comment by olonho** [comment]
Please provide more information about your graphical hardware (GPU and monitor). Also provide screenshots and vide of how it looks like.

**Comment by lbensaad** [comment]
I cannot reproduce it now because I am having this issue #279. When it is solved I will come back here with a video

**Comment by lbensaad** [comment]
OS: Ubuntu 20.04.1 LTS ; 5.4.0-58-generic 64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 GNU/Linux
GNOME: 3.36.3
Kotlin: 1.4.21
Compose Desktop: 0.3.0-build140
JDK: openjdk version "11.0.8"
GPU: GeForce GT 540M
NVIDA Driver: 390.138

A video showing the problem is attached here:
https://user-images.githubusercontent.com/2950904/104813035-c7cbc380-5806-11eb-98db-9bafa7e9d037.mp4

**Comment by igordmn** [comment]
Probably should be fixed soon.

Can you check if the issue still exists on 0.0.0-vsync-build30?

**Comment by lbensaad** [comment]
Thanks @igordmn I confirm the issue does not exists in 0.0.0-vsync-build30. It is fixed

**Comment by igordmn** [comment]
Should be fixed in 0.3.0-build146.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5546">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
