### ISSUE TITLE
Is there an example application similar to WinUI3 Gallery, or like Element-ui;Ant-Design

### ISSUE THREAD

**Issue by Doinng** [JetBrains/compose-jb#2678]

**Comment by dima-avdeev-jb** [comment]
All samples you can find here: https://github.com/JetBrains/compose-jb/tree/master/examples.
We have widgets-gallery sample with a set of UI elements: https://github.com/JetBrains/compose-jb/tree/master/examples/widgets-gallery

Also, you can look at Android specific examples and code snippets here: https://foso.github.io/Jetpack-Compose-Playground/material/card/. Most of them are the same like you can do in Compose for Desktop (or multiplatform).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2678">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
