### ISSUE TITLE
retrofit get stuck

### ISSUE THREAD

**Issue by s949492225** [JetBrains/compose-jb#268]
i use retrofit/okhttp3
if it run on idea,it work fine,
bug package exe or dmg,open it will get stuck.

i fire retrofit on Thread,and callback on awt javax.swing.SwingUtilities.invokeLater

this is my key code:
![image](https://user-images.githubusercontent.com/7496283/104401591-75cd3880-558f-11eb-9cd0-0bd38dbd8f88.png)
![image](https://user-images.githubusercontent.com/7496283/104401628-8b426280-558f-11eb-9280-46e8ddd2d6b4.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5545">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
