### ISSUE TITLE
jdk unsafe error appearing after the binary build run, not while direct running

### ISSUE THREAD

**Issue by electrodragon** [JetBrains/compose-jb#2686]
When in IntelliJIdea i run the app directly by main() function, it works smooth. But when i created its binary with followings

`./gradlew package` 
`./gradlew packageAppImage`
`./gradlew packageDistributionForCurrentOS`

The result is same, the binary can't run directly, it throws the following error, here is the terminal output.

**[attaullah@attaullah-hpelitebook840g5 xlr8]$** `./gradlew packageDistributionForCurrentOS`

&gt; Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

BUILD SUCCESSFUL in 779ms
7 actionable tasks: 7 up-to-date
**[attaullah@attaullah-hpelitebook840g5 xlr8]$** `./build/compose/binaries/main/app/xlr8/bin/xlr8 `
pure virtual method called
terminate called without an active exception
java.lang.RuntimeException: Unable to create instance of class activities.directory_picker.models.Disks. Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:373)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:427)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:383)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.Gson.fromJson(Gson.java:1227)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.Gson.fromJson(Gson.java:1137)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.Gson.fromJson(Gson.java:1047)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.Gson.fromJson(Gson.java:982)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.composables.DrawerKt$Drawer$1$8.invoke(Drawer.kt:132)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.composables.DrawerKt$Drawer$1$8.invoke(Drawer.kt:131)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at libs.ShellProcess.exec(ShellProcess.kt:96)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.composables.DrawerKt.Drawer(Drawer.kt:131)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.layout.DirectoryPickerActivityKt$DirectoryPickerActivity$1.invoke(DirectoryPickerActivity.kt:126)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.layout.DirectoryPickerActivityKt$DirectoryPickerActivity$1.invoke(DirectoryPickerActivity.kt:61)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at composables.Xlr8AppThemeKt.Xlr8AppTheme(Xlr8AppTheme.kt:41)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.layout.DirectoryPickerActivityKt.DirectoryPickerActivity(DirectoryPickerActivity.kt:59)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at ComposableSingletons$IndexKt$lambda-1$1.invoke(Index.kt:43)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at ComposableSingletons$IndexKt$lambda-1$1.invoke(Index.kt:31)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2618)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3148)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:746)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:414)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:326)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:325)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:87)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:325)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:510)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:113)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.security.AccessController.doPrivileged(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class activities.directory_picker.models.Disks. Usage of JDK sun.misc.Unsafe is enabled, but it could not be used. Make sure your runtime is configured correctly.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:117)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:370)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;... 60 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.composables.DrawerKt.Drawer(Drawer.kt:135)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.layout.DirectoryPickerActivityKt$DirectoryPickerActivity$1.invoke(DirectoryPickerActivity.kt:126)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.layout.DirectoryPickerActivityKt$DirectoryPickerActivity$1.invoke(DirectoryPickerActivity.kt:61)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at composables.Xlr8AppThemeKt.Xlr8AppTheme(Xlr8AppTheme.kt:41)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at activities.directory_picker.layout.DirectoryPickerActivityKt.DirectoryPickerActivity(DirectoryPickerActivity.kt:59)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at ComposableSingletons$IndexKt$lambda-1$1.invoke(Index.kt:43)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at ComposableSingletons$IndexKt$lambda-1$1.invoke(Index.kt:31)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2618)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3148)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:746)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:414)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:326)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:325)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:109)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:87)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:325)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:510)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:113)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.security.AccessController.doPrivileged(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@4151d2f5, androidx.compose.runtime.BroadcastFrameClock@703bfb56, StandaloneCoroutine{Cancelling}@70478b9f, FlushCoroutineDispatcher@3c94d92e]

**Comment by PPeanutButter** [comment]
same:
```
java.lang.RuntimeException: Unable to invoke no-args constructor for class gson.Album. Register an InstanceCreator with Gson for this type may fix this problem.
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:206)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class gson.Album
        at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:100)
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
        ... 11 more
```

**Comment by electrodragon** [comment]
Finally solved by adding `jdk.unsupported` module in `build.gradle.kts`

```gradle
compose.desktop {
    application {
        mainClass = "IndexKt"
        nativeDistributions {
            targetFormats(TargetFormat.AppImage)
            packageName = "xlr8"
            packageVersion = "1.0.0"
            modules("jdk.unsupported")
        }
    }
}

```
Thanks to [Vahe Gharibyan for solution](https://stackoverflow.com/questions/61727613/unexpected-behaviour-from-gson)

**Comment by paulocoutinhox** [comment]
> Finally solved by adding `jdk.unsupported` module in `build.gradle.kts`
> 
> ```groovy-gradle
> compose.desktop {
>     application {
>         mainClass = "IndexKt"
>         nativeDistributions {
>             targetFormats(TargetFormat.AppImage)
>             packageName = "xlr8"
>             packageVersion = "1.0.0"
>             modules("jdk.unsupported")
>         }
>     }
> }
> ```
> 
> Thanks to [Vahe Gharibyan for solution](https://stackoverflow.com/questions/61727613/unexpected-behaviour-from-gson)

Only to thanks a lot.

**Comment by adriantache** [comment]
> ```groovy-gradle
>             modules("jdk.unsupported")
> ```

You're a lifesaver, I've been trying to work with Kotlin Multiplatform and for whatever reason the DataStore implementation just wouldn't work on Windows without this...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2686">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
