### ISSUE TITLE
BasicTextField should expose internal scroll data

### ISSUE THREAD

**Issue by Wavesonics** [JetBrains/compose-jb#2689]
#1492 points out some of the problems with adding our own `verticalScroll` modifier to a `TextField`

While doing this gives us access to the data we need to draw a scrollbar, it also breaks some of the internal scrolling logic.

The key thing that appears to break is when you are drag-selecting text, and try to scroll the `TextField` by dragging past the view bounds.

With no `verticalScroll` modifier the `TextField` responds as expected, scrolling the view port and continuing to select text. When you add your own `verticalScroll` modifier it no longer scrolls as you drag past the bounds of the view.

This could all be solved I think if `CoreTextField`s `TextFieldScrollerPosition` was exposed as a argument for state hoisting. Then we could provide that our selves, and use it's data to draw scrollbars, and no have to override or mess with modifiers at all.

**Comment by m-sasha** [comment]
We've implemented scrollbar support for `BasicTextField` in https://github.com/JetBrains/androidx/pull/384

**Comment by Wavesonics** [comment]
that's great news @m-sasha ! Did this make it into 1.3.0?

**Comment by m-sasha** [comment]
Unfortunately no. It'll probably be out in 1.4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2689">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
