### ISSUE TITLE
retrofit or okhttp get stuck

### ISSUE THREAD

**Issue by s949492225** [JetBrains/compose-jb#269]
i use retrofit/okhttp3
if it run on idea,it work fine,
bug package exe or dmg,open it will get stuck.

i fire retrofit on Thread,and callback on awt javax.swing.SwingUtilities.invokeLater

this is my key code:
![image](https://user-images.githubusercontent.com/7496283/104401591-75cd3880-558f-11eb-9cd0-0bd38dbd8f88.png)
![image](https://user-images.githubusercontent.com/7496283/104401628-8b426280-558f-11eb-9280-46e8ddd2d6b4.png)

**Comment by s949492225** [comment]
it get stuck on button click and click will fire retrofit call

**Comment by s949492225** [comment]
All version have this bug,you can try it

**Comment by kirill-grouchnikov** [comment]
This will probably need to be rewritten using coroutines instead. And screenshots with code are better replaced with the code itself, ideally something that is small and standalone so that it can be debugged.

**Comment by s949492225** [comment]
Coroutines or Thread shouldn't matter,
Debug is ok,But package release is not work ,
Deubg and Release may be something different.

**Comment by s949492225** [comment]
This is a simple demo to test.

`import androidx.compose.desktop.Window
import androidx.compose.material.Text
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import okhttp3.*
import java.io.IOException
import java.nio.charset.StandardCharsets

fun main() = Window {
    var text by remember { mutableStateOf("request url") }

    MaterialTheme {
        Button(onClick = {
            val client = OkHttpClient()
            val request = Request.Builder()
                .url("http://www.github.com")
                .build()
            client.newCall(request).enqueue(object : Callback {
                override fun onFailure(call: Call, e: IOException) {
                }

                override fun onResponse(call: Call, response: Response) {
                    text = String(response.body!!.bytes(), StandardCharsets.UTF_8)
                }
            })

        }) {
            Text(text)
        }
    }
}`

**Comment by s949492225** [comment]
Release will get stuck

**Comment by s949492225** [comment]
You can try to make it work fine,Maybe I have a problem with it

**Comment by olonho** [comment]
Please try to log, if exception is thrown, it could be result of some library not included into native library.

**Comment by s949492225** [comment]
Just get stuck,no log,no exception.

**Comment by AlexeyTsvetkov** [comment]
@s949492225 could you try adding `modules("jdk.crypto.ec")` to the `nativeDistributions` block? Does it help?

```
compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            modules("jdk.crypto.ec")

            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "untitled"
        }
    }
}
```

**Comment by s949492225** [comment]
no,not work

**Comment by olonho** [comment]
Without additional info it's hard to debug this issue.

**Comment by s949492225** [comment]
demo is here,just try it

**Comment by AlexeyTsvetkov** [comment]
I am not able to reproduce the issue with:
* the sample above;
* Compose Desktop `0.3.0` build;
* `modules("jdk.crypto.ec")` added;

@s949492225 I've created a repo with the sample, can you try it to see if the issue still reproduces?
https://github.com/AlexeyTsvetkov/compose-okhttp-issue-sample

**Comment by s949492225** [comment]
Compose Desktop 0.3.0 work fine;
Thanks @AlexeyTsvetkov;

**Comment by ovitrif** [comment]
Doesn't work for me, even with `modules("jdk.crypto.ec")` which is probably no longer needed in version `1.1.0`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5544">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
