### ISSUE TITLE
Horizontal Scrollable doesn't work on Linux

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-jb#2690]
Horizontal Scrollable (LazyRow, Row with Vertical Scrollable) doesn't work anyway

**Comment by eymar** [comment]
Could you please share a reprodicible example? Your OS version, Compose Version, Kotlin version?

**Comment by GazimSoliev** [comment]
> Could you please share a reprodicible example? Your OS version, Compose Version, Kotlin version?



OS:
6.1.9-1-MANJARO

Gradle properties:
```
kotlin.code.style=official
kotlin.version=1.8.0
agp.version=7.3.0
compose.version=1.3.0
```

Example Code:
```
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
@Preview
fun App() {
    MaterialTheme {
        Surface(modifier = Modifier.fillMaxSize()) {
            LazyRow(horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                items(5) {
                    Box(Modifier.fillMaxHeight().width(200.dp).background(Color.Red))
                }
            }
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

I tried to scroll using computer mouse wheel and touchpad, but useless it, that's problem also in Row with horizontalScrollable Modifier
![image](https://user-images.githubusercontent.com/63443274/216789898-83bcc568-6050-4d25-a8a2-a704baf7cf5f.png)

**Comment by m-sasha** [comment]
Does it work if you hold SHIFT while using the scroll wheel?

**Comment by GazimSoliev** [comment]
Oh, I haven't thought about it, yes, it works if i'll hold shift and scroll wheel, I'm sorry for this situation, Thank You so much

**Comment by GazimSoliev** [comment]
That's done

**Comment by m-sasha** [comment]
I'm not sure that's the correct behavior. Maybe it should scroll without SHIFT as well, as long as there's no vertical scrolling.
We'll discuss it internally.

**Comment by igordmn** [comment]
There was the same issue https://github.com/JetBrains/compose-jb/issues/2528.

Let's close this one, and continue discussion there.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2690">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
