### ISSUE TITLE
Classes from dependent libraries cannot be used in a CommonMain module

### ISSUE THREAD

**Issue by deanssss** [JetBrains/compose-jb#270]
I added some dependencies in the Common module `build.gradle.kts`, like the following:

```
...
kotlin {
    android()
    jvm("desktop")

    sourceSets {
        named("commonMain") {
            dependencies {
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material)

                implementation("io.reactivex.rxjava2:rxkotlin:2.3.0")
                implementation("com.squareup.retrofit2:retrofit:2.7.1")
                implementation("com.squareup.retrofit2:converter-gson:2.7.1")
                implementation("com.squareup.retrofit2:adapter-rxjava2:2.7.1")
                implementation("com.squareup.okhttp3:logging-interceptor:4.4.0")
                implementation("com.squareup.okhttp3:okhttp:4.4.0")
            }
        }
        named("androidMain") {
            dependencies {
                api("androidx.appcompat:appcompat:1.1.0")
                api("androidx.core:core-ktx:1.3.1")
            }
        }
    }
}
...
```
However, I couldn't use them in my code, and the IDEA says unresolved reference in the project. even the classes in java standard library are not available.

![image](https://user-images.githubusercontent.com/15843306/104430881-39ff9680-55c2-11eb-9305-69a3964d8956.png)

**Comment by olonho** [comment]
Libraries you mention are not common code in Kotlin Multiplatform sense, remember that MPP is common between JVM, JS and Native. See https://github.com/JetBrains/compose-jb/blob/db3dd2af64d22e7c3e6068c8cd81a9ef966f115e/examples/issues/common/build.gradle.kts#L24 as one of possible ways of working around the problem.

**Comment by deanssss** [comment]
According to the description, Multiplatform Compose project is available for JVM/Windows, JVM/Linux, JVM/MacOS and Android, all of which are based on JVM. Why can't we share the libraries above? Does that mean the Multiplatform Compose project will support other platforms such as JS or Native in the future?

**Comment by StefanOltmann** [comment]
I'm surprised that even a Compose Library like https://github.com/vanpra/compose-material-dialogs can't be used in common code. Can someone point out what exactly needs to be changed to make that usable with jb-compose? I would create a ticket there if I knew.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5543">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
