### ISSUE TITLE
How do you package an upgrade package

### ISSUE THREAD

**Issue by Doinng** [JetBrains/compose-jb#2700]
When I installed msi for the second time, the system said it could not be installed and asked me to uninstall the previous version first

**Comment by Doinng** [comment]
I forgot to update the version

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2700">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
