### ISSUE TITLE
Fix `pack to Compose content` test

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#2714]
**Describe the bug**

Not sure, but maybe it fails after https://github.com/JetBrains/androidx/pull/388

https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_Publish_2_AllGitHubRelease/4074124?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.4-alpha01

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2714">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
