### ISSUE TITLE
App won't run with custom entitlements.plist

### ISSUE THREAD

**Issue by mazmar** [JetBrains/compose-jb#2715]
**Describe the bug**
Following the notatization sample I needed to make custom entitlements file to get access into Library/Preferences

I've added this to the end of `<dict>`

```
    <key>com.apple.security.files.library-folder.read-write</key>
    <true/>
    <key>com.apple.security.files.preferences.read-write</key>
    <true/>
```

running app via runDistributable will result in a crash:
> Process 'command '...'' finished with non-zero exit value 1

I've tried notarizing the app with success but even after notarization the app will not start with errr: The application “....app” can’t be opened.

I've removed the key/true from the entitlements only to discover that it behaves the same. Now the entitlements are exactly same as on the tutorial and result is the same, app cannot be started

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2715">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
