### ISSUE TITLE
Using AndroidX Compose specific dependencies for Android target

### ISSUE THREAD

**Issue by audkar** [JetBrains/compose-jb#272]
#### Current problem
Can't use Android target specific Compose libraries (like [Navigation](https://developer.android.com/jetpack/androidx/releases/navigation) or [Paging](https://developer.android.com/jetpack/androidx/releases/paging)) when using compose-jb dependencies in same project (MPP with desktop and android targets).

e.g. adding android target specific dependency `implementation("androidx.navigation:navigation-compose:1.0.0-alpha05")`
fails with:
```
Execution failed for task ':android-app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.compose.animation.core.AndroidAnimationClockKt found in modules animation-core-1.0.0-alpha10-runtime (androidx.compose.animation:animation-core:1.0.0-alpha10) and animation-core-debug-runtime (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build138)
<...>
```

#### Reasoning
Google and community will create more AndroidX Compose specific libraries. Having possibility to use them in android target is mandatory in long term.

#### Short term
It's becoming quite challenging to have real-word MPP project with with both targets. We are forced to choose between having shared code or using existing libraries. Maybe it would be possible to clone at-least official AndroidX compose libraries (navigation/paging) into compose-jb project?

**Comment by olonho** [comment]
This is indeed a legitimate issue, which could be worked around by using `exclude(group = "androidx.compose")` inside problematic dependencies, but generally we're aiming at having consolidated publications.

**Comment by igordmn** [comment]
For now, we can exclude all androidx.compose dependencies from the project:

```
configurations {
    "implementation" {
        exclude(group = "androidx.compose.animation")
        exclude(group = "androidx.compose.foundation")
        exclude(group = "androidx.compose.material")
        exclude(group = "androidx.compose.runtime")
        exclude(group = "androidx.compose.ui")
    }
}
```
It is not ideal, but should work. We'll figure out something better in the future.

**Comment by audkar** [comment]
My concern is that implementations can missmatch and cause runtime problems. Knowing how fast code is changing atm I see high possibility of such case happening.

**Comment by igordmn** [comment]
>My concern is that implementations can missmatch and cause runtime problems. 
Yes, there is a problem. In many cases it can be resolved just using the latest version of `org.jetbrains.compose`.

P.S. There is also an issue if we use pure androidx.compose project. Different versions of third-party libraries can use incompatible compose versions.

**Comment by audkar** [comment]
> Different versions of third-party libraries can use incompatible compose versions.

That's true for pre-compiled Compose code in library. But runtime compose dependency versions are aligned by Gradle. Using `exclude` removes that safety.

Anyway I think we all understand current early development state. Just wanted to register this issue to have track of this particular problem.

**Comment by Chozzle** [comment]
Is there a way we can see which androidx compose version each desktop build depends on?

**Comment by igordmn** [comment]
> Is there a way we can see which androidx compose version each desktop build depends on?

Currently it isn't simple. You can compare dates of androidx and jetbrains versions:
https://mvnrepository.com/artifact/androidx.compose.ui/ui
https://github.com/JetBrains/compose-jb/tags

Each version is built from the latest androidx-main (https://android.googlesource.com/platform/frameworks/support)

P.S. you can track https://github.com/JetBrains/compose-jb/issues/116 for this feature

**Comment by igordmn** [comment]
Will be fixed in the next release.

Plugin will automatically choose JetBrains version if there are two libraries in the classpath (`androidx.compose` and `org.jetbrains.compose`).

**Comment by thebino** [comment]
When will this "next release" be? Looks like, there where a new release last week ;)

**Comment by igordmn** [comment]
This was released many weeks ago :), near Feb 20, in weekly build 0.4.0-build171.

In stable 0.4.0 this is defenetely fixed. You can use androidx libraries in android target.

There can be an error that says that you use incompatible version, but that can also happened when you use Jetpack (androidx) Compose.

**Comment by thebino** [comment]
I just released a [sample multiplatform app](https://github.com/thebino/trivia) using the latest 0.4.0 where the android build is still failing. Would you mind having a look and point me what I'm doing wrong?

**Comment by igordmn** [comment]
Your `app` module doesn't use "org.jetbrains.compose" plugin, so it can't pick "org.jetbrains.compose" versions of libraries for you. You can use a workaround in https://github.com/JetBrains/compose-jb/issues/272#issuecomment-760731693 or use `org.jetbrains` compose in your app module (apply plugin and replace all `androidx...1.0.0-beta07` libraries by jb ones).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5541">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
