### ISSUE TITLE
Can't disable pop-up keyboard in whole app on Android for BasicTextField

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-jb#2724]
How to disable pop-up keyboard in Android, I tried to do it for 2 hours and useless (through manifest and activity), I'm making calculator and I don't need system pop-up keyboard, but I need BasicTextField component due to cursor.

**Comment by pjBooms** [comment]
Hum. Can't you disable popup when a physical keyboard attached?

**Comment by GazimSoliev** [comment]
> Hum. Can't you disable popup when a physical keyboard attached?

Sure, I wanna disable popup physical keyboard in android BasicTextField to keyboard won't pop up when I click on BasicTextField, but I haven't found this parameter in function

**Comment by pjBooms** [comment]
It seems to be unrelated to Compose Multiplatform. 
Though using my Google skills I found:

1. Disable virtual keyboard as system wide setting: https://support.honeywellaidc.com/s/article/CN51-Android-How-to-prevent-virtual-keyboard-from-popping-up 

2. Disable programmatically:
https://stackoverflow.com/questions/1109022/how-to-close-hide-the-android-soft-keyboard-programmatically#:~:text=You%20can%20force%20Android%20to,window%20containing%20your%20focused%20view.&text=This%20will%20force%20the%20keyboard%20to%20be%20hidden%20in%20all%20situations.
