### ISSUE TITLE
Can't find installed deb inside app launcher

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-jb#274]
I've packaged a `deb` file and installed it in my system. I tried to find the program through the app launcher, but couldn't find it. I think it's because the program doesn't contain an icon. It'd be better If the template program can have an icon too for Linux.

```groovy
linux {
    iconFile.set(iconsRoot.resolve("logo.png"))
}
```

or It's not the reason?

**Comment by olonho** [comment]
Not sure if this question relates to Compose for Desktop, it mostly question to how apps are managed in your desktop manager.

**Comment by theapache64** [comment]
I am using `Ubuntu 16.04`.

**Comment by olonho** [comment]
@AlexeyTsvetkov is it still reproducible?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-274">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
