### ISSUE TITLE
White line on the bottom in window on Windows 11

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-jb#2742]
**Describe the bug**
Always white line on the bottom in window, when I set fillMaxSize and have any background expect white.
I haven't this bug on Linux.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.8.0
- Compose Multiplatform version*: 1.3.0
- OS version(s)* (required for Desktop and iOS issues): Windows 11 Pro for Workstations 22H2 (22621.1105)
- OS architecture (x86 or arm64): x86-64
- JDK (for desktop issues): 19.0.2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Have the same OS and Compose version
2. Paste this code:
```
fun main() {
    application {
        Window(onCloseRequest = ::exitApplication, title = "Test") {
            Box(modifier = Modifier.background(Color.Red).fillMaxSize())
        }
    }
}
```
4. Run it
5. Check bottom of window:
![image](https://user-images.githubusercontent.com/63443274/218571153-7ad2d23b-2bd0-4d22-854d-7219eb9888a8.png)

**Comment by igordmn** [comment]
Thanks! Let's keep [this issue](https://github.com/JetBrains/compose-jb/issues/555)
