### ISSUE TITLE
FileDialog on Gnome 43.2 does not apply setFilenameFilter

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-jb#2746]
**Describe the bug**
Setting setFilenameFilter for FileDialog is never applied.

**Affected platforms**
Select one of the platforms below:
- Desktop (Gnome 43.2 on debian testing)

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0
- OS version(s)* (required for Desktop and iOS issues): debian testing
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): temurin 17.0.6

**To Reproduce**
```
 val dialog = FileDialog(ComposeWindow()).apply {
                        isVisible = true
                        setFilenameFilter { _, name ->
                            name.endsWith(".png") // is never called
                        }
                    }
```

**Expected behavior**
setFileNameFilter should filter files in the file dialog.

**Comment by adrientetar** [comment]
I think this is a Swing issue that filename filter was never implemented on some platforms: https://bugs.openjdk.org/browse/JDK-4031440
I don't think this is an issue with Compose.

**Comment by igordmn** [comment]
`FileDialog` is not a part of Compose Multiplatform. You should create an issue in [the OpenJDK bug tracker](https://bugs.openjdk.org/secure/Dashboard.jspa).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2746">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
