### ISSUE TITLE
could not run new project desktop

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#276]
![image](https://user-images.githubusercontent.com/23566361/104697287-7b22b280-574a-11eb-98f6-c6ca402f2cd3.png)
![image](https://user-images.githubusercontent.com/23566361/104697340-968dbd80-574a-11eb-8c7f-e4caab2b0340.png)
![image](https://user-images.githubusercontent.com/23566361/104697410-adccab00-574a-11eb-8245-b59526a81c9a.png)

and the demo also:
![image](https://user-images.githubusercontent.com/23566361/104697484-c9d04c80-574a-11eb-8f2b-b3c7c135f889.png)

**Comment by olonho** [comment]
Please run using Gradle's run task.
![image](https://user-images.githubusercontent.com/2600522/104698330-4569d380-5722-11eb-92fc-bcd871dd224e.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5538">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
