### ISSUE TITLE
TextField is missing basic features: DEL, selection, navigation, clipboard, singleLine

### ISSUE THREAD

**Issue by eekboom** [JetBrains/compose-jb#277]
I was taking Compose for Desktop for a test drive.
Because our apps are pretty form-heavy, a TextField was one of the first things I tried.
For now it is *very* alpha. These basic thing do not work:

- DELETE key handling. This is one of the things that I really hate on mobile. On the desktop I just expect it to work.
- Navigation to the beginning/end with POS1/END
- Word-wise navigation using CTRL-LEFT/RIGHT
- Text selection by holding down SHIFT and using navigation (so both SHIFT-POS1 and SHIFT-LEFT should work for example)
- Select all by CTRL-A
- Clipboard support.  On Windows please also implement the alternative shortcuts (Copy = CTRL-INS, Paste = SHIFT-INS and Cut = SHIFT-DEL)
- "singleLine = true" does not really work. Currently it only makes the text field visually "single line". I can still press ENTER, but then the caret and the rest of the text gets invisible.

Of course the shortcuts appropriate for the current system/OS should be used.

I tested both with

```
    var value by savedInstanceState(saver = TextFieldValue.Saver) { TextFieldValue() }
    TextField(
        value = value,
        onValueChange = { value = it },
        singleLine = true
    )
```
and
```
    var text by remember { mutableStateOf("") }
    TextField(
        value = text,
        onValueChange = { text = it }
    )
```
and the behaviour is the same.

```
plugins {
    kotlin("jvm") version "1.4.21"
    id("org.jetbrains.compose") version "0.3.0-build140"
}
```
OS: Windows 10 Pro 20H2

**Comment by prepor** [comment]
I think that it was solved together with https://github.com/JetBrains/compose-jb/issues/171. Feel free to reopen if you encounter this problem again

**Comment by igordmn** [comment]
Drag&drop: https://github.com/JetBrains/compose-jb/issues/322

**Comment by igordmn** [comment]
Context menu: https://github.com/JetBrains/compose-jb/issues/323

**Comment by xiao-cao-depot** [comment]
> 我正在将Compose for Desktop用作测试驱动器。
> 因为我们的应用程序非常笨重，所以TextField是我尝试的第一件事。
> 现在，它是_非常_alpha的。这些基本的东西不起作用：
> 
> * 删除键处理。这是我最讨厌手机的一件事。在桌面上，我只是希望它能工作。
> * 导航至POS1 / END的开头/结尾
> * 使用CTRL-LEFT / RIGHT逐字导航
> * 通过按住SHIFT并使用导航来选择文本（例如SHIFT-POS1和SHIFT-LEFT都应起作用）
> * 通过CTRL-A全选
> * 剪贴板支持。在Windows上，还请实现其他快捷方式（复制= CTRL-INS，粘贴= SHIFT-INS和剪切= SHIFT-DEL）
> * “ singleLine = true”实际上不起作用。当前，它仅使文本字段在视觉上“单行”。我仍然可以按ENTER键，但是插入号和其他文本将不可见。
> 
> 当然，应该使用适合当前系统/ OS的快捷方式。
> 
> 我都用
> 
> ```
>     var value by savedInstanceState(saver = TextFieldValue.Saver) { TextFieldValue() }
>     TextField(
>         value = value,
>         onValueChange = { value = it },
>         singleLine = true
>     )
> ```
> 
> 和
> 
> ```
>     var text by remember { mutableStateOf("") }
>     TextField(
>         value = text,
>         onValueChange = { text = it }
>     )
> ```
> 
> 和行为是相同的。
> 
> ```
> plugins {
>     kotlin("jvm") version "1.4.21"
>     id("org.jetbrains.compose") version "0.3.0-build140"
> }
> ```
> 
> 操作系统：Windows 10 Pro 20H2

Have you found a solution?

**Comment by eygraber** [comment]
I've been playing around with some shortcuts - https://gist.github.com/eygraber/d35cb777f4ce5d6c936774268ac859a1

**Comment by prepor** [comment]
Hey! Could you please try it with a new M3? https://blog.jetbrains.com/cross-post/jetpack-compose-for-desktop-milestone-3-released/

**Comment by timzam** [comment]
I just tried 0.4.0-build168 on Windows and on a Mac (I use BasicTextField) and I don't see any changes from before. Undo, selection, copy/paste, delete, home/end - they all don't work for me.

**Comment by kropp** [comment]
@timzam these changes are not included in 0.4.0 yet, use 0.3.0

**Comment by timzam** [comment]
@kropp I just checked 0.3.1 and all features I mentioned in my previous message work there.

**Comment by xiao-cao-depot** [comment]
Does the current version support context menu? If not, which version will it support?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5537">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
