### ISSUE TITLE
Gradle can't resolve androidx dependency

### ISSUE THREAD

**Issue by Tasztalos69** [JetBrains/compose-jb#278]
I may be missing something, but when I add `androidx.navigation:naviagtion-compose` to build.gradle.kts, I get the following error:

![image](https://user-images.githubusercontent.com/42411122/104778950-842d7700-577e-11eb-86a4-2daf66ebece3.png)

My repositories & dependencies:
```
repositories {
    google()
    jcenter()
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/compose/dev") }
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation("androidx.datastore:datastore-core:1.0.0-alpha06")
    implementation("androidx.navigation:navigation-compose:1.0.0-alpha05")
    ...
}
```

**Comment by igordmn** [comment]
See https://github.com/JetBrains/compose-jb/issues/272 for adding navigation to android target.

Navigation for desktop target isn't supported yet: https://github.com/JetBrains/compose-jb/issues/85

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5536">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
