### ISSUE TITLE
how compose desktop add C++ / C library

### ISSUE THREAD

**Issue by runtimme** [JetBrains/compose-jb#2787]
I want add C++ code to my project, is it possible? what should I do

**Comment by igordmn** [comment]
It is out of scope of this library.

I haven't checked, but this might help:

Follow [this](https://docs.gradle.org/current/samples/sample_building_cpp_libraries.html) tutorial and add a new Gradle module into your Compose project. For example, if you add a module named `lib` (generated by the tutorial), you can compile your library with a command `gradlew lib:build`. After that there should be a shared library built in `lib/build` directory. Then you can load it via JNI in your Kotlin code ([tutorial](https://matt-moore.medium.com/kotlin-jni-for-native-code-835e93af7ddf)).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2787">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
