### ISSUE TITLE
Any plans to interoperability with JavaFx?

### ISSUE THREAD

**Issue by kaushalyap** [JetBrains/compose-jb#280]
Any plans to interoperability with JavaFx? It might be easy since JavaFx is now open sourced.

**Comment by olonho** [comment]
Generally we didn't have such plans, however would consider external contributions in that direction.

**Comment by olonho** [comment]
See https://github.com/JetBrains/compose-jb/issues/519#issuecomment-804030550 for an example of JavaFX interoperability.

**Comment by sschuberth** [comment]
I would be so cool to have Compose and its DSL combined with JavaFX widgets to replace the abandoned [TornadoFX](https://github.com/edvin/tornadofx)...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5534">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
