### ISSUE TITLE
Resolution for rendering lag in unminimizing the app?

### ISSUE THREAD

**Issue by Animeshz** [JetBrains/compose-jb#281]
Seems like due to redrawing, there's a bit of lag at the time of unminimizing the application.

![compose-minimize-maximize-2](https://user-images.githubusercontent.com/26714676/104796554-28dea180-57dd-11eb-8bb6-6768bbe96eb7.gif)

Is there any workaround for hiding that? Maybe lazily open the window after drawing happens, show an animation instead when drawing, or possibly something else 👀. Did not found anything like that in the docs.

**Comment by akurasov** [comment]
@Animeshz what is the OS and hardware? Does it happen on the latest Compose build?

**Comment by akurasov** [comment]
Works fine on Mac with latest build

**Comment by Animeshz** [comment]
Yeah its pretty smooth right now
![compose_flicker_fixed](https://user-images.githubusercontent.com/26714676/127970569-cc89ee83-b4d9-424e-80ad-213c8baa5111.gif)

**Comment by akurasov** [comment]
@Animeshz good luck :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5533">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
