### ISSUE TITLE
Move compose/golden/compose/ui/ui-desktop into androidx/golden/compose/ui/ui-desktop

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#2819]
1. move this folder
2. change `systemProperties["GOLDEN_PATH"] = project.rootDir.absolutePath + "/../../golden"` in multiple places in `androidx`
3. remove submodule `compose/golden` from `compose-jb` repo

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2819">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
