### ISSUE TITLE
Remove jvm target in web.core

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#2820]
https://github.com/JetBrains/compose-jb/blob/f96b436d87d459ea8e718d6f09ff3e586c851985/web/core/build.gradle.kts#L10

What is the use-case of a jvm target in (html) web core? All sources are js only.

**Comment by dima-avdeev-jb** [comment]
It needs for unit tests in dependent module https://github.com/JetBrains/compose-jb/blob/ca3c1909464a6d621da76f9ac0e1f71d6f46c36b/web/integration-core/build.gradle.kts#L36

**Comment by hfhbd** [comment]
I saw the test module too but I still don't understand why do you need the jvm target. The test is executed in the browser, and the jvm target does not contain any code. So what's the use case?

**Comment by dima-avdeev-jb** [comment]
It's a useful workaround to apply jvm usage inside dependent module.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2820">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
