### ISSUE TITLE
suggest add a spinner widget

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#292]
like this:
![image](https://user-images.githubusercontent.com/23566361/105120158-b20f1480-5b0c-11eb-9b11-0d986f367ee2.png)

**Comment by Dominaezzz** [comment]
There's a `DropDownMenu` I think.

**Comment by FlyingYu-Z** [comment]
thank you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5526">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
