### ISSUE TITLE
Publish GitHub releases

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#300]
Now we only publish tags (https://github.com/JetBrains/compose-jb/tags)

We should publish releases similar to https://github.com/JetBrains/skiko/releases, so we can see them in notifications (https://github.com/notifications?query=repo%3AJetBrains%2Fcompose-jb)

**Comment by AlexeyTsvetkov** [comment]
Done https://github.com/JetBrains/compose-jb/releases/latest

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6441">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
