### ISSUE TITLE
Rename DesktopPlatform to DesktopLookAndFeel

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#303]
```
enum DesktopLookAndFeel { WinUI, Gnome, AppKit }

companion object {
    val Auto: DesktopLookAndFeel 
}
```
```
DesktopPlatformAmbient -> AmbientDesktopLookAndFeel
```

The ability to change DesktopPlatform through ambient is controversial.
Let's change its name to more meaningful. Changing look and feel is the real purpose of this enum.

**Comment by olonho** [comment]
Not sure if usual L&F connotations applied here.

**Comment by igordmn** [comment]
Now it only affects scrolling behavior, but in theory we can use it for scrollbars/dialogs/buttons/etc

**Comment by jimgoog** [comment]
This configuration looks like it could be design system specific, right?  Probably the ambient should live in the material package (or whatever design system you're using to draw your scrollbars).  I think it's perfectly reasonable to provide some design-system-agnostic helper functions that provide the default/expected acceleration curves or whatever, to make it easy for design systems to re-use that logic, but those probably shouldn't be ambients.

**Comment by igordmn** [comment]
DesktopPlatform is internal in 1.0.0-beta5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6246">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
