### ISSUE TITLE
Tooltip modifier for desktop applications

### ISSUE THREAD

**Issue by ragunathjawahar** [JetBrains/compose-jb#306]
Are you folks planning for a tooltip modifier for desktop applications?

**Comment by jimgoog** [comment]
Several people have requested this, so it's just a matter or prioritization.  Community contributions are welcomed.

If you were to implement/contribute such a thing, I think the primitives you would want to look at are:

- To display some content above other content, I would look into: `androidx.compose.ui.window.Popup(...)`
 - And to measure the text so you can know how/where to position the popup, probably compute a TextLayoutResult by copy-pasting some of the internals of [TextDelegate.kt](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/TextDelegate.kt) into your code.

**Comment by akurasov** [comment]
@ragunathjawahar please check BoxWithTooltip and tell us if it suits your needs.

**Comment by ragunathjawahar** [comment]
@akurasov thank you, will get back to you on this soon.

**Comment by shynline** [comment]
For reference, there's a `TooltipArea` available. 
Maybe you want to close this issue. idk

**Comment by igordmn** [comment]
As `TooltipArea` is implemented, closing this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6090">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
