### ISSUE TITLE
Unable to resolve `CircleShape`

### ISSUE THREAD

**Issue by ragunathjawahar** [JetBrains/compose-jb#311]
<img width="1904" alt="Screenshot 2021-01-23 at 1 57 08 PM" src="https://user-images.githubusercontent.com/1141970/105573360-f73c7c00-5d82-11eb-8a2c-15542f3a1518.png">

Auto-suggest can suggest the type but it is not available in `0.2.0-build132` version of the `foundation-desktop` artifact.

**Comment by ruckustboom** [comment]
`CircleShape` doesn't take any parameters

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-311">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
