### ISSUE TITLE
How to custom the installer?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#314]
this s the origin installer

![image](https://user-images.githubusercontent.com/23566361/105654394-e150c780-5ef8-11eb-8b3a-8057870713f0.png)

I want add some options,such as:

add the shortcut to the desktop 

or like this:
![image](https://user-images.githubusercontent.com/23566361/105654591-499fa900-5ef9-11eb-8d78-312c983367bd.png)

how to do it?

**Comment by olonho** [comment]
Please provide more information on what kind of features you'd like to see.

**Comment by olonho** [comment]
Sure, but we expose _some_ jpackage features via Gradle DSL, and depending on TS needs we may consider changing exposed set.

**Comment by FlyingYu-Z** [comment]
> Please provide more information on what kind of features you'd like to see.

like this:
![image](https://user-images.githubusercontent.com/23566361/106409236-11f5ab80-647b-11eb-80b6-a2287466b30d.png)

**Comment by kmenesesp** [comment]
This should be reopened as there is no option to add a desktop shortcut in the installation process, is there any way to add it already or any workaround?

**Comment by kmenesesp** [comment]
it seems that you can set this in a property as true:

compose.desktop { application { nativeDistributions { windows { shortcut = true } } } }

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6127">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
