### ISSUE TITLE
[Windows] - packageMsi doesn't work with 0.3.0-build141 tag

### ISSUE THREAD

**Issue by ypujante** [JetBrains/compose-jb#318]
On Windows, using the latest tag 0.3.0-build141, `packageMsi` fails:

```
.\gradlew.bat --stacktrace packageMsi

> Task :createRuntimeImage FAILED
untime Illegal char <   > at index 38: D:Workdesktop-compose-testbuildcompose   mpmain

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createRuntimeImage'.
> Process 'command 'C:\Program Files\Java\jdk-15.0.2\bin\jlink.exe'' finished with non-zero exit value 1
```

There seems to be some issue in how the path is being generated (the folder I am working in is `D:\work\desktop-compose-test`)

**Comment by olonho** [comment]
Please try `0.3.0-build142`.

**Comment by ypujante** [comment]
Yes it is working with `0.3.0-build142`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6488">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
