### ISSUE TITLE
Multi module app packaging issue when having sub modules with the same name

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-jb#319]
When we have a multi module app with sub modules using same name one of the sub modules are not included in package.

How to reproduce: Create an app with sub modules like this
root
->android
->desktop
->common
--->compose-ui
------>main
------>feature1
------>feature2
--->logic
------>main
------>feature1
------>feature2

**Comment by olonho** [comment]
Could you please provide simplified reproducer?
