### ISSUE TITLE
Desktop platform "Slider" dragging is not smooth

### ISSUE THREAD

**Issue by xiao-cao-depot** [JetBrains/compose-jb#320]
When dragging "Slider" on the desktop platform. It does not follow the mouse movement, but directly moves to the position where the mouse stops.

**Comment by olonho** [comment]
Is this behavior different from Android Compose? Could you share a video.

**Comment by xiao-cao-depot** [comment]
The window with Kotlin icon is Compose, and the window without icon is my own UI, which is the effect I need
https://user-images.githubusercontent.com/76673990/106132521-05353700-619f-11eb-8da8-f54c7fda3c6a.mp4

**Comment by xiao-cao-depot** [comment]
> 这种行为与Android Compose不同吗？您可以分享视频吗？

The window with Kotlin icon is Compose, and the window without icon is my own UI, which is the effect I need
https://user-images.githubusercontent.com/76673990/106132521-05353700-619f-11eb-8da8-f54c7fda3c6a.mp4

**Comment by igordmn** [comment]
Could you check on 0.3.0-build146? We fixed performance issues in https://github.com/JetBrains/compose-jb/issues/137

There is another issue with the starting of dragging. Dragging doesn't start immediately:
```
import androidx.compose.desktop.Window
import androidx.compose.material.Slider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue

fun main() = Window {
    var value by remember { mutableStateOf(5f) }
    Slider(
        value = value,
        valueRange = 0f..10f,
        onValueChange = { value = it }
    )
}
```

https://user-images.githubusercontent.com/5963351/106154944-327ae880-6191-11eb-9bc6-b3581d0e04c8.mp4



I think we should introduce proper mouse handling to Slider component. Because non-immediate start of dragging should only happened with touch gestures.

**Comment by xiao-cao-depot** [comment]
> 您可以检查0.3.0-build146吗？我们修复了[＃137中的](https://github.com/JetBrains/compose-jb/issues/137)性能问题[](https://github.com/JetBrains/compose-jb/issues/137)
> 
> 开始拖动还有另一个问题。拖动不会立即开始：
> 
> ```
> import androidx.compose.desktop.Window
> import androidx.compose.material.Slider
> import androidx.compose.runtime.getValue
> import androidx.compose.runtime.mutableStateOf
> import androidx.compose.runtime.remember
> import androidx.compose.runtime.setValue
> 
> fun main() = Window {
>     var value by remember { mutableStateOf(5f) }
>     Slider(
>         value = value,
>         valueRange = 0f..10f,
>         onValueChange = { value = it }
>     )
> }
> ```
> 
>  2021-01-28.17-40-57.mp4 
> 我认为我们应该将适当的鼠标处理引入Slider组件。因为非立即开始拖动仅应使用触摸手势进行。

**Comment by xiao-cao-depot** [comment]
> 您可以检查0.3.0-build146吗？我们修复了[＃137中的](https://github.com/JetBrains/compose-jb/issues/137)性能问题[](https://github.com/JetBrains/compose-jb/issues/137)
> 
> 开始拖动还有另一个问题。拖动不会立即开始：
> 
> ```
> import androidx.compose.desktop.Window
> import androidx.compose.material.Slider
> import androidx.compose.runtime.getValue
> import androidx.compose.runtime.mutableStateOf
> import androidx.compose.runtime.remember
> import androidx.compose.runtime.setValue
> 
> fun main() = Window {
>     var value by remember { mutableStateOf(5f) }
>     Slider(
>         value = value,
>         valueRange = 0f..10f,
>         onValueChange = { value = it }
>     )
> }
> ```
> 
>  2021-01-28.17-40-57.mp4 
> 我认为我们应该将适当的鼠标处理引入Slider组件。因为非立即开始拖动仅应使用触摸手势进行。

Thanks, this problem has been solved

Uploading video.mp4…

**Comment by xiao-cao-depot** [comment]
> 您可以检查0.3.0-build146吗？我们修复了[＃137中的](https://github.com/JetBrains/compose-jb/issues/137)性能问题[](https://github.com/JetBrains/compose-jb/issues/137)
> 
> 开始拖动还有另一个问题。拖动不会立即开始：
> 
> ```
> import androidx.compose.desktop.Window
> import androidx.compose.material.Slider
> import androidx.compose.runtime.getValue
> import androidx.compose.runtime.mutableStateOf
> import androidx.compose.runtime.remember
> import androidx.compose.runtime.setValue
> 
> fun main() = Window {
>     var value by remember { mutableStateOf(5f) }
>     Slider(
>         value = value,
>         valueRange = 0f..10f,
>         onValueChange = { value = it }
>     )
> }
> ```
> 
>  2021-01-28.17-40-57.mp4 
> 我认为我们应该将适当的鼠标处理引入Slider组件。因为非立即开始拖动仅应使用触摸手势进行。

Thanks, this problem has been solved

https://user-images.githubusercontent.com/76673990/106180081-d1760380-61d6-11eb-96ca-c17350955951.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6484">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
