### ISSUE TITLE
In some functions of "Compose" in "IntelliJ IDEA", there is no pop-up prompt when hovering the mouse.

### ISSUE THREAD

**Issue by xiao-cao-x** [JetBrains/compose-jb#326]
https://user-images.githubusercontent.com/76673990/106244873-8a275b80-6246-11eb-9116-49e9cf282a32.mp4

**Comment by olonho** [comment]
Please specify versions of IDEA, Kotlin plugin, Compose and provide reproducer.

**Comment by xiao-cao-depot** [comment]
> 请指定IDEA版本，Kotlin插件，Compose并提供复制器。

![image](https://user-images.githubusercontent.com/76673990/106264843-24949880-6261-11eb-8a9b-69c3705d6c8b.png)
![image](https://user-images.githubusercontent.com/76673990/106264880-337b4b00-6261-11eb-85bc-bfd66e8b33b8.png)
![image](https://user-images.githubusercontent.com/76673990/106264978-5ad21800-6261-11eb-8f12-e2500c76d908.png)


val kotlin_version: String = "1.4.21-2"

plugins {
    kotlin("jvm") version "1.4.21-2"
    id("org.jetbrains.compose") version "0.3.0-build146"
}



203-1.4.21-release-IJ6682.9

**Comment by igordmn** [comment]
Reproducuble in "desktop-template" and "multiplatform-template" (Idea 2020.3.2 Community Edition with Kotlin Plugin 1.4.31; Android Studio 2020.3.1 Canary 8 with Kotlin Plugin 1.4.30)

```
plugins {
    kotlin("jvm") version "1.4.31"
    id("org.jetbrains.compose") version "0.3.2"
}
```

When we manually open "Quick documentation" (Ctrl-Q on Windows/Linux), there is an error: "Cannot fetch remote documentation: internal error":

![image](https://user-images.githubusercontent.com/5963351/110793582-da51fe80-8285-11eb-89ba-eaec808359d3.png)

**Comment by ivakub** [comment]
See https://youtrack.jetbrains.com/issue/KT-38747.

**Comment by akurasov** [comment]
Not reproducible on: 
IDEA 2021.2(Ultimate edition) + kotlin 1.5.10-IJ4746.92 
and 
AS Arctic Fox 2020.3.1+kotlin 1.5.21-release-316

@xiao-cao-x do you still have this issue?

**Comment by xiao-cao-x** [comment]
> 
> 
> Not reproducible on:
> IDEA 2021.2(Ultimate edition) + kotlin 1.5.10-IJ4746.92
> and
> AS Arctic Fox 2020.3.1+kotlin 1.5.21-release-316
> 
> @xiao-cao-x do you still have this issue?

it is ready.
It has been 7 months since the last submission of illues, jetpack compose finally has an alpha version.

**Comment by akurasov** [comment]
> it is ready. 
You mean everything is fine now?

**Comment by xiao-cao-x** [comment]
> 
> 
> > it is ready.
> > You mean everything is fine now?

Yes.
---
I can not speak English, I am using Google Translate

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6320">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
