### ISSUE TITLE
Random crashes JVM with Compose application

### ISSUE THREAD

**Issue by Vadim-Kapustin** [JetBrains/compose-jb#327]
I make a simple compose application (LazyColumn with Text, Buttons and LinearProgressIndicator in the rows). When  I make it in Linux everything worked fine. But when I compiled it for Windows on the same computer and run, I got an fatal error in JRE. Compose version 0.3.0-build143. Another Compose application with a more complex interface worked fine with this version of Compose and with the previous ones. I try compile the project with different variants of JDK (liberica-14, liberica-15, adopt-openj9-15). I try to run application on different computer (but the same OS: Windows 7 64-bit) - the same result.
The crash may occur after a few clicks, or it may not occur for a long time. It occurs more often after the progress indicator is worked out and then click on some button.

Demo application placed here: [simpletimer](https://bitbucket.org/Vadim303/simpletimer/src/master/)
JVM save report files after crash. I have attached an  example of these files:

[hs_err_pid6836.log](https://github.com/JetBrains/compose-jb/files/5892958/hs_err_pid6836.log)
[hs_err_pid7576.log](https://github.com/JetBrains/compose-jb/files/5892959/hs_err_pid7576.log)

**Comment by igordmn** [comment]
It is stable reproduced on '0.3.0-build143' (start first slider, open/close multiple times "Edit" dialog)

But isn't reproduced on '0.3.0-build146' (we have new skiko/skija in that build).

Can your check 0.3.0-build146?

**Comment by Vadim-Kapustin** [comment]
I check 0.3.0-build146. Application is worked. Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6483">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
