### ISSUE TITLE
Auto add pointerMoveFilter to clickable widget

### ISSUE THREAD

**Issue by gtf35** [JetBrains/compose-jb#339]
I think moving the mouse to the clickable widget on the desktop platform should have a default effect. Just like vb .net unity.

By the way, when android device connected usb mouse, it has the same effect(ripple)
![image](https://user-images.githubusercontent.com/22125696/106387880-d1fcdd00-6416-11eb-9135-de7e1bf623d5.png)

**Comment by olonho** [comment]
This problem was discussed, probably the best would be to make it configurable via an API/theme.

**Comment by gtf35** [comment]
It seems that the official wants to let the developers solve it by themselves, close issues
