### ISSUE TITLE
detectDragGesture is unusable on Desktop

### ISSUE THREAD

**Issue by LAP2** [JetBrains/compose-jb#343]
Hi folks.

Found one interesting thing.
If you try to use detectDragGesture in pointerInput it wouldn't work on desktop cause of huge value of touchSlop configured in androidx.compose.ui.platform.DesktopViewConfiguration.

Every time i had try to drag something i run into awaitTouchSlopOrCancellation and then check `if (distance >= touchSlop) ` allways fail cause distance (1~3) is allways less then value of touchSlop (its 18).

**Comment by igordmn** [comment]
Thanks for the report!

Temporary solution - wrap top-level composable to this:
```
Window {
    WithoutTouchSlop {
        App()
    }
}

@Composable
private fun WithoutTouchSlop(content: @Composable () -> Unit) {
    fun ViewConfiguration.withoutTouchSlop() = object : ViewConfiguration {
        override val longPressTimeoutMillis get() =
            this@withoutTouchSlop.longPressTimeoutMillis

        override val doubleTapTimeoutMillis get() =
            this@withoutTouchSlop.doubleTapTimeoutMillis

        override val doubleTapMinTimeMillis get() =
            this@withoutTouchSlop.doubleTapMinTimeMillis

        override val touchSlop: Float get() = 0f
    }

    Providers(
        LocalViewConfiguration provides LocalViewConfiguration.current.withoutTouchSlop()
    ) {
        content()
    }
}
```
P.S. Touch slop should be available with touch screens on desktop, and on android there should be not touch slop if we use mouse.

So the temporary solution should be removed from the client code once the issue will be resolved.

**Comment by 06000000-0000** [comment]
Hi

**Comment by LAP2** [comment]
Update, possibly we should use CompositionLocalProvider

**Comment by Jakobeha** [comment]
This seems to work now on my windows PC. Does anyone still have the issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6282">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
