### ISSUE TITLE
Compose logger

### ISSUE THREAD

**Issue by gbaldeck** [JetBrains/compose-jb#346]
In my desktop app I have added log4j2 and wrapped the main method in a try-catch which logs all Throwables as an error in the log file and then rethrows the Throwable. 

In my log4j2,xml file the root logger is set to log to the console and the file. Since it's the root logger it should receive all log messages no matter the package.

When an exception is thrown by compose it is not caught by the main method's try-catch. I see the error in the IntelliJ console but it is not logged to the file like it should be. How do I setup my application so that compose logs to the log4j2 log file?

For reference here is my log4j2.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <Appenders>
        <Console name="LogToConsole" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss} [%t] %-5level %logger - %msg%n"/>
        </Console>
        <RollingFile name="LogToRollingFile" fileName="logs/launcher.log"
            filePattern="logs/launcher-%d{MM-dd-yyyy}-%i.log.gz">
            <PatternLayout>
                <Pattern>%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger - %msg%n</Pattern>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="50 MB"/>
            </Policies>
            <DefaultRolloverStrategy max="10"/>
        </RollingFile>
    </Appenders>
    <Loggers>
<!--        <Logger name="io" level="debug" additivity="false">-->
<!--            <AppenderRef ref="LogToConsole"/>-->
<!--        </Logger>-->
        <Root level="debug">
            <AppenderRef ref="LogToConsole"/>
            <AppenderRef ref="LogToRollingFile"/>
        </Root>
    </Loggers>
</Configuration>
```

**Comment by jimgoog** [comment]
There are a number of very real technical reasons why UI frameworks (including Compose) need to do work off the main thread.  Among other things, Compose in particular is adding some capabilities around performing parallel recomposition for improved performance, so you should never depend on what thread a given composable happens to run on.

Furthermore, throwing exceptions from within Composable functions is not yet well-supported, as it requires us to add some very complex logic to the Compose Compiler that we have not yet had the chance to implement.  This is why wrapping a call to a composable function in a try-catch block is illegal and the compiler will complain if you attempt to do so.  Just fair warning, as soon as the first exception is thrown from a composable function, it is possible to get into a pretty bad state.  We hope to improve this in a future version of Compose.

If you want to log uncaught exceptions, I'd recommend you take a look at [Thread.setDefaultUncaughtExceptionHandler](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#setDefaultUncaughtExceptionHandler-java.lang.Thread.UncaughtExceptionHandler-) which exists predominantly for purposes like the one you are describing.

I'm going to close this as it is not an actionable bug, and we would like to reserve github issues for things which are actionable bugs.  User questions about "how to configure log4j" are not directly related to Compose and better asked on sites like StackOverflow.

**Comment by pacher** [comment]
@jimgoog Wow, this sounds like errors and exception handling in Compose deserves a tutorial or some other documentation page. It is an important topic and it seems to be not straightforward right now, which can lead to surprises like in this topic. How would people know about it if they don't read every issue on GitHub?

**Comment by jimgoog** [comment]
The IDE will tell you if you try to wrap a composable function in a try-catch block.  But yes, there are many topics we'd like to better document.  Contributions welcomed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6477">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
