### ISSUE TITLE
Execution failed for task ':createDistributable'.  lateinit property nonValidatedMacSigningSettings has not been initialized

### ISSUE THREAD

**Issue by sonder-joker** [JetBrains/compose-jb#347]
When I try to excute 'runDistributable', got
```
Execution failed for task ':createDistributable'.
> lateinit property nonValidatedMacSigningSettings has not been initialized
```
My environment: windows-x64

**Comment by sonder-joker** [comment]
It's happened only in the last build 0.3.0-build148

**Comment by olonho** [comment]
Yes, this problem is known and being worked on.

**Comment by akurasov** [comment]
@olonho have it been fixed?

**Comment by akurasov** [comment]
@sonder-joker do you have it now?

**Comment by sonder-joker** [comment]
> @sonder-joker do you still have it? 
I haven't reproduce it now, may it can close.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6289">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
