### ISSUE TITLE
Can't upload snaphot builds to Sonatype after switch to builds that require Kotlin 1.4.30

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#365]
Using these dependencies:

```
    dependencies {
        classpath("org.jetbrains.compose:compose-gradle-plugin:0.3.0-build152")
        classpath(kotlin("gradle-plugin", version = "1.4.30"))
        classpath("com.vanniktech:gradle-maven-publish-plugin:0.13.0")
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.4.20")
    }
```

and running `gradlew uploadArchives`

```
> Task :bitmapfilter:dokkaHtml
Dokka 1.4.* is an alpha project
Initializing plugins
Validity check
Creating documentation models
Transforming documentation model before merging
Merging documentation models
Transforming documentation model after merging
Creating pages
Transforming pages
Rendering


> Task :bitmapfilter:publishKotlinMultiplatformPublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bitmapfilter:publishKotlinMultiplatformPublicationToMavenRepository'.
> Failed to publish publication 'kotlinMultiplatform' to repository 'maven'
   > Invalid publication 'kotlinMultiplatform': multiple artifacts with the identical extension and classifier ('jar', 'sources').
```

**Comment by arkivanov** [comment]
Looks like sources are now uploaded automatically for `kotlinMultiplatform` publication. I had to remove the corresponding custom config.

**Comment by kirill-grouchnikov** [comment]
Arkadii, can you link to the CL that removed that configuration? I started out with copying the gradle configuration from one of the sample projects, and haven't touched it since.

**Comment by arkivanov** [comment]
@kirill-grouchnikov you can check my WIP branch here: https://github.com/arkivanov/Decompose/commit/cc0af8de7d370f29e00ea73d4e91c2c6c34858f3

**Comment by kirill-grouchnikov** [comment]
I don't have `kotlinMultiplatform` or `publications` elements anywhere in my `build.gradle.kts` files. Everything around publishing is handled by the `com.vanniktech.maven.publish` plugin.

**Comment by arkivanov** [comment]
@kirill-grouchnikov What about plugin?

**Comment by arkivanov** [comment]
I'm using normal `maven-publish` plugin and it works.

**Comment by kirill-grouchnikov** [comment]
com.vanniktech.maven.publish is the plugin I'm using

**Comment by kirill-grouchnikov** [comment]
The issue was with the Maven publish plugin which they fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5522">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
