### ISSUE TITLE
Migrate Scrollbar to Modifier.pointerInput

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#366]
Currently it uses deprecated rawDragGestureFilter / pressIndicatorGestureFilter.

Also after we fix https://github.com/JetBrains/compose-jb/issues/343, we need to replace rawDragGestureFilter by detectDragGestures

**Comment by igordmn** [comment]
Migrated in:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1645492
https://android-review.googlesource.com/c/platform/frameworks/support/+/1652612

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-366">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
