### ISSUE TITLE
Error: Resource File Not Found

### ISSUE THREAD

**Issue by Shabinder** [JetBrains/compose-jb#372]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: resource common/compose-ui/src/main/res/drawable/ic_spotiflyer_logo.xml not found

Getting Resource Not Found tried paths:
1)Repository Path:"common/compose-ui/src/main/res/drawable/ic_spotiflyer_logo.xml"
2) module resources path:"drawable/ic_spotiflyer_logo.xml"

But same error , **how to verify which path should I use correctly?**

Project Structure:
![image](https://user-images.githubusercontent.com/44765050/107549097-6cb6a200-6bf5-11eb-913f-219f32f9642c.png)

Possible Paths:
![image](https://user-images.githubusercontent.com/44765050/107549242-9a035000-6bf5-11eb-810c-87e600facc48.png)
**Which to use?**

**Comment by olonho** [comment]
Looks like general resource loading issue unrelated to compose. Could you compute correct absolute path in your application and make sure file exists?

**Comment by Shabinder** [comment]
solved , by putting correct path

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5517">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
