### ISSUE TITLE
Make DropdownMenu focusable by default

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#375]
Android version of DropdownMenu is focusable by default:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/androidMain/kotlin/androidx/compose/material/AndroidMenu.android.kt;l=74

And so it supports dismissal, when we click outside menu.

Desktop version should support dismissal too, so it should be focusable by default:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/desktopMain/kotlin/androidx/compose/material/DesktopMenu.desktop.kt;l=88

**Comment by ggeetha** [comment]
Any updates on this issue? 
I am also facing issue while using DropdownMenu. As per my understanding, its internally using Popup where there is no option to set the focusable true or false. By default it takes false. So its kind of blocking UI component. It doesnt allow any click outside this. Please consider this issue as priority. We are using multiple DropdownMenu in our class which is creating usability issue.

**Comment by Rsedaikin** [comment]
Fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5516">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
