### ISSUE TITLE
BUG: java.util.logging.Logger

### ISSUE THREAD

**Issue by mitch3ls** [JetBrains/compose-jb#377]
Summary:
java.lang.ClassNotFoundException is thrown for java.util.logging.Logger if Logger is used in packaged application. This behavior does not occur with `gradle run` without packaging

Environment:
OS: Windows 10 Pro 1901 18363.900

Steps to Reproduce:
1. IntelliJ -> create new projekt -> Kotlin -> Java Compose for Desktop
2. Add TargetFormat.AppImage in build.gradle.kt
3. Add Remote JVM Debug running configuration to IntelliJ
4. Enable remote debugging in the compose app with 
```
compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb, TargetFormat.AppImage)

            jvmArgs += "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
```
5. `gradle packageAppImage`
6. run packaged app and set breakpoint in the button's `onClick` callback
7. start debugging the Remote JVM Debugging configuration
8. press the button
9. evaluate `java.util.logging.Logger("foo")` in IntelliJ's debugging panel
10. see the thrown ClassNotFoundException

Expected Results:
I would expect to receive a Logger object, as it would happen before packaging (with only `gradle run`)

Actual Results:
ClassNotFoundException is thrown, which crashes the app outside of this debugging evaluation call

Notes:
I found this bug when I tried to use squareup's okio library in a compose project ([https://square.github.io/okio/](https://square.github.io/okio/))

**Comment by jimgoog** [comment]
Can you please provide a minimal repro so we can debug locally?

**Comment by mitch3ls** [comment]
I created a sample project on my private profile: [https://github.com/mitch3ls/jb-compose-issue-377-demo](https://github.com/mitch3ls/jb-compose-issue-377-demo)

All the necessary steps are described in main.kt

**Comment by mitch3ls** [comment]
I tried the solution from #381 with both `modules("java.util.logging")` and `modules("java.util")`, but I get `jlink failed with: Error: Module java.util.logging not found` for both cases during `gradle packageAppImage`

**Comment by olonho** [comment]
https://docs.oracle.com/javase/9/docs/api/module-overview-frame.html module name is `java.logging`.

**Comment by mitch3ls** [comment]
Thank you so much, that worked! It would be great if that could be incorporated into the documentation somehow 👍

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5515">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
