### ISSUE TITLE
Tutorial snippets checker. Snippets dependencies.

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#386]
Currently the tutorial snippets checker can not compile snippets if there are things used that are defined in another snippets.

This snippet can be verified:

```kotlin
class Item
```

This snippet can not be verified:

```kotlin
import androidx.compose.runtime.Composable

@Composable
fun ItemScreen(item: Item) {
}
```

Would be nice to somehow mark the second snippet, so the checker could add another required snippets to compilation.

**Comment by olonho** [comment]
That's look too complex, IMO, why not just have commented full snippet?

**Comment by arkivanov** [comment]
It would be useful in tutorials. So you can first explain one snippet, and then explain another using the previous one. Also same snippet can be reused in multiple snippets below the tutorial. The use case raised during my work on the Navigation tutorial. But it's up to you.

**Comment by olonho** [comment]
Well, let's close it for now, as see no clear way of doing that and there are workarounds.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5510">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
