### ISSUE TITLE
Try 'gradlew runDistributable' get java.lang.IllegalArgumentException:

### ISSUE THREAD

**Issue by sonder-joker** [JetBrains/compose-jb#390]
```
> Task :miraicompose:createDistributable FAILED
WARNING: Using incubator modules: jdk.incubator.jpackage
java.lang.IllegalArgumentException: "版本 [0.3.0-build152] 包含无效组件 [0-build152]"

```
版本 [0.3.0-build152] 包含无效组件 [0-build152] translate to
 Version [0.3.0-build152] contains invalid component [0-build152]"

**Comment by olonho** [comment]
Please provide reproducer, likely version is properly formatetd. Use smth like `1.0`.

**Comment by sonder-joker** [comment]
https://github.com/sonder-joker/mirai-compose/tree/dev

version:0.3.0-build152
./gradlew run work right
and ./gradlew packageMsi work with same problem

**Comment by olonho** [comment]
https://github.com/sonder-joker/mirai-compose/blob/c997b8a37431ea3cf8be1ec0a003105b55bf491f/miraicompose/build.gradle.kts#L33 is incorrect, version must be like "1.0", it's application version, not Compose.

**Comment by sonder-joker** [comment]
Thanks for your help! It's my fault

**Comment by jimgoog** [comment]
@olonho I wonder if there is something we can do here to provide the user with a better error message?  I feel like I've seen a few people trip over this issue already.  Should we open an issue to track that?

**Comment by olonho** [comment]
Actually @AlexeyTsvetkov already planned to implement such a feature, feel free to open an issue, if you like.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
