### ISSUE TITLE
Couldn't find Modifier.preferredWidth and others

### ISSUE THREAD

**Issue by gagarin55** [JetBrains/compose-jb#391]
In the last 153 build I couldn't find functions `Modifier.preferredHeight`, `Modifier.preferredWidth` and other `preferred*`.
Are those available for desktop ?

**Comment by kirill-grouchnikov** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/1572682

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5507">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
