### ISSUE TITLE
Better error message when invalid `nativeDistributions` version is specified

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#393]
When specifying the version number in `nativeDistributions`, a few people have tripped over situations where the version they specify is invalid.  For instance, I know I recently saw a user specify a version number that included a 'v' (for version) as the first character, and then it blew up.  Another instance is https://github.com/JetBrains/compose-jb/issues/390

Maybe there is something we can do to provide a better version number.  I think @olonho mentioned that @AlexeyTsvetkov is already looking into this, so mostly opening this issue just so we have a tracking bug number.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-393">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
