### ISSUE TITLE
Support Home/End/Del in TextFields

### ISSUE THREAD

**Issue by max-kammerer** [JetBrains/compose-jb#400]
Support Home/End/Del keys in TextFields

Now they do nothing (KUbuntu 20.04)

**Comment by alialbaali** [comment]
[https://github.com/JetBrains/compose-jb/issues/277](#277)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5503">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
