### ISSUE TITLE
Changing Input Field when TAB key is pressed by default

### ISSUE THREAD

**Issue by korredor11** [JetBrains/compose-jb#409]
Idk, if this feature already exists im struggling to find someone refencing any kind o Form build with jetpack compose.
I only want to know if thats possible, bcs is kinda bad to handle that every time.

**Comment by prepor** [comment]
You can control how tab-navigation works via `Modifier.focusOrder`.

**Comment by korredor11** [comment]
Hi,

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5502">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
