### ISSUE TITLE
Problem with CircularProgressIndicator

### ISSUE THREAD

**Issue by ypujante** [JetBrains/compose-jb#411]
The following code 

```
@Composable
fun TestLayout() {
  Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.fillMaxWidth()) {
    Text("line1")
    Divider()
    Box(modifier = Modifier.border(width = 1.dp, color = Color.Blue), contentAlignment = Alignment.Center) {
      CircularProgressIndicator(
        progress = 1.0F,
        strokeWidth = 10.dp,
        modifier = Modifier.size(100.dp, 100.dp)
      )
    }
    Divider()
    Text("line3")
  }
}
```

renders this

<img width="133" alt="Screen Shot 2021-02-21 at 11 22 53" src="https://user-images.githubusercontent.com/357116/108636015-834fcb00-7437-11eb-9037-4c26271a5d23.png">
and the following code 

```
@Composable
fun TestLayout() {
  Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.fillMaxWidth()) {
    Text("line1")
    Divider()
    Box(modifier = Modifier.border(width = 1.dp, color = Color.Blue), contentAlignment = Alignment.Center) {

      Box(
          modifier = Modifier.border(10.dp, Color.Red, CircleShape).size(100.dp, 100.dp)
      )
    }
    Divider()
    Text("line3")
  }
}
```

renders that

<img width="119" alt="Screen Shot 2021-02-21 at 11 23 36" src="https://user-images.githubusercontent.com/357116/108636022-95316e00-7437-11eb-8461-1776f3ec2dc1.png">

You can see that the `CircularProgressIndicator` sticks out of the box including into line 3...

**Comment by ypujante** [comment]
This is using:

```
    kotlin("jvm") version "1.4.30"
    id("org.jetbrains.compose") version "0.3.0-rc1"

On macOS 10.14.6

With java 
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 15 Mac OS X amd64-64-Bit Compressed References 20210121_172 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 863b523566 based on jdk-15.0.2+7)
```

**Comment by kirill-grouchnikov** [comment]
This should probably go into https://issuetracker.google.com/issues/new?component=612128&template=1253476 as the `CircularProgressIndicator` is part of the material layer

**Comment by ypujante** [comment]
I would be more than happy to open an issue with the Jetpack compose project **if** I could reproduce it with a Jetpack compose test case. Unfortunately after much struggling I cannot even compile a single line of code. I downloaded the latest Android canary build, (2020.3.1 Canary 7), used the project wizard to create a Jetpack compose project and getting this exception when building:

```
java.lang.NoSuchMethodError: org/jetbrains/kotlin/serialization/DescriptorSerializer$Companion.registerSerializerPlugin(Lorg/jetbrains/kotlin/serialization/DescriptorSerializerPlugin;)V (loaded from file:/Volumes/Vault/Caches/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.30-RC/12cc8c4de87501159ed589c3ca0f05317a0bb2b7/kotlin-compiler-embeddable-1.4.30-RC.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@c6ba98f7) called from class androidx.compose.compiler.plugins.kotlin.ComposeComponentRegistrar$Companion (loaded from file:/Volumes/Vault/Caches/.gradle/caches/modules-2/files-2.1/androidx.compose.compiler/compiler/1.0.0-alpha08/f09d50a8d9dbaabce91385df3e5fafb2fa575bbd/compiler-1.0.0-alpha08.jar by java.net.URLClassLoader@33ce5024).
```

I know this is the not the place to discuss Android Studio or Jetpack compose issues, but until I am able to reproduce the issue I am not comfortable making a claim which I don't know is true. As far as I am concerned, I am getting this issue while using compose desktop (0.3.0-rc1). I cannot tell where the problem is actually taking place.

**Comment by jimgoog** [comment]
@ypujante The `NoSuchMethodError ` is a result of you using the wrong version of Kotlin.  If you are using the latest Compose (I think alpha12 at the time of this writing), be sure your kotlin version is set to `1.4.30`.  Sometimes there are gradle daemons running in the background which are running older versions of Kotlin, and there is a gradle bug where it doesn't seem to properly check the version, so you should run `jps -m` and kill everything that mentions Gradle Daemon or Kotlin Daemon.

**Comment by kirill-grouchnikov** [comment]
The relevant lines are at https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/compose/material/material/src/commonMain/kotlin/androidx/compose/material/ProgressIndicator.kt#330 which seem to be correct - offsetting the top-left corner by half the stroke width, and reducing the arc size by the full stroke width.

**Comment by igordmn** [comment]
Fixed in `0.4.0-build173`.

There was a bug in DesktopCanvas:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1612116
(https://github.com/JetBrains/compose-jb/issues/458)

On Android everything was OK.

**Comment by ypujante** [comment]
Thank you for fixing! I will check it out when I get a chance. And I guess it was indeed a bug in compose dekstop, so I am glad I reported it here.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5501">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
