### ISSUE TITLE
What happenned to FlowRow? [0.3.0]

### ISSUE THREAD

**Issue by NanoSpicer** [JetBrains/compose-jb#415]
I've just updated to 0.3.0 and code stopped compiling.

After updating everything I've found myself without `FlowRow` which one is the current alternative to it?

**Comment by kirill-grouchnikov** [comment]
`FlowRow` was deprecated in https://android-review.googlesource.com/c/platform/frameworks/support/+/1521704 and removed in https://android-review.googlesource.com/c/platform/frameworks/support/+/1575163

This is not specific to the desktop version, but rather at the foundation layer.

**Comment by NanoSpicer** [comment]
Do we have a known replacement?

**Comment by kirill-grouchnikov** [comment]
Since this is a part of the foundation layer, probably best asked on the main Compose bug tracker.

**Comment by NanoSpicer** [comment]
Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5497">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
