### ISSUE TITLE
fadeIn blinks when entering

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-jb#419]
I'm using a `tween` AnimationSpec so that I can slow the transition down to highlight the problem, but it also occurs with the other AnimationSpecs. The other `EnterTransitions` work fine (`slideIn`, etc...).

![test](https://user-images.githubusercontent.com/1100381/108958884-9a620900-7641-11eb-8031-5aa8f9273a84.gif)

(The GIF has some artifacting from ffmpeg)

```
fun main() {
  val visible = mutableStateOf(true)

  GlobalScope.launch {
    while(true) {
      delay(2500)
      visible.value = false
      delay(2500)
      visible.value = true
    }
  }

  Window(
      title = "Test"
  ) {
    MaterialTheme {
      Box(
          modifier = Modifier.fillMaxSize()
      ) {
        Test(visible)
      }
    }
  }
}

@ExperimentalAnimationApi
@Composable
fun Test(visible: State<Boolean>) {
  AnimatedVisibility(
      visible = visible.value,
      initiallyVisible = !visible.value,
      enter = fadeIn(
          animationSpec = tween(durationMillis = 1500)
      ),
      exit = fadeOut(
          animationSpec = tween(durationMillis = 1500)
      )
  ) {
    Surface(
        modifier = Modifier.fillMaxSize()
    ) {
      Text(
          "Test",
          modifier = Modifier.fillMaxSize(),
          textAlign = TextAlign.Center
      )
    }
  }
}
```

**Comment by eygraber** [comment]
This issue doesn't occur on Android when building a multiplatform version using the above as common code.

**Comment by SebastianAigner** [comment]
Can confirm, I get the same on Windows.

**Comment by SebastianAigner** [comment]
See the same glitch on macOS:

https://user-images.githubusercontent.com/2178959/109129730-3fb7d280-7751-11eb-9d36-eaf540f4c297.mp4

**Comment by igordmn** [comment]
> This issue doesn't occur on Android

I tested on Android, and the issue occurs:

https://user-images.githubusercontent.com/5963351/109147217-ced6e180-7775-11eb-9930-9d0ae9d60767.mp4

**Comment by eygraber** [comment]
@igordmn Interesting, if I use a regular Android project using beta01 artifacts, I see what you see (on device and in the Android Studio preview).

If I use a multiplatform build with version 0.3.0 of the compose plugin here's what happens on my Android device:

https://user-images.githubusercontent.com/1100381/109150741-49344100-7737-11eb-8f41-0210b32865b5.mp4

**Comment by jimgoog** [comment]
@eygraber That would be surprising for it to fail on Desktop but not Android in the MPP build at the same version, and also fail on the Android-only build.  Regardless, if it fails in the android-only build, it's a bug in upstream Compose.  Can you please file a bug using https://issuetracker.google.com/issues?q=componentid:612128 and post a link here?

**Comment by eygraber** [comment]
https://issuetracker.google.com/issues/181156422

**Comment by akurasov** [comment]
Fixed in Google. Should be retested in desktop

**Comment by akurasov** [comment]
Retested on MacOs. Works fine. Closing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5494">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
