### ISSUE TITLE
mutableStateMapOf doc copy paste mistake

### ISSUE THREAD

**Issue by LAP2** [JetBrains/compose-jb#422]
Hi team.

Found that in documentation for `mutableStateMapOf` returned object called like `MutableSet<K,V>` it seems like copy paste mistake, cause it returns `SnapshotMutableMap`.

```
/**
 * Create a instance of MutableSet<K, V> that is observable and can be snapshot.
 *
 * @sample androidx.compose.runtime.samples.stateMapSample
 *
 * @see mutableStateOf
 * @see mutableMapOf
 * @see MutableMap
 * @see Snapshot.takeSnapshot
 */
fun <K, V> mutableStateMapOf() = SnapshotStateMap<K, V>()
```

**Comment by olonho** [comment]
Please create an issue in Google issue tracker, common code issue.

**Comment by jimgoog** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/1611116

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5493">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
