### ISSUE TITLE
When are we going to be able to use the @Preview feature in IntelliJ IDEA?

### ISSUE THREAD

**Issue by NanoSpicer** [JetBrains/compose-jb#423]
The right window in the AndroidStudio is the Preview mode that I am talking about. You can use it by tagging a @Composable function with  @Preview
![imagen](https://user-images.githubusercontent.com/30906623/109055531-98e71e00-76df-11eb-93e6-02962401d57a.png)

**Comment by olonho** [comment]
No ETA, but we're thinking about what could be done here.

**Comment by JavierSegoviaCordoba** [comment]
I tried it in a multiplatform module and it is not working even in the androidMain sourceset (it always tries to rebuild).

Is it possible at least to get support in Android Studio in a composable used in androidMain which uses composables from commonMain?

**Comment by akurasov** [comment]
It is a part of recent Alpha release

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5492">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
