### ISSUE TITLE
Emit error when attempting to jpackage with less than JDK 15

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#428]
We only support using JPackage on JDK 15+ as per https://github.com/JetBrains/compose-jb/pull/427

However, if a user runs JPackage with JDK 14 we get a really obscure error message as per @theapache64 comment: https://github.com/JetBrains/compose-jb/issues/275#issuecomment-786033194

The `createDistributable` task should probably detect the JDK version and give an informative error message if it is less than JDK 15.

**Comment by olonho** [comment]
That’s correct for Linux only, IIRC.

**Comment by olonho** [comment]
We discussed it internally and decided that JDK 15 is indeed required for native distribution on all platforms

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5489">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
