### ISSUE TITLE
[Feature] Common icon for all platforms

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-jb#431]
**Problem**

- Have to maintain icons of different dimensions as the expected launcher icon size varies on each platform. 

**Current Implementation**

```kotlin
application {
    nativeDistributions {
        val iconsRoot = project.file("src/main/resources")
        linux {
            iconFile.set(iconsRoot.resolve("drawables/linux_logo.png"))
        }
        windows {
            iconFile.set(iconsRoot.resolve("drawables/windows_logo.png"))
        }
        macOS{
            iconFile.set(iconsRoot.resolve("drawables/macOS_logo.png"))
        }
    }
}
```

**Proposed Solution**

So, I think it'd be better if we have an option to set a common icon for all platforms

```kotlin
common {
    iconFile.set(iconsRoot.resolve("drawables/logo.png"))
}
```

- Another advantage would be, CD can generate the launcher icon at the time of `packageXXX` from a high-quality image provided via `common.iconFile` so the developer doesn't have to worry about the diff-dimension issue.

**Comment by olonho** [comment]
Why all three platforms cannot refer to the same icon? In many cases different icons make sense.

**Comment by AlexeyTsvetkov** [comment]
@olonho sadly, it does not work with current implementation: `jpackage` only supports `.png` on Linux, `.ico` on Windows, `.icns` on Mac, so a developer must do a conversion (probably from a png) to a 3 different formats. Also I might be wrong on this, but it seems that `ico` and `icns` need to contain an icon in multiple resolutions, so the conversion becomes a bit inconvenient.

I think we can automate conversion in the plugin.

**Comment by jimgoog** [comment]
I absolutely love the enthusiasm and sentiment, but honestly this seems like the type of thing that if it is going to get solved, should probably be solved by jpackage and not by us.  Providing multiple icons isn't that hard, and it allows for different icons on different platforms, etc.

It's up to you all, but in the name of ruthless prioritization, me personally, I'd probably close this bug as wont-fix.  That allows us to focus on improving the things that only we can do.

**Comment by jimgoog** [comment]
I absolutely love the enthusiasm and sentiment, but honestly this seems like the type of thing that if it is going to get solved, should probably be solved by jpackage and not by us. We can suggest filing a bug upstream with jpackage.  And in the mean time, providing multiple icons isn't that hard, and it has benefits like allowing different icons on different platforms, etc.

It's up to you all, but in the name of ruthless prioritization, me personally, I'd probably close this bug as wont-fix. That allows us to focus on improving the things that only we can do.

**Comment by theapache64** [comment]
Alright. I can understand that.@jimgoog You can close this issue

**Comment by olonho** [comment]
Not sure if this kind of transformation indeed belongs to the MPP plugin, so do not think that this feature is something we plan to implement.

**Comment by c5inco** [comment]
cc @bulenkov - maybe you have some thoughts based on some icon automation work for IntelliJ IDEA source

**Comment by bulenkov** [comment]
@c5inco in IntelliJ we use a set of svg icons as a base, and then generate ico, icns, png files from them.

**Comment by c5inco** [comment]
Right - it would be great I think to offer this functionality as part of the packaging/distribution tools for Compose Desktop. Seems the needs are similar, and I feel many would just like to use just one asset (e.g. SVG) to generate all the necessary icons for the different platforms.

**Comment by theapache64** [comment]
As a workaround, I use a simple shell script that I created to generate icons for all three  platforms.

<details>
<summary>Shell Script</summary>

```shell
function gen-cfd-icon() {
    ICON_DIR="src/main/resources/drawables/launcher_icons"
    mkdir -p $ICON_DIR
    ORIGINAL_ICON="$ICON_DIR/original.png"
    cp "$1" "$ORIGINAL_ICON"

    # Linux
    echo "🌀 Creating icon for Linux..."
    convert -resize x128 "$ORIGINAL_ICON" "$ICON_DIR/linux.png"

    # Windows
    echo "🌀 Creating icon for Windows..."
    convert -resize x128 "$ORIGINAL_ICON" "$ICON_DIR/windows.ico"

    # MacOS
    echo "🌀 Creating icon for macOS..."
    convert -resize x128 "$ORIGINAL_ICON" "$ICON_DIR/macos.icns"

    ## Printing code
    echo "Add this to your build.gradle.kts ⬇️"

    OUTPUT="
val iconsRoot = project.file(\"src/main/resources/drawables\")

linux {
  iconFile.set(iconsRoot.resolve(\"launcher_icons/linux.png\"))
}

windows {
  iconFile.set(iconsRoot.resolve(\"launcher_icons/windows.ico\"))
}

macOS {
  iconFile.set(iconsRoot.resolve(\"launcher_icons/macos.icns\"))
}"
    echo "$OUTPUT"
    echo "$OUTPUT" | xclip
    echo "Copied to your clipboard"
}

```
</details>

**Output**


https://user-images.githubusercontent.com/9678279/112203963-206d7180-8c39-11eb-8a7a-3ab76e531cf2.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5486">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
