### ISSUE TITLE
Tab key is not working as a key event in a textField

### ISSUE THREAD

**Issue by SaiNageswarS** [JetBrains/compose-jb#438]
Compose -> 0.3.0-build154
OS  -> Ubuntu Linux
  
Tab key is not working as a key event in a textField. 

https://github.com/SaiNageswarS/Omnishell/blob/21bc068dfd7265e1cc4fd0f49e8cdabe820ad058/src/main/kotlin/com/kotlang/ui/shell/Prompt.kt#L58

**Comment by prepor** [comment]
I guess it's because it was consumed by TextField. To intercept such events you can use `onPreviewKeyEvent`

**Comment by atoktoto** [comment]
Compose -> 0.4.0-build184
OS -> Windows 10

`onPreviewKeyEvent` does not fire on `Key.Tab`

**Comment by akurasov** [comment]
It works pretty well on 1.0.0-alpha4-build348

```
@OptIn(ExperimentalComposeUiApi::class, androidx.compose.foundation.ExperimentalDesktopApi::class)
fun main() {
    singleWindowApplication {
        Column {
            var str1 by remember{ mutableStateOf("str")}
            var str2 by remember{ mutableStateOf("str2")}
            println("Tab code: ${Key.Tab.keyCode}")
            TextField(str1, {str1 = it}, Modifier.onPreviewKeyEvent {
                println("${it.key.keyCode} : ${it.key}");
                true})
            TextField(str2, {str2 = it})
        }
    }
}
```

Please reopen if you still have this problem.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5484">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
