### ISSUE TITLE
Feature Request: Change cursor position in textField

### ISSUE THREAD

**Issue by SaiNageswarS** [JetBrains/compose-jb#439]
Not sure if this feature exists, however, I couldn't find anyway to change cursor position in textfield on invoking a shortcut.

**Comment by prepor** [comment]
You can change cursor position by setting `selection` property of `TextFieldValue` that you pass to `TextField`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5483">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
