### ISSUE TITLE
jlink fails in Ubuntu

### ISSUE THREAD

**Issue by SaiNageswarS** [JetBrains/compose-jb#441]
jlink is failing in following gradle task in Ubuntu platform.

```sh
> ./gradlew createDistributable
```

Error: java.io.IOException: Cannot run program "objcopy": error=2, No such file or directory

Jetpack Compose Version: 0.3.1
Open JDK Version:

```sh
sainageswars@sainageswars-ubuntu:~/workspace/Omnishell$ echo $JAVA_HOME
/home/sainageswars/.jdks/openjdk-15.0.2
sainageswars@sainageswars-ubuntu:~/workspace/Omnishell$ java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
sainageswars@sainageswars-ubuntu:~/workspace/Omnishell$ 
```

**Comment by jimgoog** [comment]
Haven't seen this before - Can you provide an (ideally minimal) example that reproduces the problem?  Perhaps post to github?

**Comment by olonho** [comment]
Install smth like https://packages.ubuntu.com/focal/binutils, if it'll help - maybe we shall document it.

**Comment by SaiNageswarS** [comment]
> Install smth like https://packages.ubuntu.com/focal/binutils, if it'll help - maybe we shall document it.

@olonho This worked. Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5481">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
