### ISSUE TITLE
Since 1.3.0, Build Failed by Illegal Version for 'MSI' : '1.0' on Windows.

### ISSUE THREAD

**Issue by Richie-Jang** [JetBrains/compose-jb#448]
Hello there,

On Windows, I got failed the build when I set Compose 1.3.0 or 1.4.0-build* due to MSI version numbering.
By the way, I could still run with 1.3.0-build154.

Error message is following as..
  * Illegal version for 'Msi' : '1.0' is not a valid version.
    * Correct format: 'MAJOR.MINOR.BUILD', where:
      * MAJOR is a non-negative integer with a maximum value of 255;
      * MINOR is a non-negative integer with a maximum value of 255;
      * BUILD is a non-negative integer with a maximum value of 65535;
    * You can specify the correct version using DSL properties: nativeDistributions.windows.msiPackageVersion, nativeDistributions.windows.packageVersion, nativeDistributions.packageVersion
  
Workaround...
    windows.msiPackageVersion = "1.0.0" in nativeDistributions

Thank you.

**Comment by olonho** [comment]
That's intended behavior, use version `1.0.0`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6466">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
