### ISSUE TITLE
LazyColumn can't scroll anymore after adjust window's size

### ISSUE THREAD

**Issue by ti4n1993** [JetBrains/compose-jb#459]
I don't test other components

**Comment by akurasov** [comment]
works fine on MacOs + build245. @ti4n1993, does this issue still exists?

**Comment by ti4n1993** [comment]
No, it works well

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6371">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
