### ISSUE TITLE
Unresolved reference: minimize, maximize, makeFullscreen, restore

### ISSUE THREAD

**Issue by nightrider77** [JetBrains/compose-jb#460]
Example from documentation. Produces errors. But build is successful and all the buttons work.
Why?

```
kotlin("jvm") version "1.4.31"
id("org.jetbrains.compose") version "0.4.0-build171"
```

![image](https://user-images.githubusercontent.com/20248492/109693330-95014300-7b9a-11eb-8c89-23e60e98715d.png)

**Comment by olonho** [comment]
How project was created?

**Comment by nightrider77** [comment]
> How project was created?

IntelliJ new project wizard, Kotlin -> JetPack Compose for Desktop -> Desktop

**Comment by igordmn** [comment]
After changing version of Compose you should sync IDEA with Gradle:

![image](https://user-images.githubusercontent.com/5963351/110800304-1b99dc80-828d-11eb-93a6-bdb09abc7c34.png)

Don't forget to change to `version = "1.0.0"` in `build.gradle`:
```
...
group = "com.example"
version = "1.0.0"
...
```
(new versions of Compose will throw exception if version is `1.0`)

**Comment by nightrider77** [comment]
> After changing version of Compose you should sync IDEA with Gradle

Thank you! Problem solved!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6457">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
