### ISSUE TITLE
Request: crud example - forms and tables of data, server POST/GET interaction for MacOS/Windows/Linux

### ISSUE THREAD

**Issue by bootrino** [JetBrains/compose-jb#461]
MacOS/Windows/Linux

The vast majority of typical web applications need to submit forms of data to some REST back end, and to display rows of data in tables with multiple columns that can be sorted/filtered for users to page through, and to authenticate, save some local data such as an authentication token or some user settings.

It would be immensely helpful for people like me trying to make a beginning if there was an example of an application doing just this - CRUD functionality, form GET/POST, client authentication, processing XML/JSON responses, displaying lists of data in a multicolumn table.  

thanks

**Comment by jimgoog** [comment]
There are plenty of blog posts and other internet content about creating restful/CRUD apps, and typically that documentation already includes samples using the Java programming language.

The only thing Compose does is to render the UI layer.  Everything else about your application is just standard Java/Kotlin/JVM code.  Closing because this is out of scope for our docs.

**Comment by bootrino** [comment]
Disappointed you see it that way .... this is the path into Jetbrains Compose for people from other technology backgrounds ..... tying these things together into working solution examples is exactly what's needed to encourage us to move into this new world of Jetbrains Compose ...... referring to Java application tutorials as the answer leaves me mystified as to how to build workable Jetbrains Compose applications, but I respect it's your project and your call.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6462">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
