### ISSUE TITLE
Verify module dependencies when building native images

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#463]
For context, see: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1614771641211500

When running native distributables, users are getting `ClassNotFoundException` for various packages.  The problem is that they failed to add `module(X)` inside `nativeDistributions` block, where `X` = the missing module.  This feels like the type of thing we should have caught at compile time, and should have given a message that was more actionable than `ClassNotFoundException`.

**Comment by jimgoog** [comment]
This issue is a request to add an additional verification step to `createDistributable` so users can get an error message at build time instead of a crash at runtime.

**Comment by jimgoog** [comment]
It seems that oracle publishes a tool that might help with the purpose of identifying missing dependencies:
https://docs.oracle.com/en/java/javase/15/docs/specs/man/jdeps.html

Here is the command that will print all the required modules for a jar:
`jdeps --print-module-deps --ignore-missing-deps build/libs/app-1.0.0-72.jar java.base,java.compiler,java.desktop,java.net.http,jdk.httpserver,jdk.management.jfr`

So perhaps it would be feasible to make a call to `jdeps` via `createDistributable` to determine if any modules are missing.

**Comment by SaiNageswarS** [comment]
How to add a module in nativeDistributions block. A sample here would be great.

https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution

**Comment by sureshg** [comment]
Here is the Gradle task to print the module dependencies (` ./gradlew printModuleDeps`)

```kotlin
val printModuleDeps by tasks.creating {
    doLast {
        val uberJar = tasks.named("packageUberJarForCurrentOS", Jar::class)
        val jarFile = uberJar.get().archiveFile.get().asFile

        val jdeps = ToolProvider.findFirst("jdeps").orElseGet { error("Can't find jdeps tool in JDK") }
        val out = StringWriter()
        val pw = PrintWriter(out)
        jdeps.run(pw, pw, "--print-module-deps", "--ignore-missing-deps", jarFile.absolutePath)

        val modules = out.toString()
        println(modules)
        // compose.desktop.application.nativeDistributions.modules.addAll(modules.split(","))
    }
    dependsOn("packageUberJarForCurrentOS")
}

``` 

Unfortunately, I couldn't able to wire this with `packaging` task. One main issue is, all the Gradle compose config is eagerly evaluated and there is no way to set the `nativeDistributions` config after the `jar` task. 

Also, `:createRuntimeImage` tasks is getting executed before the `jar`, so there is no way to infer module dependencies, which will know only after the jar is created.

```
:classes SKIPPED
:checkRuntime SKIPPED
:createRuntimeImage SKIPPED
:inspectClassesForKotlinIC SKIPPED
:jar SKIPPED
:packageDeb SKIPPED
:packageDmg SKIPPED
:packageExe SKIPPED
:package SKIPPED
```

**Comment by AlexeyTsvetkov** [comment]
Checking the main jar is not enough, as some modules can be used in classpath dependencies.
Checking all jars is not very fast even for small programs (could be alleviated by making it incremental, though).
But the main problem is that `jdeps` is too conservative: it does not seems doing any reachability analysis, so
results include a lot of modules, that are not necessary in practise. 

So I am not convinced, that using `jdeps` during any build by default is a good idea. Still it could be added as an option.

**Comment by sureshg** [comment]
@AlexeyTsvetkov Thanks for the info and agrees on the reachability analysis. By the way, the task uses Uber jar (`packageUberJarForCurrentOS`) for the dependency analysis. So that should include all the class path dependencies…rt?

**Comment by AlexeyTsvetkov** [comment]
Yeah, Uber jar should be enough, but it is likely to be slower, than parallel & incremental analysis per each jar.

**Comment by olonho** [comment]
We agreed to have an optional task to help figuring out the deps. In ideal world, it shall be integrated into `jlink`, IMO.

**Comment by jimgoog** [comment]
When you say optional task, would it be enabled by default?  I think 95% of the problem is that users see a `ClassNotFoundException` but then they have no idea what to do about it and wouldn't know to look for an optional task that checks dependencies.  They just assume it's a bug in Compose because it worked in the unpackaged version so if it fails in the packaged version then they assume it must just be a ComposeDesktop issue.

I imagine that people aren't doing native builds that often, right?  Usually it's not part of a user's development workflow and is instead just a step performed at the end?  My intuition is that maybe it's ok for creating distributables to be slow by default (with an option to skip checks and make it faster)?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6444">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
