### ISSUE TITLE
packageDmg fails when using spaces in package name

### ISSUE THREAD

**Issue by ypujante** [JetBrains/compose-jb#465]
With the following:

```
compose.desktop {
  application {
    mainClass = "MainKt"
    nativeDistributions {
      targetFormats(TargetFormat.Dmg, TargetFormat.Msi)
      packageName = "With Space"
    }
  }
}
```

the `packageDmg` target fails under 0.3.1 with a jpackage error:

```
Error: Invalid Option: [Space]
```

Note that the exact same name **works** with 0.3.0

**Comment by olonho** [comment]
@AlexeyTsvetkov any progress here?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6447">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
