### ISSUE TITLE
TextField cursor flickering when changing cursor position

### ISSUE THREAD

**Issue by Antimonit** [JetBrains/compose-jb#467]
When changing the cursor location with either arrow keys or by mouse, the cursor keeps flickering which makes it harder to keep track of the cursor location.

![GIF 6 3 21 10-26-17](https://user-images.githubusercontent.com/66991/110190400-68139100-7e23-11eb-84a3-dcdf1b795310.gif)

I'd expect the flickering state to be reset so that it always becomes visible, just like when inserting new characters:

![GIF 6 3 21 10-33-34](https://user-images.githubusercontent.com/66991/110190597-61394e00-7e24-11eb-8f96-147098425691.gif)

---

Compose version: 0.3.1

```
fun main() = Window(title = "Compose", size = IntSize(320, 240)) {
    MaterialTheme {
        val textState = remember { mutableStateOf("Jetbrains Compose TextField") }
        TextField(
            value = textState.value,
            onValueChange = { textState.value = it }
        )
    }
}
```

**Comment by akurasov** [comment]
I tried it on MacOs+245 and cursor is not flickering now. @igordmn, @prepor have we fixed it?

**Comment by Antimonit** [comment]
Just checked, in version 4.0.0 the issue is gone.

My best guess is that this was fixed as a part of https://android-review.googlesource.com/c/platform/frameworks/support/+/1578803.

Thanks ;)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6373">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
