### ISSUE TITLE
Navigation Up/Down within a TextField skips new lines and get stuck at the final new line. 

### ISSUE THREAD

**Issue by macorrales** [JetBrains/compose-jb#469]
I noticed the following behaviour when there are two consecutives new line (\n) at the end of the text.  To reproduce the issue input following text:

```
1
2
3


6

```
the internal AnnotatedString will look like

`text = "1\n2\n3\n\n\n6\n\n"
`

so if cursor is at the beginning ( `currentOffset = 0` ) and press key down, it navigates properly from 1 through 6. Between 6 and 1 you can navigate up as well. If you are at line 6 and press key down the cursor skips line 7 (no visible character) and is position at line 8.

Now if you press key up: it does not go up. It stays there. (You can escape this trap by pressing key left though)

I suspect the problem is at `TextLayoutResultProxy.visibleLineEnd` : 

![Screenshot_2021-03-06_16-25-05](https://user-images.githubusercontent.com/9871061/110211854-c6c72200-7e98-11eb-9364-d80bc99aa465.png)

I would love to contribute some testing code to demonstrate the problem but I can't find the repository. 

Is this code open source ? I did not find it in `androidx-main` nor in `github`, please show me where if it is out there.

**Comment by macorrales** [comment]
The  code  above is from `TextFieldKeyInput`

**Comment by prepor** [comment]
@macorrales thank you for investigating. TextField was recently refactored and should work better now (can you try 0.4.0-build173?). There are still some issues in Skia Paragraph which should be fixed soon https://bugs.chromium.org/p/skia/issues/detail?id=11321

**Comment by macorrales** [comment]
Now cursor moves up and down properly. That seems fixed.

However I found another issue:

```java
Exception in thread "AWT-EventQueue-0 @coroutine#1" java.lang.IllegalArgumentException: offset(-1) is out of bounds [0, 0)
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRange(MultiParagraph.kt:582)
	at androidx.compose.ui.text.MultiParagraph.getWordBoundary--jx7JFs(MultiParagraph.kt:426)
	at androidx.compose.ui.text.TextLayoutResult.getWordBoundary--jx7JFs(TextLayoutResult.kt:382)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset(TextPreparedSelection.kt:251)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset$default(TextPreparedSelection.kt:245)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.moveCursorPrevByWord(TextPreparedSelection.kt:167)
```

when you input  `CRTL + BACKSPACE`  to delete a whole word but the `TextField` is already empty. 

I believe the problem lies in `TextPreparedSelection`:
```kotlin
    private fun charOffset(offset: Int) =
        offset.coerceAtMost(originalText.length - 1)
```

I could not test all the corner cases.

thanks

**Comment by akurasov** [comment]
Ctrl+Backspace works fine on MacOs+245. @macorrales do you still have this issue?

**Comment by akurasov** [comment]
Seems it is fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6290">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
