### ISSUE TITLE
Todo example. Scrollbar is drawing outside of the list bounds, on top of the bottom panel

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#47]
![image](https://user-images.githubusercontent.com/5963351/98083762-e23f0380-1e8b-11eb-8e1c-4d819693f5cc.png)

See also https://github.com/JetBrains/compose-jb/pull/41

**Comment by igordmn** [comment]
Seems it isn't reproduced in 0.2.0-build130 anymore

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6514">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
