### ISSUE TITLE
HIDPI detection under Linux

### ISSUE THREAD

**Issue by adnan449** [JetBrains/compose-jb#471]
Currently JavaFX 17-EA has support for HIDPI in Linux. The default compose template app in the intellij lacks HIDPI in my Fedora Linux on GNOME with 200% UI scaling.

**Comment by igordmn** [comment]
Thanks for the report!

We aware of this issue. HiDPI support on Linux is important.

We tried to support this, but encountered some problems, so we put it aside for a while.

You can track progress [here](https://github.com/JetBrains/compose-jb/issues/188)

**Comment by floatingrain** [comment]
> Thanks for the report!
> 
> We aware of this issue. HiDPI support on Linux is important.
> 
> We tried to support this, but encountered some problems, so we put it aside for a while.
> 
> You can track progress [here](https://github.com/JetBrains/compose-jb/issues/188)

Actually, there's no progress there so far.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6345">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
