### ISSUE TITLE
Drag Window with undecorated = true

### ISSUE THREAD

**Issue by smallshen** [JetBrains/compose-jb#472]
How to make a window draggable when undecorated  set to true

**Comment by jimgoog** [comment]
This blog post is in Japanese but does a pretty good job of investigating exactly that question.  A combination of Google Translate and reading the code snippets (which are in english) may hopefully unblock you: https://matsudamper.hatenablog.com/entry/2021/02/08/025214

**Comment by smallshen** [comment]
> This blog post is in Japanese but does a pretty good job of investigating exactly that question. A combination of Google Translate and reading the code snippets (which are in english) may hopefully unblock you: https://matsudamper.hatenablog.com/entry/2021/02/08/025214

Thanks that helps a lot

**Comment by jimgoog** [comment]
Thanks to @matsudamper

**Comment by timt** [comment]
You can probably achieve something similar now using the WindowDraggableArea - see https://github.com/JetBrains/compose-jb/blob/master/tutorials/Window_API_new/README.md

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6130">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
