### ISSUE TITLE
Styles are not preserved during text editing with TextField

### ISSUE THREAD

**Issue by tchernykh** [JetBrains/compose-jb#473]
When editing styled text using TextField styles are removed after first edit, even after cursor position change.

![text-field-styles-issue](https://user-images.githubusercontent.com/8757071/110236693-5cdb7500-7f8b-11eb-9d6f-ebb2f718d952.gif)

```Kotlin
fun main() = Window {
    MaterialTheme {
        val tfValue = remember {
            mutableStateOf(
                TextFieldValue(
                    buildAnnotatedString {
                        pushStyle(SpanStyle(Color.Blue, fontWeight = FontWeight.Bold))
                        append("test")
                        pop()
                    }
                )
            )
        }
        TextField(tfValue.value, onValueChange = {
            tfValue.value = it
        })
    }
}
```
reproducible on versions: 0.3.2 and 0.4.0-build171
OS: MacOS

**Comment by prepor** [comment]
Hello. Thank you for the report. It's an upstream Compose problem, multistyle text editing isn't implemented yet, it's planned work. You can file an issue here https://issuetracker.google.com/issues?q=componentid:612128

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6458">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
