### ISSUE TITLE
How to remove ripple effect on Modifier.clickable()

### ISSUE THREAD

**Issue by smallshen** [JetBrains/compose-jb#475]
How to remove ripple effect on Modifier.clickable()

**Comment by igordmn** [comment]
Try this:

```
Modifier.clickable(interactionSource = remember(::MutableInteractionSource), indication = null)
```

@jimgoog,

Disabling the indication is a little verbose now :).

What do you think about adding an overload of `clickable` without `interactionSource` parameter?

```
fun Modifier.clickable(
    indication: Indication?,
    enabled: Boolean = true,
    onClickLabel: String? = null,
    role: Role? = null,
    onClick: () -> Unit
)= composed(
    inspectorInfo = debugInspectorInfo {
        name = "clickable"
        properties["enabled"] = enabled
        properties["onClickLabel"] = onClickLabel
        properties["role"] = role
        properties["onClick"] = onClick
    }
) {
    Modifier.clickable(
        enabled = enabled,
        onClickLabel = onClickLabel,
        onClick = onClick,
        role = role,
        indication = indication,
        interactionSource = remember { MutableInteractionSource() }
    )
}
```

Not so long ago 'interactionSource' was with a default value:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1544584/5/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/Clickable.kt#b64

**Comment by smallshen** [comment]
Thank you, it works.

**Comment by jimgoog** [comment]
I believe the ripple animation is setup when MaterialTheme is installed, which seems appropriate, and `LocalIndication` can be used to override this default behavior across the hierarchy.  Users can also work around the verbosity by creating their own overload.

That said, I don't see a reason why `Modifier.clickable`'s `interactionSource` parameter doesn't have a default value of `remember { MutableInteractionSource() }` instead forcing users to pass it in when they want to override the indication parameter.  I will raise this with API Council and see if I'm missing something.  @igordmn  - Thanks for pointing it out as an opportunity for polish.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6456">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
