### ISSUE TITLE
Compose for Desktop - Kiosk mode

### ISSUE THREAD

**Issue by nightrider77** [JetBrains/compose-jb#483]
It is more question rather than issue.
I need to make main (and the only one) window full-screen (kiosk mode) right after application launches.
And the window should be fixed in full screen mode.

This code doesn't do anything, I still can't understand why.

```
fun main() = invokeLater {
    AppWindow().show {
        AppManager.focusedWindow?.makeFullscreen()
    }
}
```

Any suggestions?

Thank you.

**Comment by igordmn** [comment]
Try

```
fun main() = invokeLater {
    val window = AppWindow()
    window.makeFullscreen()
    window.show {  }
}
```

**Comment by nightrider77** [comment]
> Try this
> 
> ```
> fun main() = invokeLater {
>     val window = AppWindow()
>     window.makeFullscreen()
>     window.show {  }
> }
> ```

Thank you, works perfectly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6455">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
