### ISSUE TITLE
Box behavior

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#488]
Not sure if is that normal behave when box out of another boxScope acting like inside? (1.4.31, 0.4.0-build173)
![Без имени-2](https://user-images.githubusercontent.com/80458677/111037974-8850da80-8437-11eb-9c52-b4f4ea0fd8bc.jpg)

**Comment by olonho** [comment]
What is Android behavior? What are your expectations?

**Comment by Exidel** [comment]
> What is Android behavior? What are your expectations?

Idk how it should be on Android.
I think padding should push 2nd box out to grab free space on the right but it acting like 2nd box can't move out of 1st box scope.

**Comment by Vahalaru** [comment]
It is because your starting your padding at 90 dp. Try left.

Jeremy Stotts

**Comment by Exidel** [comment]
Look the same example with Text()
![textOut](https://user-images.githubusercontent.com/80458677/111139865-b565d000-8592-11eb-8f30-4d2abd4f186e.jpg)
![textIn](https://user-images.githubusercontent.com/80458677/111139905-c0b8fb80-8592-11eb-9b60-9047ed655628.jpg)
Text Outside of BoxScope move free, Text INside of BoxScope can't move out of it. Box behave diffirent.
Actually now Modifier.padding for dox didn't work at all))

**Comment by Vahalaru** [comment]
That would be expected, if the text is inside the box that box becomes the
parent. Outside of the box the window is the parent. I'm to tired at the
moment to look to much into it but it has to be how your using padding. The
box composable is basically a container that let's all child or inner
composables stack on top of each other.

Jeremy Stotts

**Comment by Exidel** [comment]
1) Just findout what Box(Modifier.padding()) now working just for box inner content, before it was change box position in window.
2) Still not understand why Box, added right after other Box, become his child element and move inside it Scope?

**Comment by Vahalaru** [comment]
Just slapped my forehead. Use margin instead of padding

Jeremy Stotts

**Comment by Exidel** [comment]
> Just slapped my forehead. Use margin instead of padding

I'm very sorry for stupid question but just to be sure, which package in Compose for Desktop framework contains margin() function?

**Comment by Vahalaru** [comment]
Not a stupid question, aparently this is a missing feature or may be
intentional but there is no margin.  You can aparently accomplish the same
thing by channing your modifiers.
Here's a link that describes it.
https://stackoverflow.com/q/62939473/6915690

Order is very important.

Jeremy Stotts

**Comment by Exidel** [comment]
@Vahalaru thx a lot, that link was rly helfull. I didn't expect padding can act diffirent in diffirent positions. Somehow avoid this problem for few weeks while using padding everythere. Need to read more documentation before asking.

**Comment by Vahalaru** [comment]
Lol yeah tonight I might try and make an enhancement suggestion issue. I wouldn't of ever guessed that was how to do it. Not really an expected behavior. I'm sure it has to do with system limitations but some documentation wouldn't hurt.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6451">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
