### ISSUE TITLE
Modifier.pointerMoveFliter(onMove = {...}) does not called in nested composables

### ISSUE THREAD

**Issue by AntonAsmirko** [JetBrains/compose-jb#492]
<img width="836" alt="Screenshot 2021-03-13 at 22 50 47" src="https://user-images.githubusercontent.com/33885462/111042517-cefdff00-844e-11eb-8aea-bc7f02ec87fb.png">

on this screen onMove functions in both children composables were not invoked.

**Comment by AntonAsmirko** [comment]
sorry I i found solution)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6453">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
