### ISSUE TITLE
Add vertical slider

### ISSUE THREAD

**Issue by LAP2** [JetBrains/compose-jb#505]
Hi team, could you please add a vertical slider.

At that moment it could be only horizontal.

**Comment by olonho** [comment]
Could you please suggest that in Google's issue tracker, as this looks like generic component requirement.

**Comment by akurasov** [comment]
@LAP2, isn't androidx.compose.foundation.VerticalScrollbar what you need?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-505">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
