### ISSUE TITLE
Maven repo references missing files

### ISSUE THREAD

**Issue by Kernald** [JetBrains/compose-jb#507]
In `ui-text:0.3.2`'s [`pom` file](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-text/0.3.2/ui-text-0.3.2.pom) for example:

```
    <dependency>
      <groupId>org.jetbrains.compose.ui</groupId>
      <artifactId>ui-graphics</artifactId>
      <version>[0.3.2]</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
```

Looking at `ui-graphics:0.3.2` [here](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-graphics/0.3.2/), only a jar is found, no aar.

Some `pom` files are also missing their checksums, e.g. `desktop:0.3.2` [here](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/desktop/desktop/0.3.2/)

I suspect Gradle is mostly using the `.module` files, but this makes it tricky to integrate with other build systems.

**Comment by Kernald** [comment]
Woops sorry, I just found #479, closing this one.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6449">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
