### ISSUE TITLE
TextStyle lineHeight not working 

### ISSUE THREAD

**Issue by jershell** [JetBrains/compose-jb#508]
TextStyle `lineHeight` not working.  
Repo for reproduce https://github.com/jershell/compose-bugreport-reproduce
I attempt to set line-height to 3 em(before 30.sp) but happen nothing
```
Text(content, style = TextStyle(lineHeight = 3.em))
```
![image](https://user-images.githubusercontent.com/1238301/111600380-68783880-87e2-11eb-8f83-ea22eade0155.png)

OS: Ubuntu 20.04x64

java --version
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

Compose version: 
- 0.4.0-build174
- 0.3.2

**Comment by jershell** [comment]
Update
I had a test with "0.4.0-build184" on the desktop - not working.
Also, I tested the same version on Android  - working.

**Comment by jershell** [comment]
Update
I updated dependencies to 
Compose 0.5.0-build245
Kotlin 1.5.10
Gradle 6.9
line-height not working

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6395">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
