### ISSUE TITLE
ColorFilter tint not working on custom colors

### ISSUE THREAD

**Issue by sieveo** [JetBrains/compose-jb#512]
I'm using one of the built in icons in an image and trying to `ColorFilter.tint` it. The built in colors like `Color.LightGray` and `Color.Green` work fine. But as soon as I define a color myself, the icon disappears completely. 

```
Image(Icons.Default.AccountBox, contentDescription = "Account", Modifier.height(200.dp).width(200.dp), colorFilter = ColorFilter.tint(
            Color.Green))
```

Produces: 
![Screenshot from 2021-03-18 15-58-32](https://user-images.githubusercontent.com/52039901/111648897-265fee80-8804-11eb-82ab-a2444cad2945.png)

```
Image(Icons.Default.AccountBox, contentDescription = "Account", Modifier.height(200.dp).width(200.dp), colorFilter = ColorFilter.tint(
            Color(0xE3010F)))
```

Produces:
![Screenshot from 2021-03-18 16-11-18](https://user-images.githubusercontent.com/52039901/111649387-9d958280-8804-11eb-949a-768ed17f0c5b.png)

However it seems this has to to with the alpha of the color and the fact that there is a `shl` that results in the color getting an alpha of 0. So when I change the color to `0xFFE3010F` it works.

```
Image(Icons.Default.AccountBox, contentDescription = "Account", Modifier.height(200.dp).width(200.dp), colorFilter = ColorFilter.tint(
            Color(0xFFE3010F)))
````

Produces:
![Screenshot from 2021-03-18 16-11-56](https://user-images.githubusercontent.com/52039901/111649468-b140e900-8804-11eb-979e-8aaafd5c85dc.png)

I defined my colors in the `MaterialTheme` as per the documentation, and it works fine there, but when I want to used the `MaterialTheme.colors.primary` this does not work - above samples is just a simplification of this usecase. 
Should alpha be specified in the when configuring `MaterialTheme`? To my knowledge alpha is usually not specified.

**Comment by kirill-grouchnikov** [comment]
Color(0xE3010F) has zero alpha. How does your theme definition look like with custom colors?

**Comment by sieveo** [comment]
Like this:

```
val themeColors = lightColors(
        primary = Color(0xE3010F),
        primaryVariant = Color(0x9c000a),
        secondary = Color(0x333333),
        secondaryVariant = Color(0xB6B6B6),
    )
```

I am aware that it has zero alpha, but it works in the theme but not in the tint.

**Comment by olonho** [comment]
Does Android behave differently?

**Comment by sieveo** [comment]
I'm not sure. I'll test it out on Android and report back here.

**Comment by sieveo** [comment]
I can confirm, the behaviour is the same on Android as well. 
When I set up the minimal Android app from Android Studio Canary, I see that it automatically generated some theme and color Kotlin files, and in the `Color.kt` file the specified colors have their alpha specified. 

Following this convention I should probably also include the alpha in my Compose for Desktop app.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-512">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
