### ISSUE TITLE
Linux. Remove parent window animation on dialog open/close

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#513]
https://user-images.githubusercontent.com/5963351/111650749-a8591300-8816-11eb-8d4b-1bba66d49db0.mp4

(don't look at the green graphical artifacts, they appeared after I uploaded video on GitHub)

It is because we call `window.setResizable(false)`. For some reason there is an animation on Linux.

Also notice that we can interact with parent window.

**Comment by Sintrastes** [comment]
I can't play the video, because github says it's corrupt, but I think I am experiencing a similar issue. Whenever I open a dialog, the main window looks like it closes, then immediately re-opens. I thought maybe the issue was with my code, but this happens for this sample code from this repo as well:

```
fun main() = Window {
    val dialogState = remember { mutableStateOf(false) }

    Button(onClick = { dialogState.value = true }) {
        Text(text = "Open dialog")
    }

    if (dialogState.value) {
        Dialog(
            onDismissRequest = { dialogState.value = false }
        ) {
            // Dialog's content
        }
    }
}
```

**Comment by Sintrastes** [comment]
I can play the video now. Can confirm that I am experiencing the same issue.

**Comment by igordmn** [comment]
Should be fixed for [Dialog's in new Composable API](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new#dialogs)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6349">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
