### ISSUE TITLE
Material Toggle Button

### ISSUE THREAD

**Issue by Inego** [JetBrains/compose-jb#522]
It seems the Material Design's [Toggle Button](https://material.io/components/buttons) is not available, although the Outlined Button is. Are there plans to support it?

**Comment by c5inco** [comment]
The Material components are inherited from the Compose Material library, so it's better to ask this question on issue tracker for Compose or in kotlin-lang #compose slack channel.

**Comment by Inego** [comment]
You're right. There is a bug in Compose Material library about Toggle Button:
https://issuetracker.google.com/issues/173038382

Closing this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5473">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
