### ISSUE TITLE
Dialog always keep on top of other windows

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#526]
Even become unselected it always on top of other windows not associated with the program. `Dialog` inherited this behavior from android parent. For desktop it doesn't needed.

**Comment by olonho** [comment]
Guess it's intended behavior of modal dialog.

**Comment by Exidel** [comment]
`Window` and `AppWindow` doesn't lock main Window, thats may allow some problems. `Dialog` and `AlertDialog` lock it but also always stay on top. Mb there another types of windows which i didn't use yet but better separate "keep on top" as additional function parametr.

**Comment by Exidel** [comment]
Since M4 released and new **`androidx.compose.ui.window.Window`** added with additional **`alwaysOnTop`** and **`enabled`** parameters this issue no longer make sense.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5470">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
