### ISSUE TITLE
DisposableEffect.onDispose not called when closing the Window

### ISSUE THREAD

**Issue by opatry** [JetBrains/compose-jb#527]
Given an app like that:

```kotlin
fun main() {
    Window(
        size = IntSize(800, 600),
        onDismissRequest = {
            println("Window.onDismissRequest CALLED")
        }
    ) {
        var clickCount by remember { mutableStateOf(0) }
        if (clickCount < 5) {
            DisposableEffect(Unit) {
                onDispose {
                    println("DisposableEffect.onDispose CALLED")
                }
            }
            Text("Hello World! $clickCount", Modifier.clickable { ++clickCount })
        } else {
            Text("Clicked too much! $clickCount")
        }
    }
}
```

If you click 5 times on the label, you'll see `DisposableEffect.onDispose CALLED`, then close the Window, `Window.onDismissRequest CALLED` will be displayed.
Until then, it's 100% fine.

If you don't click 5 times on the label and simply close the Window, you'll see `DisposableEffect.onDispose` isn't called.

**Comment by olonho** [comment]
What OS shows this behavior?

**Comment by opatry** [comment]
I'm running macOS Catalina.
I can try on Big Sur if that helps, let me know.

**Comment by GooKv** [comment]
Could reproduce on Windows.
As far as I debugged it, recomposition is not performed on window close, but DisposableEffect requires recomposition to be executed to verify **forgotten** state and execute Dispose callback.

**Comment by akurasov** [comment]
NB: To reproduce on Alpha

**Comment by akurasov** [comment]
In new window API there is onCloseRequest function parameter, that is called when window is closed. onDismissRequest is not available anymore.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5469">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
