### ISSUE TITLE
Binary build of example app?

### ISSUE THREAD

**Issue by whereistimbo** [JetBrains/compose-jb#53]
I'd like to see one for Windows please.

**Comment by olonho** [comment]
We're not currently plan to provide such binary builds, but they are rather simple to build yourself.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6407">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
