### ISSUE TITLE
Need a menu that can set absolute position

### ISSUE THREAD

**Issue by gtf35** [JetBrains/compose-jb#539]
Now we can listen right click and get positon when right click, but `DropdownMenu` can't set position.

This will cause the current menu to appear not under the mouse pointer.

What should I do?

**Comment by Exidel** [comment]
Can you say pls where you found right click mouse event?

**Comment by gtf35** [comment]
@Exidel

Document [here](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events#mouse-rightmiddle-clicks-and-keyboard-modifiers)

My code is [here](https://github.com/JetBrains/compose-jb/issues/540)

**Comment by Exidel** [comment]
Don't understand clearly all that AWT functions and classes but find a way to open dropdownMenu under mouse cursor. Also thx for doc link.

There in example code `Text("Mouse event: ${lastEvent?.paramString()}")` which show all mouse event param, if you look closer there window position and global screen position. `lastEvent`, as i understand, contain a list with parametrs from last mouse event. U can take this parametrs from it. For local window position which you need u can use `lastEvent?.point?.x` and `lastEvent?.point?.y`  In a place where you will use this don't forget create `if (lastEvent?.point?.x != null && lastEvent?.point?.y != null)` to use as `Int`. I use `padding` with that `x` and `y` on `dropdownMenu` to set it position, look like it attached to place where opened.


https://user-images.githubusercontent.com/80458677/112762112-ca1c7c00-9006-11eb-8968-3f96889b415a.mp4

**Comment by prepor** [comment]
CursorDropdownMenu implements this

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5458">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
