### ISSUE TITLE
Long dropdown menu gets cut off

### ISSUE THREAD

**Issue by jollygreenegiant** [JetBrains/compose-jb#541]
When creating a `DropdownMenu` that has a long list of `DropdownMenuItem`s, if the list is long enough that the popup extends past the edges of the window, the list gets cut off.  I'd like to see a way to create a scrollable dropdown menu, or be able to give it a fixed height with automatic scrolling capability.

Here is how I'm creating the `DropdownMenu`:
```
DropdownMenu(
    expanded = isExpanded,
    onDismissRequest = { isExpanded = false }
) {
    LazyColumn {
        itemsIndexed(
            items = menuItemList,
            itemContent = { index, item ->
                DropdownMenuItem(onClick = {
                    selectedIndex = index
                    isExpanded = false
                }) {
                    Text(index.toString())
                }
            }
        )
    }
}
```

When that list is long enough to extend past the contraints of the window, it just gets cut off and is not scrollable.  Is there a way to make it scrollable or is that not possible yet?  Is there another recommended way of handling long selectable lists of data?

**Comment by Exidel** [comment]
DropdownMenu doesn't need LazyColumn inside, dropped menu it's ColumnScope so it's scrollable as default. Also you can modify your dropped menu length with Modifier.size/height.

```
                Box(   
                    modifier = Modifier
                        .size(70.dp, 50.dp)
                        .wrapContentSize(Alignment.TopStart)
                ) {
                    Text(
                        text = "anyList[varIndex]",
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable(onClick = { someBooleanVariable = true })
                    )

                    DropdownMenu(
                        expanded = dropMenuSeries,
                        onDismissRequest = { someBooleanVariable = false },
                        modifier = Modifier
                            .size(70.dp, 250.dp)
                    ) {
                        anyList.forEachIndexed { index, element ->
                            DropdownMenuItem(onClick = {
                                varIndex = index
                                someBooleanVariable = false
                            }) { Text(text = "$element") }
                        }
                    }
                }
```

**Comment by jollygreenegiant** [comment]
I had no idea it would be so easy, or that ColumnScope was scrollabel by default.  Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5456">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
