### ISSUE TITLE
Set NSSupportsAutomaticGraphicsSwitching for Mac apps

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-jb#545]
See https://bugs.openjdk.java.net/browse/JDK-8180174

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5453">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
