### ISSUE TITLE
Scrollbars. Scrollbar stops moving when we move cursor out of the window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#549]
Compose 0.4.0-build178, Windows 10

https://user-images.githubusercontent.com/5963351/113113219-be050a00-9212-11eb-994f-c93767f94d5c.mp4

As far as I remember in 0.3.2 scrollbar is moving if we even move cursor out of the window.

To reproduce run `./gradlew run1 -Pandroidx.compose.multiplatformEnabled=true` in Compose source code

**Comment by igordmn** [comment]
See also https://github.com/JetBrains/compose-jb/issues/550

Reverting https://android-review.googlesource.com/c/platform/frameworks/support/+/1652612 fixes this issue

**Comment by igordmn** [comment]
Fixed in 0.4.0-build190

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5451">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
