### ISSUE TITLE
Scrollbars. Scrollbar doesn't move if we hover it very fast

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#550]
Compose 0.4.0-build178, Windows 10

https://user-images.githubusercontent.com/5963351/113114160-bd20a800-9213-11eb-8938-1ebc80d6adfb.mp4

Scrollbar should immediately move when we hover it, press mouse button, and move mouse up/down

To reproduce run `./gradlew run1 -Pandroidx.compose.multiplatformEnabled=true` in Compose source code

**Comment by igordmn** [comment]
See also https://github.com/JetBrains/compose-jb/issues/549

Reverting https://android-review.googlesource.com/c/platform/frameworks/support/+/1652612 fixes this issue

**Comment by igordmn** [comment]
Fixed in 0.4.0-build190

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5450">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
