### ISSUE TITLE
Update ImmutableCollections to 0.3.4

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#557]
Currently, `0.3.3` is required, which is hosted on jCenter. `0.3.4` is hosted on mavenCentral.

Workaround: Bump the version manually
```kotlin
implementation("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.4")
implementation(compose.runtime)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5446">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
