### ISSUE TITLE
"Unknown OS arch: x86" when running from command line

### ISSUE THREAD

**Issue by DetachHead** [JetBrains/compose-jb#560]
build.gradle.kts:
```kt
println("arch is ${System.getProperty("os.arch")}")
dependencies {
    implementation(compose.desktop.currentOs)
}
```

when running gradle from the command line, all commands fail on `implementation(compose.desktop.currentOs)` due to the following error:

```
Unknown OS arch: x86
```
![image](https://user-images.githubusercontent.com/57028336/113472234-2ff48200-94a5-11eb-9250-0e988a88a401.png)

works when running from intelliJ, as `System.getProperty("os.arch")` returns `amd64` instead:

![image](https://user-images.githubusercontent.com/57028336/113472288-92e61900-94a5-11eb-8538-24c3bb9691e1.png)

**Comment by DetachHead** [comment]
oops

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5444">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
