### ISSUE TITLE
Closing previous window without exit all application

### ISSUE THREAD

**Issue by SnorSnor9998** [JetBrains/compose-jb#561]
im currently trying Jetpack Compose Desktop but my question is how to close/dismiss/dispose the first window and calling the second window without shutting the whole program down 

https://user-images.githubusercontent.com/56662976/113516593-aa102e00-95ad-11eb-8101-10c1fb960c77.mp4

**Comment by SnorSnor9998** [comment]
I found my answer, at the second Window "AppManager.windows[0].close()" will close the first window

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5443">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
