### ISSUE TITLE
Unresolved reference: ktor

### ISSUE THREAD

**Issue by gagarin55** [JetBrains/compose-jb#568]
Hello, 
I've created Multiplatform Project for Jetbrains Compose (New -> Project -> Kotlin -> Jetpack Compose for Desktop -> Multiplatform) from IntelliJ IDEA 2021.1 (Ultimate Edition)

The only code I've added in `commonMain/build.gradle.kts`
```
                implementation("io.ktor:ktor-client-core:1.5.2")
                implementation("io.ktor:ktor-client-cio:1.5.2")
                implementation("io.ktor:ktor-client-serialization:1.5.2")
```

It looks like

```
import org.jetbrains.compose.compose

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose") version "0.3.1"
    id("com.android.library")
    id("kotlin-android-extensions")
}

group = "io.cmpny"
version = "1.0"

repositories {
    google()
}

kotlin {
    android()
    jvm("desktop") {
        compilations.all {
            kotlinOptions.jvmTarget = "11"
        }
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material)

                implementation("io.ktor:ktor-client-core:1.5.2")
                implementation("io.ktor:ktor-client-cio:1.5.2")
                implementation("io.ktor:ktor-client-serialization:1.5.2")
...
```

Now, when I import `io.ktor.*` it says : **Unresolved reference**

It seems that such error occurs only for **Ktor Framework** import, others imports are OK

**Comment by olonho** [comment]
It has nothing to do with Compose: ktor server (unlike ktor client) is not multiplatform, so cannot be used from common code.

**Comment by olonho** [comment]
See https://github.com/JetBrains/compose-jb/blob/master/examples/issues/common/build.gradle.kts for solving similar issue.

**Comment by gagarin55** [comment]
> It has nothing to do with Compose: ktor server (unlike ktor client) is not multiplatform, so cannot be used from common code.

I though this is problem of _Jetpack Compose for Desktop_ project generator.
And I don't use ktor server, only ktor core.

**Comment by gagarin55** [comment]
> See https://github.com/JetBrains/compose-jb/blob/master/examples/issues/common/build.gradle.kts for solving similar issue.

Sorry, didn't get how it helps.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5440">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
