### ISSUE TITLE
WindowEvents should be designed to allow delegation

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#571]
Currently, `WindowEvents` is a regular class, but this makes it hard to chain if necessary.

For example, I have my own window (which is responsible for showing the user a paint canvas, named `CanvasWindow`) that allows the user to pass in its own window events. The caller uses this to do some logging / logic on various events. But the canvas window additionally wants to listen to the `onClose` event itself.

If `WindowEvents` was an interface or data class, this wouldn't be an issue.

For example, I'd be happy doing this (if `WindowEvents` was a data class):

```
@Composable
fun CanvasWindow(events: WindowEvents) = Window(
   events = events.copy(
      onClose(() -> events.onClose?.invoke(); handleClose())
   )
}
``` 

or something like this (if `WindowEvents` was an interface):

```
class CanvasWindowEvents(private val wrapped: WindowEvents) : WindowEvents by wrapped {
   @override fun onClose() {
      wrapped.onClose()
      handleClose()
   }
}

@Composable
fun CanvasWindow(events: WindowEvents) = Window(
   events = CanvasWindowEvents(events)
```

**Comment by bitspittle** [comment]
It's ugly (defines callbacks it doesn't need to) and fragile (will break if an event is ever added into the API) but my current workaround is to define a plus extension method:

```
operator fun WindowEvents.plus(other: WindowEvents): WindowEvents {
    return WindowEvents(
        onOpen = { this.onOpen?.invoke(); other.onOpen?.invoke() },
        onClose = { this.onClose?.invoke(); other.onClose?.invoke() },
        onMinimize = { this.onMinimize?.invoke(); other.onMinimize?.invoke() },
        onMaximize = { this.onMaximize?.invoke(); other.onMaximize?.invoke() },
        onRestore = { this.onRestore?.invoke(); other.onRestore?.invoke() },
        onFocusGet = { this.onFocusGet?.invoke(); other.onFocusGet?.invoke() },
        onFocusLost = { this.onFocusLost?.invoke(); other.onFocusLost?.invoke() },
        onResize = { intSize -> this.onResize?.invoke(intSize); other.onResize?.invoke(intSize) },
        onRelocate = { intOffset -> this.onRelocate?.invoke(intOffset); other.onRelocate?.invoke(intOffset) },
    )
}
```

It's possible this approach could also be worth handling in the library, as by being there, it's more likely to be kept up to date in case of future event additions.

Although if official, you probably want to avoid creating lambdas you don't need to, so instead maybe you'd do:

```
   onClose = if (this.onClose != null || other.onClose != null) { ... } else null
```

**Comment by igordmn** [comment]
This is no longer relevant with the [new Window API](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new).

If you have any issues with it, let us know.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5437">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
