### ISSUE TITLE
API missing a way to prevent a window from closing?

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#572]
In my `Window`, I want to prevent users from exiting if there is a modification and they should save their work first.

In other words, I'd like to support the following flow:

* User opens a window
* User edits some data, forgets to save
* User presses the (X) button (or selects File > Exit, or some path that calls `window.close()`)
* A dialog pops up and says: "You will lose unsaved data if you continue. [ Cancel ] [ OK ]"
* User presses cancel: dialog closes, window stays open
* User presses OK: dialog closes, window closes

One possible way to handle this would be to add a new event to WindowEvents, like `onClosing: () -> Boolean` (or `onBeforeClose` or whatever is consistent naming convention with JetpackCompose).

Another possible way would be if `AppFrame` or `AppWindow` exposed a property that allowed me to override closing behavior.

**Comment by akurasov** [comment]
@olonho isn't it implemented in notepad example?

**Comment by igordmn** [comment]
This is implemented in the new Window API, yes. When it will be no longer Experimental, I beleive we can close this issue

**Comment by bitspittle** [comment]
If it's already coming down the line, then I'm OK if you close this now. When I opened it, there wasn't a way which seemed like an oversight, or at least an unimplemented feature due to the newness of the library. Up to you!

**Comment by igordmn** [comment]
>When it will be no longer Experimental, I beleive we can close this issue

This is no longer experimental.

See https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new#open-and-close-windows

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5436">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
