### ISSUE TITLE
Is there any way to dump Canvas to a picture file?

### ISSUE THREAD

**Issue by sumy7** [JetBrains/compose-jb#574]
I want to save what I draw on the canvas. but didn't find any API to do it. Did I miss something?

**Comment by olonho** [comment]
One way is to see how our screenshot tests are organized: https://github.com/JetBrains/androidx/blob/androidx-main/compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/platform/GraphicsLayerTest.kt

**Comment by sumy7** [comment]
@akurasov Sorry forgot to reply. This is not an effective method, because some methods are not available in Canvas class.

**Comment by akurasov** [comment]
@sumy7 
I'm a bit lost. How methods absent in Canvas class relate to your original question? And what exactly is missing?

**Comment by sumy7** [comment]
@akurasov 
Hi, **akurasov**.
First of all, I want to get image bits from Canvas. It is good if there is some method like `canvas.getBitmap()` to get all Pixels on Canvas. But there is no such method.
So I opened this issue, and **olonho** give me screenshot tests. I notice that _GraphicsLayerTest.kt_ has it's own **TestComposeWindow** and take screenshot from it. But this method is too troublesome, and I could not find some method to simply it. So the issue has been put on hold.

In addition, I thought about some other methods, but did not verify whether it is feasible.

1. Implement my own MyCanvas, and replay DrawScope on it. In my control, I could get screenshot from MyCanvas.
2. Get _skija_ instance from DesktopCanvas, and dump Pixels from it.

If I follow **olonho** tests method, how could I get picture from canvas?
Is my method what i thought feasible?
Is there anything else I haven’t noticed?

**Comment by akurasov** [comment]
@sumy7 maybe Canvas.readPixels is what you need?

**Comment by akurasov** [comment]
Closing as inactive

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5434">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
