### ISSUE TITLE
run "compose-jb/examples/issues" crash

### ISSUE THREAD

**Issue by hply** [JetBrains/compose-jb#575]
2021-04-09 17:19:51.897 java[45802:560002] +[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x103e603e0
2021-04-09 17:19:51.899 java[45802:560002] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x103e603e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff204ce6af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff202063c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20550bdd __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff2043607d ___forwarding___ + 1467
	4   CoreFoundation                      0x00007fff20435a38 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff20449fec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff204e589b ___CFXRegistrationPost_block_invoke + 49
	7   CoreFoundation                      0x00007fff204e580f _CFXRegistrationPost + 454
	8   CoreFoundation                      0x00007fff2041abde _CFXNotificationPost + 723
	9   Foundation                          0x00007fff21189abe -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	10  AppKit                              0x00007fff2301b812 __NSSelectedKeyboardInputSourcesChangedNotification + 58
	11  CoreFoundation                      0x00007fff20449fec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	12  CoreFoundation                      0x00007fff204e589b ___CFXRegistrationPost_block_invoke + 49
	13  libdispatch.dylib                   0x00007fff201b05dd _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007fff201b17c7 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007fff201bdb86 _dispatch_main_queue_callback_4CF + 940
	16  CoreFoundation                      0x00007fff20491970 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x00007fff20453852 __CFRunLoopRun + 2731
	18  CoreFoundation                      0x00007fff204526ce CFRunLoopRunSpecific + 563
	19  HIToolbox                           0x00007fff286da630 RunCurrentEventLoopInMode + 292
	20  HIToolbox                           0x00007fff286da42c ReceiveNextEventCommon + 709
	21  HIToolbox                           0x00007fff286da14f _BlockUntilNextEventMatchingListInModeWithFilter + 64
	22  AppKit                              0x00007fff22c729b1 _DPSNextEvent + 883
	23  AppKit                              0x00007fff22c71177 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
	24  libosxapp.dylib                     0x0000000103ea491e -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	25  AppKit                              0x00007fff22c6368a -[NSApplication run] + 586
	26  libosxapp.dylib                     0x0000000103ea4763 +[NSApplicationAWT runAWTLoopWithApp:] + 222
	27  libawt_lwawt.dylib                  0x0000000103e26141 +[AWTStarter starter:headless:] + 834
	28  JavaNativeFoundation                0x00007fff6f74f70f +[JNFRunLoop _performCopiedBlock:] + 15
	29  Foundation                          0x00007fff212004d9 __NSThreadPerformPerform + 204
	30  CoreFoundation                      0x00007fff20454a0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	31  CoreFoundation                      0x00007fff20454974 __CFRunLoopDoSource0 + 180
	32  CoreFoundation                      0x00007fff204546ef __CFRunLoopDoSources0 + 248
	33  CoreFoundation                      0x00007fff20453121 __CFRunLoopRun + 890
	34  CoreFoundation                      0x00007fff204526ce CFRunLoopRunSpecific + 563
	35  libjli.dylib                        0x00000001038c85f6 CreateExecutionEnvironment + 399
	36  libjli.dylib                        0x00000001038c4787 JLI_Launch + 1315
	37  java                                0x00000001038afb6f main + 367
	38  libdyld.dylib                       0x00007fff20377621 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by olonho** [comment]
Would be really good to know what lead to this crash.

**Comment by m-sasha** [comment]
This is most like the same as https://github.com/JetBrains/compose-jb/issues/940
What leads to the crash seems to be a change in the selected input source on Mac OS X.

**Comment by igordmn** [comment]
See [this comment](https://github.com/JetBrains/compose-jb/issues/940)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5433">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
