### ISSUE TITLE
Application won't to run if there russian characters in path

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#577]
Kotlin v1.4.32, compose 0.4.0-build180, Windows10
Have 2x SSD and 1x HDD. On both SSD installed application work, on HDD not.

Additionally this function when run app in IDE downloading image from URL and save into folder, when installed - not.
```
fun loadImg(url: String) {
    val img = ImageIO.read(URL(url))
    ImageIO.write(img, "jpg", File("MyImg.jpg"))
}
```

**Comment by jimgoog** [comment]
I'm a little confused.  Is this one issue (all your comments are related) or two issues (one dealing with HDD/SSD, and another dealing with fetching URLs from IDE vs Packaged)?  Can you be a lot more detailed (write out HDD and SSD if they indeed mean something other than Hard Disk Drive and Solid State Drive) and provide full stack traces?

Assuming this is intended to be two separate issues...

1. The first issue seems confusing/surprising.  I don't think Compose would care (or even know the difference) if executed from a SSD or HDD.  Is there a full stack trace available or what do you mean when you say "On both SSD installed application work, on HDD not."
2. Fetching URLs from a packaged app failing looks like a duplicate of https://github.com/JetBrains/compose-jb/issues/429 and thus potentially related to https://github.com/JetBrains/compose-jb/issues/463 ?

**Comment by Exidel** [comment]
My fault, didn't check everything before write. It's not hard drive problem, it's about russian symbols in path.

About downloading images it was just a question, cos i'm understand what it's not `compose` problem but can't find info. Thx for links.

**Comment by olonho** [comment]
What kind of error do you see? Is it native distribution or just Gradle run task?

**Comment by olonho** [comment]
Tested on macOS that both `./gradlew run` and `./gradlew  runDistributable` in folder `/Users/Nikolay.Igotti/compose/визард3` works just fine.

**Comment by Exidel** [comment]
I was tested it on stand alone app, window opened without content and instantly closed. Will check gradle task soon.

**Comment by Exidel** [comment]
UPD: task `run` work fine, task `runDistributable` throw exception: 

```
A problem was found with the configuration of task ':createDistributable' (type 'AbstractJPackageTask').
> Directory 'C:\Users\UserName\Desktop\��������������\GUITest\build\compose\tmp\main\runtime' specified for property 'runtimeImage' does not exist.
```

**Comment by malliaridis** [comment]
@Exidel This is a general Gradle issue, you should therefore avoid (if possible) using non-ascii characters for paths or file encodings. I had similar issues with non-ascii project paths. Gradle cannot handle properly non-ascii characters. Same applies for file encodings like ISO-8859-1 on Windows.

I reproduced similar behavior by creating a project, placing it in an ASCII-restricted path, executing it once (making sure everything works fine) and moving it later to a non-ascii path, clearing the cache try to rebuild and execute the main class. The `Error: Could not find or load main class MainKt` occurred. Recreating the project directly into non ascii path caused the same issue.

Also doing an invalid change to the gradle file and syncing it caused an output that showed the path like this:
`C:\Users\Christos\workspace\temp\???????????\nonasciipath\build.gradle.kts:14:5: ...`

**Comment by olonho** [comment]
What will happen if you run native distribution without Gradle task?

**Comment by malliaridis** [comment]
Since I am not yet that deep into the matter of compiler and so on, I guess you probably want me to run something like `kotlinc-native main.kt -o main`, right? 

I could yet only find `kotlinc` and execute it as follow:
```bash
$ cd ~/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111/plugins/Kotlin/kotlinc/bin
$ ./kotlinc ~/workspace/temp/лмнпрελλσδη/nonasciipath/src/main/kotlin/main.kt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
error: source file or directory not found: C:/Users/Christos/workspace/temp/?????e??sd?/nonasciipath/src/main/kotlin/main.kt
```

By having the project outside of the non-ascii character path I get only unresolved references:
```bash
$ ./kotlinc ~/workspace/temp/nonasciipath/src/main/kotlin/main.kt
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ONLY A BUNCH OF UNRESOLVED REFERENCES]
```

Hope that answers at least partly your question.

**Comment by Exidel** [comment]
Running native distributive in rus named folder work fine now, but runDistributable still throw same exception and create new folder (what ectually not a problem for me cos nobody in sane will create a project folder with name other than english).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5431">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
