### ISSUE TITLE
Material Icons not implemented

### ISSUE THREAD

**Issue by blacpythoz** [JetBrains/compose-jb#58]
It seems material icon is not implemented on this release.

```kotlin
     Row {
                    Text(
                        text = "Help",
                        fontSize = 12.sp,
                        modifier = Modifier.padding(start=16.dp))
                    Icon(asset = Icons.Outlined.MoreVert)
                }
```

Got this error: [here](https://pastebin.com/qAU91P5S)

**Comment by igordmn** [comment]
Probably you have created project from IDEA Wizard?

Try to change the version of compose Gradle plugin to "0.1.0-m1-build62".

In this version Icons should be implemented.

**Comment by blacpythoz** [comment]
yeap, its working now. Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6530">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
