### ISSUE TITLE
TextField or State variable issue

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#580]
Sometimes (too often tbh) entered value didn't show in text field until GUI refresh triggered or just lost. There is no exceptions.
On video it's just `TextField` but same behavior affect on `OutlinedTextField` too.

https://user-images.githubusercontent.com/80458677/114323518-4302f400-9b2e-11eb-9715-3473b7d5074b.mp4

```
fun main() = Window(title = "Compose for Desktop", size = IntSize(500, 500)) {

    var text by remember { mutableStateOf("")}
    var otherTxt by remember { mutableStateOf("")}

    Box(Modifier.fillMaxSize().background(Color.White)) {

        Column (Modifier.padding(top = 40.dp).align(Alignment.TopCenter)) {
            TextField(
                value = text,
                onValueChange = {text = it},
                colors = textFieldColors(backgroundColor = Color.LightGray),
                singleLine = true
            )

            OutlinedTextField(
                value = otherTxt,
                onValueChange = {otherTxt = it},
                singleLine = true,
                label = {Text("LABEL test")},
                modifier = Modifier.padding(top = 10.dp),
                colors = outlinedTextFieldColors(
                    backgroundColor = Color.LightGray
                )
            )
        }
    }
}
```
It also can be gradle problem cos need `run` app again and again to catch this issue.

**Comment by akurasov** [comment]
I tried it with the latest build and MacOs and everything is fine. 

What is the Compose version you are using and what is the OS?

**Comment by Exidel** [comment]
@akurasov system: Windows 10, last time I tried it on 0.4.0-225 if I remember right. Compare to this #888 the problem with TextField still exist. Any way will try reproduce it with 0.5.0-build245.

**Comment by akurasov** [comment]
@Exidel I doubt much changed between 225 and 245. I will try it on Mac with 225 and will try to reproduce it on my Win laptop. Thank you!

**Comment by akurasov** [comment]
BTW, what jvmTarget do you use?

**Comment by akurasov** [comment]
There some issues with JVM11. Could you try it with jvmTarget="15"?

**Comment by Exidel** [comment]
Sure, will try it a bit later.

**Comment by Exidel** [comment]
Ok, I reproduced it again very quickly, actually both results with full unrendered text till another element trigger UI redraw and partically losed entered text.

```
plugins {
    kotlin("jvm") version "1.5.10"
    id("org.jetbrains.compose") version "0.5.0-build245"
}
tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "15"
}
```

**Comment by akurasov** [comment]
thank you! Will try to reproduce it here too.

**Comment by Exidel** [comment]
Can't reproduce in v1.1.1,  jvmTarget = "15". May be more complex app will cause this problem as mentioned here #888 but my own ~1000 strings app work fine.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5428">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
