### ISSUE TITLE
Mouse release event is lost if you press more than one mouse button at a time.

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#581]
To reproduce, create a new project and replace your main function with the following code:

```
fun main() = Window("Button Bug") {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .pointerInput(Unit) {
                while (true) {
                    awaitPointerEventScope {
                        val pointerEvent = awaitPointerEvent()
                        println(pointerEvent.mouseEvent)
                    }
                }
            }
    )
}
```

Then, run the app, and when the window opens, anywhere within it, do the following:

* Press and hold the left mouse button
* Press and hold the right mouse button
* Release the right mouse button
* Release the left mouse button

When I do this, I get the following output (no release event for the left button):

```
java.awt.event.MouseEvent[MOUSE_PRESSED,...,button=1,...]
java.awt.event.MouseEvent[MOUSE_PRESSED,...,button=3,...]
java.awt.event.MouseEvent[MOUSE_RELEASED,...,button=3,...]
```

And if I do left down, right down, left up, right up, it still happens (no release event for the right button):

```
java.awt.event.MouseEvent[MOUSE_PRESSED,...,button=1,...]
java.awt.event.MouseEvent[MOUSE_PRESSED,...,button=3,...]
java.awt.event.MouseEvent[MOUSE_RELEASED,...,button=1,...]
```

**Comment by akurasov** [comment]
Reproduced on Alpha build

**Comment by igordmn** [comment]
Not sure, but the bug can be located [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/DesktopOwners.desktop.kt;l=157;drc=9ee96164f86d7726ba14f2f8ef2f2535a7b987d1). We don't distinguish between left/right/etc clicks there.

**Comment by bitspittle** [comment]
For reference, here's my own code where I worked around the bug at the time: https://github.com/bitspittle/paintkit/blob/a68a9017e1a62b8e2bc406e6a796913a1975db3a/client/src/main/kotlin/bitspittle/paintkit/input/MouseUtils.kt#L25

I've since put that project on hold for a few months now, so it's running against a pretty old version of compose, no idea if the approach would even compile with latest.

**Comment by igordmn** [comment]
I have reproduced it in 1.0.0-alpha3, but can't reproduce it in 1.0.0-beta5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6219">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
