### ISSUE TITLE
Can't use android gradle plugin 7  with multiplatform template

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#584]
I'm attempting to use com.android.tools.build:gradle:7.0.0-alpha01 - alpha12 and all of them fail with different error messages.

01 fails with

> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.

12 fails with

> An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 6.8.2. Current version is 6.7.1. If using the gradle wrapper, try editing the distributionUrl in /Users/ernestg/Dev/MinimalComposeMultiplatform/gradle/wrapper/gradle-wrapper.properties to gradle-6.8.2-all.zip

So if I try to update gradle to 6.8.2, and THEN updating to alpha12, which you are greeted with this issue

> Configuration with name 'testApi' not found.

Solved by: https://stackoverflow.com/questions/65372825/kotlin-multiplatform-configuration-issue

After applying the solution above you get hit with

> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2020.3.1 or newer.

**Comment by malliaridis** [comment]
_tl;dr_
I reproduced your issue. Upgrading your IDE to an unstable version (e.g. Android Studio to version Arctic Fox 2020.3.1 14) will probably fix your issue.

_Steps to reproduce and fix the issue_
_Actual message_
I tried to reproduce your issue by using 
* Gradle 7.0.0-alpha14
* `org.jetbrains.compose` version `0.4.0-build180`

and got too the "Configuration with name 'testApi' not found.". 

After adding to the `build.gradle.kts` from the `:common` module the following lines:

``` kotlin
android {
  // ...
      configurations {
        create("testApi")
        create("testDebugApi")
        create("testReleaseApi")
    }
}
```

I got the last error message. Then I just updated my Android Studio (might work as well for IntelliJ IDEA) to the canary (unstable) version Arctic Fox 2020.3.1 14 and the error disappeared.

**Comment by ColtonIdle** [comment]
Interesting. I didn't know that I should be using AS over intellij. Either way... maybe better error messaging would be helpful here.

**Comment by malliaridis** [comment]
I didn't say that you should use Android Studio over IntellIJ IDEA, I just tested it on that IDE since it is based on IntellIJ IDEA and should work the same. The same however applies for IntelliJ IDEA. I just didn't want to upgrade IntelliJ IDEA to a probably unstable version just to test if it works.

But with that being said, I think I would personally prefer Android Studio if you develop cross-platform including android, because the IDE is pretty well optimized for android. But I don't know if `compose-jb` is supposed to work there too without further configurations.

Did the solution above solved your problem @ColtonIdle?

**Comment by malliaridis** [comment]
Btw. I just found this issue:
https://github.com/android/compose-samples/issues/144

@olonho if the statement that is [mentioned by nickbutcher](https://github.com/android/compose-samples/issues/144#issuecomment-688168992) applies for this project too, shouldn't we mention it also in the README.md?

**Comment by ColtonIdle** [comment]
As of 0.4.0 that I tried today, gradle 7 seems to work fine. Closing!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6419">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
