### ISSUE TITLE
(question) Raspberry Pi support

### ISSUE THREAD

**Issue by felislynx-silae** [JetBrains/compose-jb#59]
Will raspberry pi be ever supported?
This might be gamechanger, since flutter is possible but dart is much worse than kotlin and rpi is primary platform for many iot projects

**Comment by peterfortuin** [comment]
You can install Android on a Raspberry Pi and create an Android app with Jetpack Compose.

**Comment by felislynx-silae** [comment]
@peterfortuin yeah, it is possible. It is not production ready solution. Also you loose many advantages of raspbian/arch for heavy duty tasks. I had project that used features that are unavailable in android. So it might be a good idea for many projects but not for all of them.

**Comment by dvaldespino00** [comment]
It would be great if Kotlin Compose was supported on Kotlin/Native, are there any plans for that?

**Comment by olonho** [comment]
It's possible, however to keep discussion to the point - feel free to compile Skiko (https://github.com/JetBrains/skiko) for Linux/ARM and provide relevant patches/instructions.

**Comment by felislynx-silae** [comment]
@olonho I don't feel confident enough in my knowledge from c/c++ to compile skiko for ARM :). I would be glad to test the solution and provide feedback on my RPI

**Comment by Adriankhl** [comment]
I also just come up with this question. After investigating it a bit, I think the first step should be compiling Skia in the Jetbrain repo (https://github.com/JetBrains/skia-build), the skiko (https://github.com/JetBrains/skiko) project depends on that. This is definitely possible (e.g. https://skia.googlesource.com/third_party/sdl/+/master/docs/README-raspberrypi.md), but it takes some effort to set it up.

**Comment by jimgoog** [comment]
If you do get the build on a raspberry pi, please do contribute the relevant build script to the jetbrains repository so everyone can benfit.

**Comment by olonho** [comment]
Note that link above explains SDL build, not Skia one.

**Comment by olonho** [comment]
As of 0.5.0-build229 we support linux-arm64 in Compose builds.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6401">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
