### ISSUE TITLE
pointerMoveFilter onEnter is not triggered when scroll stops

### ISSUE THREAD

**Issue by antonshilov** [JetBrains/compose-jb#594]
I'm trying to build a scrollable list with item background highlight on hover following the [tutorial](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events).
When scrolling stops and mouse pointer stays on top of the item, `pointerMoveFilter` callback is not triggered until the mouse pointer moves.
The expected behavior would be that once item ends up under the pointer the callback will be triggered.

https://user-images.githubusercontent.com/8353068/115140627-d5305e00-a040-11eb-87ec-519e5e54a598.mp4

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta6-dev474

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6213">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
