### ISSUE TITLE
gradle package fails on arch linux because it thinks its debian

### ISSUE THREAD

**Issue by soloturn** [JetBrains/compose-jb#596]
tried to build the todo-app. after 10 minutes waiting time and downloading half the internet it fails with:
```
> gradle package
...
* What went wrong:
Execution failed for task ':packageDeb'.
> External tool execution failed:
  * Command: [/usr/lib/jvm/java-15-openjdk/bin/jpackage, @//src/st-todo/build/compose/tmp/packageDeb.args.txt]
  * Working dir: []
  * Exit code: 1
```
it looks like as it tries to create a debian package on arch.

**Comment by olonho** [comment]
One could install Debian on Arch, see https://www.maketecheasier.com/install-deb-package-in-arch-linux/. Generally, we(and jpackage) do not  yet support non-debian redistribution formats, however usually it could be repackaged, if needed.

**Comment by olonho** [comment]
Maybe in your case some additional dependencies, such as `fakeroot` aren't installed, see https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html#GUID-786E15C0-2CE7-4BDF-9B2F-AC1C57249134

**Comment by soloturn** [comment]
what is necessary to create an arch package is installed. fakeroot included. but nothing for debian. while it is certainly possible to use a deb package, arch packages are so simple and easy to create that it is easier to repackage it. take for example, the kotlin package, which you guys provide and arch repackages it with mini-effort.

there is one single file to create it, PKGBUILD:
https://github.com/archlinux/svntogit-community/blob/packages/kotlin/trunk/PKGBUILD

with the two commands 
```
makepkg --printsrcinfo > .SRCINFO
makepkg
```

the output is then a tar file compressed with zstd:
```
> tar tvf /var/cache/pacman/pkg/kotlin-1.4.32-1-any.pkg.tar.zst
-rw-r--r-- root/root      5044 2021-04-02 23:46 .BUILDINFO
-rw-r--r-- root/root      6742 2021-04-02 23:46 .MTREE
-rw-r--r-- root/root       407 2021-04-02 23:46 .PKGINFO
<other files as on disk>
```
pgkinfo lists the version, dependencies, which is only java in the compose-jb case.
```
> cat .PKGINFO 
# Generated by makepkg 5.2.2
# using fakeroot version 1.25.3
pkgname = kotlin
pkgbase = kotlin
pkgver = 1.4.32-1
pkgdesc = Statically typed programming language that can interoperate with Java
url = https://kotlinlang.org/
builddate = 1617400006
packager = Alexander Rødseth <rodseth@gmail.com>
size = 68878016
arch = any
license = APACHE
license = custom
depend = java-environment>=8
makedepend = setconf
```
buildinfo just lists what was installed when building. the sha is from the source file packaged, i.e. from the kotlin download in this case.
```
> cat .BUILDINFO 
format = 1
pkgname = kotlin
pkgbase = kotlin
pkgver = 1.4.32-1
pkgarch = any
pkgbuild_sha256sum = 6ced10bfc2ecaae28b13b0d2c3efc962be0aeffacc07df3a6342c0775b94610a
packager = Alexander Rødseth <rodseth@gmail.com>
builddate = 1617400006
builddir = /build
buildenv = !distcc
buildenv = color
buildenv = !ccache
buildenv = check
buildenv = !sign
options = strip
options = docs
options = !libtool
options = !staticlibs
options = emptydirs
options = zipman
options = purge
options = !debug
installed = acl-2.3.1-1-x86_64
installed = archlinux-keyring-20210110-1-any
...
installed = zstd-1.4.9-1-x86_64
```
the .MTREE file is just created with bsdtar, the relevant part out of "makepkg" script used to create the package:
```
        # ensure all elements of the package have the same mtime
        find . -exec touch -h -d @$SOURCE_DATE_EPOCH {} +

        msg2 "$(gettext "Generating .MTREE file...")"
        list_package_files | LANG=C bsdtar -cnf - --format=mtree \
                --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
                --null --files-from - --exclude .MTREE | gzip -c -f -n > .MTREE
        touch -d @$SOURCE_DATE_EPOCH .MTREE

        msg2 "$(gettext "Compressing package...")"
        # TODO: Maybe this can be set globally for robustness
        shopt -s -o pipefail
        list_package_files | LANG=C bsdtar --no-fflags -cnf - --null --files-from - |
                compress_as "$PKGEXT" > "${pkg_file}" || ret=$?

```

**Comment by soloturn** [comment]
hmm .. ok. i saw there is even a simpler way, thanks to your hint @olonho :) install dpkg on arch:
https://archlinux.org/packages/community/x86_64/dpkg/

and, oh wonder, it creates a debian package with:
```
gradle package
```
not that i want a debian package, but it can be extended to build packages for differenc platforms :)

**Comment by qavan** [comment]
> hmm .. ok. i saw there is even a simpler way, thanks to your hint @olonho :) install dpkg on arch: https://archlinux.org/packages/community/x86_64/dpkg/
> 
> and, oh wonder, it creates a beautiful debian package with:
> 
> ```
> gradle package
> ```
> 
> not that i want a debian package, but it can be extended to build packages for differenc platforms :)
> 
> at the end of the day, the output of compose-jb is always a single file, a jar, started with "java -jar", which is platform dependent, is it?

Wow thx, finally found way to build Deb using Manjaro.
Also installing rpm-tools https://archlinux.org/packages/community/x86_64/rpm-tools/ resolve Rpm target

**Comment by dragossusi** [comment]
@olonho can we add support for arch as well using RPM? We can create a RPM and a `PKGBUILD` file with it, something like this

```kotlin
package packager

import org.gradle.api.Project
import java.io.File

object ArchPackager {

    fun createPKGBUILD(project: Project) {
        //don't know how to decide this, it would be better if we could get this from package task
        val rpmDir = File(project.buildDir, "compose/binaries/main/rpm")
        val rpmFile = File(rpmDir, getRpmName(project.name))
        if (rpmFile.exists()) {
            File(rpmDir, "PKGBUILD").writeText(
                createPKGBUILDContent(rpmFile)
            )
        }
    }

    fun createPKGBUILDContent(rpmFile: File): String {
        return """
            pkgname=sevens
            pkgver=${Versions.app}
            pkgrel=${Versions.appCode}
            pkgdesc="${Details.description}"
            pkgver="2021.04.09"
            pkgrel="1"
            pkgdesc="Short description of rpm package"
            arch=("x86_64")

            source=("${rpmFile.path}")
            sha256sums=("78b21e65300025cd418157ca3cf14a7e0b5f06557fba2639cb0c62ed402d3fc1")

            package() {
              install -d "${'$'}pkgdir/etc"
              cp -r "${'$'}srcdir/etc/." "${'$'}pkgdir/etc"
            }
        """.trimIndent()
    }

    private fun getRpmName(moduleName: String): String {
        return "$moduleName-${Versions.app}-${Versions.appCode}.x86_64.rpm"
    }

}
```
Maybe add an Arch target and some configuration fields for name,version, version code, description etc

**Comment by acmpo6ou** [comment]
I'm not sure if this is what you're looking for, but you can create a .jar file using the `packageUberJarForCurrentOS` task, like this:
```
./gradlew packageUberJarForCurrentOS
```
You can then run this jar on Arch Linux, but your users will need java installed on their machine of course.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6014">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
