### ISSUE TITLE
packageUberJarForCurrentOS no main manifest attribute

### ISSUE THREAD

**Issue by soloturn** [JetBrains/compose-jb#597]
creating the example as shown in https://github.com/JetBrains/compose-jb/tree/master/tutorials/Getting_Started can be run with "gradle :run". creating a fat jar does not work:
```
> gradle packageUberJarForCurrentOS
> java -jar build/libs/st-todo-1.0.0.jar
no main manifest attribute, in build/libs/st-todo-1.0.0.jar
```

**Comment by olonho** [comment]
https://github.com/JetBrains/compose-jb/tree/master/examples/codeviewer with `0.4.0-build180` produce runnable JAR just fine. Please provide reproducer and version info.

**Comment by soloturn** [comment]
@olonho , confirmed, codeviewer produces a runnable jar with
```
> gradle packageUberJarForCurrentOS
```
also the example works when doing
```
> java -jar build/compose/jars/st-todo-linux-x64-1.0.0.jar 
```
i used the following which does not work: 
```
> java -jar build/libs/st-todo-1.0.0.jar
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6438">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
