### ISSUE TITLE
(question) what layout managers are planned? 

### ISSUE THREAD

**Issue by felislynx-silae** [JetBrains/compose-jb#60]
Most of ui frameworks are missing modern manager like constraint layout in android which is superb over flutter, javafx and even ios constraint layout. What layouts are planned?

**Comment by olonho** [comment]
Please suggest what are your requirements for the layout manager?

**Comment by felislynx-silae** [comment]
Well, for me perfect layout manager is something like ConstraintLayout in android/ios. It is much easier to use than hbox/vbox in javafx or html/flutter counterparts. I know that people that comes from web, like those solutions. I started with java servers, then jumped into Android. So relative layout and later constraint layout are very easy to use. Jumping into ios was also easy. Using flutter/javafx is like jumping with tied legs into mountain. Doable but frustrating ;)

**Comment by tonsky** [comment]
Any concrete examples of what is simple in ConstraintLayout but complex in Flutter? After watching https://www.youtube.com/watch?v=UUfXWzp0-DU, I thought Flutter solution was way superior to e.g. web

**Comment by felislynx-silae** [comment]
Flex is so similar to both javafx and web. Examples - real life layout from client that took me few minutes in constraint layout in both ios and android. In flutter i had so many flex issues (something wasn't stretching as it should etc.). As i said, it is my own opinion and you might like flex/vbox/hbox :) for me they are less friendly in conplex designs

**Comment by liudonghua123** [comment]
I saw the example code, it is very much like flutter's dart code. The UI code is `intuitive`.

> Just describe your UI, and Compose takes care of the rest. As app state changes, your UI automatically updates.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6104">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
