### ISSUE TITLE
Demo Todo at Android crash 

### ISSUE THREAD

**Issue by CMingTseng** [JetBrains/compose-jb#601]
0.4.0-build180
 
 java.lang.NoSuchFieldError: No static field Companion of type Landroidx/compose/foundation/layout/BoxScope$Companion; in class Landroidx/compose/foundation/layout/BoxScope; or its superclasses (declaration of 'androidx.compose.foundation.layout.BoxScope' appears in /data/app/example.todo.android-i_SgJasTtR6L0LLltZjurA==/base.apk)

**Comment by olonho** [comment]
Does it happen with the latest Compose build as well?

**Comment by CMingTseng** [comment]
@olonho 

very thx

i  upgrade to   kotlin 1.4.32 & JB_Compose 0.4.0-build183  now is ok

THX

and   Can help  modify  this project ? https://github.com/ShikaSD/compose-server-side 

this project  has  the same todo demo    but  it use  modify version android_compose !!

i want try  modify to  JB Compose (compose fo desktop)

THX

**Comment by olonho** [comment]
To add code to our repo please send a pull request.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6433">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
