### ISSUE TITLE
Code signing and notarization for Mac is broken

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-jb#602]
`0.4.0-build180`:
*  "statusSummary": "Archive contains critical validation errors",
* "message": "The signature of the binary is invalid.",
https://kotlinlang.slack.com/archives/C01D6HTPATV/p1618749612133100

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6435">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
