### ISSUE TITLE
explain reasoning behind complex directory structure

### ISSUE THREAD

**Issue by soloturn** [JetBrains/compose-jb#605]
there is a beautiful template for a multiplatform app:
https://github.com/JetBrains/compose-jb/tree/master/templates/multiplatform-template

can you explain or point to a link explaining the thought process behind all of these directories and gradle files? there is android, and there is common/android, desktop, common/desktop. if you could simplify it would be great.

**Comment by jimgoog** [comment]
The gradle directories and files are all relatively standard, there really isn't much there that could be simplified given that we are using gradle.  Perhaps if it were a different build system, it could be simplified.

There is a top-level directory for each of the platform modules (desktop/android/common) and within the common module, a directory for each of the source sets (desktop/android/common).  Each platform module has its own build.gradle file, and there is a top-level build.gradle file that allows you to build for all the platforms.

**Comment by igordmn** [comment]
Probably we can [get rid of unnecessary modules](https://github.com/JetBrains/compose-jb/issues/121) and keep only single module with 3 sourcesets desktop/android/common, but we didn't try this yet.

**Comment by soloturn** [comment]
@igordmn where is one expected to put java code, or call java code? tried to do "import java.net.URL" in multiplatform template App.kt, but intellij  chokes. on the command line it is able to compile and run. 

IntelliJ IDEA 2021.1 (Community Edition)
Build #IC-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.16-arch1-1
GC: ParNew, ConcurrentMarkSweep
Non-Bundled Plugins: com.dmarcotte.handlebars (211.6693.44), PythonCore (211.6693.119)
Kotlin: 211-1.4.32-release-IJ6693.72
Current Desktop: GNOME

**Comment by soloturn** [comment]
@igordmn where is one expected to put java code, or call java code? tried to do "import java.net.URL" in multiplatform template App.kt, but intellij  chokes. on the command line it is able to compile and run. 

IntelliJ IDEA 2021.1 (Community Edition)
Build #IC-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.16-arch1-1
GC: ParNew, ConcurrentMarkSweep
Non-Bundled Plugins: com.dmarcotte.handlebars (211.6693.44), PythonCore (211.6693.119)
Kotlin: 211-1.4.32-release-IJ6693.72
Current Desktop: GNOME

**Comment by soloturn** [comment]
the template has a "kotlin" subdirectory, so i thought java code would go into "java" -  but neither intellij nor the command line gradle build does find the files there. how do you envision this to work?

**Comment by igordmn** [comment]
>  expected to put java code, or call java code? tried to do "import java.net.URL"
You mean Kotlin code, but using JDK classes?

In goes to `common\src\desktopMain\kotlin`

**Comment by soloturn** [comment]
@igordmn i mean both cases. on one hand, kotlin code calling java code (a bug in intellij?), on the other hand pre-existing java code, which gets a new GUI. like when migrating from swing to compose.

**Comment by igordmn** [comment]
Note that `multiplatform` here means not Windows/Linux/macOs, but JVM/android/iOs/native/js (Compose only supports JVM and android for now). To support only Windows/Linux/macOs you can use [desktop template](https://github.com/JetBrains/compose-jb/tree/master/templates/desktop-template). It much simplier.

If you need a pure java code inside your project then you should apply `java` plugin in `desktop/build.gradle`  (or build.gradle for desktop template):
```
plugins {
    ...
    id("java")
}

...

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
```

And move java code to `desktop/src/jvmMain/java` (or to `src/main/java` for desktop template)

After that you can use Kotlin from Java and Java from Kotlin.

If you just need to use third-party precompiled classes (from maven, from jar's, from JDK) you don't need `java` plugin.

**Comment by soloturn** [comment]
@igordmn thank you! i hoped it would then work on android and desktop, i put the java code into ```common/src/commonMain/java``` but it then said ``` 'java' plugin has been applied, but it is not compatible with the Android plugins. ```

i found an issue from 2020-08, saying:
Kotlin multi-platform is very experimental and the current MPP support in JetBrains' plugins do not allow this to be fixed. We are working with them on a better solution.

https://issuetracker.google.com/issues/132576775

does this still apply?

**Comment by igordmn** [comment]
> does this still apply?

Unfortenately, yes. For now, you can use 'java' plugin only in a separate module.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6424">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
