### ISSUE TITLE
How to obfuscate code with proguard on compose for desktop?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#607]
like on Android:
![image](https://user-images.githubusercontent.com/23566361/115811032-96741c80-a421-11eb-9da0-a63e33cf1283.png)

**Comment by olonho** [comment]
There's nothing special with obfuscation of CfD programs, it's the same as with all other JVM programs. We provide task 
`packageUberJarForCurrentOS` which produces self-contained JAR, then use steps similar to what's described in 
https://stackoverflow.com/questions/64355998/proguard-example-for-gradle-java-application

**Comment by Thomas-Vos** [comment]
@olonho is there a way to use R8 with the `packageX` tasks?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6155">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
