### ISSUE TITLE
org.jetbrains.compose       or   org.jetbrains.compose.plugin  

### ISSUE THREAD

**Issue by CMingTseng** [JetBrains/compose-jb#608]
Dear Sir

now  compose for desktop library version is 0.4.0-build183  

i know  this project   https://github.com/JetBrains/compose-for-web-demos   not JB office support 

but  i find  is  plugin library  org.jetbrains.compose.plugin   version 1.4.255-SNAPSHOT

normal    org.jetbrains.kotlin.multiplatform version  is the same kotlin version ?

but  when i use 

plugins { 
    id 'org.jetbrains.kotlin.multiplatform' version '1.4.32'
    id 'org.jetbrains.compose.plugin' version '1.4.32' 
}

i can not find !!

THX

**Comment by olonho** [comment]
Please do not use  https://github.com/JetBrains/compose-for-web-demos, it's not properly functional, we're working on improved version.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6434">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
