### ISSUE TITLE
Dialog open/close causes major UI redraw

### ISSUE THREAD

**Issue by SteynSieveo** [JetBrains/compose-jb#609]
Hi there!

We are using AlertDialog in one of the apps that we are developing. We noticed that when the dialog opens and closes it does a redraw of the entire window, causing a flashing like effect. See the attached screen recording.

We see this issue on Linux but not on MacOS nor on Windows. 

Our development machines run some different versions of Linux, and our deployment environment will be Ubuntu 20.04.
 
We tested on the following Linux machines and the all have this issue:
- Ubuntu 20.04 with Gnome Shell on X11
- Fedora Silverblue 33 with Gnome Shell on X11 and Wayland
- Arch with XFCE on X11
- ChromeOS with Crostini, with Wayland

I can provide the source if needed, but it is pretty basic use case in the minimal proof that I built. 

https://user-images.githubusercontent.com/52039901/115884027-be2da980-a44e-11eb-9c70-92f451d91253.mp4

**Comment by igordmn** [comment]
Looks like the same issue as https://github.com/JetBrains/compose-jb/issues/513.

Soon we will use a different implementation for Dialog's (https://android-review.googlesource.com/c/platform/frameworks/support/+/1684868).

Most likely this issue will be fixed.

**Comment by sieveo** [comment]
Great, thanks for the feedback!

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6247">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
