### ISSUE TITLE
"androidx dependency" is compiled by a new Kotlin compiler backend and cannot be loaded by the old compiler

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#61]
Hello,

I created the base project using you getting started tutorial. Well, it runs, it works, but IntelliJ IDEA thinks it should not work. It shows me the error that I specified in the issue name. How can I fix this?

![image](https://user-images.githubusercontent.com/61655029/98283970-19ef9d80-1fa9-11eb-922d-8c161d7d1564.png)

**Comment by igordmn** [comment]
We had similar problem earlier:
https://github.com/JetBrains/compose-jb/issues/21

And fixed it with https://github.com/JetBrains/compose-jb/pull/30

(we moved buildscript from settings.gradle.kts to the root build.gradle.kts and the problem was gone)

Do you have buildscript in settings.gradle.kts?

**Comment by veyndan** [comment]
I'm facing the same issue as @GGorAA, and my `settings.gradle.kts` is identical to that found in the [Getting Started](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Getting_Started/README.md) guide:

```kts
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}
```

**Comment by Animeshz** [comment]
Same issue :(

**Comment by igordmn** [comment]
Can you tell which versions of IDEA and Kotlin IDEA plugin do you use?

If it is possible it would be very helpful if you attach project archive here.

**Comment by Animeshz** [comment]
Intellij IDEA: 2020.2
Kotlin (plugin): 1.4.10
JB Compose: 0.1.0-m1-build62
JDK Version: 11.0.8
JVM Target: 1.8

**Comment by blacpythoz** [comment]
same issue here

**Comment by igordmn** [comment]
> Intellij IDEA: 2020.2
> Kotlin (plugin): 1.4.10
> JB Compose: 0.1.0-m1-build62
> JDK Version: 11.0.8
> JVM Target: 1.8

Unfortunately I can't reproduce the issue on this configuration.
I tried to open these templates:
https://github.com/JetBrains/compose-jb/tree/master/templates/desktop-template (which is almost the same as described in https://github.com/JetBrains/compose-jb/tree/master/tutorials/Getting_Started)
https://github.com/JetBrains/compose-jb/tree/master/templates/multiplatform-template

Can anyone that have this issue attach archive with project? 

Also is there "-Xuse-ir" in Project Settings?
![image](https://user-images.githubusercontent.com/5963351/98362122-c1b6ab00-203d-11eb-94c5-8a2beced4d60.png)
It should be added automatically after the import of the project.
If not - will it be added after Gradle Sync?
![image](https://user-images.githubusercontent.com/5963351/98362256-f62a6700-203d-11eb-850d-ed21d621f0dd.png)

**Comment by blacpythoz** [comment]
Repro: https://gofile.io/d/WpJQbh

**Comment by Animeshz** [comment]
Strange enough, The same thing happens with the desktop-template project as well when (importing in Intellij).

**Comment by subashz** [comment]
I don't have any issue with desktop-template  based project. It only happens on MPP template for me.

**Comment by igordmn** [comment]
> Repro: https://gofile.io/d/WpJQbh

Multiplatform template from IDEA Wizard currently have this problem (we fixed it in a new version)

Try this:
[demo.zip](https://github.com/JetBrains/compose-jb/files/5501221/demo.zip)

I changed version to "0.1.0-m1-build62" and converted desktop module from kotlin("jvm") to kotlin("multiplatform")
(kotlin("jvm") doesn't work well in multiplatform project)

**Comment by subashz** [comment]
Got new error after tyring to run desktop app, 

> > Repro: https://gofile.io/d/WpJQbh
> 
> Multiplatform template from IDEA Wizard currently have this problem (we fixed it in a new version)
> 
> Try this:
> [demo.zip](https://github.com/JetBrains/compose-jb/files/5501221/demo.zip)
> 
> I changed version to "0.1.0-m1-build62" and converted desktop module from kotlin("jvm") to kotlin("multiplatform")
> (kotlin("jvm") doesn't work well in multiplatform project)

Got new error after trying to run desktop app: Gradle > desktop > Tasks > application > run 
 https://pastebin.com/0MWuepJe

**Comment by igordmn** [comment]
> Got new error after tyring to run desktop app,
> 
> > > Repro: https://gofile.io/d/WpJQbh
> > 
> > 
> > Multiplatform template from IDEA Wizard currently have this problem (we fixed it in a new version)
> > Try this:
> > [demo.zip](https://github.com/JetBrains/compose-jb/files/5501221/demo.zip)
> > I changed version to "0.1.0-m1-build62" and converted desktop module from kotlin("jvm") to kotlin("multiplatform")
> > (kotlin("jvm") doesn't work well in multiplatform project)
> 
> Got new error after trying to run desktop app: Gradle > desktop > Tasks > application > run
> https://pastebin.com/0MWuepJe
> 
> But it works fine if I replace
> 
> ```kotlin
> import me.subash.common.App
> import androidx.compose.desktop.Window
> 
> fun main() = Window {
>     App()
> }
> ```
> 
> with
> 
> ```kotlin
> import androidx.compose.desktop.Window
> import androidx.compose.material.Text
> 
> fun main() = Window {
>     Text("Hello")
> }
> ```

I forgot to change version  in android/build.gradle.kts and common/build.gradle.kts

(you can redownload demo from a comment above, I changed the version)

**Comment by GGorAA** [comment]
> Do you have buildscript in settings.gradle.kts?

I have just copy pasted all code from you getting started guide, and the IDEA just gone wild with errors.

**Comment by GGorAA** [comment]
> Multiplatform template from IDEA Wizard currently have this problem (we fixed it in a new version)
> Try this:
> demo.zip
Forgot to say, I have the Kotlin/JVM project, not the MPP one

**Comment by GGorAA** [comment]
> If it is possible it would be very helpful if you attach project archive here.

Easily. https://drive.google.com/file/d/1VRKk64t8z7GwYD6H2bp1hoF6z7nzYqFq/view?usp=sharing

**Comment by olonho** [comment]
What exactly version of IDEA? 2020.2.3?

**Comment by X1nto** [comment]
This is what I did to fix the problem: Went into project structure, I had "Use project settings" ticked so I clicked on "Edit project settings" and changed Target JVM Version to 11, then added `-Xuse-ir` to the command line options, after these operations red lines were gone. Screenshot of my project settings: 
![image](https://user-images.githubusercontent.com/48173186/98791823-087e1980-241f-11eb-8235-9c07b53aedf9.png)

**Comment by GGorAA** [comment]
> What exactly version of IDEA? 2020.2.3?

yes

**Comment by GGorAA** [comment]
I upgraded to the latest build of JetBrains Compose plugin, added the command line argument, and it is finally working! No more red lines :D

**Comment by igordmn** [comment]
> > If it is possible it would be very helpful if you attach project archive here.
> 
> Easily. https://drive.google.com/file/d/1VRKk64t8z7GwYD6H2bp1hoF6z7nzYqFq/view?usp=sharing

I changed the Gradle version from 6.3 to 6.5.1 and red underlying is gone.
On Gradle 6.7 and Compose 0.1.0-build113 everything is fine too.

**Comment by GGorAA** [comment]
I will try this too

**Comment by GGorAA** [comment]
I also forgot that my target JVM version was 1.6, after the upgrade to 11 every single error is gone

**Comment by steklopod** [comment]
My solution:
`build.gradle.kts`
```kotlin
plugins {
    val kotlin = "1.5.0-M1"
    kotlin("jvm") version kotlin
}
tasks{
            val java: String by project
            withType<KotlinCompile> {
                kotlinOptions { freeCompilerArgs += listOf("-Xskip-prerelease-check", "-Xjsr305=strict"); jvmTarget = java }; sourceCompatibility = java; targetCompatibility = java
            }
}
```
![image](https://user-images.githubusercontent.com/29500153/112015065-87f1c700-8b3c-11eb-8f6c-3135d6e08481.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6442">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
