### ISSUE TITLE
explain exception handling

### ISSUE THREAD

**Issue by soloturn** [JetBrains/compose-jb#619]
tried something simple in your multiarch template and added a textinput which produces an exception to App.kt. i entered no text into the text field and pressed the download button. it throws an exception then the GUI does not allow any click any more.

```
@Composable
fun App() {
    MaterialTheme {
        Column {
            TextInput()
        }
    }
}

@Composable
private fun TextInput() {
    var ripUrl by remember { mutableStateOf(TextFieldValue("")) }
    OutlinedTextField(
        value = urlText,
        trailingIcon = {IconButton(onClick = {
            var url: java.net.URL? = java.net.URL(urlText.toString())
        }) {
            Icon(Icons.Default.DownloadForOffline, contentDescription = "Download")
        }}
        ,
        modifier = Modifier.padding(8.dp).fillMaxWidth(),
        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Text),
        label = { Text(text = "URL:") },
        placeholder = { Text(text = "Download URL.") },
        onValueChange = {
            urlText = it
        }
    )
}
```

it would be quite helpful if you mention in the documentation and template at some point where the "top level exception handling" should be done to allow displaying the error and anyway continue the program.

**Comment by olonho** [comment]
It's general feature of compose that exception handling shall not be propagated beyond callbacks.

**Comment by soloturn** [comment]
@olonho what does it mean in the mentioned case, that every composable function should catch all exceptions?

**Comment by olonho** [comment]
It's non-composable callback throwing exception, if I read correctly.

**Comment by soloturn** [comment]
@olonho,  the input field contains no good url, converting the text to a url throws an exception. not too sure if you mean this by "non composable callback":
```
        trailingIcon = {IconButton(onClick = {
            var url: java.net.URL? = java.net.URL(urlText.toString())
        }) {
            Icon(Icons.Default.DownloadForOffline, contentDescription = "Download")
        }}
```
should it be like this then the exception handling? 
```
        trailingIcon = {IconButton(onClick = {
            msg = HandleUrl(url)
        }) {

l..
private fun HandleUrl(url: TextFieldValue): String {
   val msg: String
   try {
        val handler: HandlerInJava = HandlerInJava.get(java.net.URL(url.text.toString()))
    }
    catch (e: Exception) {
        e.printStackTrace()
        msg = e.message.toString()
    }
   return msg
```
maybe you can point to an example or write a cpoule of lines? i volunteer to include it in some documentation if it is possible via pull request. catching the exception - constructing an error string, and then put it into a log file and on the GUI.

**Comment by soloturn** [comment]
exception handling is explained thank you! error messages is a different topic. what you think @olonho ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6423">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
