### ISSUE TITLE
androidx.compose.ui.window.Notifier

### ISSUE THREAD

**Issue by jvisker** [JetBrains/compose-jb#62]
The Tray_Notifications_MenuBar mentions shows a "Notifier" class, but I can't find any references to it anywhere to actually make it work. Am I missing something?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6531">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
