### ISSUE TITLE
Mouse drag on Canvas is delayed

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-jb#622]
I have a Canvas where I have attached the following code to the modifier in order to catch mouse drag events.
```
.pointerInput(Unit) {
    detectDragGestures { change, dragAmount ->
        change.consumeAllChanges()
        println("dragAmount: $dragAmount")
    }
}
```
This works well in general but I observe one strange behavior. In order to get the first event I have to drag the mouse almost one centimeter (on a large screen) away from the initial point where the left mouse button was pressed. After that the events are comming in as expected. This effect is critical because it makes any detailed mouse based editing impossible.

I am on macOS 10.15.7 with a large Retina screen and I am using the compose plugin 0.4.0-build185.

**Comment by mipastgt** [comment]
Just incorporated your second proposal into my code and it works great. Thanks a lot. The only drawback is that I have to compute the dragAmount myself now :-) (Which is very easy thanks to Kotlin `val dragAmount = change.position - change.previousPosition`)

**Comment by camdenorrb** [comment]
@igordmn I think I am currently experiencing this issue, is there any updates on this one in particular?

**Comment by mipastgt** [comment]
I still have this issue and just had to use the above workarround again.
I am now on macOS 12.6.3, Kotlin 1.8.10 and Compose desktop 1.3.1.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6060">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
