### ISSUE TITLE
Docs should point out that most https requires the jdk.crypto.ec module

### ISSUE THREAD

**Issue by jamesward** [JetBrains/compose-jb#630]
https://github.com/JetBrains/compose-jb/blob/master/tutorials/Native_distributions_and_local_execution/README.md

Should include details on:
```
modules("jdk.crypto.ec")
```

**Comment by AlexeyTsvetkov** [comment]
The module is now included by default, so enabling it manually is not required anymore

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6363">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
