### ISSUE TITLE
Gradle plugin no longer works for projects that do not target web

### ISSUE THREAD

**Issue by msfjarvis** [JetBrains/compose-jb#632]
Since v0.4.0-build187 the Gradle plugin will instantly error out during configuration on projects that do not target web, due to a check for the web platform being evaluated eagerly [here](https://github.com/JetBrains/compose-jb/blob/8658e381328a324e8220f85357fb50e48ce2dff9/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/ComposePlugin.kt#L119).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6431">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
