### ISSUE TITLE
Suggestion: Package for AppImage instead of dep on linux

### ISSUE THREAD

**Issue by fadyadal** [JetBrains/compose-jb#64]
the title says it, I don't know if it's doable but I think it could enhance the popularity of the library on linux by supporting more than the debian-based distributions

**Comment by olonho** [comment]
Here we depend on jpackage support for  various packaging formats.

**Comment by AlexeyTsvetkov** [comment]
In near future we don't plan to support new packaging formats beyond what is supported by jpackage.
For now I'm closing the issue (this may be reconsidered in future).

**Comment by camdenorrb** [comment]
:C

**Comment by jimgoog** [comment]
To be clear, you can always use your own packager if you want additional formats, we don't force you to use jpackage.  There is just a limit to how far down the packaging rabbit hole we're reasonably able to go ourselves.  At some point, we need to defer to other teams.  It might be worth creating a feature request against jpackage.

**Comment by jimgoog** [comment]
To be clear, Compose for Desktop is just like any other JVM application.  You can always use your own packager if you want additional formats, we don't force you to use jpackage.  The only reason we provide jpackage out of the box is to try to make your life a little easier.  There is just a limit to how far down the packaging rabbit hole we're reasonably able to go ourselves.

It might be worth creating a feature request against jpackage or consider using a different packager that supports your desired output format.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6475">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
