### ISSUE TITLE
Desktop/Android: Slider/Scrollbar drag. Don't drag the slider when we move mouse outside of its bounds

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#643]
When we drag Slider or Scrollbar it continues to move even if we move mouse outside of its bounds (see the bottom Slider on the video below).

Probably this is a common with Android issue. I compared the native widget behavior on Android with a new behavior on Compose. And the native Android widget behaves exactly like the native desktop widget. But the Compose widget behaves in a different way:

https://user-images.githubusercontent.com/5963351/117175843-eebefd00-add7-11eb-98f4-4d9b3a38f4f1.mp4

(native on the top, Compose on the bottom)

**Comment by igordmn** [comment]
It isn't very noticeable on Android, because Slider on Android usually occupies the whole width.

**Comment by VeselovAlex** [comment]
Resolved in upstream: [1959198](https://android-review.googlesource.com/c/platform/frameworks/support/+/1959198), [1960699](https://android-review.googlesource.com/c/platform/frameworks/support/+/1960699)

**Comment by akurasov** [comment]
Fixed in 1.1.0-alpha04

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6138">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
