### ISSUE TITLE
The TextField component cannot be typed in Chinese

### ISSUE THREAD

**Issue by nukiyoam** [JetBrains/compose-jb#655]
I used the TextField component to build a text input field, but I could not enter Chinese.

```kotlin
var inputText by remember { mutableStateOf("") }
        TextField(
            value = inputText,
            onValueChange = {
                println(it)
                inputText = it
            }, modifier = Modifier.height(226.dp).fillMaxWidth(),
            colors = TextFieldDefaults.textFieldColors(
                cursorColor = Color.Gray,
                backgroundColor = Color(247, 242, 243, 100),
                unfocusedIndicatorColor = Color.Transparent,
                focusedIndicatorColor = Color.Transparent,
            ),
            keyboardActions = KeyboardActions(
                onDone = {

                }
            )

        )
```

And I still can't enter Chinese when I run the official TodoApp example.

> Library version: 0.4.0-build184
> JDK version: Oracle jdk 15
> OS: MacOS bigsur

**Comment by olonho** [comment]
This issue likely could be fixed with https://github.com/JetBrains/skiko/commit/beeb6e52a95f12cfc6bb5b0ab0f0af186a53df97#diff-0b041b443ea5a5f9b95a9ca5b68e5561315ff77cddd323fafb920586a540a379, could you please try latest version of CfD.

**Comment by MaoYiKun12138** [comment]
> This issue likely could be fixed with [JetBrains/skiko@beeb6e5#diff-0b041b443ea5a5f9b95a9ca5b68e5561315ff77cddd323fafb920586a540a379](https://github.com/JetBrains/skiko/commit/beeb6e52a95f12cfc6bb5b0ab0f0af186a53df97#diff-0b041b443ea5a5f9b95a9ca5b68e5561315ff77cddd323fafb920586a540a379), could you please try latest version of CfD.

Great, I solved the problem using the latest version of Skiko dependencies 

```kotlin
implementation("org.jetbrains.skiko:skiko-jvm-runtime-macos-x64:0.2.33")
```

 When will the Skiko dependency version in the Commpose for Desktop project be updated

Thank you very much

**Comment by akurasov** [comment]
@MaoYiKun12138 
Latest Compose MP builds using skiko versions that contains the fix. Do you still have this issue on a recent CMP build?

**Comment by nukiyoam** [comment]
> @MaoYiKun12138 Latest Compose MP builds using skiko versions that contains the fix. Do you still have this issue on a recent CMP build?

Now I can type in Chinese

Sorry it took so long to get back to you

**Comment by zerofancy** [comment]
I have the same issue when using compose on Linux.

I can copy and paste into it, but it not works when I try to type Chinese directly.

OS: Ubuntu 20.04 LTS
de: gnome
jdk: Amazon Corretto version 15.0.2
Input Method: IBUS

**Comment by nukiyoam** [comment]
> I have the same issue when using compose on Linux.
> 
> I can copy and paste into it, but it not works when I try to type Chinese directly.
> 
> OS: Ubuntu 20.04 LTS de: gnome jdk: Amazon Corretto version 15.0.2 Input Method: IBUS Compose Version: 1.2.0-alpha01-dev620

@zerofancy 
There is no problem now, it has been fixed in the earlier version, but I am macOS, maybe your problem is Linux platform specific

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6129">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
