### ISSUE TITLE
Memory leaks on 0.4.0-build185

### ISSUE THREAD

**Issue by darvld** [JetBrains/compose-jb#657]
When running any Compose Desktop application (at least with the specified version), every time the UI is drawn some memory leaks.
To reproduce:

- Create a new Compose Desktop project using the default IDEA template in the Kotlin project wizard.
-  Switch to compose version 0.4.0build-185 and run the application.
- When clicking the button, the program's memory usage should increase by around 1mb (with some delay).
- Resizing the window will also trigger an increase in memory usage, much more dramatic than simple clicks.

Tested on MacOS Big Sur and Ubuntu 20.10 with kotlin 1.4.32

**Comment by olonho** [comment]
Could you please check if garbage collection frees the memory or growth is permanent?

**Comment by darvld** [comment]
A closer inspection using VisualVM revealed the the actual heap of the process didn't exceed 35MB, so the issue must be that the GC isn't releasing the freed memory. In any case, it's clear that Compose is not the problem here (which I always suspected).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5426">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
