### ISSUE TITLE
Web compose example contain non-idiomatic code with inspection warnings

### ISSUE THREAD

**Issue by elizarov** [JetBrains/compose-jb#669]
* `onClick { count = count - 1 }` should be replaced with `onClick { count-- }`
* `onClick { count = count + 1 }` should be replaced with `onClick { count++ }`
* `Text("${count}")` should be replaced with `Text("$count")`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5417">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
