### ISSUE TITLE
The input method bar failed to follow the input field

### ISSUE THREAD

**Issue by drakeet** [JetBrains/compose-jb#67]
![Snip20201106_2](https://user-images.githubusercontent.com/5214214/98339404-a00df180-2046-11eb-924c-ae046bd9ae49.png)

**Comment by prepor** [comment]
It should be fixed. Please, check with 0.2.0-build129.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6516">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
