### ISSUE TITLE
Issue with notarizeDmg if there are multiple providers linked to the account used for signing

### ISSUE THREAD

**Issue by odvratnozgodan** [JetBrains/compose-jb#674]
When running the task `notarizeDmg` an error occurs if the account used for singing/notarization has multiple providers. This is quite common with larger teams.

The error:
`
Error Messages: Your Apple ID account is attached to other providers. You will need to specify which provider you intend to submit content to. Please contact us if you have questions or need help. (1627)
`

This can be easily mitigated by passing an extra argument(`--asc-provider`) to the `xcrun altool` command.

See Apple docs for more info: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow?language=objc (section **Upload Your App to the Notarization Service**)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5414">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
