### ISSUE TITLE
How to request server api json data?

### ISSUE THREAD

**Issue by mdddj** [JetBrains/compose-jb#678]
How to access url address to get data

**Comment by olonho** [comment]
Not sure if this question relates to Compose, see https://ktor.io/docs/client.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5410">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
