### ISSUE TITLE
Desktop. TextField. When we press Arrow keys, the focus moved into TextField

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#680]
```
import androidx.compose.desktop.Window
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material.TextField
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue

fun main() = Window {
    var text by remember { mutableStateOf("") }
    Column {
        Row {
            TextField(text, onValueChange = { text = it })
            TextField(text, onValueChange = { text = it })
        }
        Row {
            TextField(text, onValueChange = { text = it })
            TextField(text, onValueChange = { text = it })
        }
    }
}
```

1. Run example
2. Press any arrow key
3. Result - some TextField become focused

I think it is because recently in the common Compose was implemented moving the focus with keys.

But on desktop the focus should be moved with [Tab/Shift-Tab keys](https://github.com/JetBrains/compose-jb/issues/109), not with Arrow-keys

**Comment by igordmn** [comment]
Should be an issue in 1.0.0-beta5

**Comment by Thomas-Vos** [comment]
@igordmn is there an easy way to enable arrow navigation for all lists and grids in the app?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5408">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
