### ISSUE TITLE
How to handle global state

### ISSUE THREAD

**Issue by lazaroofarrill** [JetBrains/compose-jb#684]
Hello. I wanted to know if there was a standard way of handling global state in compose for desktop like Vuex or Redux.

**Comment by olonho** [comment]
Maybe this kind of question can be better answered on Slack or other interactive media. See https://developer.android.com/jetpack/compose/state

Usually global state is bad, so please try to use composition locals, at least.

**Comment by jimgoog** [comment]
Composition locals are bad, please try to use parameters.

**Comment by jimgoog** [comment]
CompositionLocal should be thought of like ThreadLocal or Globals - they create implicit data dependencies and implicit API contracts that break modularity and make your code much less maintainable.  You should feel bad every time you use it, prefer passing parameters explicitly.

**Comment by lazaroofarrill** [comment]
So I'm getting that, if I have two deeply nested components bonded to the same variable, I should pass that variable as a property down both trees. That's a refactorization nightmare and the reason Vuex was created in the first place.

**Comment by lazaroofarrill** [comment]
So I'm getting that, if I have two deeply nested components bonded to the same variable, I should pass that variable as a property down both trees. That's a refactorization nightmare and the reason Vuex was created in the first place.

**Comment by olonho** [comment]
You can use CompositionLocal in certain cases, if understand implications and ready to handle them.

**Comment by lazaroofarrill** [comment]
CompositionLocal seems pretty much like it, thank you.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5407">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
