### ISSUE TITLE
[Web] Ability to merge classes

### ISSUE THREAD

**Issue by mpetuska** [JetBrains/compose-jb#688]
Given this snippet
```kotlin
@MDCDsl
@Composable
inline fun MDCIconButton(
  icon: String,
  crossinline attrs: AttrsBuilder<Tag.Button>.() -> Unit = {},
  crossinline style: (StyleBuilder.() -> Unit) = {},
) {
  MDCIconButton(
    attrs = {
      classes("mdc-icon-button", "material-icons")
      attrs() // <------------------------------ If the consumer sets classes here, above classes are gone
    },
    style = style,
  ) {
    Text(icon)
  }
}
```

it'd be great if we could somehow merge `classes()` declarations rather than have them completely override each other. A way to inject extra classes would also work.

**Comment by eymar** [comment]
Added in https://github.com/JetBrains/compose-jb/pull/690
should be in the next release.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5404">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
