### ISSUE TITLE
Add native macOS target with SwiftUI to the TODO Sample App

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-jb#689]
I think many people using this will likely also target MacOS apps.
So it would be helpful if the sample app would showcase that, too.

**Comment by olonho** [comment]
macOS target (as well, as Linux and Windows) is already supported in TODO App.

**Comment by StefanOltmann** [comment]
> macOS target (as well, as Linux and Windows) is already supported in TODO App.

As far as I can see there is only an iOS target.

I'm not talking about creating a DMG file with a bundled JVM, but a native MacOS app.

Look at the People In Space sample from https://github.com/joreilly/PeopleInSpace which actually has a native MacOS target.

I think this is most likely the way you want to deploy MacOS if you already have an iOS app.

**Comment by olonho** [comment]
There's no native port of Compose at the moment, but for practical purposes there shalln't be much of a difference between native application and what we currently produce when packaging. It is native application, with certain implementation detail that some data bundled with app is actually bytecode for the JVM.  Is there anything but bundle size which makes it unsuitable for your purposes?

**Comment by StefanOltmann** [comment]
I know that there is no native port. That would be very nice in the future, but I'm aware of that.

I wanted to suggest that there should a macOS project be added to the sample similar to [PeopleInSpace](https://github.com/joreilly/PeopleInSpace).

That way the TODO sample app would run on Windows (using compose), Linux (using Compose), Android (using compose), iOS (SwiftUI) and macOS (SwiftUI).

It's nice that there is a packaging option for macOS with a bundled JRE, but I think most people that already build an iOS app will more likely build an native macOS SwiftUI app withe the same code as for iOS rather than using the JVM option.

On a side note: I would really love to see if the project wizard would also provide a macOS option.
Now I can only add iOS there and it's not connected with the "shared" module. That's unlucky.

To build a multiplatform app I either need to start with PeopleInSpace template (and remove a lot of stuff) or I would need to create a new Compose Multiplatform app with the wizard and after that create an iOS & macOS SwiftUI app in XCode and try to fit it altogether somehow.

If the TODO sample app would already have an macOS part I (and everyone else) could just start by copying and modifying that project. Dou you see what I mean?

Maybe I should create another issue for the problem that the default template contains no iOS app (and if you add one it's not connected).

**Comment by StefanOltmann** [comment]
Ok, I see that you want to go with the JVM bundled Compose app for macOS to show that and having a SwiftUI Multiplatform to cover macOS with that is not what the examples are intended to showcase. I close this now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5403">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
