### ISSUE TITLE
"after load called" printed twice on app startup

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#692]
This is new in `build210`, maybe coming from a logging statement left in Skiko / Skija

Any app launched prints "after load called" twice to the console, in Studio and in terminal

**Comment by olonho** [comment]
Will be fixed with Skiko update, was a typo.

**Comment by olonho** [comment]
Fixed with 0.4.0-rc1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5401">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
