### ISSUE TITLE
NoSuchMethodError when running desktop with 0.0.0-web-dev-13

### ISSUE THREAD

**Issue by CyberDie22** [JetBrains/compose-jb#697]
When running the run target in Compose, it crashes with the error
`Exception in thread "main" java.lang.NoSuchMethodError: 'androidx.compose.runtime.internal.ComposableLambda androidx.compose.runtime.internal.ComposableLambdaKt.composableLambdaInstance(int, boolean, java.lang.Object)'
	at ComposableSingletons$MainKt.<clinit>(main.kt:4)
	at MainKt.main(main.kt:4)
	at MainKt.main(main.kt) `

I can’t provide much else for a few hours as I am currently not able to use a computer

**Comment by shabunc** [comment]
Hi @CyberDie22! Whenever you'll be able it will be very helpful if you'll provide some more context - what was the code that causes this issue - any chance it is composable lambda passed as param to function or to constructor?

**Comment by eymar** [comment]
+1 to @shabunc We weren't able to reproduce this issue using our examples. More details/code/build.gradle will probably help to dig into this.

**Comment by CyberDie22** [comment]
Ok, I found the issue, It doesn't appear to be an issue with compose, but the error occurred in compose
When I removed my dependency on Decompose, it immediately started working

I believe this is an issue with Decompose.

**Comment by sieveo** [comment]
@CyberDie22 there is a know issue in Decompose: https://github.com/arkivanov/Decompose/issues/150
This will be fixed in when Compose beta 8 comes out, as there is a blocking bug in beta 7.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5400">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
