### ISSUE TITLE
Build211: MaterialIcons Extended -> NoSuchMethodError

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#701]
Using the Extended Material Icons with `build211` on android (desktop not tested) results into a runtime exception.
With `build210` the call works as expected and results into a visible icon.

Sample project: [TestIcons.zip](https://github.com/JetBrains/compose-jb/files/6549272/TestIcons.zip)

Stacktrace
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.testicons, PID: 11839
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;FFFFJLandroidx/compose/ui/graphics/BlendMode;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Landroidx/compose/ui/graphics/vector/ImageVector$Builder; or its super classes (declaration of 'androidx.compose.ui.graphics.vector.ImageVector$Builder' appears in /data/app/~~atIV6HSX0_BomD9ZpNBV1g==/com.example.testicons-gTBPl-e8TU-8Ungev1QQdQ==/base.apk)
        at androidx.compose.material.icons.filled.VisibilityKt.getVisibility(Visibility.kt:57)
        at com.example.testicons.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:16)
```

**Comment by igordmn** [comment]
You use both "org.jetbrains.compose" and "androidx.compose" in the same project.

They similar to each other, but have different versions. So you have to use only  "org.jetbrains.compose":

```
...
    buildFeatures {
        compose = false
    }
...
dependencies {
    implementation("androidx.core:core-ktx:1.5.0")
    implementation("androidx.appcompat:appcompat:1.3.0")
    implementation("com.google.android.material:material:1.3.0")

    implementation(compose.runtime)
    implementation(compose.foundation)
    implementation(compose.material)
    implementation(compose.materialIconsExtended)

    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.3.1")
    implementation("androidx.activity:activity-compose:1.3.0-beta01")
    testImplementation(kotlin("test"))
    androidTestImplementation("androidx.test.espresso:espresso-core:3.3.0")
}
```
or only "androidx.compose" (without applying `id("org.jetbrains.compose")`)

**Comment by hfhbd** [comment]
@igordmn Thank you! 
Why do you recommend to disable `buildFeature.compose = false`? If this flag is false, Android Studio does not provide the previews.

**Comment by igordmn** [comment]
> disable buildFeature.compose = false

If it works then you can enable it.

In the past this flag added an implicit compose compiler plugin (that can be not compatible with compiler plugin that is added by  `org.jetbrains.compose` gradle plugin), not sure what happens now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5399">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
