### ISSUE TITLE
Update IDE wizard to support compose-web projects

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#707]
https://kotlinlang.slack.com/archives/C01F2HV7868/p1622073134074100

**Comment by akurasov** [comment]
It is available starting with IDEA 2021.2.2 Preview

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5397">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
