### ISSUE TITLE
web-dev-13: chrome not working

### ISSUE THREAD

**Issue by userquin** [JetBrains/compose-jb#714]
I'm using plugin version `0.0.0-web-dev-13` and it is not working on chrome (only tested on windows). It seems chrome is not returning an `HTMLElement` when calling `document.getElementById`, it is returning an `Element` and so `renderComposable(rootElementId = "app")` just fails with a `ClassCastException` (on firefox works).

What version can I use?

![imagen](https://user-images.githubusercontent.com/6311119/120024167-15dfa780-bfef-11eb-8e05-544afb255fd3.png)

![imagen](https://user-images.githubusercontent.com/6311119/120024261-2f80ef00-bfef-11eb-8dfb-5d62a3b99757.png)

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/120026025-c5b61480-bff1-11eb-89fb-e66fdc215d92.png)

**Comment by userquin** [comment]
On android is working but version is 90.0.4430.210

**Comment by eymar** [comment]
Hi @userquin 
What project did you use when the issue occurred?
 
 I tried to build and run https://github.com/Foso/compose-snake-web also from the link - https://foso.github.io/compose-snake-web/index.html
 
 I was using Win10 and Chrome 91.0.4472.77 when trying to reproduce but it worked fine.

**Comment by userquin** [comment]
@eymar a fork of snake project running on local machine also failing on remote, the output is created right now:

![imagen](https://user-images.githubusercontent.com/6311119/120181596-94199500-c20d-11eb-8581-d598ac3cb6ce.png)

**Comment by userquin** [comment]
upps, on incognito just works... some plugin installed on chrome???

**Comment by userquin** [comment]
@eymar I don't know why using HTMLElement instead Element since document.getElementById just returns an Element, the api is there.

In fact `DomNodeWrapper` requires a `Node`, `renderComposable` requires `HTMLElement`, this make no sense !!!.

**Comment by eymar** [comment]
@userquin did you find what plugin in chrome caused the probelm?

thanks!

**Comment by userquin** [comment]
@eymar I have a few, I'm going to disable them one by one and then I'll tell you which one

**Comment by userquin** [comment]
@eymar `Polymer DevTools Extension` is causing the problem: WTF

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5395">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
