### ISSUE TITLE
Issue Building on ARM

### ISSUE THREAD

**Issue by BobdoIe** [JetBrains/compose-jb#717]
Hello, 
I am getting the following error when attempting to build a compose multi-platform project on my PinePhone. Specifically, the error occurs when building the 'desktop' submodule:
```> Task :desktop:compileKotlinJvm FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:compileKotlinJvm'.
> Could not resolve all files for configuration ':desktop:jvmCompileClasspath'.
   > Could not find org.jetbrains.compose.desktop:desktop-jvm-linux-arm64:0.2.0-build125.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/compose/desktop/desktop-jvm-linux-arm64/0.2.0-build125/desktop-jvm-linux-arm64-0.2.0-build125.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/desktop/desktop-jvm-linux-arm64/0.2.0-build125/desktop-jvm-linux-arm64-0.2.0-build125.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/desktop/desktop-jvm-linux-arm64/0.2.0-build125/desktop-jvm-linux-arm64-0.2.0-build125.pom
     Required by:
         project :desktop

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Here is the gradle build file for that module:
```
plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose") version "0.2.0-build125"
}

group = "com.example"
version = "1.0"


kotlin {
    jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "11"
        }
    }
    sourceSets {
        val jvmMain by getting {
            dependencies {
                implementation(project(":common"))
                implementation(compose.desktop.currentOs)

            }
        }
        val jvmTest by getting
    }
}

compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "jvm"

        }
    }
}

```

This exact same project and gradle build file works 100% normally and correctly without throwing any errors on a debian machine with an x86 processor.

**Comment by malliaridis** [comment]
Is there a reason why you are using a very old build version (0.2.0-build125)? And have you tried the latest release or build?
Latest stable release: 0.3.2
Latest build: 0.4.0-rc2

Soon there will be a stable release 0.4.0, so stay tuned for that too.

_P.s. be careful while switching to the latest build, there were multiple breaking changes from your current version._

**Comment by kirill-grouchnikov** [comment]
FWIW there are only ARM builds available for macOS at https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/desktop/

**Comment by BobdoIe** [comment]
> Is there a reason why you are using a very old build version (0.2.0-build125)? And have you tried the latest release or build?
> Latest stable release: 0.3.2
> Latest build: 0.4.0-rc2
> 
> Soon there will be a stable release 0.4.0, so stay tuned for that too.
> 
> _P.s. be careful while switching to the latest build, there were multiple breaking changes from your current version._

Yes I had same problem with the latest version. The reason for posting the issue with the old version is because that is the version that a project created with the new project window uses. 
@kirill-grouchnikov  is correct that there isn't an ARM build other than for Mac. Does anyone know if there are plans to add a build for other ARM machines?

**Comment by olonho** [comment]
Linux/ARM is not supported at the moment, as there's no Skia/Skiko build for it. Contributions are welcome.

**Comment by olonho** [comment]
Added very experimental linux/arm64 support to Skiko 0.3.2. Feel free to test it with Compose and let us know the result!

**Comment by BobdoIe** [comment]
> Added very experimental linux/arm64 support to Skiko 0.3.2. Feel free to test it with Compose and let us know the result!

Awesome, thanks! Will give it a try on a arm64 PinePhone with several different OS's and provide feedback.

**Comment by olonho** [comment]
As of `0.5.0-build229` we support `linux-arm64` in Compose builds.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5393">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
