### ISSUE TITLE
OutlinedTextField doesn't match designs

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#718]
The code using `OutlinedTextField` at the bottom yields the following:

<img width="301" alt="Screen Shot 2021-05-29 at 3 26 35 PM" src="https://user-images.githubusercontent.com/871169/120087376-54d83080-c0b5-11eb-9331-f09a1ca353b9.png">

There is no easy way to center the `label` vertically to 1. Look good and 2. Match the designs on google's site - https://material.io/components/text-fields#anatomy

```Kotlin
val userState = remember { mutableStateOf(TextFieldValue()) }
OutlinedTextField(
    value = userState.value,
    onValueChange = { userState.value = it },
    label = {
        Text("User")
    },
)

Spacer(Modifier.height(10.dp))

val passwordState = remember { mutableStateOf(TextFieldValue()) }
OutlinedTextField(
    value = passwordState.value,
    onValueChange = { passwordState.value = it },
    label = { Text("Password") },
    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
    visualTransformation = PasswordVisualTransformation(),
)
```

**Comment by malliaridis** [comment]
On what build version and platform have you build this example? Because I couldn't reproduce your issue with the build version `0.4.0-build211` on desktop (windows).
![Screenshot_1](https://user-images.githubusercontent.com/33470669/120090042-c9d05800-c0ff-11eb-990b-6b484b00906a.jpg)

**Comment by ScottPierce** [comment]
Setting `singleLine = true` fixes this, and centers it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5392">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
