### ISSUE TITLE
Where is the DirectoryDialog

### ISSUE THREAD

**Issue by zhanweisun** [JetBrains/compose-jb#726]
I use compose develop a build tools ,need to select a Directory,so where is the DirectoryDialog,how can i use it.

**Comment by olonho** [comment]
See https://github.com/JetBrains/compose-jb/blob/a7b837257940492e045fe8b81b82cb96b82698a1/examples/notepad/src/main/kotlin/util/Dialogs.kt#L17 for example.

**Comment by akurasov** [comment]
@zhanweisun 
do you have any other questions here?

**Comment by zhanweisun** [comment]
Thanks!no questions!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5391">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
