### ISSUE TITLE
0.4.0 template says "// TODO: remove after new build is published"

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#727]
```
pluginManagement {
    repositories {
        // TODO: remove after new build is published
        mavenLocal()
```

Not sure if it was left in intentionally.

**Comment by igordmn** [comment]
Fixed in https://github.com/JetBrains/compose-jb/pull/719

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5390">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
