### ISSUE TITLE
0.4.0 template: Consider removing "(System.getenv("COMPOSE_TEMPLATE_COMPOSE_VERSION")"

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#728]
`id("org.jetbrains.compose") version (System.getenv("COMPOSE_TEMPLATE_COMPOSE_VERSION") ?: "0.4.0")`

The template contains the above. It's not immediately clear why someone using a template would have a system env for a template compose version and I'd argue that it's actually more confusing to a newcomer. Consider removing?

**Comment by akurasov** [comment]
@olonho what do you think about it?

**Comment by akurasov** [comment]
I believe it doesn't hurt, but is convenient for people who want to go through all examples. This way they don't need to modify version for each one.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5389">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
