### ISSUE TITLE
0.4.0 multiplatform template: "kotlin("multiplatform") // kotlin("jvm") doesn't work well in IDEA/AndroidStudio"

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#729]
`kotlin("multiplatform") // kotlin("jvm") doesn't work well in IDEA/AndroidStudio (https://github.com/JetBrains/compose-jb/issues/22)`

That issue linked in the template seems to be fixed. Should that line in the template be updated now?

**Comment by StefanOltmann** [comment]
Is it fixed? Using the current v0.4.0 I tried to change the "desktop" part into a `kotlin("jvm")` and Android Studio 4.2.1 had a lot of weird problems compiling the gradle script. Unfortunately without giving any explicit error - just a low of red.

Which exact tools and settings do you use that this works for you?

( I'm on a Apple M1 by the way. That seems to cause a low of problems anyway. )

**Comment by akurasov** [comment]
@ColtonIdle , @StefanOltmann do you have such issue now?

**Comment by ColtonIdle** [comment]
My bug was just pointing out the fact that someone should fix this in the template

https://github.com/JetBrains/compose-jb/blob/master/templates/multiplatform-template/desktop/build.gradle.kts#L5

You can see the template (which I copy pasted) now includes kotlin("multiplatform"), but I don't know whether kotlin("jvm") is actually what should be there.

**Comment by StefanOltmann** [comment]
> My bug was just pointing out the fact that someone should fix this in the template
> 
> https://github.com/JetBrains/compose-jb/blob/master/templates/multiplatform-template/desktop/build.gradle.kts#L5
> 
> You can see the template (which I copy pasted) now includes kotlin("multiplatform"), but I don't know whether kotlin("jvm") is actually what should be there.

Why don't you test if that works now instead of guessing?

My "desktop" module is currently "multiplatform" because "jvm" did not work the last time I tried it.

**Comment by ColtonIdle** [comment]
@StefanOltmann why the downvote. Is this not a valid question?

**Comment by StefanOltmann** [comment]
> You can see the template (which I copy pasted) now includes kotlin("multiplatform"), but I don't know whether kotlin("jvm") is actually what should be there.

In you do not know there is a way to find it out.

I suggest that you change it and test how well it works now.

**Comment by ColtonIdle** [comment]
That's not helpful because I'm not asking about my code. I'm asking about the template. This bug was created suggesting that the template should be updated if possible, similar to this TODO that was left in the code which was then subsequently removed.

https://github.com/JetBrains/compose-jb/issues/727

**Comment by akurasov** [comment]
It is correct to use multiplatform in this case. I removed the comment.

**Comment by ColtonIdle** [comment]
@akurasov can you explain why multiplatform is correct to use? I'm just curious at trying to understand kmm projects better.

**Comment by akurasov** [comment]
@ColtonIdle 
desktop code could be compiled both for jvm and native (in future) platforms.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5388">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
