### ISSUE TITLE
LazyColumn does not re-render items

### ISSUE THREAD

**Issue by gbaldeck** [JetBrains/compose-jb#733]
This is happening in Compose version 0.4.0.

After debugging it appears that the composable passed to the `items` function in LazyListScope is not being called when state changes.

The expected behavior can be seen in this video on an old build of my application, when I click items they are being selected and highlighted appropriately.
https://imgur.com/q0HilDl

And below is the video of the bugged behavior. The items are not being highlighted when clicked, they are only highlighted when I open another window.
https://imgur.com/Cmopmyp

Here is the code and project where the bug can be reproduced. When the project is run and you are prompted for the GD Installation Folder and GD Save Folder the only one required is the GD Installation Folder. Create a folder with a new text file, then rename the text file and its extension to "GrimInternals64.exe". Put that folder as the GD Installation Folder and you will be taken to the main screen where the bug can be reproduced.
https://github.com/recursivelftr/Grim-Locations/blob/master/src/main/kotlin/io/grimlocations/ui/view/component/LocationListComponent.kt#L52

**Comment by fyam1997** [comment]
should be the same issue here, the button that never have clicked will not respond to the changes of primary color

```kotlin
@Composable
fun test(
) {
    var isDark by remember { mutableStateOf(false) }
    MaterialTheme(
        colors = lightColors(primary = if (isDark) Color.Black else Color.White)
    ) {
        LazyColumn {
            items(5) {
                Button(
                    onClick = { isDark = !isDark },
                    content = { Text("Button") }
                )
            }
        }
    }
}
```

**Comment by igordmn** [comment]
> the button that never have clicked will not respond to the changes of primary color

Look like it is because of this [issue](https://issuetracker.google.com/issues/189170789). `LazyColumn` doesn't update its items because `MaterialTheme` uses `CompositionLocal` under  the hood

**Comment by gbaldeck** [comment]
I debugged this, and whatever the underlying cause the compose function passed to the items function is not being called when it should.

**Comment by igordmn** [comment]
>be fixed once merged into this repo.

Let us know if the issue still reproduces on the latest version

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5384">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
