### ISSUE TITLE
compose web: IllegalStateException: could not convert sym to ClassifierSymbol

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#734]
Was reported in slack:
https://kotlinlang.slack.com/archives/C01F2HV7868/p1622556507126100

```
In my module serverApp, I can reproduce just with these dependencies added and no additional javascript code in the module (and no common dependencies).

val jsMain by getting {
    dependencies {
        implementation(libs.kotlinxCoroutines)
        implementation(compose.runtime)
        implementation(compose.web.core)
        implementation(compose.web.widgets)
    }
}
But in my module browserApp (which where the actual compose code lives), I’m not able to reproduce with a similar set of dependencies.

There was a similar stacktrace from the compiler caused by ktor and a coroutines version conflict, which was resolved with the ktor 1.6 release.  This could be a similar issue, although the error isn’t really helpful to isolate further.
```

**Comment by ccjernigan** [comment]
This should reproduce the issue with `./gradlew assemble`

[project.zip](https://github.com/JetBrains/compose-jb/files/6578452/project.zip)

**Comment by hfhbd** [comment]
Compose (and androidx) still use Coroutines 1.4.3 under the hood, and the JS artifact is a compiled artifact, which is not binary compatible with 1.5.0

**Comment by eymar** [comment]
There is a new (not very official) release 0.0.0-web-dev-14.1 and it has coroutines version overridden. It's built from a "fix" branch, so people could start migrating to new APIs sooner rather than waiting for androidx getting the coroutines new version.

```
kotlinVersion=1.5.10
kotlinxCoroutinesVersion=1.5.0
composeWebVersion=0.0.0-web-dev-14.1
```

having these versions, `./gradlew assemble` was successful.

I'm not closing the issue for now. Please let me know how dev-14.1 works for you. Thanks :)

**Comment by langara** [comment]
0.0.0-web-dev-14.1 fixed the issue for me.

**Comment by hfhbd** [comment]
It works for me too. But I don't like the current dependency behavior with the compiled IR klib artifacts at all. This prevents you changing one dependency, you can't simple override one usage.

Eg I have a `bootstrap` compose wrapper library, and to use `14.1`, I have to update compose not only in the consumer project, but in the library as well. This is not a problem with owned libraries, but it is one with third party libraries.

**Comment by eymar** [comment]
@hfhbd I see your point.  The thing is that sometimes such things can't be avoided unfortunately. 
We hope/expect it won't happen often though, especially when we get to some mature state of compose-web.  

Thanks for your feedback!

**Comment by eymar** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/1717755 - is not merged at the moment.
So I guess we'll need to make a special build  from a "fix" branch for the next release as well.

Closing this for now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5383">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
