### ISSUE TITLE
tutorials/Window_API outdated

### ISSUE THREAD

**Issue by Foso** [JetBrains/compose-jb#74]
The tutorial isn't working anymore with version "0.1.0-build63" . 

The constructors/functions of Window and AppManager changed.

Box is also missing "alignment", but that can quickly be replaced with "gravity"

**Comment by GGorAA** [comment]
`+`

I tried to update to that version, and part of my `build.gradle.kts` with Compose settings is broken.

![image](https://user-images.githubusercontent.com/61655029/98442723-137b3600-210f-11eb-85cc-463076731500.png)
![image](https://user-images.githubusercontent.com/61655029/98442725-18d88080-210f-11eb-9b4a-366dc4e8c372.png)

But documentation hasn't been updated :)

**Comment by igordmn** [comment]
Actually it is "0.1.0-build63" that outdated :).

The most latest version is "0.1.0-m1-build62".

We increment the build number separately for m1.

But to avoid confusion in the future I think we should use only one build number.

**Comment by nightrider77** [comment]
Trying to make app fullscreen...
Example from official docs...
What's wrong? Lib version is "0.3.0-build152"

![image](https://user-images.githubusercontent.com/20248492/107887380-bfa29900-6f16-11eb-9bac-8209791a03aa.png)

**Comment by jimgoog** [comment]
@nightrider77 You are probably using an incompatible version of Kotlin.  Please ensure you are using `1.4.30`.

**Comment by nightrider77** [comment]
> @nightrider77 You are probably using an incompatible version of Kotlin. Please ensure you are using `1.4.30`.

Thank you, version was 1.4.20. Changed to 1.4.30, built & run ok.
But still have

> Lambda argument should be moved out of parentheses 

and very interesting notice

![image](https://user-images.githubusercontent.com/20248492/107949900-0049f300-6fa7-11eb-8be4-387008e9cd59.png)
