### ISSUE TITLE
Web: Publish TestUtils

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#740]
To test compose web html code, your test utils provide a nice api.  Please publish it as a separate artifact.
```kotlin
val jsTest by getting {
  dependencies {
    implementation(compose.web.test)
  }
}
```

**Comment by hfhbd** [comment]
Fixed by https://github.com/JetBrains/compose-jb/pull/1165

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5379">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
