### ISSUE TITLE
Web: No content builder on EmptyElements

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#744]
Some HTML elements are not allowed to have a body.

https://developer.mozilla.org/en-US/docs/Glossary/Empty_element

Currently, at least `Br { Text("foo") }` is possible, but should not.

_Originally posted by @hfhbd in https://github.com/JetBrains/compose-jb/pull/741#discussion_r644674888_

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6418">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
