### ISSUE TITLE
web: error when @Composable passed to constructor

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#746]
Reported here: https://github.com/JetBrains/compose-jb/issues/740

```
It is possible to store a @Composable function as an attribute and execute it later?
I want to implement a table, which holds the composable rows and display/execute the composable row function lazily when needed
data class Cell(val color: Color?, val content: @Composable () -> Unit)
SPOILER: I get this error message: this._$cell_0._content is not a function. (In 'this._$cell_0._content($composer_0, 0)', 'this._$cell_0._content' is undefined)

To play around: Use the defined Table in https://github.com/hfhbd/bootstrap-compose
```

Related: https://youtrack.jetbrains.com/issue/KT-46880

**Comment by eymar** [comment]
It works since kotlin 1.5.10

**Comment by gsteckman** [comment]
I'm still running into this issue, using kotlin 1.5.21 and compose-web 1.0.0-alpha2.

**Comment by hfhbd** [comment]
@gsteckman @eymar
This workaround works, but I still want native support :)
```kotlin
data class DataHolderTyped<T>(val s: T)

@Test
fun dataClassTypedWorkaroundTest() = runTest {
    val s = @Composable { Text("a") }
    val holder = DataHolderTyped(s)
    composition {
        holder.s()
    }
   assertEquals("a", root.innerHTML)
}

data class DataHolder<T>(val s: T)

@Test
@Ignore // https://github.com/JetBrains/compose-jb/issues/746
fun dataClassTest() = runTest {
    val holder = DataHolder @Composable { Text("a") }
    composition {
       holder.s()
    }
    assertEquals("a", root.innerHTML)
}
```

**Comment by gsteckman** [comment]
I wasn't getting compiler crashes, but rather all class instance values that should be initialized by constructor parameters were uninitialized. So for example DataHolder's val s would be uninitialized. Even other parameters to the same class that are not @Composable function types, like a String, would be unitialized.

**Comment by hfhbd** [comment]
@gsteckman Yes, this is the reason. Composable overrides the function to add all composable stuff, but resets other parameters to null too.

Interesting this crashes for me, I don't know what is "better" no crash but null, or compiler crash :D
```
org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (61,38) in /Users/philipwedemann/GitHub/bootstrap-compose/src/jsTest/kotlin/app/softwork/bootstrapcompose/TableTest.kt
```
```kotlin
@Test
fun dataClassTypedWorkaroundTestCrash() = runTest {
    val holder = DataHolderTyped(@Composable { Text("a") })
    composition {
        holder.s()
    }
    assertEquals("a", root.innerHTML)
}
```

**Comment by eymar** [comment]
fixed. added new tests cases: https://github.com/JetBrains/compose-jb/blob/master/web/compose-compiler-integration/src/jsTest/kotlin/ComposablesInConstructorTests.kt

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6299">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
