### ISSUE TITLE
ui.window.Window() reacting strange to `enabled` parameter change

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#752]
Was making window which block parent window when opened (Dialog analog), and find out what parent window always go under previous selected window when child window closed and **`enabled`** go back to **true**. It's not going under all opened windows, just previous one. Same moves without **`enabled`** changing doesn't provoke this behavior.

https://user-images.githubusercontent.com/80458677/120803570-5c338a00-c54c-11eb-98fc-c0ac67eebfce.mp4

```
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowSize
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState

@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {

    var switch by remember { mutableStateOf(false) }
    var text by remember { mutableStateOf("")}
    var untouchable by remember { mutableStateOf(true) }
    val state = rememberWindowState(size = WindowSize(300.dp, 300.dp))

    Window(state , title = "MainWindow", enabled = untouchable) {
        Box(Modifier.fillMaxSize()) {
            Button( onClick = { switch = !switch }, modifier = Modifier.align(Alignment.Center) ) {
                Text("Open")
            }
        }
    }

    if (switch) {
        untouchable = false
        val statePopup = rememberWindowState(size = WindowSize(200.dp, 200.dp))
        Window(statePopup, title = "PopUp", onCloseRequest = {switch = false; untouchable = true}) {
            Box(Modifier.fillMaxSize()) {
                Text( text, Modifier.align(Alignment.Center) )
            }
        }
    }

}
```

**Comment by igordmn** [comment]
It is strange behavior, will look into it.

BTW, maybe [Dialog](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new#dialogs) would work for your case? It will block the parent window.

**Comment by Exidel** [comment]
When you minimize child window with blocked parent it minimize too. Seems like when you close child window it become unfocusable and same happening with parent one. 

`ui.window.Dialog` doesn't block `ui.window.Window` but work fine with old `compose.desktop.Window`. Also following question: Gonna be old `desktop.Window` deprecated since ui.window.Window will came out of `@ExperimentalApi`?

**Comment by igordmn** [comment]
> ui.window.Dialog doesn't block ui.window.Window
It should block if you place Dialog inside Window.

> Also following question: Gonna be old desktop.Window deprecated since ui.window.Window will came out of @ExperimentalApi

Yes, the old one will be deprecated. There will still be the usual `ComposeWindow` that extends JFrame.

**Comment by Exidel** [comment]
> It should block if you place Dialog inside Window.

My fault, it work fine. Thanks

**Comment by igordmn** [comment]
Can't reproduce the original issue on 1.0.0-beta5, with using Window(enabled=false) instead of Dialog (Window, OpenJDK 15).

If it is still relevant for you, let us know.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6250">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
