### ISSUE TITLE
Capture output / headless usage

### ISSUE THREAD

**Issue by XLordalX** [JetBrains/compose-jb#753]
I'm trying to use compose purely as a positioning framework of nodes. I don't need it to render anything on the screen. All I need is for compose to layout the nodes and return the x, y, width and height of each node every time something is updated. Kind of similar to a headless browser.

Is it possible to use compose as a headless renderer?

**Comment by igordmn** [comment]
Try this:
```
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.platform.TestComposeWindow
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking

@OptIn(ExperimentalComposeUiApi::class)
fun main() = runBlocking {
    val window = TestComposeWindow(width = 800, height = 600, coroutineContext = coroutineContext)
    window.setContent {
        LaunchedEffect(Unit) {
            while (true) {
                delay(1000)
                println("tick")
            }
        }
    }

    delay(5000)
    window.dispose()
}
```

There still be a picture in the background to which compose will render.

Probably in the future we can use fake picture instead of the real one. We can provide ability to override surface, so developers can write comething like this:
```
TestComposeWindow(surface = Surface.makeNull(800, 600))
```

**Comment by ragunathjawahar** [comment]
I am able to get the picture, is there anything else I am missing here?

```kotlin
val imageBytes = window.surface.makeImageSnapshot().encodeToData()?.bytes ?: return@runBlocking
ByteArrayInputStream(imageBytes).use {
  val renderedImage = ImageIO.read(it)
  ImageIO.write(renderedImage, "png", FileOutputStream("this-better-be-good.png"))
}
```

**Comment by igordmn** [comment]
1. If you only need the first frame, you shouldn't override `coroutineContext = coroutineContext`, just omit it.
2. You don't need to read/write image, the bytes are already in PNG format (you can choose another format, using for example `encodeToData(EncodedImageFormat.JPEG)` ):
```
val imageBytes = window.surface.makeImageSnapshot().encodeToData()!!.bytes
File("this-better-be-good.png").writeBytes(imageBytes)
```

**Comment by ragunathjawahar** [comment]
Very helpful, thank you!

**Comment by XLordalX** [comment]
> Try this:
> 
> ```
> import androidx.compose.runtime.LaunchedEffect
> import androidx.compose.ui.ExperimentalComposeUiApi
> import androidx.compose.ui.platform.TestComposeWindow
> import kotlinx.coroutines.delay
> import kotlinx.coroutines.runBlocking
> 
> @OptIn(ExperimentalComposeUiApi::class)
> fun main() = runBlocking {
>     val window = TestComposeWindow(width = 800, height = 600, coroutineContext = coroutineContext)
>     window.setContent {
>         LaunchedEffect(Unit) {
>             while (true) {
>                 delay(1000)
>                 println("tick")
>             }
>         }
>     }
> 
>     delay(5000)
>     window.dispose()
> }
> ```
> 
> There still be a picture in the background to which compose will render.
> 
> Probably in the future we can use a fake picture instead of the real one. We can provide ability to override surface, so developers can write comething like this:
> 
> ```
> TestComposeWindow(surface = Surface.makeNull(800, 600))
> ```

How would I get the coordinates, width and height of all nodes in the hierarchy using this approach?
