### ISSUE TITLE
Support `isSystemInDarkTheme()`

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#755]
For my project that I'm converting from android compose to jetbrains compose, I created a theme that is basically a replica of the "jetsnack" compose sample app. https://github.com/android/compose-samples/tree/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme

But in Theme.kt `isSystemInDarkTheme` does not compile on desktop. import androidx.compose.foundation.isSystemInDarkTheme

**Comment by smallshen** [comment]
https://github.com/Dansoftowner/jSystemThemeDetector
this may work

**Comment by akurasov** [comment]
Closing, as it is a duplicate of https://github.com/JetBrains/compose-jb/issues/169. 
BTW, it already works on MacOs and Windows.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6358">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
