### ISSUE TITLE
Compose desktop not compatible with macOS 10.14.6

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-jb#76]
I tried to run the demo app provided here: https://github.com/JetBrains/compose-jb/issues/61#issuecomment-723054985 with the changes proposed down here https://github.com/JetBrains/compose-jb/issues/61#issuecomment-723083540 but after a successful build it crashed immediately at runtime on my Mac with macOS 10.14.6. The crash report indicates that this only seems to work with macOS 10.15+. Is this intended and documented somewhere?

```
Dyld Error Message:
  Symbol not found: _objc_opt_new
  Referenced from: /Users/USER/*/libskiko.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
```
The test was done on OpenJDK 15.

**Comment by olonho** [comment]
Yes, this issue is known and to be fixed with following releases.

**Comment by timmattison** [comment]
I can verify that it does work in 10.15.x for me. Are there any plans in fixing it for 10.14.x? Is that what you meant when you said it will be "fixed with following releases"? Or do you mean that it is fixed with following releases of MacOS?

**Comment by olonho** [comment]
Fixed in recent builds, i.e. 0.2.0-build128.
