### ISSUE TITLE
SVG scaling changed in Skija 0.92.1, be aware

### ISSUE THREAD

**Issue by tonsky** [JetBrains/compose-jb#763]
Scaling via `SVGDOM::setContentSize()` will no longer work. Instead, more correct approach is implemented via `SVGDOM::getRoot()` and `SVGSVG::get/set X/Y/Width/Height/ViewBox/PreserveAspectRatio`.

Usage examples here: https://github.com/JetBrains/skija/blob/90712df54e0d93e48678746fc2e6b1741c3d26a0/examples/scenes/src/SVGScalingScene.java#L76-L83

**Comment by igordmn** [comment]
Fixed in 0.5.0-build224

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6417">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
