### ISSUE TITLE
Update IntelliJ plugin example to gradle intellij plugin 1.0

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#768]
It looks like writing intellij plugins with gradle hit 1.0 ~2 weeks ago. Would be nice to have the example updated.

https://github.com/JetBrains/gradle-intellij-plugin

**Comment by akurasov** [comment]
Now it uses 1.1.4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6322">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
