### ISSUE TITLE
Code Coverage / JaCoCo possible? Can you showcase it?

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-jb#769]
Starting from the Multiplatform template in IDEA 2021.1 I added the `jacoco` plugin to generate coverage reports for SonarQube, but the Task `jacocoTestReport` does not show up. Running `gradle tasks` does not list it at all.

How do I get a coverage report for my Compose for Desktop application?
Is there some special configuration or is JaCoCo just not able to coverage the unit tests (written in Kotlin) in `commonTest` or `jvmTest`?
Is that a bug that should be reported to Kotlin/Native or to the JaCoCo project?

**Comment by olonho** [comment]
Not sure if it relates to Compose for Desktop. It's just JVM application, so all tools applicable to JVM applications can be used.

**Comment by StefanOltmann** [comment]
I'm also not sure. Normally it is be possible with Kotlin Multiplatform to have JaCoCo report for the JVM modules, but I didn't get it working starting with the Compose for Desktop sample.

So I'm asking if a bug specific to Compose for Desktop does prevent this or if you can point me to how to do it.

If you write unit tests for Compose, don't you monitor/track your code coverage?

**Comment by StefanOltmann** [comment]
Ok, I figured out that Code coverage with KMM and Android is not possible right now. That's bad news, but it is how it is.
