### ISSUE TITLE
[Web] Should AttrsBuilder have "out" type parameter?

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#775]
The class is defined as follows:
```kotlin
class AttrsBuilder<TTag : Tag> : EventsListenerBuilder() {
    // ...
}
```

Looks like the `TTag` type parameter can be defined as `out`. This would give more flexibility when building custom components.

**Comment by eymar** [comment]
there is no `Tag` type parameter in the recent versions anymore. So I close this question.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6398">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
