### ISSUE TITLE
Can`t focus on compose like Box.

### ISSUE THREAD

**Issue by WWALKINGG** [JetBrains/compose-jb#776]
For create my components , but I cant focus the Box.
`

    var value by remember { mutableStateOf(TextFieldValue()) }
    val focusRequester = FocusRequester()
    Column(
        modifier = Modifier.padding(10.dp)
    ) {
        Box(
            modifier = Modifier.background(Color.Red).size(20.dp)
                .focusRequester(focusRequester)
                .focusModifier()
                .onFocusEvent {
                println("the red box is in [$it] focus state")
            }
        )
        Button({
            focusRequester.requestFocus()
        }) {
            Text("focus")
        }
    }

`

**Comment by igordmn** [comment]
You should place `onFocusEvent` before `focusModifier` (it is renamed to `focusTarget` in the latest version)

**Comment by WWALKINGG** [comment]
> You should place `onFocusEvent` before `focusModifier` (it is renamed to `focusTarget` in the latest version)

you are right.Thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6412">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
