### ISSUE TITLE
Text input doesn't support Option-Left/Right

### ISSUE THREAD

**Issue by soderbjorn** [JetBrains/compose-jb#79]
On the Mac, the Option key with Left/Right doesn't traverse between words, and Option-Shift with Left/Right doesn't select words. This can be seen in the Todo sample and makes text input feel non-native and cumbersome. (Other than that, impressive work!)

**Comment by olonho** [comment]
Yes, this is known issue.

**Comment by prepor** [comment]
The issue to track progress about this feature is here https://github.com/JetBrains/compose-jb/issues/277

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6486">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
