### ISSUE TITLE
Support for custom Info.plist entries

### ISSUE THREAD

**Issue by saket** [JetBrains/compose-jb#795]
For setting up deeplinking on macOS using `Desktop.getDesktop.setOpenURIHandler()`, Apple requires these entries to be present in its `Info.plist` file:

```xml
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>PACKAGE NAME OF APP</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>DEEPLINK SCHEME</string>
    </array>
  </dict>
</array>
```

It'd be nice if compose for desktop offers a standard API for contributing custom entries to `Info.plist`. This is possibly related to https://github.com/JetBrains/compose-jb/issues/773.

**Comment by AlexeyTsvetkov** [comment]
Issue for other platforms https://github.com/JetBrains/compose-jb/issues/855

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6400">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
