### ISSUE TITLE
Add support for hover/rollover modifier or interaction

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#80]
There is no `Interaction.rollover` which is an integral part of desktop experience that is driven by mouse. There's `Modifier.mouseScrollFilter` but no matching modifier to get notified on the mouse entering and leaving the composable bounds.

**Comment by olonho** [comment]
Please read tutorial at https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events

**Comment by olonho** [comment]
Not a bug. Common hover API in MPP Compose is desirable, but not yet done.

**Comment by kirill-grouchnikov** [comment]
Thanks for the link!

**Comment by kirill-grouchnikov** [comment]
Where is `import androidx.compose.ui.input.pointer.pointerMoveFilter` defined? I'm on build113 and it's not found.

**Comment by kirill-grouchnikov** [comment]
Oh, my bad. My code was in `commonMain` instead of `desktopMain`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6526">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
