### ISSUE TITLE
LazyColumn gets stuck scrolling when an item is too big.

### ISSUE THREAD

**Issue by Dominaezzz** [JetBrains/compose-jb#800]
I haven't isolated a reproducer for this yet but when the size of an item in the `LazyColumn` is really close to size of the `LazyColumn` itself, the scrollbar keeps snapping back, preventing further scrolling.
To escape this, I have to scrolll very aggressively, or fast enough to beat the snap.

**Comment by Dominaezzz** [comment]
Note to self: https://github.com/androidx/androidx/blob/d3a8167883356ee9c2d8cc7b48cc0463a8780c74/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/Scrollbar.desktop.kt#L458

**Comment by ryihan** [comment]
Fix 0.5.0........

**Comment by Dominaezzz** [comment]
Sorry this has nothing to do with srollbar. LazyColumn does this by itself.

**Comment by Dominaezzz** [comment]
https://user-images.githubusercontent.com/14130965/125849316-8885173f-faf6-4b52-8e66-b5d42a56e3fb.mp4

**Comment by Dominaezzz** [comment]
Tracked it down to this here https://github.com/androidx/androidx/blob/9f596ce819a7fd24401992aa249596d0dbc21d1d/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/lazy/LazyListMeasure.kt#L34 .

**Comment by Dominaezzz** [comment]
Moved to here https://issuetracker.google.com/issues/179593134 . It's not desktop specific.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-800">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
