### ISSUE TITLE
How can I get the lifecycle — attach to window on compose view?

### ISSUE THREAD

**Issue by dearXiaoCheng** [JetBrains/compose-jb#808]
I used the funcion:

DisposableEffect(key1 = true) {
     
        onDispose {
        }
    }

but in LazyColumn, the function is called ahead of attaching to window

How can I get the lifecycle — attach to window on compose view?

**Comment by igordmn** [comment]
What is meant by `ahead of attaching to window`?

The lifecycle is:
1. create the native window
2. show window
3. run frame rendering loop
- recompose content (call DisposableEffect's on the first recompose)
- layout
- draw
4. dispose
- call onDispose of DisposableEffect's
- dispose the native window

What code are you trying to run in `DisposableEffect`?

**Comment by dearXiaoCheng** [comment]
In RecyclerView, we can know the time of each item exposed (1px) exactly from window via the callback function-onViewAttachedToWindow & onViewDetachedFromWindow.

But in LazyColumn, I tried to use the side-effects function as follows:

DisposableEffect(true) {
      
        //enter the composition, do something.
        onDispose {
        // leave the Composition, do something
        }
    }

which happened before the item view exposed from the window.

For example, the last index  of visible item is 6, when I scrolled up, item 7 will be exposed but item 8 or 9 entered the composed function.

How can I get the exact time of exposing(attaching) and disposing(dettaching) from the window?

**Comment by igordmn** [comment]
You need to know if item in LazyColumn becomes visible to user? You can use `rememberLazyListState` for that

```
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.Text
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        val state = rememberLazyListState()

        fun isVisible(index: Int) = index in
                state.firstVisibleItemIndex until state.firstVisibleItemIndex + state.layoutInfo.visibleItemsInfo.size

        Column {
            Text("30 item is visible: ${isVisible(30)}")

            LazyColumn(Modifier.size(300.dp), state) {
                items(100) {
                    Text(it.toString())
                }
            }
        }
    }
}
```

LazyColumn can precomposes items that is not yet visible to user, or don't dispose already composed items if they are near the visible area of LazyColumn, but hidden.

**Comment by dearXiaoCheng** [comment]
It does work! Thanks a lot!!

But I also want to get the extra info about the node, such as the position on the screen, size

**Comment by igordmn** [comment]
>But I also want to get the extra info about the node, such as the position on the screen, size
You can write this info to a separate state using `Modifier.onGlobalyPositioned` and use it where you need it:

```
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.Text
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.remember
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.layout.boundsInParent
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        val state = rememberLazyListState()
        val indexToBounds = remember { mutableStateMapOf<Int, Rect>() }

        fun isVisible(index: Int) = index in
                state.firstVisibleItemIndex until state.firstVisibleItemIndex + state.layoutInfo.visibleItemsInfo.size

        Column {
            Text("item 30. is visible: ${isVisible(30)}. bounds: ${indexToBounds[30]}")

            LazyColumn(Modifier.size(300.dp), state) {
                items(100) { index ->
                    Text(
                        index.toString(),
                        Modifier.onGloballyPositioned {
                            indexToBounds[index] = it.boundsInParent()
                        }
                    )

                    DisposableEffect(indexToBounds) {
                        onDispose {
                            indexToBounds.remove(index)
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by akurasov** [comment]
@dearXiaoCheng do you have any other questions here?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6354">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
