### ISSUE TITLE
Incorrect / incomplete code snippet for getting raw mouse events

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#812]
https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events#mouse-rightmiddle-clicks-and-keyboard-modifiers has a snippet that is a bit vague about what exactly it provides. If you look at the accompanying GIF, it only reports PRESSED events, and no RELEASED events.

On Windows, `MouseEvent.isPopupTrigger` is true on release, not on press. So this snippet can't be used to detect a popup trigger mouse event. Is there another way to get access to all underlying raw mouse events until there's something at the higher, Compose level?

**Comment by Exidel** [comment]
Doesn't it similar to #540 ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6262">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
