### ISSUE TITLE
web: Create a tutorial to showcase the usages of DomSideEffect

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#813]

**Comment by akurasov** [comment]
implemented with https://github.com/JetBrains/compose-jb/pull/975

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6331">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
