### ISSUE TITLE
How to set ripple's state?

### ISSUE THREAD

**Issue by gtf35** [JetBrains/compose-jb#814]
Now I could listen mouse enter and leave

```
Modifier.pointerMoveFilter(
    onEnter = {
        active.value = true
        false
     },
     onExit = {
         active.value = false
        false
     }
)
````

But how can I set ripple to holder state(just like the effect of a button being held)?

This way I can make a user feedback that fits the theme when the mouse hovers over

**Comment by akurasov** [comment]
@gtf35 do you mean you want to create ripple effect when cursor is above the button? Or is it something else?

**Comment by gtf35** [comment]
Yes, you are right! I want to use this feature to create ripple effect when mouse cursor is above the button :)

**Comment by akurasov** [comment]
You can achieve it be passing your own MutableInteractionSource as a parameter of Button creation and send to it PressInteraction.Press events whenever mouse is moved inside the button, but it looks quite shitty, because ripple is good when it is rare, but when you move mouse it will look like you do 100 clicks per second. But you may play with it. 

Good example to learn this mechanics is https://github.com/Konyaco/BattleNetCompose/blob/4397f0be307702080d4527d37ad9a05e5739cb43/src/main/kotlin/component/Hoverable.kt

And for your specific case code example is: 
        var interactionSource = remember { MutableInteractionSource() }
        var active by remember{mutableStateOf(false)};
        MaterialTheme {
            Box() {
                Column {
                    Button(onClick = {}, modifier = Modifier.pointerMoveFilter( onEnter = {active = true; false}, onExit = {active=false; false},
                                    onMove = {position -> if (active) interactionSource.tryEmit(PressInteraction.Press(position)); false} ).
                                 clickable(interactionSource, indication = rememberRipple(color = Color.Green.copy(0.02f)), onClick={} )) {
                        Text("test2")
                    }
                }
            }
        }

**Comment by gtf35** [comment]
Thanks a lot, but the effect looks a bit funny, 🤣🤣

By the way, when android device connected usb mouse, it has the same effect(the first layer of ripples when hovering, the second layer of ripples when pressed)
![image](https://user-images.githubusercontent.com/22125696/126753173-7a013afd-6912-4504-97d3-8d51c6b5c5f0.png)

**Comment by akurasov** [comment]
I think such effects require careful tuning. From my perspective simple static hover looks much better. 

Do you have any other questions here regarding Compose MPP or I will close it?

**Comment by gtf35** [comment]
How could I let the ripple unfold directly without animation, I did not find the relevant API(At the same time, it does not affect the ripple animation when clicked.)

**Comment by akurasov** [comment]
What do you mean by ripple without animation? For me whole idea of the ripple is animation of circle...

**Comment by gtf35** [comment]
Yeah, but, if each button is manually implemented, I feels it so hard, is it directly calling the built-in ripple component is better

**Comment by akurasov** [comment]
I don't understand you( 
What exactly you want to draw and in what situations?

**Comment by gtf35** [comment]
https://user-images.githubusercontent.com/22125696/126758919-9e88039c-df7a-482c-9d0a-0863d58f7f3b.mp4

I want to achieve the effect of Android default mouse

**Comment by akurasov** [comment]
Basically, you want to draw circle when mouse is on top of component and draw another one of the same color on top of it (so it become darker) when mouse is clicked?

**Comment by akurasov** [comment]
Then you just need to combine hoverable logic from the example I shared, with the ripple indication and use the same color for both. Probably you will need to play with Alpha value.

**Comment by gtf35** [comment]
It seems that I have to solve it manually by myself, thanks for your help
