### ISSUE TITLE
Resources not included in app package

### ISSUE THREAD

**Issue by carlos-sa** [JetBrains/compose-jb#826]
Hello!

First of all thank you for this wonderful tool such as compose desktop!

I'm building a simple project and it is working fine, but when I build a MSI (.\gradlew package) 
the installed program do not have my application assets (png's, html's) which I have under a src/main/resources folder

I noticed that it stopped working  when I updated the compose plugin to version "0.5.0-build225" (which solved a whole lot of other issues, so thank you)

any suggestion on this?

Thank you!

**Comment by AlexeyTsvetkov** [comment]
@carlos-sa how exactly do you read a resource? A snippet or a simplified example project would be useful.

I've checked with the `0.5.0-build228`, and normal Java resource loading works, as expected:
```
import androidx.compose.desktop.Window
import androidx.compose.material.Text
import androidx.compose.material.MaterialTheme
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue

object Program {
    @JvmStatic
    fun main(args: Array<String>) {
        val resource = this.javaClass.getResource("example-resource.txt")
        val contents = resource.openStream().use {
            it.readBytes().toString(Charsets.UTF_8)
        }
        Window {
            var text by remember { mutableStateOf(contents) }

            MaterialTheme {
                Text(text)
            }
        }
    }
}
```

**Comment by carlos-sa** [comment]
Hi There

I was using it in a different way... But tried the way you said

`object FileUtils {
    fun imageFromFile(path: String): URL {
        return this.javaClass.getResource(path)
    }
}`

and in main()
`    val resource = FileUtils.imageFromFile("pinrequest.html")
    val contents = resource.openStream().use {
        println(it.readBytes().toString(Charsets.UTF_8))
    }`

It worked fined running local, but the package still do not contain the resource

Thank you

**Comment by olonho** [comment]
Resource shall be packed in jar, is it?

**Comment by carlos-sa** [comment]
Hi there!
before the update the resources were packed into the app folder of the built application.
It was my mistake. Tried again with "this.javaClass.getResource(path)" and it in fact worked.

Thanks for the help, closing this issue!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6372">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
