### ISSUE TITLE
Desktop. Disable default reaction on secondary clicks when we click on Button, move Slider, etc

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#832]
Currently we can click on a Button with the right mouse Button and it will consume it.

Desktop platforms don't usually send clicks when we we click not with the left mouse button.

**Comment by olonho** [comment]
We can also just right click on button and get `onClicked` callback.

**Comment by igordmn** [comment]
Should be fixed in 1.0.0-beta6-dev474

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6215">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
