### ISSUE TITLE
Web: 228 - InputType.Number is the only nullable implementation

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#834]
"Why" is `InputType.Number` the only nullable implementation of the latest `Input` refactoring? Every other `InputType` is non-null, even when the casting fails.

**Comment by eymar** [comment]
`RangeInput` also has nullable parameters.

I'm not sure I completely understand the question.  Are you asking why not to make all other inputs accept nullables?

For example:
```kotlin
fun TextInput(value: String = "", attrsBuilder: InputAttrsBuilder<String>.() -> Unit = {}) {..}
```

Or maybe are you asking about the non-nullable types of the values in `onInput { value -> ... }` ?

In what case the casting fails?

thanks!

**Comment by hfhbd** [comment]
> Or maybe are you asking about the non-nullable types of the values in onInput { value -> ... } ?

Yes, every other input (Boolean, String) has a default non-null [value](https://github.com/JetBrains/compose-jb/blob/585da89c8c0c2d57876885380ed83366960dc616/web/core/src/jsMain/kotlin/androidx/compose/web/attributes/PredefinedAttrValues.kt#L38) if the cast fails (`false` or `""`), only the `InputTypeNumberValue` uses a nullable `Number`
