### ISSUE TITLE
Desktop. Preview. Graphical artifacts when the system DPI is fractional

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#837]
Compose 0.0.0-custom-build322, Windows 10, System scale 1.25

1. Run IDEA with Compose IDEA plugin (`./gradlew runIde` in idea-plugin)
2. Open example `idea-plugin\examples\desktop-project`
3. Start preview
4. Result:
![image](https://user-images.githubusercontent.com/5963351/123925077-3bb3ef80-d993-11eb-8f98-7efbda580b8b.png)
On the screenshot we can see that the image was scaled, and not rendered pixel-top-pixel

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5378">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
