### ISSUE TITLE
GUI Builder

### ISSUE THREAD

**Issue by Immortalin** [JetBrains/compose-jb#84]

**Comment by dector** [comment]
In-IDE preview and proper hot-reload is more preferable as for me. :)

**Comment by olonho** [comment]
Please provide more details on what do you expect for the UI builder?

**Comment by akurasov** [comment]
Closing as inactive. in-IDE Preview functionality is available with IDEA plugin starting from build 0.5.0-build235.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6396">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
