### ISSUE TITLE
app is broken (singing application for MacOS)

### ISSUE THREAD

**Issue by qq7866196** [JetBrains/compose-jb#840]
I  packageDmg a dmg file,  I can install and run in current macos ,but when I copy this file to another macos , it can install but 
can't run , the dialog show me it is broken。how can I fix it ?

jdk:15
kotlin("jvm") version "1.4.30"
id("org.jetbrains.compose") version "0.3.1"
current macos version:11.2
another macos version:11.4

**Comment by olonho** [comment]
One must sign and notarize app with Apple to run it on other machines, see https://github.com/JetBrains/compose-jb/tree/master/tutorials/Signing_and_notarization_on_macOS

**Comment by qq7866196** [comment]
@olonho thank you! I found in the test,The app build from Xcode can run  on other machines,and it not need Developer ID ,so why the compose need,do you know?

**Comment by olonho** [comment]
Do not think that one can run unsigned apps of other machines on recent macOS versions.

**Comment by akurasov** [comment]
@qq7866196 probably that app is being signed by Xcode somehow. We cannot sign applications automatically, since we don't have certificate to sign it (it should be provided by developer).

**Comment by qq7866196** [comment]
I want use it development some tools, and share in my team. But I am  not an apple developer, it  not free.  I not need to publish to app store. hope it can support on the future version.

**Comment by akurasov** [comment]
@qq7866196 it is not about publishing to appStore. MacOs verifies signature for any application that is run on a modern MacOS system. And an application should be signed by developer certificate, that, by default we don't have - developer shall provided it to build system, as described in the tutorial.

**Comment by akurasov** [comment]
Closing as inactive

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5376">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
