### ISSUE TITLE
Remove "Trying METAL rendering..." from every single new ComposeWindow launch

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#844]
Every single new ComposeWindow launch is accompanied with "Trying METAL rendering..." in the console output

**Comment by olonho** [comment]
Fixed in Skiko https://github.com/JetBrains/skiko/commit/a1246846ca60605389fe0109cabc83c3fd644d72 - will be merged with next Skiko update.

**Comment by akurasov** [comment]
Fixed in 0.5.0-build245

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-844">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
