### ISSUE TITLE
@Preview annotation can't be resolved

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#846]
Hello! I followed Nikolays steps (from slack) for adding @Preview to my desktop app

This is what I did

I'm on Android Studio latest arctic fox. downloaded plugin. Tried adding compose.uiTooling but it didn't find that dep. Then I updated version to 0.5.0-build229 and then it found uiTooling dep. :thumbsup:

I then added a simple composable in a file without a main function and I get this error:
<img width="703" alt="Screen Shot 2021-07-01 at 10 55 01 AM" src="https://user-images.githubusercontent.com/31751141/124285328-d17a8680-db1b-11eb-988d-6656435b6177.png">

The file that I added this temporary composable to is /src/commonMain/kotlin/App.kt

Here is the block where I added uiTooling dep.

```
kotlin {
    android()
    jvm("desktop")
    sourceSets {
        named("commonMain") {
            dependencies {
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material)
                implementation(compose.uiTooling)
            }
        }
    }
}
```

**Comment by chris-hatton** [comment]
I think the issue is that there's no intended 'common' artifact for this; if you place `implementation(compose.uiTooling)` within a `desktopMain` dependency block, it should be resolved.

**Comment by olonho** [comment]
Common `@Preview` annotation is not yet supported.

**Comment by ColtonIdle** [comment]
@olonho so I cannot have any Previews in my common code?

**Comment by olonho** [comment]
Not at the moment, but you can create common annotation.

**Comment by ColtonIdle** [comment]
@olonho thanks for confirming. I thought with the fact that desktop now had preview that I could put Previews in common code.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5374">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
