### ISSUE TITLE
Compose Preview Plugin won't install on AS Bumblebee

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#847]
Tried to install from AS Bumblebee C2.
Installed fine in arctic fox
<img width="257" alt="Screen Shot 2021-07-01 at 10 20 26 AM" src="https://user-images.githubusercontent.com/31751141/124285633-17cfe580-db1c-11eb-98cb-26b559218b4a.png">

**Comment by olonho** [comment]
![image](https://user-images.githubusercontent.com/2600522/124448226-dee97800-dd8a-11eb-9a3b-65813a9e89e7.png)

**Comment by olonho** [comment]
![image](https://user-images.githubusercontent.com/2600522/124469828-85da0e00-dda3-11eb-8e44-c2fcd00db6f3.png)

**Comment by olonho** [comment]
Seems to work fine on Bumblebee, please reopen if still relevant.

**Comment by ColtonIdle** [comment]
Still won't install for me?

<img width="445" alt="Screen Shot 2021-07-06 at 2 37 26 PM" src="https://user-images.githubusercontent.com/31751141/124650395-b2575e00-de67-11eb-93ee-1484462e0ff8.png">

<img width="638" alt="Screen Shot 2021-07-06 at 2 37 49 PM" src="https://user-images.githubusercontent.com/31751141/124650435-be432000-de67-11eb-99ec-9c424319a683.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5373">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
