### ISSUE TITLE
macOS 12: Window is blurry

### ISSUE THREAD

**Issue by AshStefanOltmann** [JetBrains/compose-jb#856]
After updating from macOS 11 stable to macOS 12 Beta 2 (21A5268h) the Compose for Desktop window is blurry as you see in the screenshots.

### Screenshots

<img width="1121" alt="all" src="https://user-images.githubusercontent.com/85175249/124605439-301d6880-de6c-11eb-9b94-d4b097e480b2.png">

<img width="722" alt="single" src="https://user-images.githubusercontent.com/85175249/124605454-34498600-de6c-11eb-8f85-6bd4be438433.png">

<img width="223" alt="menu" src="https://user-images.githubusercontent.com/85175249/124605471-37dd0d00-de6c-11eb-875a-2bd8716892b5.png">

### Sample project
Using the stable IDEA version create a new  "Jetpack Compose for Desktop" - "Multiplatform" project and start the application with "gradle run".

### IDE
```
IntelliJ IDEA 2021.1.3 (Community Edition)
Build #IC-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins: detekt (1.17.1), org.sonarlint.idea (5.0.1.33703), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), org.jetbrains.compose.desktop.ide (0.0.1)
Kotlin: 211-1.5.20-release-284-IJ7442.40
```
### Java version
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

**Comment by olonho** [comment]
Are regular Swing apps rendered in the same low-dpi manner?

**Comment by olonho** [comment]
Also which JDK do you use to run Compose apps?

**Comment by AshStefanOltmann** [comment]
> Are regular Swing apps rendered in the same low-dpi manner?

I don't know as I don't have another Swing app to test.
Is there a particular project you want me to check out and run?

> Also which JDK do you use to run Compose apps?

I run It with `AdoptOpenJDK 15.0.2` as described above.
I just tested `Liberica 11.0.11` and `Amazon Coretto 16.0.1` with the same issue.

Updating to macOS 12 was really the single thing I changed.

**Comment by olonho** [comment]
Just in the same app run smth like 

```
fun main() {
    SwingUtilities.invokeLater { // Setup the application's window
        val frame = JFrame("Text")
        frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE

        // Setup the content pane
        val contentPane = JPanel()
        contentPane.layout = BorderLayout()
        frame.contentPane = contentPane

        // Add a button to the content pane
        val button = JButton("Click here")
        contentPane.add(button, BorderLayout.CENTER)
        button.addActionListener { button.text = "Clicked" }

        // Display the window
        frame.pack()
        frame.setSize(400, 400)
        frame.setLocationRelativeTo(null)
        frame.isVisible = true
    }
```

**Comment by AshStefanOltmann** [comment]
Yes, that's also blurred.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/85175249/124612192-6d84f480-de72-11eb-8aa4-e23a16424908.png">

So, yes, it may not relate to Compose but a general Swing rendering Issue on macOS 12. :/

**Comment by Rsedaikin** [comment]
Please try the following example
```
fun main() {
    System.setProperty("sun.java2d.uiScale.enabled", "true")
    System.setProperty("sun.java2d.uiScale", "2.0")

    SwingUtilities.invokeLater { // Setup the application's window
        val frame = JFrame("Text")
        frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE

        // Setup the content pane
        val contentPane = JPanel()
        contentPane.layout = BorderLayout()
        frame.contentPane = contentPane

        // Add a button to the content pane
        val button = JButton("Click here")
        contentPane.add(button, BorderLayout.CENTER)
        button.addActionListener { button.text = "Clicked" }

        // Display the window
        frame.pack()
        frame.setSize(400, 400)
        frame.setLocationRelativeTo(null)
        frame.isVisible = true
   }
}
```

**Comment by AshStefanOltmann** [comment]
@Rsedaikin Thanks, that half of the solution.

The window content like "Click here" on the button becomes sharp again, but the Window title and menu stay blurry.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/85175249/124615910-f18cab80-de75-11eb-9c03-7c51debb1150.png">

**Comment by Rsedaikin** [comment]
It's all about the `NSHighResolutionCapable` parameter, which is put in the application settings file `info.plist`, and since when launched via `./gradlew run`, there is no `info.plist`, then everything appears in low resolution
If you run your code through `./gradlew run`, everything will be blurry, but if you pack it into the application through the `./gradlew package`, everything is fine because `NSHighResolutionCapable` is set automatically.

<img width="771" alt="pic" src="https://user-images.githubusercontent.com/32446626/124879244-b3a69900-dfd5-11eb-848d-8e38a7c7d4a6.png">

**Comment by AshStefanOltmann** [comment]
Thank you for investigating that issue. This is fine as it's a dev-only issue. I don't see why it worked before macOS 12, but I can live with that if it looks good in production.

**Comment by AshStefanOltmann** [comment]
I can also confirm now that the production build looks fine on macOS 12 and setting the system properties help in development for the contents of the window.

@Rsedaikin  I'm fine with closing this issue should you decide not to fix this minor issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5368">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
