### ISSUE TITLE
Regression in Todo example app after multiple Compose updates

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#86]
There are two issues currently.

Originally the Todo app looked like this:
![1](https://user-images.githubusercontent.com/26204457/98739014-84854c80-23a0-11eb-82a3-c298b29142f0.png)

`0.1.0-m1-build62` update (3b583678c7cdca638b4a3a10fb5e11d06534baf8) broke some colors and styles:
![2](https://user-images.githubusercontent.com/26204457/98739418-3755aa80-23a1-11eb-9dc4-09b5cfa64421.png)

And the most important is `0.1.0-build113` update (aa2a8740ca95225b776b0b951654b5880b3bffc4). Navigation now does not work, when you click on an item - nothing happens. I tried to debug and found that when the `Router` applies the new state (with the new child), the view receives old state (with old child).

How to debug the second bug:
1. Put first breakpoint [here](https://github.com/JetBrains/compose-jb/blob/60ac4a7ab17f3989a3e736acf1d03a3503da3497/examples/todoapp/common/utils/src/commonMain/kotlin/example/todo/common/utils/ValueComposable.kt#L21)
2. Put second breakpoint [here](https://github.com/JetBrains/compose-jb/blob/60ac4a7ab17f3989a3e736acf1d03a3503da3497/examples/todoapp/common/utils/src/commonMain/kotlin/example/todo/common/utils/RouterStateComposable.kt#L36)
2. Click on an item
3. The first breakpoint will fire and you can observe the new state (`it.activeChild` ~ Edit)
4. Continue execution
5. The second breakpoint will fire and you can observe the old state (`state.activeChild` ~ Main)

Please let me know if I can help anyhow.

**Comment by arkivanov** [comment]
Android app also has broken text styles. But navigation works just fine.

**Comment by prepor** [comment]
It's not broken, the version of `Text` with previous behavior was moved to `androidx.compose.material.Text`

**Comment by arkivanov** [comment]
Thanks! I will update Text part tonight. The navigation in desktop still needs to be addressed.

**Comment by igordmn** [comment]
There is a problem in Compose:
https://github.com/JetBrains/compose-jb/issues/87

And in the example:
https://github.com/JetBrains/compose-jb/pull/88
(I change imports for Text too :) )

TodoRoot was created two times, and when we click on item - we are using not the right "router".

**Comment by arkivanov** [comment]
Thanks for fixing the issues!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6524">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
