### ISSUE TITLE
Web: Build235 No recomposing attribute builders after state change

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#863]
With the latest unreleased build235 the button won't update its state from `disabled` to `enabled`, because this attribute builder function is not called anymore, although the states `username` and `password` are changed (and the inputs are updated/recomposed).
```kotlin
var username by mutableStateOf("")
var password by mutableStateOf("")
H1 {
    Text("Login")
}
TextInput(username) {
    placeholder("user.name")
    onInput {
        username = it.value
    }
}
PasswordInput(password) {
    placeholder("password")
    onInput {
        password = it.value
    }
}
Button(attrs = {
    if (username.isEmpty() || password.isEmpty()) {
        disabled()
    }
    onClick {
        println("clicked")
    }
}) {
    Text("Login")
}
```

[ComposeTodo Kopie.zip](https://github.com/JetBrains/compose-jb/files/6778555/ComposeTodo.Kopie.zip)

**Comment by hfhbd** [comment]
Missing `remember`...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5366">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
