### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError ???

### ISSUE THREAD

**Issue by youndon** [JetBrains/compose-jb#868]
I'm trying build simple desktop application compose and in my normal kotlin code try something like: 

 ```kotlin
fun main() = Window {
     Text("kotlin compose!!")
}
```
So when I make run to code, I got this Error :
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void androidx.compose.desktop.AppWindow_desktopKt.Window-BIDTD-Q$default(java.lang.String, long, long, boolean, java.awt.image.BufferedImage, androidx.compose.ui.window.v1.MenuBar, boolean, boolean, androidx.compose.desktop.WindowEvents, kotlin.jvm.functions.Function0, kotlin.jvm.functions.Function0, int, java.lang.Object)'
```
To be honest code like this work fine when I use *Default desktop compose project*,
But I trying in normal kotlin project in this time.

OS: Ubuntu 20.10 
INV: Intellij Idea 2021.1

**Comment by akurasov** [comment]
Hi! Which Compose MP build do you use?

**Comment by youndon** [comment]
I used desktop compose 0.4.0 and that's one works fine like I said, The Error showing when only I run the compose in normal kotlin project.

**Comment by akurasov** [comment]
Could you try to use latest build and new Window API?

plugins {
    kotlin("jvm") version "1.5.10"
    id("org.jetbrains.compose") version "0.5.0-build235"
}

@OptIn(ExperimentalComposeUiApi::class)
fun main() {
    application {
        Window(::exitApplication) {
            Text("Hello!")
        }
    }
}

**Comment by youndon** [comment]
> Could you try to use latest build and new Window API?
> 
> plugins {
>     kotlin("jvm") version "1.5.10"
>     id("org.jetbrains.compose") version "0.5.0-build235"
> }
> 
> @OptIn(ExperimentalComposeUiApi::class)
> fun main() {
>     application {
>         Window(::exitApplication) {
>             Text("Hello!")
>         }

**Comment by youndon** [comment]
Thanks a loot, And yes this solve my issue compose and everything works fine.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5363">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
