### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by Yourun-proger** [JetBrains/compose-jb#876]
in main page under the codeviewer exists a link:
https://github.com/JetBrains/compose-jb
but i think it need to be:
https://github.com/JetBrains/compose-jb/tree/master/examples/codeviewer
and i want to fix it. I search the source where i can change this link, but i not found this. Can anybody help me to update link?

**Comment by igordmn** [comment]
The link on main page to codeviewer example is right and leads to https://github.com/JetBrains/compose-jb/tree/master/examples/codeviewer

Can you post a link to the page which has a wrong link to the codeviewer example?

**Comment by Yourun-proger** [comment]
Hello @igordmn! I can't send a photo, but i can get a html-code, where i see:
`<a class="wt-link wt-link_external" href="https://github.com/JetBrains/compose-jb/" target="_blank">GitHub</a>`
and see this on the main page - https://www.jetbrains.com/lp/compose/

**Comment by Yourun-proger** [comment]
I check the [dir](https://github.com/JetBrains/compose-jb/tree/master/examples/web_landing) of site, but in `src/jsMain/kotlin/com/sample/content` don't see file with mention of codeviewer => i don't know how i can fix it(

**Comment by igordmn** [comment]
> Hello @igordmn! I can't send a photo, but i can get a html-code, where i see:
> `<a class="wt-link wt-link_external" href="https://github.com/JetBrains/compose-jb/" target="_blank">GitHub</a>`
> and see this on the main page - https://www.jetbrains.com/lp/compose/

Thanks for noticing! We will change the link on that page. The source of this page is not open-source

**Comment by Yourun-proger** [comment]
Okay) Im glad to help you!

**Comment by Yourun-proger** [comment]
Today i see the good link. Thank you to fix)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5358">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
