### ISSUE TITLE
Can not find org.jetbrains.compose.demo.widgets.ui.MainView

### ISSUE THREAD

**Issue by toplinuxsir** [JetBrains/compose-jb#884]
Can not find org.jetbrains.compose.demo.widgets.ui.MainView
How to add the depenceny?
Thanks!

**Comment by akurasov** [comment]
Are you trying to build CodeViewer application?

**Comment by akurasov** [comment]
Closing as dormant topic

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5355">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
