### ISSUE TITLE
Name clash for maxWidth/minWidth max/minHeight as extensions of StyleBuilder and of GenericStyleSheetBuilder

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#886]
Right now we don't have StyleBuilder.maxWidth/minWidth but having them is the most intuitive thing to do, so right now I don't see any other quick non-intrusive option rather than to just rename media counterparts.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5353">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
