### ISSUE TITLE
Don't pass String as a Color signature

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#891]
This is the part of our intention to get rid of passing String signatures in CSS API.  There should be no need to use string-backed signatures in first place, in extreme cases when this had to be done we have property. In all other cases the benefits of using typed Signature outweighs the usability perks one might encounter. As a part of our efforts to improve such usability we also introduce HTML constants - see https://github.com/JetBrains/compose-jb/issues/890

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5350">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
