### ISSUE TITLE
Add API for referring external CSS variable

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#892]
As of now there's no convenient way to access a CSS variable that was set externally via stylesheet

**Comment by Schahen** [comment]
I'm moving this one to the next milestone since we still need to design it better

**Comment by eymar** [comment]
closing. it's possible to achieve the same via `variable(...)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5349">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
