### ISSUE TITLE
Remove CSSVariables context and introduce specialized methods for adding String- and Number-valued CSS variables

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#894]
The only purpose of CSSVariables interface is to limit the scope of `by variable` delegation. We've decided that it's totally fine to keep this delegation in global scope and in StyleBuilder scope (where prefix is optionally added - this is the way how it is right now)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5348">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
