### ISSUE TITLE
Introduce support for CSS Grid API

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#895]
De-facto this is the last big missing piece in our CSS API

**Comment by Schahen** [comment]
There will be some improvements on type system but we can claim that now it's possible to create some standard grid interface without calling "raw" property calls. Overall I'm considering this task done and will introduce any changes / improvements and bugfixes, if needed, in a separate issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-895">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
