### ISSUE TITLE
How to add local Jar dependencies？

### ISSUE THREAD

**Issue by D10NGYANG** [JetBrains/compose-jb#899]
I want to use compose to develop a serial communication tool on macOS, but I need to load a native jar library, adding it to Project Structure is not working

**Comment by D10NGYANG** [comment]
`dependencies {
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    implementation(compose.desktop.currentOs)
    implementation(files("libs/RXTXcomm.jar.aar"))
}`

I got it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5344">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
