### ISSUE TITLE
Add screenshots of example applications within their README.

### ISSUE THREAD

**Issue by ibmorgan** [JetBrains/compose-jb#90]
Add a screenshot of the application within the README to show off what's been achieved, rather than a interested individual needing to pull and build the application just to view the UI.

**Comment by rcgonzalezf** [comment]
This is definitely a great point to offer some datapoints:
- I cloned the repo.
- And then when I tried to build the project it took almost 10 minutes to download the dependencies and IntelliJ is still indexing dependencies all to just see the example:

![Screen Shot 2020-11-11 at 8 43 25 PM](https://user-images.githubusercontent.com/437653/98893027-d5f41100-245e-11eb-829f-a85b6fd5ff27.png)

And now is asking me for the Android SDK, another 10 or more minutes.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6523">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
