### ISSUE TITLE
Deprecate Color.RGB, Color.HSL etc. functions in favor of top-level rgb, hsl an so on

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#902]
We've decided that this:

```kotlin
   borderColor(rgb(10, 20, 30))
```

is better than this
```kotlin
   borderColor(Color.rgb(200, 20, 10))
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5343">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
