### ISSUE TITLE
New Window API code snippet does not work

### ISSUE THREAD

**Issue by stoddartaw** [JetBrains/compose-jb#903]
[https://github.com/JetBrains/compose-jb/blob/3df74e26aa0170452720ea4ba10cfbdc42b3f6e9/tutorials/Window_API_new/README.md#handle-window-level-shortcuts](https://github.com/JetBrains/compose-jb/blob/3df74e26aa0170452720ea4ba10cfbdc42b3f6e9/tutorials/Window_API_new/README.md#handle-window-level-shortcuts)

The code here does not work as onPreviewKeyEvent is not a parameter in the Window constructor, latest release 0.4.0.

How can I set top level shortcuts with the new Window API?

**Comment by stoddartaw** [comment]
Parameter exists in newer builds v0.5.0-build245

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5342">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
