### ISSUE TITLE
The Preview feature does not work in a KMP module with Compose enabled

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#908]
STR:

1. Add `implementation(compose.uiTooling)` to `desktopMain` source set of the `todoapp/common/compose-ui` module
2. Sync Gradle
3. Add any `@Preview @Composable` function to `desktopMain` source set
4. Run the preview

AR: The `configureDesktopPreview` Gradle task is not added for the module and Preview feature fails with the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'configureDesktopPreview' not found in project ':common:compose-ui'.
```

ER: The Preview feature works

**Comment by slavonnet** [comment]
I have another issue)) Preview migrate to cwd up and AS does not find class ActivittPreview in classpath

**Comment by akurasov** [comment]
I took the application and was not able to use uiTooling. Seems compose version is a bit old. I can't where compose version is setup there. Could you point to it?

**Comment by arkivanov** [comment]
@akurasov What application do you mean? If it is the TodoApp example, then it's [here](https://github.com/JetBrains/compose-jb/blob/e071b2889b86b7008f03719e96b2fa46c96cc63a/examples/todoapp/buildSrc/buildSrc/src/main/kotlin/Deps.kt#L16).

**Comment by arkivanov** [comment]
@akurasov I updated Compose to `0.5.0-build262` and Kotlin to `1.5.21`, and pushed a reproducer [commit](https://github.com/arkivanov/compose-jb/commit/3f0ec9012df109208cd06b24f9f9a519d1059d4c) to a separate [branch](https://github.com/arkivanov/compose-jb/tree/preview-kmp-issue). The not working preview can be found [here](https://github.com/arkivanov/compose-jb/blob/preview-kmp-issue/examples/todoapp/common/compose-ui/src/desktopMain/kotlin/example/todo/common/ui/PreviewIssue.kt).

**Comment by akurasov** [comment]
So with build262 everything works fine? 

The issue could be in incompatible versions of Compose and IdeaCompose plugin. A check for it have been added recently.

**Comment by arkivanov** [comment]
@akurasov No, the issue is still there. I have updated the Compose IDEA plugin to match the Compose version.

**Comment by akurasov** [comment]
Reproduced(build262). configureDesktopPreview present in Gradle window, however if run manually the following error occurs:
> No value has been specified for property 'idePort$compose'.
> No value has been specified for property 'previewTarget$compose'.

**Comment by akurasov** [comment]
@arkivanov it is different - I tried to run the task manually.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5340">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
