### ISSUE TITLE
packagemsi version shoud be number

### ISSUE THREAD

**Issue by youngxhui** [JetBrains/compose-jb#91]
![image](https://user-images.githubusercontent.com/16971804/98884358-c3172600-24ca-11eb-8591-35fa90f611f6.png)

in windows,  **version**  format of the string is as follows:

major.minor.build

and major, minor and build mast be number.

https://docs.microsoft.com/zh-cn/windows/win32/msi/productversion?redirectedfrom=MSDN

like this.

```markdown
compose.desktop {
    application {
        nativeDistributions {
            packageName = "ExampleApp"
            version = "0.1.0"
            description = "Compose Example App"
            copyright = "© 2020 My Name. All rights reserved."
            vendor = "Example vendor"
        }
    }
}
```

**Comment by olonho** [comment]
What exactly prevents setting string which you find appropriate?

**Comment by youngxhui** [comment]
write  `version = "0.1-SNAPSHOT"` ,**packageMsi** command is error.

```
������������, �����˴������MSI ��װ�����: �汾�ַ��������� MSI ���� [1.0-SNAPSHOT] �޸�����: �������¹������ô��������� “win.msi.productVersion"��https://msdn.microsoft.com/en-us/library/aa370859%28v=VS.85%29.aspx��
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6471">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
