### ISSUE TITLE
Graphics card: Microsoft Basic Render Driver is blacklisted.

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/compose-jb#918]
Running any Compose for Desktop app prints on startup:

```
Graphics card: Microsoft Basic Render Driver is blacklisted.
Graphics card: Microsoft Basic Render Driver is blacklisted.
Failed to create DirectX12 device.
Failed to create Skia Direct3D context!
```

The application however launches and works fine - well, except for being slow, and I'm not sure if this is because of above or just because of the framework not being optimized enough yet. E.g. the codeviewer example app I tried is unusably laggy.

System: `Microsoft Windows [Version 10.0.18363.1500]`
Potentially relevant ss from Device Manager:
![2021-07-21_163809](https://user-images.githubusercontent.com/38111589/126508066-059070d1-cf53-4210-8735-e61359808a68.png)

The only other such case I found on Internet is here: https://github.com/arkivanov/CompoSnake/issues/1

**Comment by akurasov** [comment]
@mcpiroman 
it means that there are known issues with your driver and Compose MPP most probably won't work properly with it. So it falls back to software rendering. 
cc: @Rsedaikin

**Comment by akurasov** [comment]
@mcpiroman do you have any other questions here?

**Comment by mcpiroman** [comment]
Noo, only maybe that it could be explained in the message itself more. I assume the blacklist will eventually shrink as more drivers are supported right? Otherwise yeah, you may close this ticket.

**Comment by akurasov** [comment]
Yes, we are working now on enhancing fallback logic to reduce blacklist as much as possible

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5334">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
