### ISSUE TITLE
Impossible to negate CSSNumeric value directly

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#921]
This work as expected:

```kotlin
bottom((-10).percent)
```

While this does not:
```kotlin
bottom(-10.percent)
```
Even though first version is recommended - and IDE will even suggest to wrap the negative value,  I don't see a reason why we should not support the second form - it's cheap and we already override bunch of operators

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5333">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
