### ISSUE TITLE
Support transform functions in CSS API

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-jb#922]
Basically we've decided to make it possible to write typed versions of any transformation, so instead of
```kotlin
 property("transform", "perspective(500px) translate(10px, 0, 20px) rotateY(3deg)")
```

one will be able to form arguments without necessity to form a string

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6316">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
