### ISSUE TITLE
web inputs bug: Inputs internal state can deviate from the mutableState or even constant value

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#925]
```kotlin
TextInput(value = "hardcoded value should never change")
```
**Expected result:**
The input value should never change (when someone types in).

**Actual result:**
The text in the input can be edited by typing.

The issue brings a need to support two modes for the inputs:
- controlled (when compose manages the state and input obey it)
- uncontrolled (when input relies on its own internal state)

https://kotlinlang.slack.com/archives/C01F2HV7868/p1626746533003700

**Comment by eymar** [comment]
was merged while ago

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6276">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
