### ISSUE TITLE
.dmg .deb can not be run if package name contains dots

### ISSUE THREAD

**Issue by AChep** [JetBrains/compose-jb#928]
If your `packageName` contains dots (and/or long enough) then opening the app on Ubuntu or Mac will fail with
```
Error opening "/opt/xx.xxxxxxx.xxxxx.xxxxxxx.yyyyy/lib/app/xx.xxxxxxx.xxxxx.xxxxxxx.cfg" file: No such file or directory
```
Notice the `.yyyyy` part missing in the .cfg file.

Windows distribution works fine.

Used compose `0.5.0-build262`.

**Comment by AChep** [comment]
The log is from Ubuntu, on Mac I was unable to get any kind of info from it.

**Comment by akurasov** [comment]
Seems it is the same as https://github.com/JetBrains/compose-jb/issues/904 
@AChep could you share your project there?

**Comment by akurasov** [comment]
@AChep  thank you!

**Comment by AChep** [comment]
![image](https://user-images.githubusercontent.com/990982/126676747-b54dc66b-45bd-44b1-b5fe-f1d4fa0bab1e.png)
Error log.

[ComposeBug.zip](https://github.com/JetBrains/compose-jb/files/6863920/ComposeBug.zip)
@akurasov  It's basically a generated Hello world app with package name set to `ComposeBug.Pls.Fix`. I have not tested it on the Mac, cause of certificates and apples and stuff.

**Comment by akurasov** [comment]
@AChep thank you! Would you mind if we continue in https://github.com/JetBrains/compose-jb/issues/904 (I copied the reproducer there) and I close this one as duplicate?

**Comment by AChep** [comment]
If that's the same issue then I don't mind at all.

**Comment by akurasov** [comment]
Closing. We continue in https://github.com/JetBrains/compose-jb/issues/904

**Comment by AChep** [comment]
@akurasov judging from the comments in https://github.com/JetBrains/compose-jb/issues/904 this is not a duplicate, is it?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6139">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
