### ISSUE TITLE
Why DesktopPlatform change to internal 😲

### ISSUE THREAD

**Issue by Modificator** [JetBrains/compose-jb#930]
`androidx.compose.ui.platform.DesktopPlatform` it's useful , I do not want to write same code 😣

**Comment by kirill-grouchnikov** [comment]
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/DesktopPlatform.desktop.kt has something like 4-5 real lines of code to copy to your codebase

**Comment by igordmn** [comment]
It was added mostly for our internal purposes in the past, but we aren't ready to make it a public API yet, as there maybe problems in the future extending it. Word `Platform` is vague and doesn't tell what it returns (os/architecture/shell/etc).

You can use `org.jetbrains.skiko.hostOs` and `org.jetbrains.skiko.hostArch` instead, they are narrower in their responsibilities.

**Comment by Modificator** [comment]
Thanks 😄, `org.jetbrains.skiko.hostOs` make it working. Maybe I should create a issue for  skiko about provide source.jar

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6352">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
