### ISSUE TITLE
JS preset not working

### ISSUE THREAD

**Issue by dragossusi** [JetBrains/compose-jb#935]
## What I'm trying to do
I have a gradle module called `ui` which has the code for the screen for android/desktop/web. I am also using Kodein for DI.
I can't get the web to work, if I comment these lines, everything works.

## Version

    const val kotlin = "1.5.21"
    const val compose = "0.5.0-build262"

## Config

    js(IR) {
        browser()
        binaries.executable()
    }

        val jsMain by getting {
            dependencies {
                api(compose.web.core)
            }
        }

## Error

No matching variant of org.jetbrains.compose.foundation:foundation:0.5.0-build262 was found. The consumer was configured to find a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:

**Comment by akurasov** [comment]
Hi! Is your project available at GitHub or somewhere?

**Comment by dragossusi** [comment]
Hello, it is private, but I can add you to it, let me push the changes.

**Comment by dragossusi** [comment]
I have sent you an invite

**Comment by eymar** [comment]
Hi @dragossusi 
do you use `org.jetbrains.compose.foundation:foundation` in the common source set? 

`foundation` and some other modules are not ported to be used in kotlin/js.

here is a list of dependencies that can be used with js:
```
compose.web.core
compose.web.widgets
compose.runtime
```

**Comment by akurasov** [comment]
I also see that you are using Serialization plugin together with Compose plugin and they are not compatible at the moment. Workaround is to use them in separate modules.

**Comment by dragossusi** [comment]
> Hi @dragossusi
> do you use `org.jetbrains.compose.foundation:foundation` in the common source set?
> 
> `foundation` and some other modules are not ported to be used in kotlin/js.
> 
> here is a list of dependencies that can be used with js:
> 
> ```
> compose.web.core
> compose.web.widgets
> compose.runtime
> ```

I am using these:

                api(compose.runtime)
                api(compose.foundation)
                api(compose.material)
                api(compose.ui)

**Comment by eymar** [comment]
I see. It's not possible to use `foundation, material, ui` in kotlin/js.
I think you need to move these  dependencies to jvmMain source set so android and desktop depend on it.
And in kotlin/js you will need to implement `ui` using `compose.web.core` and/or `compose.web.widgets`.

**Comment by dragossusi** [comment]
@eymar would it be easy to do this myself(contributing to this repository)?

**Comment by akurasov** [comment]
@dragossusi what exactly do you want to contribute here?

**Comment by dragossusi** [comment]
Porting foundation, material and ui to kotlin/js

**Comment by eymar** [comment]
@dragossusi 
You might find this thread interesting - https://kotlinlang.slack.com/archives/C01F2HV7868/p1627583669021500
Porting those to kotlin/js won't be easy, although it should be doable. 

material, foundation and ui are not in compose-jb repo. They're in androidx project or its fork here - https://github.com/JetBrains/androidx

**Comment by akurasov** [comment]
@dragossusi do you have any other questions regarding this topic?

**Comment by dragossusi** [comment]
@akurasov no, we can close this issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6327">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
