### ISSUE TITLE
Provide unaryMinus operator for CSSSizeValue

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/compose-jb#936]
Hello!
I think it'd be great to be able to negate any `CSSSizeValue`.

Example use case where I try to negate the margin of the `:before` pseudo element to have a special border effect (using gradients on background):
```kotlin
val borderSize = 2.px
"$self:before" {
    margin(-borderSize)
    // other code
}
```

**Comment by Schahen** [comment]
Hey @LouisCAD! It looks like this was shipped with https://github.com/JetBrains/compose-jb/releases/v0.5.0-build270 (check out this issue - https://github.com/JetBrains/compose-jb/issues/921)

**Comment by LouisCAD** [comment]
True, thank you!
I updated and removed my extension.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6348">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
