### ISSUE TITLE
Allow custom packing of assets and folders

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#938]
It's important for us to have the ability to compile our own assets and resources into the final product that's installed on each platform. i.e. `System.load` doesn't know how to access files inside of a jar resources. The files have to be unpacked to folder, and then have `System.load` point to the extracted assets. I don't access these assets in my dev environment this way, and I shouldn't need to detect production and do something special for production concerning assets.

It's far easier to just package up a folder that's extracted on the internal path with each installed application. We'll need a way to access the path to these reliably. In development, I've been using `System.getProperty("user.dir")` to get the active running directory.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6337">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
