### ISSUE TITLE
compose table widget?

### ISSUE THREAD

**Issue by toplinuxsir** [JetBrains/compose-jb#941]
Is there any table wdigets ? to show grid table datas ?

**Comment by akurasov** [comment]
Have you tried LazyVerticalGrid?

**Comment by akurasov** [comment]
@toplinuxsir do you have any other questions here?

**Comment by toplinuxsir** [comment]
@akurasov , No , thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6326">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
