### ISSUE TITLE
Add transparency to Color in multiplatform widgets

### ISSUE THREAD

**Issue by andyburris** [JetBrains/compose-jb#943]
Currently, the Color class in the multiplatform widgets only supports red, green and blue values, and adding an alpha value would open up the entire range of colors.

**Comment by Schahen** [comment]
@andb3 just to be sure, are you talking about the multiplatform widgets that also have web target?

**Comment by andb3** [comment]
Yeah, from the `compose.web.widgets` artifact

**Comment by bitspittle** [comment]
> @andb3 just to be sure, are you talking about the multiplatform widgets that also have web target?

Yes, please, definitely. Working with web compose here, and was surprised to find out that there's no alpha on Color.

**Comment by eymar** [comment]
closing this issue. Reason: since 1.0.0 compose.web.widgets module was deprecated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6185">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
