### ISSUE TITLE
Compose Web: Missing support for SVG elements

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#958]
I'd like to use Web Compose to generate something like https://www.w3schools.com/html/html5_svg.asp:

```html
<!DOCTYPE html>
<html>
<body>

<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>

</body>
</html>
```
but it's not working.

**Comment by bitspittle** [comment]
I tried creating my own composables (forking code from `Elements.kt`), but am ending up with <svg> tags in my final html that for some reason don't work right.

I found these two links promising, they seem like what I'm dealing with:

https://stackoverflow.com/questions/24961151/svg-wont-show-until-i-edit-the-element-in-chrome-developer-tools
https://stackoverflow.com/questions/3492322/javascript-createelementns-and-svg

but the answers seem to point to using createElementNs, which I tried doing, but that's not even rendering my tag at all (I'm getting a class cast exception). I think it's time to give up for the night :)

---

Here's my code, maybe someone with more experience will spot the flaw right away:

```kotlin
import androidx.compose.runtime.Composable
import kotlinx.browser.document
import org.jetbrains.compose.web.dom.AttrBuilderContext
import org.jetbrains.compose.web.dom.ContentBuilder
import org.jetbrains.compose.web.dom.ElementBuilder
import org.jetbrains.compose.web.dom.TagElement
import org.w3c.dom.Element
import org.w3c.dom.svg.SVGElement
import org.w3c.dom.svg.SVGRectElement

private class SVGElementBuilderImplementation<TElement : SVGElement>(private val tagName: String) : ElementBuilder<TElement> {
    private val el: Element by lazy { document.createElement(tagName) }
//    Also tried:
//    private val el: Element by lazy { document.createElementNS("http://www.w3.org/2000/svg", tagName) }

    @Suppress("UNCHECKED_CAST")
    override fun create(): TElement = el.cloneNode() as TElement
}

private val Rect: ElementBuilder<SVGRectElement> = SVGElementBuilderImplementation("rect")
private val Svg: ElementBuilder<SVGElement> = SVGElementBuilderImplementation("svg")

@Composable
fun Rect(
    attrs: AttrBuilderContext<SVGRectElement>? = null,
    content: ContentBuilder<SVGRectElement>? = null
) {
    TagElement(
        elementBuilder = Rect,
        applyAttrs = attrs,
        content = content
    )
}

@Composable
fun Svg(
    attrs: AttrBuilderContext<SVGElement>? = null,
    content: ContentBuilder<SVGElement>? = null
) {
    TagElement(
        elementBuilder = Svg,
        applyAttrs = attrs,
        content = content
    )
}
```

**Comment by bitspittle** [comment]
Ah, probably traces to TagElement itself:

```kotlin
@Composable
fun <TElement : Element> TagElement(...) {
    ...
    ComposeDomNode<ElementScope<TElement>, DomElementWrapper, DomApplier>(
        factory = {
            DomElementWrapper(elementBuilder.create() as HTMLElement)...
```

<svg> is **not** an HTMLElement, so this is throwing a cast exception

**Comment by eymar** [comment]
@Schahen Could you please link your PR with SVG support here once its merged?

**Comment by akurasov** [comment]
SVG elements are supported in beta.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6242">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
