### ISSUE TITLE
specified for property 'iconFile' does not exist.

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#960]
When running `./gradlew clean :app:packageDmg` I get the following error:
```
 File '/Users/scott.pierce/repository/app/build/compose/default-icons/0.4.0/icon-mac.icns' specified for property 'iconFile' does not exist.
```

If I then run `./gradlew :app:packageDmg` again without the `clean`, everything compiles fine.

**Comment by erawhctim** [comment]
FWIW, I'm seeing the same error when clean building the "issues" example app: `./gradlew clean :desktop:package` throws the error, removing `clean` succeeds.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6128">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
