### ISSUE TITLE
Trailinig icon bug

### ISSUE THREAD

**Issue by AcoustickSan** [JetBrains/compose-jb#964]
after migration to 1.0.0-alpha1-rc1 a strange bug appeared
First screenshot - 0.5.0-build270
![изображение](https://user-images.githubusercontent.com/2283454/127771978-80eb8c6e-3d02-476a-a918-16f0acda3d71.png)
Second screenshot - 1.0.0-alpha1-rc1
![изображение](https://user-images.githubusercontent.com/2283454/127771987-725b73a8-3ecf-4017-a081-2c9624337909.png)

https://user-images.githubusercontent.com/2283454/127851397-8a1fecee-109a-4de3-8498-462503744d46.mov

**Comment by akurasov** [comment]
@AcoustickSan try it with 1.0.0-alpha1-rc3. For my tests it is fine again now.

**Comment by AcoustickSan** [comment]
> @AcoustickSan try it with 1.0.0-alpha1-rc3. For my tests it is fine again now.

fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6339">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
