### ISSUE TITLE
[Ubuntu 20.04] WindowEvents.onMaximize is never called

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#965]
If I pass `WindowEvents.onMaximize` to the main `Window`, it is never called.

```kotlin
    Window(
        title = "Example",
        events = WindowEvents(
            onMaximize = { println("onMaximize") },
        )
    ) {
        // Some content here
    }
```

I tried to minimize/maximize/restore the window, no output in the console.

Also maybe unrelated, but KDoc says about `WindowEvents.onRestore` the following:
> @param onRestore The event that is invoked when the window is restored after the window has been maximized or minimized.

Currently on my machine it is called only when the window's state is changed from minimized to normal. It is not called when the window is de-maximized. So it seems, either the KDoc is incorrect or there is a bug.

**Comment by AcoustickSan** [comment]
Have you tried the new Windows API? 
```kotlin
fun main() = application {
    val windowState = rememberWindowState()
     Window(
        onCloseRequest = ::exitApplication,
        state = windowState,
    ) {
            LaunchedEffect(windowState){
                snapshotFlow { windowState.placement }
                  .onEach {
                      if (it == WindowPlacement.Maximized){
                          println("onMaximize")
                      }
                  }
                .launchIn(this)
        }
    }
}    
```

**Comment by arkivanov** [comment]
Checked the new API, it works fine

**Comment by arkivanov** [comment]
However I could not find any replacement for `onFocusGet` and `onFocusLost` events.

**Comment by igordmn** [comment]
> However I could not find any replacement for onFocusGet and onFocusLost events.

Unfortunately, we haven't implemented it for the new API yet (but we plan to). As a temporary workaround, you can use Swing interop:

```
import androidx.compose.runtime.DisposableEffect
import androidx.compose.ui.window.singleWindowApplication
import java.awt.event.FocusEvent
import java.awt.event.FocusListener

fun main() = singleWindowApplication {
    DisposableEffect(Unit) {
        window.addFocusListener(object : FocusListener {
            override fun focusGained(e: FocusEvent) {
            }

            override fun focusLost(e: FocusEvent) {
            }
        })
        onDispose {}
    }
}
```

**Comment by AcoustickSan** [comment]
> > However I could not find any replacement for onFocusGet and onFocusLost events.
> 
> Unfortunately, we haven't implemented it for the new API yet (but we plan to). As a temporary workaround, you can use Swing interop:
> 
> ```
> import androidx.compose.runtime.DisposableEffect
> import androidx.compose.ui.window.singleWindowApplication
> import java.awt.event.FocusEvent
> import java.awt.event.FocusListener
> 
> fun main() = singleWindowApplication {
>     DisposableEffect(Unit) {
>         window.addFocusListener(object : FocusListener {
>             override fun focusGained(e: FocusEvent) {
>             }
> 
>             override fun focusLost(e: FocusEvent) {
>             }
>         })
>         onDispose {}
>     }
> }
> ```

not work for me

**Comment by igordmn** [comment]
Let's move requestFocus/isFocused to [another issue](https://github.com/JetBrains/compose-jb/issues/1343)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6252">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
