### ISSUE TITLE
Icons are only rendered as black

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-jb#99]
When using `Icon` instead of `Image`, only a black filled version of a PNG is rendered. Compare this to the image being rendered properly (via `Image`).

Reproduction snippet:

```kotlin
import androidx.compose.desktop.Window
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.asImageAsset
import java.net.URL

fun main() {
    Window {
        Column {
            Image(
                image(URL("https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f004.png")),
            )
            Icon(
                image(URL("https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f004.png")),
            )
        }
    }
}

@Composable
fun image(url: URL) = remember(url) {
    org.jetbrains.skija.Image.makeFromEncoded(url.readBytes()).asImageAsset()
}
```

![image](https://user-images.githubusercontent.com/2178959/99086314-a1509880-25c9-11eb-994d-33b18c5ad343.png)

**Comment by andkulikov** [comment]
Icon is adding the tinting by default. It is expected to be used with real icons, not opaque bitmaps. the default text color is automatically calculated by the background. for example when the background color is `surface` icon is tinted to `onSurface`. the same color js used as a color for the Text. so it work as expected by the compose material library

**Comment by olonho** [comment]
Guess works as intended.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6522">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
