### ISSUE TITLE
Screen Density isn't adjusted when plugging in an external monitor

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-jb#990]
This is a recreation of the bug I created here: https://github.com/JetBrains/compose-jb/issues/183

I have a 16" MBP with a retina display, 2X 1080P monitors.

I'm still seeing this problem, when I open the app on my macbook pro, then plug in the laptop to my dock, the app will display incorrectly as it's now on a monitor with different density. When I move the app back to my macbook monitor, it then looks even worse.

The only way to fix it is to close and open the app back up.

**Comment by asapha** [comment]
Adding some examples in case it can help.
Happens at least on `1.0.0-alpha4-build398` and `build396`.

### When the app is started on the mac's retina display
![CleanShot 2021-10-14 at 21 59 10@2x](https://user-images.githubusercontent.com/1147807/137387192-7c62d24b-7c4c-48f9-8d68-3118f79635b0.png)

### After moving the window to a 3440x1440 monitor
![CleanShot 2021-10-14 at 21 59 13](https://user-images.githubusercontent.com/1147807/137387184-504540df-78f5-4dc7-b3cb-584fa67cfdd0.png)

MacOS Version 11.6 (20G165)

Retina Display
15,4-inch (2880 × 1800)

External Display
34-inch (3440 × 1440)

**Comment by igordmn** [comment]
The known density issues fixed in 1.0.0-beta6-dev455.

Let us know, if there are still some issues. Individual components can react to density changes in a wrong way.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6229">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
