### ISSUE TITLE
Jetbrains compose desktop can work with raspberry pi ?

### ISSUE THREAD

**Issue by toplinuxsir** [JetBrains/compose-jb#992]
Jetbrains compose desktop can work with raspberry pi ? Thanks!

**Comment by olonho** [comment]
Yes, it works on 64-bit Raspberry Pi.

**Comment by toplinuxsir** [comment]
@olonho Thanks! I will try

**Comment by toplinuxsir** [comment]
How to build for raspberry pi4 ?
Thanks !
Just copy the jar to rasperrypi ,and run it ?
