### ISSUE TITLE
How to add files out of 'app' dir when package exe ?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#993]
we can add files by following code:
`            fromFiles(project.fileTree("include/") { include("**/*.dll") })`

![image](https://user-images.githubusercontent.com/23566361/128287297-7ee9af5b-1300-45b4-8bbb-027f7a49a37b.png)

but it will add files into 'app' dir,how to make it out of 'app' dir? like 'test_file'
![image](https://user-images.githubusercontent.com/23566361/128116369-8c79ec11-b539-45a9-8af6-c9a6f72f8928.png)

**Comment by AlexeyTsvetkov** [comment]
@FlyingYu-Z sorry, we don't support that. We rely on jpackage creating packages/installers, and it does not provide a reliable way to achive the described layout (at least I'm not aware of such mechanism)

**Comment by wiiznokes** [comment]
@FlyingYu-Z Hi, sorry to bother you but I have a similar problem. I put the same line of code in gradle: `fromFiles(project.fileTree("include/") { include("**/*.json") })`.

Here is the stucture of the project: 

![iclude](https://user-images.githubusercontent.com/78230769/211475235-a383bfdf-f1fc-4a55-8356-61364fcf193f.png)

But I can't see any json file in the final package, even inside app folder. Are there anything I do wrong here ?

**Comment by FlyingYu-Z** [comment]
> 
try use like the line
![image](https://user-images.githubusercontent.com/23566361/211477029-18f18a55-e5be-4c65-b920-62519522eca9.png)

**Comment by wiiznokes** [comment]
Thanks! But that doesn't change anything. I made a repo if you want to take a look : https://github.com/wiiznokes/IncludeDemoTest

**Comment by FlyingYu-Z** [comment]
> Thanks! But that doesn't change anything. I made a repo if you want to take a look : https://github.com/wiiznokes/IncludeDemoTest

I tried,but can't include the *.json files.
Maybe you can visit:https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution

**Comment by wiiznokes** [comment]
Okay, I already check that, I post an issue, will see. Thanks anyway

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6073">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
