### ISSUE TITLE
Actual/Expect with Composable as default value -> Validation Failed

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#998]
Hey,
Providing a default value in an expect function, which is also `@Composable` crashes the compiler:
`java.lang.IllegalStateException: Validation failed in file App.kt`

```kotlin
// shared App.kt
@Composable
expect fun App(value: String = defaultString)

expect val defaultString: String
    @Composable
    get

// android
@Composable
actual fun App(value: String) {
    Text(value)
}

actual val defaultString: String
    @Composable
    get() = stringResource(R.string.hello)
```
[untitled1.zip](https://github.com/JetBrains/compose-jb/files/6931824/untitled1.zip)

**Comment by eymar** [comment]
Hi @hfhbd ,
Did you notice this issue only when targeting kotlin/js, or kotlin/jvm as well?

**Comment by hfhbd** [comment]
@eymar 
The included sample contains `jvm` and `android` targets only :D

**Comment by akurasov** [comment]
It looks like an issue of main Compose, not a Compose Desktop, right?

**Comment by hfhbd** [comment]
@akurasov Yes.

**Comment by akurasov** [comment]
Then, I believe, it should be reported to Jetpack Compose tracker

**Comment by hfhbd** [comment]
https://issuetracker.google.com/issues/196413692

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6325">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
